### ISSUE TITLE
Do not convert `--` to em-dash (or en-dash, whichever it is) when in code-formatted blocks

### ISSUE THREAD

**Issue by ferventcoder** [gitterHQ/gitter#1003]
When I'm formatting code, every time I type ` --switch` it converts it to em-dash.

![image](https://cloud.githubusercontent.com/assets/63502/11459969/a6b9ab1e-96a8-11e5-9005-9f4621518750.png)

![image](https://cloud.githubusercontent.com/assets/63502/11459971/c1b3d30e-96a8-11e5-8e99-7554f8aa3c1d.png)

**Comment by MadLittleMods** [comment]
Are you on a Mac? Mac seems to autoformat double/em-dashes and quote marks.

This is not a problem on Windows.

**Comment by ferventcoder** [comment]
Aha! So that's my issue.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/521
