### ISSUE TITLE
Additional API fields and methods

### ISSUE THREAD

**Issue by SerafimArts** [gitterHQ/gitter#1005]
What you think about add some Http API improvements?

- Add inside room object `messageCount` field
- Add `rooms/:roomId/chatMessages/first` and `rooms/:roomId/chatMessages/last` for first and last chat messages

**Comment by trevorah** [comment]
Last message time would be really useful for the mobile apps.

**Comment by SerafimArts** [comment]
And first message too for loading\parsing all messages with `afterId` argument in historical order.

**Comment by MadLittleMods** [comment]
@SerafimArts Can you split this off into two separate issues:

 - Add API endpoints for first/last messages in room
 - Add API field for `messageCount` in room

**Comment by SerafimArts** [comment]
Fixed
