### ISSUE TITLE
Condense room icons on left hand side

### ISSUE THREAD

**Issue by kbrock** [gitterHQ/gitter#1006]
In the upper right, the people list icons are condensed and mouse over shows details. This is nice because it can fit many more users/rooms in the view.

Could you do something similar for rooms on the left hand side?

Ideas:

a) showing icon with same width: so they can be packed in there. (mouse over could work like users)
b) show a narrow view on the left hand side to give more real estate for the chat / center.
c) move over to upper right hand corner (next to people) (not sure about this)

This would work great alongside custom icons as well. #762

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/253

**Comment by MadLittleMods** [comment]
You can now collapse the left menu to give more real estate to the chat area.
