### ISSUE TITLE
Email unsubscribe is not present in plain text

### ISSUE THREAD

**Issue by du5t** [gitterHQ/gitter#1007]
For reasons of accessibility and compatibility with email clients, it would be a good idea to include a non-HTML unsubscribe link, as it does not appear in plain text components of the email. This may be an intercom.io issue, but it falls to the user to dig through the email source if they haven't an HTML render of the email body--not exactly an enjoyable or convenient process.

**Comment by mydigitalself** [comment]
Unfortunately it's an Intercom issue, which I've raised with them and haven't had any movement on it, so there's really not much we can do about it I'm afraid.

**Comment by du5t** [comment]
Ah. Sorry to hear that, but thanks for the information.
