### ISSUE TITLE
Arrow keys scroll room list AND current chat window

### ISSUE THREAD

**Issue by JoshTGreenwood** [gitterHQ/gitter#1011]
When in a room with chat focused, clicking up/down arrow keys scrolls the current room's messages (which is expected).  It also adds a hover like effect to the room list (which is unexpected).

Example: http://recordit.co/zSJKxEKoF0

OSX 10.11.1
Safari 9.0.1

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/300, move discussion there.
