### ISSUE TITLE
Archive heatmap is not aligned with actual archive contents

### ISSUE THREAD

**Issue by lucaswerkmeister** [gitterHQ/gitter#1016]
Example: The heatmap for [lucaswerkmeister/me-test](https://gitter.im/lucaswerkmeister/me-test/archives/all). Independent of timezone, it shows an entry on Sunday, November 29. However, for some people, depending on timezone, that message will actually be shown in the archives of Monday, November 30.

The request URL, as requested by @MadLittleMods, is:
> https://gitter.im/api_staging/private/chat-heatmap/565b909916b6c7089cbca2bc?tz=-01:00

This issue might become invalid, depending on the resolution of #1015.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/1015
