### ISSUE TITLE
Users per room API does not support skip 

### ISSUE THREAD

**Issue by roelver** [gitterHQ/gitter#1022]
The user list for a room is recently limited to max 100 users. There is no skip feature to retrieve more users (eg pagination).

Please add a skip parameter to the API.

Eg: https://api.gitter.im/v1/rooms/546fd572db8155e6700d6eaf/users?access_token=xxx&skip=2000&limit=100  should return users #2001 - #2100.

**Comment by abhisekp** [comment]
:+1:

**Comment by evaristoc** [comment]
:+1:

**Comment by lerouxb** [comment]
There's a fix for this that's currently in a staging release. It should be out into production pretty soon.

**Comment by evaristoc** [comment]
lerouxb: just realising... would the skip parameter be effective for *any* kind of request that could require a skip/limit approach? For example: I was also planning to download information not about users but *messages* in the same rooms as abhisekp and roelver...

**Comment by MadLittleMods** [comment]
@evaristoc Please use the `beforeId` and `afterId` parameters instead: https://developer.gitter.im/docs/messages-resource

**Comment by evaristoc** [comment]
@MadLittleMods, I was just checking that option, and was to ask by the chatroom to be sure... Thanks!

**Comment by abhisekp** [comment]
@lerouxb so now it supports `skip`? What's the documentation?

**Comment by MadLittleMods** [comment]
@abhisekp Just as proposed in the original message: `https://api.gitter.im/v1/rooms/xxx/users?skip=100`. Feel free to [update the docs](https://github.com/gitterHQ/docs).
