### ISSUE TITLE
401 Bad Credentials when signing in

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1023]
We have had a few reports of 401 Bad Credentials errors when trying to sign in to Gitter.

This issue is meant to be a central place people can track and give updates to the problem.

**Comment by dab1029384756** [comment]
This happened to me, but I found out if you go to the gitter.im site then register your Email it will stop giving you that error

**Comment by MadLittleMods** [comment]
@dab1029384756 What do you mean by "register your email"?

**Comment by trevorah** [comment]
I think he means confirming your email address. You can technically use all of github without confirming your email address, but theyve only recently started to warn unconfirmed accounts that they need to have a valid email address. Perhaps this is part of the crackdown?

**Comment by mydigitalself** [comment]
Ah, interesting, we could go back and ask them that @lerouxb

**Comment by MadLittleMods** [comment]
There were a few more tickets of this but verifying/confirming/registering/adding an email solved the issue. I haven't heard a report of this in a long while.
