### ISSUE TITLE
The :smile: is too much of a grin.

### ISSUE THREAD

**Issue by Georgiel** [gitterHQ/gitter#1027]
The :smile: is too much of a grin. It should be replaced with more of a smile one, prototype: 
![](https://cloud.githubusercontent.com/assets/12939434/11778512/6d5d4cc0-a25d-11e5-854a-10b813f2ace8.png)

(The prototype is from @demon000 , not me. I merely thought it was a issue worth requesting.)

**Comment by MadLittleMods** [comment]
Some discussion has taken place in [this issue](https://github.com/gitterHQ/gitter/issues/781) but thanks for creating this separate one.

I like to using `:grinning:` :grinning:

**Comment by GeorgeUni** [comment]
Yeah, I thought it best to separate so as not to have clutter in that one, like to keep it on topic.

Cause really the op of that one has two separate semi-related issues which would work best handled separately.

to use words, :smile: feels more like an ecstatic joy, when the more common use is a mild excitement or contentment.

**Comment by Demon000** [comment]
I'm glad you oppened this issue, I was too lazy to do it. The existing smile sends the message of excitement, rather than compassion, which isn't really appropriate, at last for the way I use it.

**Comment by georgiel** [comment]
:+1:

**Comment by mholt** [comment]
Seconded.

- `:)` is a simple smile, should not be a laugh like currently: :smile: 
- `:P` renders to :stuck_out_tongue_winking_eye: which is winking. Why is it winking?? Winking is inappropriate in some contexts, and embarrassing. ;P is the winking variant.

**Comment by abhisekp** [comment]
:+1: 
### Disastrous side effects

> [![Side Effects of laughing vs smiling](http://i.imgur.com/FGXfjUg.png)](http://i.imgur.com/FGXfjUg.png)

The guy thought I was laughing at him :pensive:

**Comment by georgiel** [comment]
:laugh: oops I meant :smile:

**Comment by georgiel** [comment]
:+1:

**Comment by dasilvacontin** [comment]
I wouldn't even make it have the `^^` eyes. The eyes in 😀 would be okay.

**Comment by Georgiel** [comment]
I tend to think of : D as being laughter smiley. and : ) as being the little tiny happy smile.

**Comment by interDist** [comment]
emojis are proving more and more confusing in opposite to their declared goal – see recent research highlighting that people cannot even agree on whether a particular emoji represents a positive or negative emotion. it does not help that each platform renders them in a different way.

**Comment by nagits** [comment]
I think `:simple_smile:` ![image](https://cloud.githubusercontent.com/assets/4932134/16615218/7a200204-438e-11e6-8757-3b29fe8bf8c1.png) from http://www.emoji-cheat-sheet.com/ would be better than `:blush:` or `:grinning:` for `:)`
