### ISSUE TITLE
Search for non-ASCII in the explore view returns HTTP 400

### ISSUE THREAD

**Issue by kba** [gitterHQ/gitter#1031]
Searching with words containing non-ASCII characters in the [Explore interface](https://gitter.im/home/explore) returns a HTTP `400 Bad Request` response and shows the text "Something went wrong. We're sorry. :(".

The endpoint the query is sent to ([/explore/tags](https://gitter.im/explore/tags/)) accepts these characters if they are properly URL-encoded, so it is an encoding issue.

For example, if I browse to https://gitter.im/explore/tags/%C3%9F%C3%A4%C3%BC%C3%B6%E6%97%A0 I am informed that they are no results for `ßäüö无` (as expected). If I type `ßäüö无` into the search bar and press enter, the query is sent to https://gitter.im/explore/tags/%DF%E4%FC%F6%E0 and results in an application error.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/582

**Comment by MadLittleMods** [comment]
Search has been removed from explore, see https://github.com/gitterHQ/gitter/issues/582#issuecomment-201079624
