### ISSUE TITLE
Network error on Android

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#1032]
Its rare per user, but it happens consistently to certain users.

Almost all network requests fail, but other chat apps work fine. Even the web app works when on the same patchy cellular network. `api.gitter.im` is reachable via web.

Fresh install doesnt fix it. Perhaps some more lenient timeouts than the defaults in Volley?

via @creativewolf

**Comment by trondn** [comment]
It happened constantly on my Nexus 6 running Android 6.0.1. Every time I start the app I get the network error thing.. then after trying to refresh it start working as expected. Given that I don't sit and watch the chat window all day long I found it really annoying that every time I clicked on the app I got that behavior ==> uninstalled the app after a week+.

**Comment by trevorah** [comment]
@trondn @creativewolf we've got a new build out on beta right now. Does it improve the network performance for you?

You can join the public beta here: https://play.google.com/apps/testing/im.gitter.gitter

**Comment by CreativeWolf** [comment]
Hi @trevorah Just signed up for the Public Beta, will test it and update on my feedback. Thank you for taking effort on this!

**Comment by trevorah** [comment]
No worries! let me know how it goes.

**Comment by trondn** [comment]
I installed it, entered my credentials and during login I got the "no
connection" message again... "rooms" show up blank (at the same time I am
receiving emails, notifications from other apps etc).

Trond

**Comment by trevorah** [comment]
@trondn If you pull to refresh, how long does it take before you see the error message?

**Comment by trondn** [comment]
I did a manual refresh it worked.. Then I killed the app, started it again.. This time it worked.. Did that a few times, then I just switched to another app and when I switched back I got the same error message again.

**Comment by trevorah** [comment]
Cool, ill create a build with some more descriptive error messages. If the error message pops up after ~2.5 seconds, then thats the request timing out.

**Comment by trondn** [comment]
Just tested it and this time it could be 2.5 sec..  (to be honest I've
never timed it ;-) )

Cheers,

**Comment by trevorah** [comment]
I've just pushed a build with more informative error messages, but it will take a few hours before it reaches googles cdn. In the meantime i'll take a look at making the timeout more lenient.

**Comment by trevorah** [comment]
There is now also a build with more lenient network timeouts (10 seconds) that should be reaching you as 2.4.1-beta.3. Let me know if that helps.

**Comment by trevorah** [comment]
@CreativeWolf any luck with the beta?

**Comment by CreativeWolf** [comment]
@trevorah I'm seeing good improvements. Rooms list refreshes on load in about 4 seconds and when clicked on particular chat, takes about 5-6 seconds to refresh. The issue with the back button looping the same screen has disappeared. Overall good improvements that what it used to be. No error messages what so ever so far. Thanks for making this happen! :)

**Comment by trevorah** [comment]
@CreativeWolf thanks for helping me diagnose this! I'll publish a full release today.

**Comment by trevorah** [comment]
I've just released this as 2.4.1. @trondn i'm going to assume that this has fixed your network issue too.

**Comment by trondn** [comment]
I did some testing today and didn't see any problems

**Comment by trevorah** [comment]
Fantastic. Thanks again @trondn!
