### ISSUE TITLE
Message appears at the bottom of current chunk of messages (even when browsing history/search result)

### ISSUE THREAD

**Issue by cbj4074** [gitterHQ/gitter#1034]
I wish there were a more elegant means by which to summarize the issue.

Essentially, if I scroll way back (up) into the chat history, and then I place the cursor into the new message field and send a new message, the chat scrollbar does not zip back down the very bottom upon sending the message. Instead, the scrollbar stays exactly where it is and my new message appears to be inserted "after" whatever message is at the bottom of the "current view".

So, if it's December and I scroll back up to (or search for) a message that was posted in June, and then I send a new message, my new message appears after the message that was sent in June. This is somewhat disorienting and unexpected.

All of this said, I can see why the observed behavior is actually desirable (being scrolled back down to the most recent message in the chat could be annoying when attempting to respond to older unread messages in the chat).

My primary purpose in documenting this issue is that an enhancement request has been made that *describes the exact behavior that I observe* ( https://github.com/gitterHQ/gitter/issues/956 ), but that request is still open.

To quote @MadLittleMods:

> Create a new issue so we can fix the problem then explicitly implement it so it doesn't rely on some magic side-effects we weren't aware of in the first place (feel free to reference the other one).
>
> :point_up: [December 17, 2015 1:10 PM](https://gitter.im/gitterHQ/gitter?at=567308bf3e71e0707f9bb847)

So, that's what I've done. :)

**Comment by abhisekp** [comment]
:+1:
