### ISSUE TITLE
bug on a page https://gitter.im

### ISSUE THREAD

**Issue by alexbananabob** [gitterHQ/gitter#1035]
bug:
![gitter_bug](https://cloud.githubusercontent.com/assets/13943006/11909556/3ab7cddc-a5f9-11e5-81cc-93f58dcfbfe1.png)

last two links(for iphone and android app) must be in previous tag p
like this:
![gitter_without_bug](https://cloud.githubusercontent.com/assets/13943006/11909649/d3e59268-a5fa-11e5-8858-3944bc8d9050.png)

**Comment by trevorah** [comment]
Thanks @alexbananabob, but the links for the mobile apps are meant to be separate from the desktop apps. That is why they are grouped in a different `<p>` tag.
