### ISSUE TITLE
Number of Members in sidebar is not Updated

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#1037]
The number of members in a room in the people section are not updated. Only at the first load (probably) 

Here is an example of people comparing the disparity:

> See the conversation about the issue for *FreeCodeCamp/FreeCodeCamp* room :point_right: [December 21, 2015 8:01 AM](https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=5677647532644f030a13ce83)

**Comment by MadLittleMods** [comment]
They seem to only update on page-load. Room-switching has no effect.

![](http://i.imgur.com/pfUvaXC.png)

**Comment by mydigitalself** [comment]
This is somewhat by design, we don't keep the full collection of people in the room live - in particular because of large rooms.
