### ISSUE TITLE
Set background of textarea explicitly

### ISSUE THREAD

**Issue by magthe** [gitterHQ/gitter#1038]
Changes to the Gnome/Gtk theme can have an impact on Firefox defaults, as you can see in the screen shot here

![screenshot from 2015-12-21 09-11-25](https://cloud.githubusercontent.com/assets/327270/11926162/db2d7e72-a7c2-11e5-9622-823643a75c9d.png)

(That's from my machine running Arch Linux, Firefox 43.0.1, with the default Gtk theme Adwaita and *Global Dark Theme* turned on.)

Yes, this issue can be worked around locally by putting the following into `userContent.css`:

```
textarea {
    background-color: white;
    -moz-appearance: none !important;
}
```

However, I think it's arguably better if Gitter explicitly sets all styles to sensible defaults, rather than relying on browser defaults and users fixing up the odd corner cases :)

**Comment by abhisekp** [comment]
:+1:

**Comment by mydigitalself** [comment]
This should be available on next.gitter.im now.
