### ISSUE TITLE
Random Links from array index

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#1041]
When a user posts about arrays, the array indexes are linked to random pages.

> [![Array Index Links](http://i.imgur.com/j8fbtbF.png)](http://i.imgur.com/j8fbtbF.png)

Ref. messages:-
- :point_right: https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=567f89d40199d70069dfce4f
- :point_right: https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=567f89c03acb611716ffddd4

More such messages
- https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=56851f394f069158055c7b81
- https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=568512653c689402692578dc
- https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=56855d0d0199d70069e064ec
- https://gitter.im/FreeCodeCamp/Help?at=5686a9d735e1a316162eedab
- https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=568824b39606b15a055e88bd
- https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=56882e4b3c6894026925ba81
- https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=5688d9149606b15a055e9881
- https://gitter.im/FreeCodeCamp/HelpJavaScript?at=56b4048c25142e764dfd08ed
- https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=56c105c74dfe1fa71ffcc6fb

**Comment by MadLittleMods** [comment]
Also seen when typing `arr[0]` and `arr[1]`

**Comment by trevorah** [comment]
Hmm, looks like the markdown parser is rendering them as references.

**Comment by MadLittleMods** [comment]
More reproduction here from @M108: :point_up: [March 24, 2016 9:07 PM](https://gitter.im/gitterHQ/developers?at=56f49d71bbffcc665fa936f6)

```
[1]
```

```
[2]
```

**Comment by MadLittleMods** [comment]
Reproductions here https://gitter.im/WatchBeam/developers?at=57b3d96e6a2fa2ff3d9174aa

**Comment by mydigitalself** [comment]
I think the primary difference here with #1638 is that nobody has previously pointed out that the links seem to come from other chat messages. I personally can't understand how this can happen, as each message is individually parsed in a separate process, but it is somewhat mildly concerning.
