### ISSUE TITLE
Delayed/Slow loading new messages

### ISSUE THREAD

**Issue by nigeljoy** [gitterHQ/gitter#1044]
I get new messages on the app like 2-3 minutes later. Make the chats appear instant

**Comment by trevorah** [comment]
What browser are you using? Are you using a mobile app?

**Comment by nigeljoy** [comment]
@trevorah I'm using the Windows desktop app for gitter.

**Comment by trevorah** [comment]
Do you have the room open while you are waiting for the new message to come in? Is this for a specific room? Could you please give us the steps to reproduce this.

**Comment by nigeljoy** [comment]
@trevorah Yes, i have the room open. I don't know if it's specific room because I mainly use only one room which is gitter.im/FreeCodeCamp/FreeCodeCamp and it is highly active group with new messages every few seconds.. The issue is noticed after using the app for like 10 minutes or so..

Sometimes, if I'm active on a chat room, and if I get mentioned, I get alerted but it takes like good 15 + seconds for that message to load....that is when it gets frustrating.

**Comment by MadLittleMods** [comment]
@nigeljoy How do you know there is a new message 15 seconds before?

Are you getting the browser notification and unread green banner, but the message is not showing in the chat area?

**Comment by nigeljoy** [comment]
@MadLittleMods becasue I got notification of being mentioned and it took atleast 15 seconds for that message to show up in the chat even though the focus was on that gitter desktop app and I had the chat room open waiting for the message.

Also, sometimes when I feel like new messages are not getting loaded instantly, and if I check gitter website, I can see dozens of new messages there that is yet to show up in the gitter desktop app.

**Comment by nigeljoy** [comment]
@trevorah @MadLittleMods this issue is also experienced on Google Chrome when using gitter website for a few minutes. If you Gitter desktop app uses webkit engine, I guess that shows the root of issue.

**Comment by MadLittleMods** [comment]
@nigeljoy  Just to rule it out, what does your computer resource usage look like when this happens (CPU, Disk, Network)?

**Comment by MadLittleMods** [comment]
@nigeljoy Are you still experiencing delayed/slow chats?
