### ISSUE TITLE
Incoming emails for rooms

### ISSUE THREAD

**Issue by phlax** [gitterHQ/gitter#1052]
It would be really useful if it was possible to receive emails into rooms - ie to have an associated mailbox.

This allows a quick way of integrating other apps that do not have a gitter.im integration.

It also allows a room to be used to respond to incoming support emails etc.

**Comment by MadLittleMods** [comment]
Open up an issue on the integrations repo: https://github.com/gitterHQ/services

**Comment by phlax** [comment]
done gitterHQ/services#61
