### ISSUE TITLE
issues count isn't right

### ISSUE THREAD

**Issue by srisankethu** [gitterHQ/gitter#1054]
The issue count in https://gitter.im/levlaz/braindump and issue count in https://github.com/levlaz/braindump is different.But in case of your repo gitterHQ/gitter it is correct
https://gitter.im/gitterHQ/gitter https://github.com/gitterHQ/gitter.

**Comment by MadLittleMods** [comment]
The issue indexes match what is in the repo. It looks like you have 89 issues and 69 pull requests which share the same incrementing index.

**Comment by srisankethu** [comment]
@MadLittleMods it seems that the 4 open pull requests are counted as issues i.e 28 issues(open) + 4 pull requests(open)(https://github.com/levlaz/braindump)=32 issues(https://gitter.im/levlaz/braindump).

**Comment by MadLittleMods** [comment]
Ahhh, you are referring to the Repo Info section. My initial thought was just the indexes in the activity panel.

![](http://i.imgur.com/qUtOUHH.png)

While they are not all issues, I'm not sure this should be fixed as GitHub considers everything an issue and those pull requests do need be addressed in some way.

**Comment by srisankethu** [comment]
@MadLittleMods Ok!
