### ISSUE TITLE
Add tooltip for favorite and settings

### ISSUE THREAD

**Issue by srisankethu** [gitterHQ/gitter#1055]
It would be nice to add a tooltip to each icon in the header.

![screenshot 12](https://cloud.githubusercontent.com/assets/12644108/12178712/e76d8b3a-b598-11e5-80c8-a52a89b08f51.png)

**Comment by MadLittleMods** [comment]
Update, this has been in place for a little while now.

![](http://i.imgur.com/bgZLUaC.gif)
