### ISSUE TITLE
Save window location and state (desktop app, windows)

### ISSUE THREAD

**Issue by mrexodia** [gitterHQ/gitter#1059]
Hello,

When my machine boots, I start the Gitter desktop app. However it does not remember the window position or state. I have a dual screen setup and the gitter app should pop up on my secondary screen when it boots. Now I have to manually move the window there.

Thanks for you great product!

**Comment by MadLittleMods** [comment]
Hey @mrexodia,

Can you create an issue on the desktop repo: https://github.com/gitterHQ/desktop/issues

**Comment by MadLittleMods** [comment]
Moved to https://github.com/gitterHQ/desktop/issues/92
