### ISSUE TITLE
Add support for alt text on uploaded images

### ISSUE THREAD

**Issue by MichielBijl** [gitterHQ/gitter#1060]
The ability to upload images directly to Gitter is great. It can be even greater with support for alt text. This would require either:

* A bit of logic so that if you type `alt=Cute kittens lick the Gitter logo` it will be added to the last served image
* Piece of UI that prompts the user to supply an alt text

The first one—I feel—would be easier/less intrusive. Where as the second one teaches people that are not familiar with accessibility/proper image markup that there is such a thing as alt text. Second one is easier for people who aren't as familiar with command line usage (more explicit anyway).

Could also be an option to choose between both / let the user decide.

**Comment by MadLittleMods** [comment]
You can already add alt-text to uploaded images. After it is uploaded, just edit the message and add the text. By default it has the file name as the alt text.

```md
[![somefile.png](https://files.gitter.im/org/repo/icsy/thumb/123f4185fc5e65fd75474446f713e4789.png)](https://files.gitter.im/org/repo/icsy/123f4185fc5e65fd75474446f713e4789.png)
```

**Comment by MichielBijl** [comment]
Ah, of course, you can do markdown formatting for images -.-

My bad.
