### ISSUE TITLE
Travis webhooks 

### ISSUE THREAD

**Issue by ray26** [gitterHQ/gitter#1070]
I have already add web hooks to my .travis.yml , but it still showed me that there are no recent events. Should i do some extra config?
![default](https://cloud.githubusercontent.com/assets/6435613/12370250/ce20a272-bc44-11e5-920d-4d480db2f933.jpeg)
![default](https://cloud.githubusercontent.com/assets/6435613/12370256/f6945424-bc44-11e5-9ae7-cb41277a8b80.jpg)

**Comment by MadLittleMods** [comment]
Has there been any events since you added the integration?

Did you properly replace the `YOUR_WEBHOOK_URL` in the snippet to paste in `.travis.yml`?

**Comment by ray26** [comment]
![default](https://cloud.githubusercontent.com/assets/6435613/12370719/a09db972-bc56-11e5-9dde-5f68c07045bb.jpeg)
![default](https://cloud.githubusercontent.com/assets/6435613/12370718/9fe01048-bc56-11e5-96e8-c2428b3adb51.jpg)

**Comment by ray26** [comment]
http://imgur.com/gallery/amEV0/new @MadLittleMods You could see that i have used the right web hooks url

**Comment by MadLittleMods** [comment]
Can you try starting the process over with a new hook?

**Comment by ray26** [comment]
could you tell some details？

**Comment by MadLittleMods** [comment]
@ray26 Did you get this working?

**Comment by promethe42** [comment]
Hello,

same problem here. Gitter tells me there "no recent event".
