### ISSUE TITLE
GitHub references in channel

### ISSUE THREAD

**Issue by galenlin** [gitterHQ/gitter#1074]
I create a [Github Repo](https://github.com/wequick/Small) which contain multi platforms (**Android** and **iOS**). I would like to create separated rooms(channels) for **Android** and **iOS** developers. 

I have tried to create a [channel](https://gitter.im/wequick/SmallAndroid) and authorize the `WebHooks' to the repo, but it seems to cannot automatically refer to my repo issue when typing something like 

```
#11
```

Following is the error:

![qq20160118-1](https://cloud.githubusercontent.com/assets/5291591/12384772/a786da84-bdf0-11e5-88cf-18070ae339ec.png)

Am I missing something or can Gitter make approach to this and how?

**Comment by MadLittleMods** [comment]
In order for the standalone `#11` to work, you need to create a repo room for the associated repo. We currently don't have a way to set the default reference repo outside of that, see https://github.com/gitterHQ/gitter/issues/757

You can instead use the full name of the repo `org/repo#11` which works everywhere.
