### ISSUE TITLE
Smaller Issue link abbreviation

### ISSUE THREAD

**Issue by kbrock** [gitterHQ/gitter#1077]
When I am in `gitterHQ/gitter` room, I can link to issues in a number of ways:

- `#1077`
- `gitterHQ/gitter#1077`
- `http://githubcom/gitterHQ/gitter/issues/1077`

The first one displays as a nice compact `#1077`, while the other two display as `gitterHQ/gitter#1077`.

Is it possible to always display the shortened one?

Maybe it is not, since it is smart enough to know that `rails/rails#1077` should not display `#1077`.

ASIDE: When I cut and paste that text, it includes the whole url which is such a nice touch. thanks.
ASIDE 2: You know you are doing a great job when you get nit picks like this.

**Comment by MadLittleMods** [comment]
We only recognize the standalone number version `#x` when the default repository is set(repo room), https://github.com/gitterHQ/gitter/issues/757

When you use the longer reference, it will work in any room and keep it explicit.

**Comment by kbrock** [comment]
@MadLittleMods thanks
