### ISSUE TITLE
Add multiple administrators/moderators

### ISSUE THREAD

**Issue by a11smiles** [gitterHQ/gitter#1079]
Is there a way to add multiple owners/administrators to a channel or room?

**Comment by MadLittleMods** [comment]
You can create a room with organisation permissions so anyone who is in the org has admin privileges. You can also create a repo room and anyone with write access to the repo, has admin privileges. With channels, you can only have one owner at the moment, which is the person who created it.

**Comment by a11smiles** [comment]
An alternative would be the ability to _transfer_ ownership of a channel.  The reason I've asked for this feature is because we've created a private channel for a client whose project we're currently working on.  Our internal development team and the client's team are in the channel.  When the project ends, I'd like to be able to "hand off" the channel to the client so that they have a history of all conversations of bugs, features and/or business requirements.

Thanks!

**Comment by Fryguy** [comment]
@MadLittleMods How does one determine the moderator in a channel?  If someone posts the secret sauce, I need to be able to track down the moderator to fix it (at least until the feature requested here, or when the expected changes for #620 are implemented).

Do org admins have moderator access in a channel?

Also, can a moderator edit/delete a message that has been marked as old (and thus Edit/Delete is now greyed out for the poster).

**Comment by MadLittleMods** [comment]
@Fryguy Currently only Gitter staff can handle spam and abuse. If you see something, email support@gitter.im with permalinks(click the timestamp in the top-right of every message and copy the URL in the address bar) and any background on the situation.

Indicating roles in a room is a separate issue:

 - https://github.com/gitterHQ/gitter/issues/227
 - https://github.com/gitterHQ/gitter/issues/356
 - https://github.com/gitterHQ/gitter/issues/832
 - https://github.com/gitterHQ/gitter/issues/7

**Comment by MadLittleMods** [comment]
The permissions modal has been around since September which allows manage the admins of the room, group, and grant additional admins outside of the rule.

![](http://i.imgur.com/wc3Etly.png)

![](http://i.imgur.com/qGgZh5d.png)
