### ISSUE TITLE
Disable notification for @/all mention

### ISSUE THREAD

**Issue by GeorgeUni** [gitterHQ/gitter#1080]
Add an option to disable `@/all` mention notifications

**Comment by georgiel** [comment]
:+1:

**Comment by MadLittleMods** [comment]
This will be covered by our future notification work.

**Comment by GeorgeUni** [comment]
I think checkbox would be best way, cause some people like the @all

**Comment by WardBenjamin** [comment]
+1

**Comment by GeorgeUni** [comment]
:+1:

**Comment by mydigitalself** [comment]
This is now live on Gitter Next (https://gitter.zendesk.com/hc/en-us/articles/203904511).

You'll notice you can change notification settings to one of three values, if you choose "Mute" this will only notify you when someone **directly** mentions you and not for `@/all`

This is just a small piece of a larger amount of work we are doing on changing notifications and will also be introducing defaults. You'll probably notice that Lurk mode is gone, these new settings supersede the old Lurk mode.

**Comment by mydigitalself** [comment]
This is now in production.

**Comment by GeorgeUni** [comment]
:+1:

**Comment by GeorgeUni** [comment]
what of mobile?

**Comment by MadLittleMods** [comment]
@GeorgeUni What do you mean, you should get notifications on mobile per your room settings? In case you meant this, adjusting notification settings is a separate issue: https://github.com/gitterHQ/gitter/issues/848
