### ISSUE TITLE
Using over 500MB of ram in desktop client

### ISSUE THREAD

**Issue by SirUncleCid** [gitterHQ/gitter#1081]
Ok, in reality, I'm ok with it's memory usage.  My system has plenty to spare.  However, if Gitter plans on using that much ram, why is it so damn slow to respond?  Why is it the most painful thing ever to scroll up and down to view previous things posted in chat?  And not to mention switching rooms.  Even if the room you're switching to has been idle for the past 5 hours, it still takes a good 8+ seconds to load up the tab.

Gitter provides an incredibly frustrating user experience.  If nothing changes, I hope to figure out an alternative for FreeCodeCamp to migrate to.

Thanks for listening to the rant.

Specs:
Both Windows 7 and Ubuntu 15
i7-3630QM
8GB Ram
Geforce GTX 670MX
[insert seemingly redundant specs here]

**Comment by MadLittleMods** [comment]
What happens if you restart the app? Is it still slow and using a lot of resources?

**Comment by SirUncleCid** [comment]
When I restart the app, Gitter loads relatively quickly, and is then holding 82MB of ram.  It steadily increases constantly, however.  About 30 seconds in, I'm at 90MB, and still increasing per second.

**Comment by SirUncleCid** [comment]
So, woke up this morning to gitter using 968MB of ram, and 13% of my CPU.

**Comment by MadLittleMods** [comment]
I won't be able to test the Windows desktop app until next week.

In the meantime, if you want to try to work this out yourself, you can open the devtools and profile some things. Also, the source is on GitHub: https://github.com/gitterHQ/desktop

**Comment by MadLittleMods** [comment]
I can't reproduce this on Windows 10 64-bit. Stays at around ~23mb for me.

I am upgrading the desktop app to the latest nw.js version at the moment which may solve your issue. Stay tuned for the next desktop release.

**Comment by michaelmrose** [comment]
I can confirm that on the 64 bit linux client this happens as well.  I'm using it on Funtoo Current which is a derivative of Gentoo.

**Comment by MadLittleMods** [comment]
@michaelmrose What version of the desktop app are you using?

**Comment by MadLittleMods** [comment]
Move discussion to https://github.com/gitterHQ/desktop/issues/122
