### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by liatreis** [gitterHQ/gitter#1082]
I've been using Gitter for a while now on this computer. Yesterday I closed the app and when trying to open it again it was loading for about 5 seconds and then crashed, the app window did not even appear. I tried this multiple times and always the same behavior. After restarting the computer (windows 7) it was working again, but then closing the app and trying to reopen triggered the same behavior as before, and I could not reopen it without restarting my computer.

**Comment by MadLittleMods** [comment]
Try going through this guide: https://github.com/gitterHQ/desktop/issues/69#issuecomment-126656798

**Comment by liatreis** [comment]
@MadLittleMods The issue you referred to related to the application not showing in expanded mode. In the scenario I described the application does is not showing at all, so that even the icon is not showing on the windows taskbar. 

I have however found a way to get around this: on windows task manager I ended the running process for "Gitter.exe *32" and then when starting up Gitter it finally opened. Not ideal but at least now I can reopen Gitter without restarting my PC. Would be great to have it fixed.

**Comment by MadLittleMods** [comment]
We will be updating nw.js soon which might fix this.

**Comment by liatreis** [comment]
Thanks!

**Comment by MadLittleMods** [comment]
@liatreis Has the latest v3.0.3 of the desktop client helped?

If not, try logging what is happening https://github.com/gitterHQ/desktop#enabling-logging-on-windows and paste a text version of the logs in a gist to link here.
