### ISSUE TITLE
No back button on channel list

### ISSUE THREAD

**Issue by MichielBijl** [gitterHQ/gitter#1084]
In the new 3.0.0 release of the iOS app there is no back button on the channel list page; this makes it unpractical to undo the action and return to the channel you came from. A user now has to remember which room they were in and click that. This is not always the first in the list; favourites are placed before other channels.

**Comment by trevorah** [comment]
Hmm, do any other ios apps do this? Or is it just the unpredictability of the channel list sorting?

**Comment by MichielBijl** [comment]
No, the way [you describe it](https://github.com/gitterHQ/gitter/issues/780#issuecomment-173637562) makes sense.

> The channel list is now the root view, so there is nothing to go back to.

Think this can be closed.

**Comment by trevorah** [comment]
cool, will do.
