### ISSUE TITLE
android notification only clears if clicked

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#1085]
If you visit a room manually, any android notifications for that room will never clear. We could probably assume that the notifications are no longer needed once a user opens the corresponding room.

This should do it:
```java
NotificationManager notificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
notificationManager.cancel(NOTIFICATION_ID);
```

**Comment by RossBarnie** [comment]
Uninstalled the app because I had no control over the notifications. It's a really nice app otherwise.

**Comment by MadLittleMods** [comment]
@RossBarnie This seems like the wrong place for this comment. You can turn off Android notifications for the app, see https://github.com/gitterHQ/gitter/issues/799#issuecomment-126119695

Perhaps your issue pertains more to https://github.com/gitterHQ/gitter/issues/848 or  https://github.com/gitterHQ/gitter/issues/462
