### ISSUE TITLE
API bug while users fetching

### ISSUE THREAD

**Issue by SerafimArts** [gitterHQ/gitter#1086]
This request (`https://api.gitter.im/v1/rooms/:roomId/users`) returns only **30 users** but docs (https://developer.gitter.im/docs/rooms-resource) has no contains info about users query limit.

Please add information about `skip=N` arg in documentation

**Comment by SerafimArts** [comment]
Yes. Please add information about `?skip=N` arg in documentation

**Comment by MadLittleMods** [comment]
Feel free to create a PR about the `skip` and `limit` parameters: https://github.com/gitterHQ/docs

Same as the `/v1/rooms/:roomId/chatMessages` `skip` and `limit`: https://developer.gitter.im/docs/messages-resource

**Comment by SerafimArts** [comment]
@MadLittleMods kk, thx
