### ISSUE TITLE
Bug while updating message throw gitter http api

### ISSUE THREAD

**Issue by SerafimArts** [gitterHQ/gitter#1087]
Request: `PUT /v1/rooms/:roomId/chatMessages/:chatMessageId` (and POST method too)
Body: `{"text": "Новый текст!"}`

https://developer.gitter.im/docs/messages-resource

Response: 
```
SyntaxError: Unexpected token Н
    at parse (/opt/gitter/gitter-webapp/node_modules/body-parser/lib/types/json.js:83:15)
    at /opt/gitter/gitter-webapp/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
```

**Comment by MadLittleMods** [comment]
I am able to POST and PUT that text without any problem.

`POST /v1/rooms/:roomId/chatMessages`
`{ "text": "Новый текст!" }` x-www-form-urlencoded
`Authorization Bearer xxx` header

**Comment by SerafimArts** [comment]
@MadLittleMods stack trace response is trace of your production environment ;)

Screenshot:
![http://docs.rudev.org/stream/6ab24833b19bb6141b4628313d2ac4a9](http://docs.rudev.org/stream/6ab24833b19bb6141b4628313d2ac4a9)

Api: https://github.com/SerafimArts/gitter-api

Headers:
```
'Content-Type'    => 'application/json',
'Accept'          => 'application/json',
'Authorization'   => 'Bearer ...',
'User-Agent'      => 'SerafimArts/GitterAPI Client 1.0',
'Accept-Language' => 'en',
'Cache-Control'   => 'no-cache',
```

Test script:
```php
<?php
require __DIR__ . '/vendor/autoload.php';

$client = new \Gitter\Client('api_token'); // API Token
$room   = $client->getRoomByUri('LaravelRUS/GitterBot');

$msg    = $room->sendMessage('Hello world!');

$msg->updateMessage('Новый текст!');
```

Script requests (debug info):
```
POST https://api.gitter.im/v1/rooms?
POST https://api.gitter.im/v1/rooms/560281040fc9f982beb1908a/chatMessages?id=560281040fc9f982beb1908a
PUT https://api.gitter.im/v1/rooms/560281040fc9f982beb1908a/chatMessage/56a2b46cc54bc2bf180b865d?roomId=560281040fc9f982beb1908a&id=56a2b46cc54bc2bf180b865d
```

**Comment by SerafimArts** [comment]
Lol =) Its fail inside body of update message request:
```
Script requests:
```
POST https://api.gitter.im/v1/rooms?
// body {"uri":"LaravelRUS/GitterBot"}

POST https://api.gitter.im/v1/rooms/560281040fc9f982beb1908a/chatMessages?id=560281040fc9f982beb1908a
// body {"text":"Hello world!"}

PUT https://api.gitter.im/v1/rooms/560281040fc9f982beb1908a/chatMessage/56a2b46cc54bc2bf180b865d?roomId=560281040fc9f982beb1908a&id=56a2b46cc54bc2bf180b865d
// body "Новый текст!"  <<< Error
```

But i think u can hide production stacktrace ;)
