### ISSUE TITLE
Don't decorate non-issues (issue references)

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#1089]
If the issue decorator returns a 404, don't decorate it at all.

**Comment by sgrif** [comment]
I have been told I should :+1: this, so I am. https://twitter.com/sgrif/status/691401176898666496 and its replies have context.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/454

**Comment by MadLittleMods** [comment]
Fixed. This will be in the next release :grinning:

**Comment by sgrif** [comment]
<3
