### ISSUE TITLE
room doesnt load on ios app

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#1090]
* List of rooms loads ok
* selecting a room just has a frozen loading icon
* join button shows even when already a member
* iOS v8.1.1, Gitter v3.0.0 (EDIT: works after upgrading to iOS v9)

via @tboerger

**Comment by trevorah** [comment]
I cant reproduce this on an iphone 4s running iOS v8.1. @tboerger, do you have anything special going on with your phone? Also, have you tried reinstalling the app?

**Comment by tboerger** [comment]
Nothing special as far as I know. It's a iPhone 5c with ios 8.1.1.

I have uninstalled and installed the app again, tried to clear the cache, logged out and logged in afain. Nothing changes.

Yesterday have been another guy on the gitter chat who got the same issue.

**Comment by trevorah** [comment]
Thanks @tboerger. @ZeldaZach, Is your iPhone a 5c running iOS 8.1.1 as well?

**Comment by trevorah** [comment]
Also @tboerger, could you give me a screen shot of what happens when you try to load the gitterHQ/gitter room please?

**Comment by tboerger** [comment]
@trevorah sorry but I already upgraded iOS to the latest version and everything works for me now.

**Comment by ZeldaZach** [comment]
iPhone 6, iOS 8.3

**Comment by trevorah** [comment]
thanks @ZeldaZach. I dont suppose you could send me a screenshot?

**Comment by ZeldaZach** [comment]
It freezes like this:
![img_8413](https://cloud.githubusercontent.com/assets/7460172/12556258/0d99af06-c353-11e5-8871-992ff0b432b8.PNG)

**Comment by Gormartsen** [comment]
I have latest gitter app on  iOS 8.4 iPhone 6 plus.
Exactly the same issue.

Looks like app is using some API that is available only on iOS9.

You need to double check if function that render chat page is get triggered on iOS8.x version.

**Comment by trevorah** [comment]
Thanks @ZeldaZach!

@Gormartsen its not quite an api availability issue as we target iOS 8 anyway. It looks like it was an issue that isnt visible in the simulator. Im setting up an iOS 8 test device now.

**Comment by Gormartsen** [comment]
@trevorah feel free to contact me, if you need help. I am iOS developer as well.

**Comment by trevorah** [comment]
Thanks @Gormartsen! Hopefully once this test device has downgraded then I should be able to play with a fix.

**Comment by Gormartsen** [comment]
@trevorah It could be painful. iOS devices is not easy to downgrade OS. 
Wish you luck and find that bug quickly.

**Comment by trevorah** [comment]
@Gormartsen I've got a fix. Could you please email me your apple id so that I can send you a beta copy via testflight?

**Comment by trevorah** [comment]
@ZeldaZach you too if you like. andy@gitter.im.

**Comment by Gormartsen** [comment]
@trevorah sent by email.

**Comment by trevorah** [comment]
Looks like the 3.0.1 build fixes it. I've requested an expedited review to get this public.

**Comment by ZeldaZach** [comment]
Nice job :)

**Comment by Gormartsen** [comment]
@trevorah Thank you. 3.0.1 is fixing this issue for me. No other issues appear so far!

**Comment by trevorah** [comment]
3.0.1 should now be live in the app store :tada:

Thanks again @tboerger, @ZeldaZach and @Gormartsen for spotting this and helping with the debugging!
