### ISSUE TITLE
Ignore/Mute/Block user

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1093]
On an individual basis, be able to ignore/mute/block user. Ideally, you would still be able to see that the muted user chatted but not see the message contents. This is in order to maintain context in case someone else interacts with them.

---

Related to https://github.com/gitterHQ/gitter/issues/370

semi-related to https://github.com/gitterHQ/gitter/issues/398 and https://github.com/gitterHQ/gitter/issues/245

**Comment by iCloud** [comment]
:+1:

**Comment by mpotra** [comment]
+1
Additionally a way to report someone for bad conduct/trolling/etc

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/370
