### ISSUE TITLE
Lurk unread circle badge re-appears after reading and reloading

### ISSUE THREAD

**Issue by ewnd9** [gitterHQ/gitter#1094]
Reproduction steps:

 1. Have `roomA` with a unread lurk circle badge
 2. Visit `roomA` and notice the circle goes away
 3. Visit any other room and reload the page
 4. Notice the unread lurk circle badge back on `roomA` without any new messages in that room.

![2016-02-02t20 47 07 419z](https://cloud.githubusercontent.com/assets/1713789/12764136/9ee701ba-ca2a-11e5-873c-e79dd24e2783.gif)

@MadLittleMods [confirmed](https://gitter.im/gitterHQ/gitter?at=56b1183490f586ba68075ceb) a reproduction in a `gitterHQ/gitter` room

**Comment by mydigitalself** [comment]
@suprememoocow you might want to take a look at this while you are in notification-land.
