### ISSUE TITLE
Tray icon on elementary os missing

### ISSUE THREAD

**Issue by awishformore** [gitterHQ/gitter#1098]
On elementary os, there is no tray icon in the notification tray.

This is problematic because once you close the user interface using the cross, there is really no way to reopen the client, even though it is still running in the background.

Other applications work fine like this because relaunching the application will simply activate the current instance if it is already running. Gitter, on the other hand, tries to launch a new instance, which fails because of an already held lock on sqlite.

Even if it would launch fine, it would be undesirable to have many instances running in parrallel. An easy (but less clean) fix would thus be to simply make a launch of the application activate the already running instance if one exists.

I think the issue is related to the fact that elementary os freya is built on Ubuntu 14.04 LTS, but uses a different window manager or tray manager (it uses Wingpanel for the tray afaik). I was able to solve a similar issue with dropbox using the following workaround:

https://unix.stackexchange.com/questions/198977/dropbox-tray-icon-doesnt-show-up-in-elementary-os-luna-freya

It suggests that on elementary os, applications should use libappindicator and the unity desktop environment to have a working tray icon.

**Comment by MadLittleMods** [comment]
Move to https://github.com/gitterHQ/desktop please, sorry for not pointing you to it earlier.
