### ISSUE TITLE
Layout bugs in "Repo Info" section on right-sidebar

### ISSUE THREAD

**Issue by WardBenjamin** [gitterHQ/gitter#1099]
The "Repo Info" section of the right-sidebar has very incorrect formatting, as seen here:

![Screen capture of desktop client](http://i.imgur.com/2iTJ67f.png)

This is also an issue, though slightly differently, in the web client.

![Screen capture of web client](http://i.imgur.com/BFIzokG.png)

In both cases, though, it leads to some pretty hard to read text.

**Comment by awishformore** [comment]
I can confirm this issue in the Linux desktop client.

**Comment by MadLittleMods** [comment]
This happens everywhere and is in the webapp base itself.

**Comment by trevorah** [comment]
Looks like the `activity-item-inner` class is being used on that div, and its applying flexbox.

**Comment by trevorah** [comment]
Removing that class seems to fix it. @MadLittleMods?

**Comment by trevorah** [comment]
Fix is on its way to production right now. Thanks for reporting, @WardBenjamin!

**Comment by MadLittleMods** [comment]
@trevorah It is used on the activity list. It looks like it was accidentally added to `./public/js/views/righttoolbar/tmpl/repoInfo.hbs` when I added to the rest of the different integration templates in that directory (open all of them and paste it in): https://github.com/troupe/gitter-webapp/commit/8c808b9519d5d7e23dfb60f49a50a430b4dec594

**Comment by WardBenjamin** [comment]
No problem!
