### ISSUE TITLE
Heading does not seem to update.

### ISSUE THREAD

**Issue by howardroark** [gitterHQ/gitter#1106]
Hey!  So I may be missing something but I can't understand how gitter updates the channel "heading" that it sources from GitHub.  Does it just use the original one forever?

**Comment by MadLittleMods** [comment]
@howardroark You can update the room topic/description by using the `/topic foo` command or double clicking the description(note this currently only works on the page-loaded room).

**Comment by howardroark** [comment]
Thanks!  I didn't even know gitter had IRC style commands :P Good to know!!!

**Comment by MadLittleMods** [comment]
@howardroark You can start typing `/` to see a list of available commands. We also have a FAQ article on it that describes each one: https://gitter.zendesk.com/hc/en-us/articles/200178991--commands
