### ISSUE TITLE
Add some teammates box is broken on next

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1108]
Add some teammates(`collaboratorsView`) box is broken on next (works fine in production).

 - Enable `next`: http://next.gitter.im/
 - Create a new room
 - Notice broken box with one dummy user

![](http://i.imgur.com/SXTW2dp.png)

**Comment by suprememoocow** [comment]
Looks like the problem is that the response is being wrapped in an additional array....

```
GET https://gitter.im/api_staging/v1/rooms/xxxx/collaborators
[[{ "login": ".....",
```

**Comment by suprememoocow** [comment]
Fix should be rolling in in the next few minutes

**Comment by MadLittleMods** [comment]
@suprememoocow :+1: Seems to be working now
