### ISSUE TITLE
Need a way to disable the green slide-out notifications banner

### ISSUE THREAD

**Issue by SteveALee** [gitterHQ/gitter#1109]
The green "slideout" notifications of updates are REALLY distracting and interfere with reading.

There needs to be a way to turn them off completely.

**Comment by MadLittleMods** [comment]
There is a setting to hide the green unread message badge but this is synonmous with lurk mode so you won't get unread notifications. You will get a green circle if anything is unread and still get direct mentions though.

![](http://i.imgur.com/ZlhDgg2.png)

**Comment by SteveALee** [comment]
Cool.
Why is that like lurking? Surely that just means I don't post (or perhaps presence is hidden)

Do you mean no email notifications? That's not a big issue I guess as I find them a little to noisy too.

**Comment by SteveALee** [comment]
Am being really daft here but I can't find global settings. Only per channel

**Comment by MadLittleMods** [comment]
@SteveALee The "Hide unread message badge" is lurk mode. If you press "Enable lurk mode" on that modal or `/lurk` it will toggle that setting.

You won't get browser or email notifications if lurk mode is enabled. Presence is not affected

There aren't any global notification settings at the moment but this is a separate issue and will be addressed in our new notifications work: https://github.com/gitterHQ/gitter/issues/999

**Comment by SteveALee** [comment]
@MadLittleMods Thanks. To me Lurk means no one else knows your are there. Not you don't get notifications. ;) Silent mode might be better?

So I checkedthe hide badge checkbox and then clicked outside the modal. That usually means cancel, but I noticed the checkbox stuck when I re viewed. I didn;t hit the 'enable lurk' link so sort off assumed I did not do it, what ever it is

**Comment by MadLittleMods** [comment]
@SteveALee hmm, I haven't noticed that clicking outside a modal means cancel. I have always only associated with exiting the modal and makes even more sense in our case because we don't have an explicit "Ok", "Apply", "Save" button.

**Comment by SteveALee** [comment]
@MadLittleMods I don't know if there is a standard UX pattern for it. I just assumed cancel is safer and made more sense that. Effectively the 'enable' is OK and I think outside should be same as the X. Or better does nothing :)

**Comment by MadLittleMods** [comment]
Closing because we now only show the green in-app banners if you haven't enabled desktop notifications.

**Comment by SteveALee** [comment]
Id like a little non obtrusive in app indicator that there are new message (green or orange currently dot) and no slide outs or desktop pop toast notification. Do I get that still? Thanks

**Comment by MadLittleMods** [comment]
@SteveALee If you don't want any notifications, you can adjust your notification settings to announcements or mute. You will still get a small green circle when activity occurs.

**Comment by SteveALee** [comment]
perfect - will do now!
