### ISSUE TITLE
Return/Enter key on Android Chrome doesnt send message

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#1111]
* android 6.0.1 on Nexus 6 with the Google keyboard
* same for edit (i.e. not a compose mode bug)
* tap away still sends messages

via @fommil

**Comment by MadLittleMods** [comment]
Looks to be a mobile web app problem in general. Doesn't work on Android 5.1 Chrome(on a Moto E)

**Comment by trevorah** [comment]
@MadLittleMods you mean the return key to send?

**Comment by MadLittleMods** [comment]
@trevorah Correct, I can reproduce the return/enter key not sending a message.

**Comment by terrysahaidak** [comment]
why do you guys can't create a button to sent message? sometimes I wanna write multiliine message but can't because enter/return sent the message instead create new line.

**Comment by trevorah** [comment]
@terrysahaidak thats probably going to happen for the native mobile apps.

**Comment by trevorah** [comment]
fix is on its way to production...

**Comment by fommil** [comment]
:clap:
