### ISSUE TITLE
Add meta tags: mobile-web-app-capable and apple-mobile-web-app-capable

### ISSUE THREAD

**Issue by spacejack** [gitterHQ/gitter#1116]
I add the website to my homescreen rather than installing the app. Adding:

	<meta name="mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>

to the page `<head>` would allow it to open fullscreen rather than having an address bar at the top.

**Comment by mydigitalself** [comment]
@spacejack is there a reason you do this rather than installing the app?

**Comment by MadLittleMods** [comment]
:+1: webapp ftw

**Comment by spacejack** [comment]
Starts faster, uses less space, doesn't require me to download app updates, more secure, more stable, less likely to data-mine me, the web app is perfectly serviceable for me as-is. I don't know why I'd want to install a whole extra browser instance just for it. Too many "apps" do this already. All I'd really like is the ability to go full screen and for Chrome to treat it as a proper web app.

**Comment by spacejack** [comment]
By the way, just to be clear, I think Gitter is great and works perfectly. Those 2 extra tags would just make it that much better on my phone.

I already use Chrome's "Add to Desktop" feature to run it as a standalone app on my Windows PC and it works great.

**Comment by MadLittleMods** [comment]
This has been added and will be available when we cut the next release! :grinning:

**Comment by spacejack** [comment]
Thanks very much. Looking forward to it!
