### ISSUE TITLE
Can't create org room after rename

### ISSUE THREAD

**Issue by ancizararenas** [gitterHQ/gitter#1117]
After having renamed the name of my organisation on GitHub, I am not not able to create room for my organisation. Would it be possible to perhaps remove the existing room for the organisation and for me to create a new one. Many thanks

**Comment by MadLittleMods** [comment]
@ancizararenas Can you please send a message to support@gitter.im with the old and new org names? Also make sure your membership is public on the new org. I think we have started supporting automatic org renames but it looks like it didn't kick in for you. We need to manually run a script to rename the org on our side.
