### ISSUE TITLE
Unable to change notification settings in OSX app

### ISSUE THREAD

**Issue by weizlini** [gitterHQ/gitter#1119]
I had to change my notification settings in the webapp for it to work.

**Comment by MadLittleMods** [comment]
@weizlini Changing notification settings works the exact same way in the OSX app as it does in the webapp. Click the wrench and screwdriver icon in the top-right of each room -> Notifications -> Adjust any settings and exit the modal. Can you elaborate on what wasn't working?

**Comment by kbrock** [comment]
The notifications are working for me.

Is this still an issue?

**Comment by MadLittleMods** [comment]
I am going to close as they never stopped working as far as I can tell and @weizlini never elaborated.

**Comment by mattattaque** [comment]
Experienced the same issue. The issue with the OSX app is that the "Apply" button seems to have been forgotten. So while there is a menu to change notifications, there's no way to actually apply the changes. You're doomed to receive endless notifications unless you log into the web app and change notifications there, where there is actually a button to press that accepts your changes.

**Comment by kbrock** [comment]
Hmm. In the OSX app, in notifications for a room I see the "Apply" button.
Tested it under "next ui" and regular one.

Did you use notifications for something else?
Do they work for a group room?

**Comment by MadLittleMods** [comment]
@mattattaque @kbrock This is an issue with the safari-backed desktop app on an older version of OS X.

See https://github.com/gitterHQ/gitter/issues/1574
