### ISSUE TITLE
No way to view Activity pane when browser too narrow

### ISSUE THREAD

**Issue by lbjay** [gitterHQ/gitter#112]
Yay, responsive design, but the Activity pane needs some kind of manual open/close drawer handle.

**Comment by MadLittleMods** [comment]
The right toolbar activity pane area is no longer hidden at a certain breakpoint.

Instead it can now be collapsed/expanded/toggled at any time with the button in the top-right of the chat header.

![](http://i.imgur.com/PJ8HFE9.gif)
