### ISSUE TITLE
Android: pm a user for the first time

### ISSUE THREAD

**Issue by vadmeste** [gitterHQ/gitter#1120]
No way to send a message to a user when you did never exchange a message before

**Comment by trevorah** [comment]
Can you not find them through search?

**Comment by MadLittleMods** [comment]
Using the room search will find one to one user rooms.

**Comment by vadmeste** [comment]
Thanks it works.. Though maybe it was not that obvious.. The search icon next to Rooms label will just give a feeling that it can only search for rooms with many users.. What I suggest is to replace Rooms word by Conversations, and maybe replace Search icon by a button "New conversation" (+)

**Comment by MadLittleMods** [comment]
@vadmeste :+1: Create a a new issue. Currently it does seem like just an icon
