### ISSUE TITLE
Unable to open integrations and share modal

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1125]
When trying to open the integrations and share modals, nothing happens because a error is thrown in the JS.

[As reported](https://gitter.im/gitterHQ/gitter?at=56c5fe5739baba992473a9e8) by @rgolea and @bote795

**Comment by rgolea** [comment]
Has this been released?

**Comment by MadLittleMods** [comment]
This is now been hotfixed and is in production. Everything should be working now.
