### ISSUE TITLE
Distinguish between 400 and timeout errors when decorating issues

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1126]
When solving https://github.com/gitterHQ/gitter/issues/1089, we introduced a problem where sometimes a request to check issue existence can timeout or the user can go offline for a split moment which results in the issue not getting linked when you know it exists.

We need to distinguish between the different HTTP status code responses:

 - 400-499: Issue doesn't exist
 - 500-599: Link issue but don't decorate issue

---

note: This issue is outside of newly created issues showing up as non-existent which has to do with how we cache stuff from GitHub.

**Comment by mydigitalself** [comment]
Is this currently in progress as part of the work you were doing with @suprememoocow yesterday?

**Comment by MadLittleMods** [comment]
@mydigitalself nope, this was https://github.com/troupe/gitter-webapp/pull/1076 but when @trevorah was reviewing we decided on just decorating the issues as a link straight away no matter what.

@suprememoocow just fixed part of the issue with the response not coming through.
