### ISSUE TITLE
Unable to login  "E11000"

### ISSUE THREAD

**Issue by samayo** [gitterHQ/gitter#1127]
I have been unable to login to any room for a month now, I don't know what is the problem. 

I get this error. 
````
Login Failed

We're very sorry, but we're unable to log you in right now.
(E11000 duplicate key error collection: gitter.users index: githubId_1 dup key: { : 5304093 })
````

**Comment by MadLittleMods** [comment]
Hey @samayo,

This happens sometimes if you have you renamed your accounts? The problem is caused by someone having two Gitter accounts, userA and userB. They delete userA and rename userB to userA. We just needed delete the old userA entry in the db.

Send an email to support@gitter.im and please explain the whole situation and we can get this sorted: the account names and the renaming that took place(old and new account names). Also send us a email that was associated with the old accounts so we can verify it is actually you.

**Comment by samayo** [comment]
@MadLittleMods I haven't renamed anything. It just stopped on day without any cause. I used to log in to https://gitter.im/fastpress/fastpress a room I created and the github repo I created also. But one day it just stopped and now I can't log in to any room. My github username, email and repo names are all the same as they have been, even before I created the gitter rooms.

**Comment by MadLittleMods** [comment]
@samayo Are you sure you didn't do any renaming or deleting?

https://api.github.com/users/samayo is returning `"githubId" : 5304093,` which we previously had stored for a profile named `bivoc` (doesn't exist on GitHub currently)

**Comment by samayo** [comment]
Yes, my username was bivoc, but that was a long time ago. After I changed it to samayo, that is when I started using gitter, and created the gitter chat rooms. So, gitter should not even know anything about the username I had before using it the first time. 

Anyway, if you can fix the problem from your side it would be nice.

**Comment by MadLittleMods** [comment]
@samayo Thanks for the clarification on you actually doing a rename.

I have done some work. Can you try logging in again?

**Comment by samayo** [comment]
@MadLittleMods  It doesn't work. Thanks for trying, but I get the same error as always. This is the url to the error page. 

```
https://gitter.im/login/failed?message=E11000%20duplicate%20key%20error%20collection%3A%20gitter.users%20index%3A%20githubId_1%20dup%20key%3A%20%7B%20%3A%205304093%20%7D
```

**Comment by MadLittleMods** [comment]
@samayo Try it again, previously I removed/renamed `bivoc`. I just removed `samayo`.

**Comment by samayo** [comment]
@MadLittleMods  Nope :' 
I tried logging via multiple browsers, clearing sessions .. it's all the same. I get this error always. 

`https://gitter.im/login/failed?message=E11000%20duplicate%20key%20error%20collection%3A%20gitter.users%20index%3A%20githubId_1%20dup%20key%3A%20%7B%20%3A%205304093%20%7D`

**Comment by MadLittleMods** [comment]
@samayo Sorry for the iteration here. I just removed/renamed `samayo` away. Can you try signing in again?

**Comment by samayo** [comment]
It Works!! :+1:  thanks for all the hard work.
