### ISSUE TITLE
User Info Hover box not visible under "See All" modal

### ISSUE THREAD

**Issue by SaintPeter** [gitterHQ/gitter#1130]
If I click on the "See All" button for a room it brings up a modal which lists all of the users.  However, if I hover over a user's profile pic, the typical user info pop-up is under the modal.
![image](https://cloud.githubusercontent.com/assets/553494/13198731/8aa88f9a-d7c5-11e5-924e-2075f20d4358.png)

**Comment by MadLittleMods** [comment]
This has been fixed and will be available when we cut the next release.
