### ISSUE TITLE
Support custom CSS for theming

### ISSUE THREAD

**Issue by ochrons** [gitterHQ/gitter#1136]
It would be really nice to be able to customize Gitter client (web and desktop) via a custom CSS file.

Examples include improving legibility, changing fonts (especially for code blocks) etc.

Simple implementation would download a gist from user's Github account, so that users can do changes in whatever way they want. Provifing a gist-hash in the UI would enable this functionality.

Of course this is only for the _power users_ but it might also provide good input for the Gitter design team in general.

**Comment by MadLittleMods** [comment]
Sorry @ochrons, this isn't in the plans right now but there are a few options at your disposal.

You can use a browser plugins/extension:
 - [GitterThemer](https://chrome.google.com/webstore/detail/gitterthemer/fbakhnfjhdfielcjfmhfohodphiefnha) by @eskydar, [*source, GitHub project*](https://github.com/eskydar/GitterThemer)
 - Or the hundreds of options of more general options like Stylish, or Stylebot

If you are using the desktop app, you can use the [solution explained here to add custom CSS](https://github.com/gitterHQ/desktop/issues/28#issuecomment-187577244).
