### ISSUE TITLE
Desktop update notification annoyance

### ISSUE THREAD

**Issue by fwsGonzo** [gitterHQ/gitter#1141]
The update notification was not going away when I updated, and it got so bad I just had to remove the gitter client, so now I'm on the web client instead.

It's probably that the client wasn't restarted, but you know, I cracked. Web client.

**Comment by MadLittleMods** [comment]
@fwsGonzo We just updated the Gitter desktop app to v3.0.1. The old auto-update logic pings you every 5 minutes if it finds an update. We have updated the auto-update logic in v3.0.1 to only notify on startup and every 24 hours. This means that if you upgrade future, updates won't bother you.

**Comment by fwsGonzo** [comment]
:+1:
