### ISSUE TITLE
Search across all my rooms

### ISSUE THREAD

**Issue by kbrock** [gitterHQ/gitter#1151]
Sometimes I know a certain person said something, but I don't know in which context. Whether it is in a particular room or a 1:1.

So I click on the left hand side to change to each of my rooms and rerun the search.

Is there a way to search across all the rooms/1:1 on the left hand side?

Thanks

**Comment by mydigitalself** [comment]
There isn't, we've had an open request for this for a long time, but hasn't received many upvotes. Feel free to :+1: it. 

We are moving search over to the left quite soon in anticipation of bringing this out in the future.
