### ISSUE TITLE
It is not possible to click when hovering on the profile (appears on a different layer).

### ISSUE THREAD

**Issue by Egorvoz** [gitterHQ/gitter#1155]
The **[screenshot](https://yadi.sk/i/emxtcumppxa2L)** tells better than me. And this **_bug_** in every rooms and lists of members.
[Spare link for screen.](https://cloud.githubusercontent.com/assets/6547453/13563742/6f40576e-e455-11e5-9980-391bb4f886a2.png)

**Comment by trevorah** [comment]
Hi @Egorvoz, it looks like this has already been reported (https://github.com/gitterHQ/gitter/issues/1130). The fix should be live in the next day or so.
