### ISSUE TITLE
Top-right Mobile App Download Block

### ISSUE THREAD

**Issue by ricardobaeta** [gitterHQ/gitter#1156]
> ![explore-redesign-five](https://cloud.githubusercontent.com/assets/1746146/13526094/8ec2fc04-e1fd-11e5-943a-d478523d30bb.png)
> https://github.com/troupe/gitter-webapp/issues/1067#issuecomment-192246283

**Comment by MadLittleMods** [comment]
> ![explore-redesign-five](https://cloud.githubusercontent.com/assets/1746146/13526094/8ec2fc04-e1fd-11e5-943a-d478523d30bb.png)
> https://github.com/troupe/gitter-webapp/issues/1067#issuecomment-192246283
