### ISSUE TITLE
No connection, try again later error

### ISSUE THREAD

**Issue by richyvk** [gitterHQ/gitter#1166]
My Gitter Android app has stopped working. When I launch it, it just shows a blank rooms page and can't see any rooms I'm subscribed to.

Weirdly, I am still getting notifications though, and when I click on a notification I mostly get sent to the relevant room and can see posts.

I am using Android 6.0 on Moto G 3rd Gen, and version 2.5.4 of Gitter, although this problem first started using my Nexus 5, running Android 6.2.1.

**Comment by richyvk** [comment]
Just updated to version 2.5.5 and the problem seems to have gone away :)

**Comment by trevorah** [comment]
Hmm, the only change in that version was to fix a bug with lurked rooms. If this happens again, please let us know and I'll reopen this issue.
