### ISSUE TITLE
Multiple Android search buttons after clicking back

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#1177]
Reported via Twitter and I think has also been mentioned in `gitterHQ/gitter` 

> So many search buttons! One extra every time I press the back button on Android Marshmallow. 
> ![](https://pbs.twimg.com/media/CdaQVUtUIAAwAYW.jpg:large)
https://twitter.com/home_assistant/status/708912687741145088

**Comment by balloob** [comment]
The Twitter report was mine.

- I do not have guaranteed STR.
- I use Nexus 5x with the Android Marshmallow - February 1, 2016 release.
- It does not occur for me if I quit the app and open it.
- I have blocked Gitter notifications on Android. This means I only open Gitter via the app icon on my home screen.
- I use Gitter many times throughout the day.
- Issue is triggered by pressing the hardware back button when I have the channel overview activity open. It looks like sometimes the app history stack contains multiple entries for the channel overview activity.

**Comment by trevorah** [comment]
Thanks @balloob!

**Comment by trevorah** [comment]
@balloob this should be fixed in the latest release (2.6.0). Let me know if you see this happen again and i'll reopen this issue.
