### ISSUE TITLE
Disable desktop notifications but enable unread messages

### ISSUE THREAD

**Issue by sschaef** [gitterHQ/gitter#1178]
Since today, I receive a lot of desktop notifications that don't mention me directly. I don't have to say that they are really distracting.

For all rooms, I was in the now legacy mode "mention mode with lurk off", which meant to me that I received all messages (counter increased) but I only got desktop notifications if someone mentioned me directly. This feature no longer seems to be supported.

The notification setting "all" shows a desktop notification for all messages, the setting "announcements" disables desktop notifications but also disables the counter of unread messages. Is there a way to get back the old behavior?

**Comment by jvasileff** [comment]
I agree 100%. The old "mention mode, with lurk off" was perfect, whereas the new options make desktop and mobile notifications useless.

**Comment by MadLittleMods** [comment]
@sschaef There isn't a way to mimic the legacy mentions and disabled-lurk mode that counted unreads. The new `Announcements` setting is the new notification equivalent but not the unread-tracking equivalent. The unread horizon functionality is going to be improved in the future which I think will cover your use case. As you will be able to jump back to last message you saw. You can track this issue to know when the unread horizon gets updated: https://github.com/gitterHQ/gitter/issues/937

@jvasileff Why do you find them useless?

**Comment by jvasileff** [comment]
@MadLittleMods "All: Notify me for all messages" is clearly the right setting for usability of the mac app for rooms in which you are an active participant, and also to allow others in the room to see that you've read things. But then, you have to disable mobile alerts to avoid having your phone beep on all activity.

I really doubt there are many people at all that wish to have mobile alerts for all messages of active rooms. But being pinged when mentioned would be (was) useful.

**Comment by MadLittleMods** [comment]
@jvasileff This is a separate issue. The new notifications work we are doing will allow you to fine tune your settings on a per-platform basis (web, desktop, mobile, email, etc).

**Comment by jvasileff** [comment]
@MadLittleMods ok, that would definitely solve my biggest complaint.

Although, it would still be nice to have unread counts, etc. on both desktop and mobile, and be notified for only mentions on both desktop and mobile. I imagine some combination of wip features will help with this.

Thanks for being responsive and keeping us informed.
