### ISSUE TITLE
Add search results matching message sender name

### ISSUE THREAD

**Issue by matanster** [gitterHQ/gitter#1180]
I think there's no way of directly locating messages of yourself (or by any sender name?). Search results yield mentions, whereas it makes sense to allow searching by poster name. E.g. go find my post where I discussed this matter on https://gitter.im/gitterHQ/gitter. You probably can't (to avoid being mean, it [starts here](https://gitter.im/gitterHQ/gitter?at=56ea920b89dd3cce100743c3)).

**Comment by matanster** [comment]
Enabling this may be a foundation for addressing the more elaborate (and perhaps less basic) https://github.com/gitterHQ/gitter/issues/566

**Comment by MadLittleMods** [comment]
You can use `foo from:MadLittleMods`
