### ISSUE TITLE
Stuck in the same room in chrome for android

### ISSUE THREAD

**Issue by gboyega** [gitterHQ/gitter#1181]
When I navigate to gitter.im I am sent straight to https://gitter.im/FreeCodeCamp/FreeCodeCamp no matter what I do. And the menu on the top left corner doesn't work. There is no text box to enter messages. I can only see what others are posting. I don't want to download the app because the notifications can't be disabled or at least adjusted (to limit them to mentions only for example)

**Comment by mydigitalself** [comment]
This should be fixed now, please reopen if not.
