### ISSUE TITLE
Join channel on Favourite bug

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#1182]
Marking any channel as favourite automatically makes me join the channel.

#### How it should behave?
It should only pin the channel in the channel list

> P.S. I'm using gitter next with shiny new :sparkles: left menu bar but it applies for all.

**Comment by mydigitalself** [comment]
This is the way the backend works, you have to be a member of a room to join it.

**Comment by abhisekp** [comment]
@mydigitalself i don't wanna join it.
See https://github.com/gitterHQ/gitter/issues/1112
