### ISSUE TITLE
Room messages order bug

### ISSUE THREAD

**Issue by SerafimArts** [gitterHQ/gitter#1184]
Algo:
1. Take 10 messages from room
2. Iterate
3. After iteration save in memory first message in array
4. Send new new request with saving message as beforeId
5. See: 1.

Result: Around page ~35 I have broken result. Output ( id: text )

```
Page 34 before id 56f25a4ed8f8e9624e75ee1e

56f25a272d4bbff80a3fe1dc: @jhaoda я, по идее, что-то путаю, наверное. Как я понял - по кро
56f258e9ba45ef634e8da3c0: @Hunternnm или через крон, в зависимости от условий
56f25877e247956f1e30426b: @jhaoda т.е. нынче по фен-шую через Job'ы всё делать? 
56f25866ba45ef634e8da39e: _Спасибо (+1) для @jhaoda принято! Текущая карма **+745**._
56f25865ba45ef634e8da39c: @jhaoda ок, спасибо
56f257c2a80ca7f40ae331d3: @Hunternnm всё правильно мыслишь, просто в русской ветке 5.2 был
56f253f10d5edb734e672a31: Но вот читаю http://laravel.su/docs/5.2/queues и https://laravel
56f25395ddb288721eed3f86: @jhaoda может мне подскажешь... Нужно по таймауту парсить канал 
56f25291d8f8e9624e75ec58: _Спасибо (+1) для @jhaoda принято! Текущая карма **+744**._
56f25291ddb288721eed3f48: @jhaoda спасибо

Page 35 before id 56f25291ddb288721eed3f48

56f25291d8f8e9624e75ec58: _Спасибо (+1) для @jhaoda принято! Текущая карма **+744**._
56f25273673d92744ee056f9: @jhaoda то что надо доке только что увидел это
56f251f1ddb288721eed3f16: Дедушка имеет связь с папой, папа с сыном: `grandfather.father.s
56f2517fba45ef634e8da1f2: @arsen-s ты плохо доку читал. В модели, связанной через связь `t
56f251700d5edb734e6729a9: @jhaoda в моделе tag должен быть метод foo?
56f25128673d92744ee056a5: я читал конечно докуно все ровно не могу понять как правильно д
56f25127ba45ef634e8da1de: @arsen-s ну вон пример выше
56f250ff673d92744ee05695: @jhaoda у меня есть аттрибуты а у каждого аттрибута есть options
56f250dd2d4bbff80a3fdf87: `Products::with('tags.foo.bar')` чем не устраивает?
56f250b5673d92744ee05688: @arsen-s и зачем в with вкладывать with?
```

Watch to the message with duplicated id `56f25291d8f8e9624e75ec58`. In page 34 i have order `56f25291d8f8e9624e75ec58` then `56f25291ddb288721eed3f48`. In page 35 `56f25291d8f8e9624e75ec58` then `56f25273673d92744ee056f9`.

- Page 34 request: `/rooms/52f9b90e5e986b0712ef6b9d/chatMessages?limit=10&beforeId=56f25a4ed8f8e9624e75ee1e`

- Page 35 request: `/rooms/52f9b90e5e986b0712ef6b9d/chatMessages?limit=10&beforeId=56f25291ddb288721eed3f48`

**Comment by SerafimArts** [comment]
I can use `skip`, it is more reliable. But @mydigitalself complained about the slow execution of this method...

**Comment by SerafimArts** [comment]
> it is more reliable.

Its a joke `https://api.gitter.im/v1/rooms/52f9b90e5e986b0712ef6b9d/chatMessages?limit=100&skip=5100&access_token=***` (Room has more than 5100 messages, around 1 million)

Result: `{"error":"Bad Request"}`

Guys, no offense, but you've heard of unit tests? :smile:

**Comment by SerafimArts** [comment]
Ok, try to use in historical order. First message of this chat is `52f9b93e74e32f4a3c0000ec`. Example algo:
- Sets afterId = '52f9b93e74e32f4a3c0000ec'
- Take 100 messages & iterate
- Update afterId (sets id of last message in resulting array)

In page (chain) 27 (take 100 after id `53148e6a7bfe198c0c005e2e`) I have `5315e0dc6366e2284c0003f8` => `5315e0dc5394f4ec21000241` order.

In page 28 (take 100 after id `5315e0dc5394f4ec21000241`) `5315e0dc6366e2284c0003f8` => `5315e0eba92c3dfd21000990`

Error again

**Comment by MadLittleMods** [comment]
@SerafimArts While not documented, if you are going above 5000 on the `skip` parameter, it should be giving you a 400 with `Skip is limited to 5000 items. Please use beforeId rather than skip. See https://developer.gitter.im`

**Comment by mydigitalself** [comment]
@SerafimArts yip, we've heard of unit tests ;)

As per @MadLittleMods's comment, skip is incredibly inefficient as the database has to load the whole set of data into memory in order to skip and we've mentioned before that the **right** way to do this is with beforeId

**Comment by mydigitalself** [comment]
@SerafimArts any way you can include the json output from original post including a timestamp that the message was sent? My brain is hurting trying to figure it out with the Russian.

**Comment by SerafimArts** [comment]
> @SerafimArts any way you can include the output from original post including a timestamp that the message was sent?

Request (page) 64 before id 56eff00b4b41e04c4ffdf0aa limit 25
```
....
56efedc2c2ffd1c1211d950c: [created] 2016-03-21T12:49:06.620Z; [updated] ; [text] @kodermax ну массивы все равно ч
56efed94ba8673bf21a24694: [created] 2016-03-21T12:48:20.376Z; [updated] ; [text] не я классы не сериализую..
56efed83ba8673bf21a2468e: [created] 2016-03-21T12:48:03.502Z; [updated] ; [text] @kodermax "битрикса был глюк"
56efed62481556db4e6b53a7: [created] 2016-03-21T12:47:30.304Z; [updated] 2016-03-21T12:47:33.221Z; [text] @jhaoda @kodermax https://3v4l.o
56efed62ba8673bf21a24687: [created] 2016-03-21T12:47:30.223Z; [updated] ; [text] которая почту отправляет в табли
```

Requst (page) 65  before id 56efed62ba8673bf21a24687 limit 25
```
56efed62481556db4e6b53a7: [created] 2016-03-21T12:47:30.304Z; [updated] 2016-03-21T12:47:33.221Z; [text] @jhaoda @kodermax https://3v4l.o
56efed52481556db4e6b53a3: [created] 2016-03-21T12:47:14.715Z; [updated] ; [text] да у битрикса был глюк  водной и
56efed2fba8673bf21a24679: [created] 2016-03-21T12:46:39.094Z; [updated] ; [text] @kodermax а что за глюк то? А то
56efecc48984fd494f7fe1ee: [created] 2016-03-21T12:44:52.208Z; [updated] ; [text] не я не буду, видел глюк с ним о
56efecaa481556db4e6b537f: [created] 2016-03-21T12:44:26.718Z; [updated] ; [text] да в джобах он используется
```

![123123](https://cloud.githubusercontent.com/assets/2461257/14015446/20eb894e-f1ca-11e5-9e4f-474398b157ad.jpg)

**Comment by mydigitalself** [comment]
When you see it happening, does it only happen on messages that have been updated?

**Comment by SerafimArts** [comment]
@mydigitalself nope

![123123](https://cloud.githubusercontent.com/assets/2461257/14015946/cdd14cd6-f1cd-11e5-81a2-307e77dee1b4.jpg)

**Comment by mydigitalself** [comment]
What am I supposed to be looking at in that last screenshot, it appears to be the same as the previous one and also has the updated message highlighted.

**Comment by SerafimArts** [comment]
@mydigitalself press f5, I update it. (My mistake. I upload old screenshot)

**Comment by MadLittleMods** [comment]
@SerafimArts Are you still running into this? Just for sanity, can you give us another example with clear API calls, text output and pointing to what is wrong?

**Comment by SerafimArts** [comment]
Yes, but I can answer this question later. 

Now this code cant be runnig due to the global refactoring and import data - one of the last points for the completion of the plan of refactoring.

**Comment by SerafimArts** [comment]
@MadLittleMods what info about this problem you want? Just call `chatMessages` api command. You can watch the intersecting entites in different calls.

Example using this gitter api: https://github.com/SerafimArts/gitter-api
```php
$messages = [];
$token = '...';

$client = new Client($token);

$room = $client->http->getRoomByUri('gitterHQ/gitter')->wait(); // Get room info by uri

$iterator = $client->http->getMessagesIterator($room->id); // Get all messages in target room

foreach ($iterator as $data) {
    if (in_array($messages, $data->id)) {
        var_dump($data); // Dump message data
        throw new Exception('Message with id ' . $data->id . ' already exists');
    }

    $messages[] = $data->id;
}
```

**Comment by MadLittleMods** [comment]
Are you still running into this @SerafimArts ?

I can't reproduce with this demo with various rooms, https://jsfiddle.net/MadLittleMods/56kqgb72/ - Am I doing something wrong?

**Comment by SerafimArts** [comment]
This error is very rare. I think you can try to catch it in more than 200000-300000 messages in the room.

// I think your code is not wrong

**Comment by MadLittleMods** [comment]
If you can reproduce the issue again, feel free to comment and we can re-open.

**Comment by SerafimArts** [comment]
Ok, i trying to sync all messages with local db and repoen this issue if reproduce a problem. Thx =)
