### ISSUE TITLE
Request to rename rooms

### ISSUE THREAD

**Issue by ebkalderon** [gitterHQ/gitter#1185]
I'm new to using Gitter with organizations.

After two long days of work, I've transferred the `ebkalderon/amethyst` and `ebkalderon/amethyst_tools` repositories to a new GitHub organization and [created a bunch of channels](https://gitter.im/orgs/amethyst/rooms). See [this issue](https://github.com/amethyst/amethyst/issues/27) to see how the chat room layout was supposed to look like.

I created `general`, `tools`, `documentation`, and `engine` as normal channels. Unfortunately, the old `ebkalderon/amethyst` chat room transferred over and renamed itself `amethyst/amethyst`.

I was wondering if you could manually make the following changes:

1. Rename the `amethyst/amethyst` channel into `amethyst/general` while deleting the existing `amethyst/general` (I don't care if I lose the chat from the existing room).
2. Change [`amethyst/tools`](https://github.com/amethyst/tools) and [`amethyst/engine`](https://github.com/amethyst/amethyst) into repository channels, so that collaborators can be marked appropriately and all activity tracked in the sidebar. I don't want to lose the chat logs of either room.

How doable are these requests? Thanks and keep up the good work!

**Comment by MadLittleMods** [comment]
See https://github.com/gitterHQ/gitter/issues/1162,

I have moved your messages from `amethyst/amethyst` to `amethyst/general`. You can now choose to delete the the `amethyst/amethyst`, etc. Please note that the message transfer did not move the users.

**Comment by MadLittleMods** [comment]
Please note that you can add the GitHub integration to add to the activity section at any time in any room. Go to your room settings -> Integrations.

I have updated `amethyst/tools` and `amethyst/engine` to repo rooms but you still need to add the integration yourself if necessary.

**Comment by ebkalderon** [comment]
@MadLittleMods Thank you so much! I appreciate the help.

**Comment by ebkalderon** [comment]
Is the `engine ` room nearly finished being converted into a repo room? It is still not accessible.

**Comment by MadLittleMods** [comment]
@ebkalderon The conversion to repo room is a simple change in the db and was done when I commented.

Was the room accessible before? Can anyone else see it? This room/repo is private so I can't visit it.

Do you have private repo scope granted personally and for the org?

**Comment by ebkalderon** [comment]
@MadLittleMods Yes, the channel was public and the repo is still public, like the others. I did not create any custom private channels. Currently, it doesn't show up on our community page.

**Comment by MadLittleMods** [comment]
@ebkalderon This room and repo are not public, see https://github.com/amethyst

**Comment by ebkalderon** [comment]
@MadLittleMods I'm sorry, I think we may have a misunderstanding. There is no repo named `engine `, I wanted to make `engine ` a repo room for https://github.com/amethyst/amethyst. Does this make sends? Is it at all possible?

**Comment by MadLittleMods** [comment]
@ebkalderon Do you want `amethyst/engine` to be public?

We can't create a repo room for a repo of a different name. If you want activity, just add the integration.

**Comment by ebkalderon** [comment]
@MadLittleMods I didn't know that it's impossible to create a repo room named differently from the repo itself. I suppose I can keep it a normal channel and add the integrations. Could you please make the channel public again?

**Comment by MadLittleMods** [comment]
@ebkalderon I changed `amethyst/engine` back to a channel and made it public.

**Comment by ebkalderon** [comment]
@MadLittleMods I saw it reappear for a moment, but it's gone again.

**Comment by MadLittleMods** [comment]
@ebkalderon Weird, something must be changing it back. Does it disappear only when you try to visit/join?

**Comment by ebkalderon** [comment]
@MadLittleMods I don't know how, but it's back now!
