### ISSUE TITLE
chat input doesnt appear on android

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#1186]
* Moto X2
* latest Gitter app (assuming v2.5.6)
* app restart doesnt fix it
* leaving/joining doesnt fix it
* cannot reproduce on Android 4.4, 5.1 and 6.0

via @daryllabar

**Comment by trevorah** [comment]
So what version of android are you running, and do you see this in other rooms?

**Comment by daryllabar** [comment]
Hmm... I attempted to create a screen shot, while I was holding done the green join room bubble, and it fixed itself...

Now all rooms are working.  I'm running on Republic Wireless, so maybe some of there software was causing an issue?  Idk.

This can be closed

**Comment by trevorah** [comment]
How weird! Thanks for the report anyway @daryllabar, let me know if anything odd happens again.
