### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by Achifaifa** [gitterHQ/gitter#1189]
I just tried to use gitter via the website and I got a "414 Request-URI Too Large" error message. The url is 

`https://fail.gitter.im/jupyter/notebook?host=gitter.im&status=502&request=GET%20/jupyter/notebook%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/jupyter/notebook?host=gitter.im&status=502&request=GET%20/jupyter/notebook%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/jupyter/notebook%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/jupyter/notebook?host=gitter.im&status=502&request=GET%20/jupyter/notebook%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/jupyter/notebook?host=gitter.im&status=502&request=`

(same thing repeated several dozen times). That happens when accessing any url inside gitter.im

I get that error consistently, so it doesn't really look like an isolated thing. I have no idea what is causing this, but I'm willing to bet it's because something related to the processing of the user agent string.

I'm using iceweasel 38.5 in a debian machine (If it helps...)

Let me know if there is any extra information I can give.

**Comment by MadLittleMods** [comment]
What is the original URL you try to visit?

**Comment by Achifaifa** [comment]
It happens with any URL. No extra actions are needed, just trying to go to a url inside gitter.im makes it happen.

**Comment by MadLittleMods** [comment]
That is very strange :confused: 

Does it happen in other browsers or a incognito instance?

**Comment by Achifaifa** [comment]
It does happen in incognito. Haven't tried other browsers but I've been fiddling a bit and I think it's because of unicode characters in the user agent string.

It's a nginx error screen but in other pages using nginx the results vary, so I think it's because of the specific configuration in that page (But I don't really know how it works so I can't really offer a solution or anything)

**Comment by MadLittleMods** [comment]
@Achifaifa Were you signed in when it happened and when testing? Can you share a screen capture of what happens or a screenshot?

Can I try authenticating as you to try to reproduce what you are seeing? No credentials needed, just asking permission.

**Comment by Achifaifa** [comment]
No, to authenticate I need to access the page, but it doesn't even load. Here's a screenshot:

![](http://achi.se/share/url.png)

It happens every time, in every URL.

It may be beacuse of [this](https://twitter.com/jocmeh/status/714700505793105920) tho. Try changing your UA and opening gitter.im and see what happens (I don't have other computers to try this on right now)

**Comment by MadLittleMods** [comment]
This doesn't seem to be a Gitter issue. It looks like you are doing some odd stuff with some sort of network middleware or browser. Trying a custom random user agent string doesn't cause any issues for me.
