### ISSUE TITLE
Fedora / RHEL / Centos RPM distribution

### ISSUE THREAD

**Issue by RayFoss** [gitterHQ/gitter#1196]
The app is currently being distributed in a Debian only .deb file. Would love to see a distro agnostic distribution or better yet an RPM repo.

**Comment by MadLittleMods** [comment]
We currently do not put the linux desktop app on any package update repos. You need to download the latest from https://gitter.im/apps when you get the notification. We do want to improve the auto-update experience on all platforms in the future and this may be necessary.

**Comment by ranchow** [comment]
How soon do we expect a download for RPM based linux version?

**Comment by MadLittleMods** [comment]
@ranchow No plans or work at the moment. See https://github.com/gitterHQ/desktop/pull/44 and https://github.com/gitterHQ/gitter/issues/1283

Feel free to get an updated PR going.

**Comment by Gokul1201** [comment]
we want rpm repo file of gitters.....

**Comment by rayfoss** [comment]
A tar ball would be fine aswell... or at least stop remove the claims that Gitter supports Linux while the download links provide a very distro specif debian file. It's like giving a DMG file to a windows user.

**Comment by n370** [comment]
For now a solution is possible as described here https://ask.fedoraproject.org/en/question/65767/how-to-install-gitter-on-fedora-21/
