### ISSUE TITLE
Useful links tabs

### ISSUE THREAD

**Issue by jaumard** [gitterHQ/gitter#1197]
It can be nice to have a "useful links tabs" on the left with "Activity" for example we can have two tabs : 
Links and Activity. Links will be manage by admin and they will add links to getting started, useful tutorials website... Can help some developers to not ask something already ask before for example.

**Comment by MadLittleMods** [comment]
Hey @jaumard,

We have something in the works that covers this in a slightly different way.

For now, you can change the room topic to point to a getting started document that fleshes out further links.
