### ISSUE TITLE
Room order no longer updating - with `lastAccessTime` and unread activity

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1198]
Rooms are no longer bubbling to the top of the list when you get new activity.

Just to try to narrow down the change that caused the bug. I [first mentioned on 2016-3-22](https://gitter.im/gitterHQ?at=56f0df5250729b203be73a77), but it was there a few days before.

Also reported by @Fryguy in a ticket and @vadmeste, https://gitter.im/gitterHQ/gitter?at=56fea5b4d9b73e635f68618b

**Comment by mydigitalself** [comment]
I think lastAccessTime is a red herring here - it updates perfectly correctly in the new left menu, but not the old one. lastAccessTime **shouldn't** update when you get a new message btw.

cc @trevorah @suprememoocow
