### ISSUE TITLE
Change Name and URL of a Gitter Room

### ISSUE THREAD

**Issue by alayek** [gitterHQ/gitter#1200]
I created a room for a study group on Angular. But I made a spelling mistake and wrote room-name as "Amgular". So the room URL is now `https://gitter.im/alayek/Amgular`.

I have added a few people, and I don't want to kick them all out and create a new room, and add them again.

Is there a way I can change the room name and URL?

**Comment by suprememoocow** [comment]
Hi @alayek, I don't see a room called `alayek/Amgular` but I've renamed `alayek/AmgularAttack` to `alayek/AngularAttack`...
