### ISSUE TITLE
Notifications blocking text field [annoying]

### ISSUE THREAD

**Issue by AskYous** [gitterHQ/gitter#1206]
Hello,

It gets frustrating when I'm typing in the text box and a notification pops up and I can't see what I type. I have to constantly close them when I type. How do you guys get around this?

![image](https://cloud.githubusercontent.com/assets/791996/14391624/0828da16-fd72-11e5-85ab-1d15200634e9.png)

**Comment by MadLittleMods** [comment]
Notifications usually appear in the bottom-right of the monitor so it would only affect longer messages. It looks like they are appearing in a different position for you?

It personally never affects me as I have Gitter on the left-side of the screen.

**Comment by AskYous** [comment]
@MadLittleMods Aaah... I have my taskbar docked to the left. This is probably causing notifications to appear on the left. Thanks!

**Comment by MadLittleMods** [comment]
We can't control the position of desktop notifications so this is a bit out of our hands.

You can disable desktop notifications and still get the green fly-out banners in the UI if they are really bothering you.
