### ISSUE TITLE
"Unable to create channel" but still creates the room

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1207]
When you go through the create room modal flow, and press the create button, it shows a "Unable to create channel" error. Sometimes the new room is on your menu but most of the time doesn't appear until refresh.

**Comment by lerouxb** [comment]
aargh I see it. fixing now..

**Comment by lerouxb** [comment]
https://github.com/troupe/gitter-webapp/pull/1297/commits/92d39c480e7c74bf494da73a427dd4944b1eb57a
