### ISSUE TITLE
Error install on Ubuntu-based distro

### ISSUE THREAD

**Issue by darrrk** [gitterHQ/gitter#1209]
For example, Kubuntu.
**dpkg** throws error:
`/var/lib/dpkg/info/gitter.postinst: line 23: desktop-file-install: command not found`

    22 # Unity Launcher icon
    23 desktop-file-install /opt/Gitter/linux64/gitter.desktop

Problem, that it's hardcoded on Unity desktop.

**Comment by MadLittleMods** [comment]
@darrrk Create the issue here https://github.com/gitterHQ/desktop, feel free to make a custom build or submit a PR.
