### ISSUE TITLE
Color PR links the same as GitHub

### ISSUE THREAD

**Issue by chfast** [gitterHQ/gitter#1214]
GitHub colors merged PRs differently than closed PRs. Examples:
https://github.com/gitterHQ/node-gitter/pull/13
https://github.com/gitterHQ/node-gitter/pull/11

It would be nice to have purple links to merged PRs in Gitter chat.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/418
