### ISSUE TITLE
Is it possible to migrate or rename a room?

### ISSUE THREAD

**Issue by sibeliusseraphini** [gitterHQ/gitter#1216]
Is it possible to migrate or rename a room?

**Comment by MadLittleMods** [comment]
Hey @sibeliusseraphini,

We can move over the messages over manually.  Please note this won't move members over. Create the new room and send an email to support@gitter.im with the old and new room names. If it is a room under an org, make sure your org membership is public on GitHub.

We can also setup a redirect.

**Comment by sibeliusseraphini** [comment]
thanks
