### ISSUE TITLE
Main Chat Room per Organization or User (if they want)

### ISSUE THREAD

**Issue by michieriffic** [gitterHQ/gitter#1219]
I noticed that we can create rooms per specific projects. Why not create a Main Room not related to any specific project at Github?

It's the main Organization or Username chatroom and you can use the URL --> http://gitter.im/gitterHQ
where it shows a chatroom and all the activities happening within public repos in Github. Just like the other rooms. The only difference is that is it is not related to a specific project.

Also add a link or button that helps them navigate to all the rooms available which is the --> http://gitter.im/gitterHQ/rooms

**Comment by mydigitalself** [comment]
We already have this today, you can create a room for your organisation by clicking on the organisation at the bottom of your left menu. Note it won't automatically show activity happening within all the repos, you'd have to add the integrations manually.

You can also create any arbitrary channel you like, you can create `gitterHQ/jokes` which isn't tied to a repo.

There's also already a link in the header, next to the favourite icon, which will show a directory of all public rooms under the organisation.

**Comment by michieriffic** [comment]
Thank you :)
