### ISSUE TITLE
New UI: cannot switch from People to Rooms

### ISSUE THREAD

**Issue by SylvainCorlay** [gitterHQ/gitter#1220]
In the New UI, when loading gitter

 - from the URL corresponding to a user such as `https://gitter.im/SylvainCorlay`,
    the left toolbar appears empty and one cannot switch to another room.

 - However, when the first connection occurred via the URL of an organization or a repository such as https://gitter.im/gitterHQ, the left toolbar is working as expected.

**Comment by MadLittleMods** [comment]
If this is with the new UI (new left-menu), you should be creating issues here: https://github.com/gitterHQ/change

It sounds like you are [visiting a deleted user](https://github.com/troupe/gitter-webapp/issues/1075) but I can visit the user and move around just fine.

If you are still having this issue, can I authenticate as you and see what is going on? (no credentials needed, just asking permission)

**Comment by SylvainCorlay** [comment]
This occurs with any user and in a systematic fashion. The user URL that I took ad an example is me since I did not want to put anyone else's.

**Comment by MadLittleMods** [comment]
I can't reproduce.

Can you share a screen shot of what your [next.gitter.im](http://next.gitter.im/) shows?

**Comment by MadLittleMods** [comment]
I still can't reproduce.

There is an [existing issue about page-loading a one-to-one room](https://github.com/troupe/gitter-webapp/issues/1521) and it not being selected but you can still switch and see other rooms just fine.
