### ISSUE TITLE
Rickroll doesn't work

### ISSUE THREAD

**Issue by Haroenv** [gitterHQ/gitter#1221]
The last link on the [next](http://next.gitter.im)-page links to a rickroll video, but that one has been taken down. <https://www.youtube.com/watch?v=dQw4w9WgXcQ> is the most regularly used video, so it could be replaced by that.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/1148

**Comment by Haroenv** [comment]
sorry 👍
