### ISSUE TITLE
Push "private repo access" into separate flow.

### ISSUE THREAD

**Issue by tomchristie** [gitterHQ/gitter#1222]
Firstly, thanks for the stunning product - really great!

I've read the blog post about why Gitter requests write access to the profile, but I'd suggest considering altering the user flow so that 'private org access' isn't provided for unless the user has explicitly requested that.

I nearly stopped using Gitter immediately once it requested write access, although after denying it everything works absolutely fine for public repos, *which is all I want and exactly what I need*.

If "private orgs" had been a separate flow, I wouldn't have needed to see the "write access" request. For example "Create a room" could have separate "Create a room from a public repo" and "Create a room from a private repo", and only request write privileges in the later case.

In fact, the "Create a room" flow once bitter *does* have read-only access is already exactly as it should be - public repos are listed, and "create from a private repo" is a separate link.

Ensuring that your users don't see that flow unless they *absolutely* need to might be a nicer flow, as the 'write access' prompt is an absolute killer, and a point at which many of your potential users will simply walk away and potentially never come back.

**Comment by MadLittleMods** [comment]
Private repo access is already in a separate flow. How did you get into the private repo access flow? (curious on how it wasn't necessary for the case you came in through).

> Gitter Public Repo Access
>  - Read org and team membership
>  - Access user email addresses (read-only)


> Gitter Private Repo Access
>  - Read org and team membership
>  -  Full control of private repositories
>  -  Access user email addresses (read-only)

---

![](http://i.imgur.com/d69gRBQ.png)

![](http://i.imgur.com/MOVEpc8.png)

**Comment by tomchristie** [comment]
Agree with closing the thread in absence of exact replicable steps, tho making a reminder to myself to try to find some time and go through again in order to give a clearer step-by-step.

Thanks for the great service!
