### ISSUE TITLE
Need to rename a room on gitter

### ISSUE THREAD

**Issue by alayek** [gitterHQ/gitter#1224]
Hi, I created a room on gitter chat a few days ago and I would like to rename it. It's https://gitter.im/FreeCodeCamp/BackendChallanges

It should be https://gitter.im/FreeCodeCamp/BackendChallenges (**a** replaces **e**). How do I change that?

**Comment by MadLittleMods** [comment]
Hey @alayek,

We can move the messages manually if you create the new room. Note that won't move the members over.

**Comment by alayek** [comment]
Would it also move integrations?

**Comment by MadLittleMods** [comment]
@alayek No, only messages.

**Comment by alayek** [comment]
@MadLittleMods thanks! Please do. I have created the new room here: https://gitter.im/FreeCodeCamp/Backend-Challenges

Please move messages to this room and let me know. I would archive the previous room.

**Comment by MadLittleMods** [comment]
@alayek Done, I have moved messages from  `FreeCodeCamp/BackendChallanges` to `FreeCodeCamp/Backend-Challenges`

**Comment by alayek** [comment]
Thanks @MadLittleMods !
