### ISSUE TITLE
Two unneeded scrollbars in Firefox 45

### ISSUE THREAD

**Issue by nikola3244** [gitterHQ/gitter#1232]
![screenshot 3](https://cloud.githubusercontent.com/assets/15911110/14820439/f24467c0-0bc6-11e6-97b2-e298b10c34cd.png)
First one is on the left menu and second one is all the way on the right

**Comment by MadLittleMods** [comment]
Thanks for the formal report @nikola3244 

There are already [fixes](https://github.com/troupe/gitter-webapp/pull/1388) for these [issues](https://github.com/troupe/gitter-webapp/pull/1380)

**Comment by nikola3244** [comment]
@MadLittleMods  I'm getting 404 on both links

**Comment by MadLittleMods** [comment]
@nikola3244 As expected, links to internal PRs, just decided to share their existence.
