### ISSUE TITLE
Some messages hidden after I go back to read unread ones

### ISSUE THREAD

**Issue by jducoeur** [gitterHQ/gitter#1234]
I'm not 100% sure of the recipe here, but this has been happening to me quite frequently for at least the past couple of months.  Here's what I know:

* I look at Gitter, typically first thing in the morning.  (My Gitter tab is always open -- the recipe does not involve newly opening it, but might involve fronting it.)
* I enter a room with a lot of unread messages.  (The recipe *may* require 99+, but I'm not sure it does.)
* I click on the green label at the top of the message list, to go back to the beginning of the unread messages.
* I begin to read, slowly scrolling down as I do so.
* Somewhere along the line, I reach the bottom of the unread messages -- only it isn't actually the bottom.  As I *continue* to scroll down, and the last of the previously-unreads scrolls off the top, the "N unread messages" label at the top *re-appears*.  If I click on that, it goes back up, revealing a bunch more messages, right after the end of what I just read, that simply weren't there when I was originally scrolling down.

That latter bit is the bug: consistently, anywhere from a few to 50+ messages just fail to get loaded, so I scroll right on past where they should be, not realizing it until I get further down and the up-label reappears.  (I've learned to expect this if I notice a discontinuity in the timestamps.)

This recipe *may* require that additional messages are getting posted at the bottom while I am reading up above.  I haven't proven that yet, but given that this only happens sometimes, and it is only happening in relatively busy rooms such as scala/scala, I have a suspicion that it's part of the recipe...

**Comment by MadLittleMods** [comment]
Also reported here by @nafg :point_up: [May 14, 2016 11:29 PM](https://gitter.im/gitterHQ/gitter?at=5737fb29feb8cb327ee1e98b)

**Comment by jducoeur** [comment]
In re: @nafg's comment -- I'm quite sure that the problem has nothing to do with the new UI.  I've been having this problem for at least a month or two before the new UI came in.

I should also note, while I think if it, that I'm now pretty sure that it does *not* require 99+ in order to cause this symptom -- I've seen it a number of time when I only had 60-80 unreads.

I do tend to have a fairly heavily loaded connection and machine.  Is there anything unreliable in the protocol, where a dropped message could cause this?

**Comment by MadLittleMods** [comment]
Possibly related to https://github.com/gitterHQ/gitter/issues/1184

**Comment by jducoeur** [comment]
Possible, although I don't need to go back terribly far for my problem to occur -- it's often happening when I have only ~60 or so unread messages...

**Comment by nafg** [comment]
Lately this seems to be very consistent behavior:

1. I go to a room that has 100 (haha) unread messages
2. Gitter takes me to the end, immediately causing the last screenful to be marked read (arghhh)
3. I click on the ":arrow_up_small: 86 unread" to go to where gitter thinks I left off
4. I start reading down, the green fading away as I go, scrolling more and more
5. At some point an indicator appears: " :arrow_up_small: 46 unread"
6. I click the indicator. I'm sure those messages weren't there before! I repeat step 4.
7. At some point an indicator appears AGAIN: " :arrow_up_small: 22 unread"
8. Repeat step 6.
9. I get to the end

Note that step 9 can occur between steps 5 & 6, i.e. only click the the 46 indicator after I get to the bottom.

I'm not sure about 86, but 46 and 22 seem to be pretty consistent.

PLEASE FIX THIS ASAP

**Comment by jducoeur** [comment]
Yep -- @nafg's description is pretty much identical to my experience.  (Indeed, while I hadn't thought about it before, those numbers sound familiar: the "breakpoints" in the experience may be at least semi-consistent.)  But I'm also sure that this isn't new: I was seeing this behavior for at least a month or two before the new UI rolled out.

Overall, it's the biggest annoyance about using Gitter -- and since I often spend something like an hour a day on Gitter, it's pretty significant...

**Comment by MadLittleMods** [comment]
Reproduction from @dmeltzer :point_up: [July 29, 2016 6:00 PM](https://gitter.im/gitterHQ/gitter?at=579be00f80e833723ffb86f4)

**Comment by mevsme** [comment]
It affects me too. My internet is not the fastest in the world, so it's really an issue to me.

**Comment by siriniok** [comment]
It is confirmed and easy reproducible issue, so I think it should be labeled as a `bug` at least.

**Comment by jducoeur** [comment]
Yeah, I'm a bit mystified how this has gone untriaged for so long.  As a heavy Gitter user (I spent over an hour a day actively using it), this is by *far* the most annoying bug in the system...

**Comment by MadLittleMods** [comment]
I have reproduced this multiple times in the past but I am investigating this now and having trouble reproducing to debug the situation.

Are you still seeing this bug regularly? Any extra details for consistent reproducibility would be awesome.

**Comment by jducoeur** [comment]
Actually, I was going to comment on that.  This stopped happening to me sometime recently -- I first noticed two days ago, and I started paying attention, but I haven't seen a repro since, even though it was happening pretty frequently before.  Behavior could have shifted any time in the past week or two.

Smells like somebody fixed some apparently-unrelated bug that was actually the same thing?

**Comment by MadLittleMods** [comment]
Potentially, will roll back a few weeks and try it out.

I did make [this fix](https://github.com/troupe/gitter-webapp/pull/2107) for scrolling sequentially that touches the `infinite-mixin` for collections but you would have seen some errors in the console if that was affecting this. That fix was part of [release 17.9.0](https://github.com/troupe/gitter-webapp/pull/2163) which rolled out 2016-9-30 for `next` and 2016-9-31 for `prod`.

```
chat-collection live collection error TypeError: response.map is not a function(…)
```

**Comment by jducoeur** [comment]
"console" as in the browser console?  I don't think it's ever occurred to me to open that on my Gitter window (I usually have 50ish tabs open, so I usually only use the console for my own product), so it's possible that there were errors and I never noticed them.

Certainly the timing for that fix is plausible for when I stopped seeing the problem.  (I don't have access to the PR, so I can't evaluate whether it seems like a likely match from a code POV.)

**Comment by MadLittleMods** [comment]
@jducoeur Yes the browser devtools console. Linking the issues/PRs for my own reference and so you can see/assume there are real things happening 😀 

Rolling back a few weeks and I can instantly reproduce and I can see the error [I mentioned previously](https://github.com/gitterHQ/gitter/issues/1234#issuecomment-245741865) in the console.

```
chat-collection live collection error TypeError: response.map is not a function(…)
```

Note the missing messages between 100 and 120.

![](http://i.imgur.com/AzDKcyW.gif)

Sorry for such a slow response on this. It's difficult convincing others to get this into the cycle and was recently pushed after another team member experienced it after coming back from vacation. Really appreciate the bumps and others giving :+1: reactions.

**Comment by jducoeur** [comment]
Understood -- these things are always challenging.  Happy to have it fixed, though -- thanks!
