### ISSUE TITLE
Activity right-toolbar overlaps people roster

### ISSUE THREAD

**Issue by McPringle** [gitterHQ/gitter#1235]
The button to add new users to the chat is hidden by the label of the activity stream:
<img width="306" alt="bildschirmfoto 2016-05-01 um 12 38 42" src="https://cloud.githubusercontent.com/assets/1254039/14941404/38abf602-0f9a-11e6-8a3b-4bab224c4879.png">

**Comment by MadLittleMods** [comment]
A fix has already been added and will be in the next release.

**Comment by raisedadead** [comment]
Thanks @MadLittleMods for the update!
