### ISSUE TITLE
Text selection handles are white (instead of blue) - invisible

### ISSUE THREAD

**Issue by cbj4074** [gitterHQ/gitter#1241]
With the Gitter Android **app**(LG G4 with Android 6.0), when I press-and-hold, to highlight some text from the chat, the little handles that allow me to adjust the selection are white, and therefor nearly invisible against the white chat background.

**Comment by MadLittleMods** [comment]
:+1: I can reproduce on Android 5 and 6. They are blue in the Android Chrome though.

**Comment by MadLittleMods** [comment]
Actually, it looks like the recent release v2.9.1 fixes this issue and makes the handles caribbean green.

![](http://i.imgur.com/4RQCbwk.png)
