### ISSUE TITLE
Gitter detects some public rooms as private

### ISSUE THREAD

**Issue by kuza55** [gitterHQ/gitter#1247]
Gitter seems to detect some public repos as private.

One example would be https://gitter.im/google/password-alert where the underlying repo is public https://github.com/google/password-alert

**Comment by MadLittleMods** [comment]
Not every repo has a room on Gitter. It is up to someone with push access to create the Gitter room.

There isn't a room for that repo.

**Comment by kuza55** [comment]
Ah, you might want to make your errors clearer at least.

Though it's disappointing that you can't talk to other people about a project without one of the repo authors opting in.

**Comment by MadLittleMods** [comment]
@kuza55 Community owners sometimes have other means of support and don't want to maintain or dilute their existing setup. For example, they may only want support questions for their framework to be on StackOverflow and development talk around the project to be in GitHub issues.

You are free to create your own room but we understand it isn't the same as a direct connection and the same URL.
