### ISSUE TITLE
Force users to read a popup before entering a room

### ISSUE THREAD

**Issue by agibsonccc** [gitterHQ/gitter#1256]
The top notice of a room doesn't seem to get read. We would like the ability to enforce a read through of a notice before entering a room.

**Comment by MadLittleMods** [comment]
Stay tuned, we plan to [add a customization welcome message](https://github.com/troupe/gitter-webapp/issues/1346) just as you are describing.

**Comment by mydigitalself** [comment]
Yip, we're working on this right now!

**Comment by mydigitalself** [comment]
This is now on Next (https://gitter.zendesk.com/hc/en-us/articles/203904511).

If you click on the room options icon (top right) and choose Settings, you can set a welcome message there. It supports Markdown. Easiest way to test is to leave the room, open the room again and don't join it. As an admin you can still edit the settings without being in the room, so edit the settings, click Join and see what happens.

We're going to add a preview to it very soon to make that process easier, but for now at least you can do something. It will only be displayed to people on Next at the moment - but will be live to everyone in a day or two.
