### ISSUE TITLE
Keep chat messages as main focal-point in search view

### ISSUE THREAD

**Issue by nomadme** [gitterHQ/gitter#1257]
This is my suggestion for improving the experience on Search panel.

Current layout brings out few problems that would make someone logically follow and read without putting much effort. When you query, it shows "Rooms and People" section first and "Chat message" below it. This pulls away users focus on what they were looking for, since the top area taking quite a bit of the space from the panel, making the main chat queries being pushed down, hard to be noticed/read what you were looking for.

I specially believe, main purpose of a search box/panel is to be: 
1. Quick and Easy way to find what you need
2. It need to add functionality, not distraction

I couldn't think of much scenarios where people search about "Rooms & People" all the time. It would add more positive experience if "Chat message" shows up on top of "Rooms and People", OR have tabs for scope of queries.

**Comment by MadLittleMods** [comment]
Putting Rooms and People below chat messages would put it way below the fold hidden in the overflow to not be noticed for many people.

It could perhaps be a tabbed system to switch between the different types of results though.

**Comment by nomadme** [comment]
yeah, that might be a better way to separate the scopes and concise solution for both areas.
