### ISSUE TITLE
Unable to switch rooms in MS Edge

### ISSUE THREAD

**Issue by nponeccop** [gitterHQ/gitter#1270]
It worked before, but now when I click on a room I cannot switch to it. The only method of switching is typing the URL. It works in Firefox. Also I minimized the menu and now cannot make it persistently maximized again. I'm not sure if the latter is worth a separate issue as it is an Edge-specific regression too.

Steps to reproduce:

- open gitter
- minimize the left side bar
- reopen gitter
- click on an icon to expand a submenu
- click on an item to attempt navigation to a room

Expected behavior: the room is opened
Actual behavior in Edge browser: nothing happens

**Comment by MadLittleMods** [comment]
@nponeccop A fix just rolled out to prod. Ping if you are still seeing the issue.

**Comment by nponeccop** [comment]
@MadLittleMods works for me. Good job!
