### ISSUE TITLE
Unable to create room for organization

### ISSUE THREAD

**Issue by CoinGame** [gitterHQ/gitter#1273]
I'm unable to create rooms for the organization http://github.com/bc-exchange which I am and admin of.

This was an organization which I had to add using the manual process described here: https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-

Permissions for private and public repos are added for this organization on both of these pages:
 - https://github.com/settings/applications
 - https://github.com/organizations/BC-Exchange/settings/oauth_application_policy

I'm able to create rooms for other organizations which I am an owner of, but not the one mentioned above. You can see the error message below when I try to create a room:

![image](https://cloud.githubusercontent.com/assets/7383066/15649318/891a0824-2668-11e6-8cd9-9c2f227c642e.png)

---

Discussion here :point_up: [May 29, 2016 5:12 PM](https://gitter.im/gitterHQ/gitter?at=574b696280352f204df33ef7)

**Comment by MadLittleMods** [comment]
:+1: I am able to reproduce with only one of my orgs but it seems to work just fine with all of the others.

cc @suprememoocow about the room policy changes

**Comment by suprememoocow** [comment]
Hi @CoinGame, 

We use [this api](https://developer.github.com/v3/orgs/members/#check-membership) to check your (published or private) organisation membership, using your public access token. 

For some reason, when I call this api with your account (using either of your tokens), I get an `HTTP 302` response, meaning that -- *as far as Gitter's OAuth scope allows us to tell* -- you are not an organisation member (hence the denial of access)

Please could you double-check your third-party access settings, particularly for the Gitter Public Repo access token. 

As an extra check, I've also checked some other GitHub APIs (for example `/user/teams` and `/users/:username/orgs`) and can't find any reference to `BC-Exchange` being returned from the GitHub API.

If we're unable to resolve this, we'll try escalate it to the GitHub support team.

**Comment by CoinGame** [comment]
Hey thanks for all of the details. Gives me some points to troubleshoot on my end. I'll do a bit of digging and let you know what comes up.

**Comment by MadLittleMods** [comment]
@suprememoocow 

This might be an issue of using the wrong GitHub token but also something fishy seems to be happening.

As stated before, I can only reproduce with one of my orgs(`EricTroupeTester-Org`) but I have two test orgs where I am member of that org but my membership isn't public. 

 - Private membership: `https://api.github.com/orgs/EricTroupeTester-Org/members/MadLittleMods`
    - Using `githubUserToken`, responds with 204 :white_check_mark: 
    - Using `githubToken`, responds with 404 :x:, `User does not exist or is not a public member of the organization`
    - Some random personal token, responds with 204 :white_check_mark: 


 - Private membership: `https://api.github.com/orgs/EricTroupeTester-Org2/members/MadLittleMods`
    - Using `githubUserToken`, responds with 204 :white_check_mark: 
    - Using `githubToken``, responds with 204 :white_check_mark: 
    - Some random personal token, responds with 204 :white_check_mark:


It is a bit strange the endpoint fails only for `EricTroupeTester-Org` with the `githubToken`. The only difference I can see between my membership in the test orgs, is that I don't have any repository access on `EricTroupeTester-Org2`.

**Comment by CoinGame** [comment]
I unfortunately don't have a lot of time to play around with this. I can say that I was able to create the room after making my membership public on the organization.

**Comment by MadLittleMods** [comment]
This seems to be a GitHub API issue.

**Comment by MadLittleMods** [comment]
Just tested this again to confirm.

To clarify, I am testing from `MadLittleMods` tokens:

 - Private membership: `https://api.github.com/orgs/EricTroupeTester-Org/members/MadLittleMods`
    - Using `githubUserToken`, responds with 204 :white_check_mark: 
    - Using `githubToken`, responds with 404 :x:, `User does not exist or is not a public member of the organization`
    - Random personal token [without any specific scopes selected](http://i.imgur.com/fKzroGC.png), responds with 404 :x:, `User does not exist or is not a public member of the organization`
    - Random personal token [with repo scope selected](http://i.imgur.com/PFM5an5.png), responds with 204 :white_check_mark: 


 - Private membership: `https://api.github.com/orgs/EricTroupeTester-Org2/members/MadLittleMods`
    - Using `githubUserToken`, responds with 204 :white_check_mark: 
    - Using `githubToken`, responds with 204 :white_check_mark: 
    - Random personal token [without any specific scopes selected](http://i.imgur.com/fKzroGC.png), responds with 404 :x:, `User does not exist or is not a public member of the organization`
    - Random personal token [with repo scope selected](http://i.imgur.com/PFM5an5.png), , responds with 204 :white_check_mark:

**Comment by MadLittleMods** [comment]
@CoinGame Can you take a image of what your https://github.com/organizations/BC-Exchange/settings/oauth_application_policy page shows? I am not convinced you actually granted "Gitter Private Repo Access"
