### ISSUE TITLE
"Done" keyboard button should not send message

### ISSUE THREAD

**Issue by momothereal** [gitterHQ/gitter#1274]
Currently, using the Gitter app for iOS, pressing the Done button while writing a message will send it automatically; I think it should just hide the keyboard like other apps do.

Other than that, switching to another app and back to Gitter also sends the message, which is quite annoying when trying to copy a link.

**Comment by MadLittleMods** [comment]
This has to do with the app not using a native keyboard so when you focus away, it sends a message. See https://github.com/gitterHQ/gitter/issues/705
