### ISSUE TITLE
Webfont too slow to load in desktop apps

### ISSUE THREAD

**Issue by viki53** [gitterHQ/gitter#1276]
Hi,

The title is pretty explicit, but here it is:

When opening the app (which happens pretty often, as I often keep it closed so that I just get the notifications, without having the window hanging around) the text takes a *long* while to show up.

The font used in the app takes a long time to load, meanwhile (almost) no text appears, which is far from ideal.

I'm on a pretty good DSL connection, so it's not related to its speed.

See following screenshot for a more precise idea of the result I get:

![Gitter loading without text appearing](https://cloud.githubusercontent.com/assets/1763364/15725776/b7e08f7a-284d-11e6-87bc-55fdf19e7774.png)

**Comment by MadLittleMods** [comment]
:confused: The web font should be in your cache after you download it the first time.

The buttons on the right that are rendered use this font stack `'Source Sans Pro', source-sans-pro, pt sans, calibri, sans-serif` which will use your locally installed version first.

The rest of the page uses `source-sans-pro,-apple-system,Roboto,pt sans,calibri,sans-serif` which we can update to be the same stack.

We have an [issue internally](https://github.com/troupe/gitter-webapp/issues/1251) about certain things not being rendering until a forced paint but this seems more like a FOUT issue (as I assume the font loads in for you eventually).

**Comment by viki53** [comment]
The font does load, but it doesn't seem to stay in cache, as I get the same issue every time I reopen the app window.

What's weirder is that all the avatars and images load up before the font.

I get approximately the following timeline:
* 4s: window is open
* 13s: all images (avatars, icons…) are displayed
* 20s: webfont is loaded and painted

So it takes about 20 seconds before I am able to read a single message.

I'd be happy to give you more details if I can access the DevTools window somehow…

**Comment by MadLittleMods** [comment]
@viki53 You can [enable devtools using the option in the top bar](https://i.imgur.com/SmPWvju.png). Then you can inspect element or even debug from Safari itself through the `Develop` menu.

**Comment by viki53** [comment]
I did both those things, but Gitter doesn't appear in Safari's `Develop` menu. Weird.

Although my Mac has some issue since I last rebooted it, so I'll try again later (after I reboot it) and let you know

**Comment by mydigitalself** [comment]
Well, this would probably go a long way to explaining it. Seems like the embedded WebView isn't respecting cache hits...

<img width="552" alt="screen shot 2016-06-02 at 10 26 02" src="https://cloud.githubusercontent.com/assets/1491887/15740378/8a57d43c-28ac-11e6-8525-e3725d397bc6.png">

**Comment by viki53** [comment]
Or maybe the webfont should be embedded inside the app, like the icons and styles.

That way it can load in an instant, without requiring an Internet connection.

**Comment by mydigitalself** [comment]
The desktop apps are currently purely browser shells that load the entire webapp, otherwise if you do CI and CD (as we do) you'd have to update the desktop binaries constantly. 

The cache should work and works fine in Safari, Chrome and other desktop apps, will have to investigate why it's not working. I assume you're on El Capitain? Apple did change some Webview behaviour recently and perhaps we missed something that's changed regarding the caching defaults.

**Comment by viki53** [comment]
I am, indeed, on the last version of the OS.

I'll probably reboot it tonight as I also have graphic rendering bugs all around the system since the last system update. I'll see if that changes anything.

**Comment by suprememoocow** [comment]
@viki53 thank you so much for bringing this to our attention. 

You were correct. The OSX desktop client was indeed doing a shoddy job of caching things. 

I've built a new preview release of the Desktop Client which should hopefully correct this issue. 

Would you mind trying it out and giving me your feedback.

Keep in mind that the first time you open the client it'll still need to cache the resources, but after that it should be a lot quicker.

**Comment by suprememoocow** [comment]
@viki53 actually, there's a second problem, on the server-side too. I'll look into that ASAP.

**Comment by viki53** [comment]
Hi,

I downloaded the Beta app, got the following screen for a bit, then everything was incredibly slow. The sign-in screen from GitHub took almost 30 seconds to open up, meanwhile I thought the app was buggy.

![capture d ecran 2016-06-02 22 58 02](https://cloud.githubusercontent.com/assets/1763364/15760903/be01732e-2915-11e6-9651-f1592ff1f720.png)

But the issue is still present: the font takes a long while to load on the second opening.

Also, when I try to resize the window to make it wider, it keeps moving around, going back to the same place and getting narrow again.

**Comment by mydigitalself** [comment]
Have you tried this again recently? The caching should be a lot better now.

**Comment by MadLittleMods** [comment]
> Hi folks. We've made some recent updates to the Gitter OSX application mainly focused on performance, particularly for users on slow internet connections. The new version is much better at caching and with an upcoming server-side update, won't need to download webfonts from the server any more.
> There are also a few smaller bug fixes.
> We have a release candidate, but it hasn't been pushed to the main auto-update channel yet.
> If you would like to give it a try you can download it from here: https://s3.amazonaws.com/update.gitter.im/osx/Gitter-1.176.dmg
> Also, if theres anybody using an old-ish version of OS X, would be great if you could confirm that it's working for you.
Thanks!
>
> [*source @suprememoocow*](https://gitter.im/gitterHQ/gitter?at=57616af8ea84f717479b916a)

**Comment by viki53** [comment]
Seems indeed much faster! 👍 

Not perfect yet (some parts still take some time to be properly painted), but it's way better than it was.
