### ISSUE TITLE
Firefox: clicking on "open chat" in mail notification displays a blank page

### ISSUE THREAD

**Issue by xem** [gitterHQ/gitter#1279]
Hello,
When I receive a Gitter new message notification on Gmail and click on "open chat" on Firefox, the conversation doesn't appear. Instead, I get a blank page and I have to hard-refresh the page to see the discussion.

Example: 

I click on this link in my e-mail:
http://mailtracking.gitter.im/track/click/30050491/gitter.im?p=eyJzIjoiN0pOWW1QbjVsTk9sVDRfUGdwaV8wSkwwUXlnIiwidiI6MSwicCI6IntcInVcIjozMDA1MDQ5MSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2dpdHRlci5pbVxcXC94ZW1cXFwvTWluaVNoYWRlcnRveSN1dG1fc291cmNlPW5vdGlmaWNhdGlvbiZ1dG1fbWVkaXVtPWVtYWlsJnV0bV9jYW1wYWlnbj11bnJlYWQtbm90aWZpY2F0aW9uc1wiLFwiaWRcIjpcImQyYjk5ODAxM2UwNzRiMTE4ZGMxOGMzMDUxNDg0ODZlXCIsXCJ1cmxfaWRzXCI6W1wiOWU0NjU4NzZiYTUwYzg0NWI1Y2YwZmM2ZjFkMzhmMWRhYzlmZjc3ZFwiXX0ifQ

And arrive on this url:
https://gitter.im/xem/MiniShadertoy#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications

And see only the sidebar.

Thanks!

**Comment by MadLittleMods** [comment]
Do you see a page when you visit https://gitter.im/xem/MiniShadertoy ?

That link and room loads just fine for me. Can you check the devtools console for any errors?

**Comment by xem** [comment]
Hello, thanks for your answer. Yes, goind directly to the chatroom works fine, it's only when I click on the url(s) above that I see nothing. See attached a screenshot with my console open (excuse my french)
![bug](https://cloud.githubusercontent.com/assets/1225909/15747039/3be6dc80-28d9-11e6-947a-759d92557e46.png)

**Comment by MadLittleMods** [comment]
Everything looks pretty fine there. Just to translate those errors:

 - The connection to wss://ws-staging.gitter.im/bayeux was interrupted while the page was loading.
 - Firefox can't establish a connection to the server at wss://ws-staging.gitter.im/bayeux.
 - Image loading over insecure

---

 - Does it happen in other browsers?
 - Does it happen in an incognito instance of Firefox without any extensions?
 - When you inspect element in the black area, is there an iframe?
 - What do you get when execute `window.location.href` in the devtools console with the iframe context, ([here is how you switch to the iframe context](http://i.imgur.com/chcPtmj.png))

**Comment by xem** [comment]
Damn. It was AdBlock Plus. Disabling it for all the fomain gitter.im fixes the problem. Thanks!
