### ISSUE TITLE
Gitter starts and then closes down.

### ISSUE THREAD

**Issue by lambainsaan** [gitterHQ/gitter#1280]
I am using Windows 10 build KB3152599. I am not able to start gitter, I am not sure what I messed up because the same version was working fine a few days ago. Gitter starts for a moment and then closes automatically in a second or so. I am facing a similar problem with Firefox, by the way all other softwares are working totally fine. Maybe I have removed some dependencies while I was uninstalling some programs. 

Could you help me with this?

**Comment by MadLittleMods** [comment]
Hey @lambainsaan,

You can setup logging and try to see something obvious, https://github.com/gitterHQ/desktop#enabling-logging-on-windows

Or you can start up the app with debugging enabled. `gitter.exe --remote-debugging-port=1234` and visit `localhost:1234` to inspect the instances.

But if you are having problems in general with your computer, it would be too hard to debug.
