### ISSUE TITLE
Difficult to differentiate 'org' room from 'repo' room with same name

### ISSUE THREAD

**Issue by dregad** [gitterHQ/gitter#1281]
Consider the (quite common) case of an organization using it's *org* private room, and having a _repository_ bearing the same name as the org itself.

In this situation, the UI makes it impossible to differentiate the 2 rooms:
![selection_002](https://cloud.githubusercontent.com/assets/449891/15804553/34016874-2b0d-11e6-81d9-6d01c00f077d.png)

**Comment by MadLittleMods** [comment]
We truncate the org name if the overall room name is too long but have been doing some work to add some lock icons to private rooms. Just to note this solution only works to distinguish if the repo is public which in the majority of cases is where this happens.

**Comment by dregad** [comment]
That would be perfect actually. Thank you. 
Any ETA for go live?

**Comment by MadLittleMods** [comment]
This was solved on 2016-8-12 by showing the full URI if the room name matches the group name and ellipsing as necessary, see https://github.com/gitterHQ/gitter/issues/1350


>  - If `roomName = groupName`, then do cunning ellipses thing
>
> [...]
>
> ![](http://i.imgur.com/2ZtfpcV.gif)
>
>https://github.com/gitterHQ/gitter/issues/1350#issuecomment-243312475

**Comment by dregad** [comment]
Awesome, thanks !
