### ISSUE TITLE
Make it really easy to search the current chat room and get informative results

### ISSUE THREAD

**Issue by benhutchison** [gitterHQ/gitter#1282]
https://gitter.im/typelevel/cats is a busy chat room with a huge and valuable back archive. Ive often gone to ask a question there and thought "I really should check if this has been discussed before..". more often than not it has.

Its not easy. The current gitter search functions feel a bit like a toy. heres why:

- They show "Room and People" over the top 50% of the screen. Im trying to do research and it's showing me completely irrelevant rooms Im not even a member of!  Thats a separate function for a very different purpose, please dont "bundle" them in a 2 for 1 offer.

- You need some docs on how search works. What is the result ordering, and how can I control it? How are terms treated; and, or, scored? How many total results are there.

- I trust googles search a whole lot more than Gitter's ATM. Unfortunately, Google indexing seems disabled in gitter, even though the chatrooms are public. If you're going to turn the googlebot away, you must provide decent search yourself.

I'm trying to use the feature for real world research and its frustrating and underpowered.

**Comment by MadLittleMods** [comment]
Search is an area we know needs work and realize it is a bit of pain to get desired results. It is definitely something we will be tackling in the future.

I created a milestone with various search issues that have been raised, https://github.com/gitterHQ/gitter/milestones/search-label

#### UI

 - Track https://github.com/gitterHQ/gitter/issues/1257


#### Searching

 Search is based on natural language and I am pretty sure it is a pretty simple elasticsearch query. Here are some tricks:
 
 - `from:username`: Find messages from user
 - `*`: wildcard
 - `@user`: Find messages that mention a user like yourself
 - Some characters need to be escaped `\`

Results are currently ordered by how they scored in relevance. You can track this issue for sorting/ordering options like date descending, https://github.com/gitterHQ/gitter/issues/566



#### Google Indexing

Indexing is turned on by default but a room owner can turn it off in the archive pages.

![](http://i.imgur.com/T0jSyBq.png)

**Comment by MadLittleMods** [comment]
Closing in favor of the individual issues. If there isn't an issue that covers something what you brought up, feel free to raise individual issues.

**Comment by ehernandez-xk** [comment]
Hi, What is the status of this?

I belong to this room https://gitter.im/drone/drone

The room has a lot of memberd and daily they write a tons of chats, I want to search before to ask.

Thanks.

**Comment by mydigitalself** [comment]
You can search the current room using the search icon on the left of the UI.

**Comment by macropin** [comment]
I also came here from the `drone/drone` room. The only search solution I've found is to use google:

[google.com/?q=site:gitter.im/drone/drone](google.com/?q=site:gitter.im/drone/drone)

**Comment by Mark-L6n** [comment]
Looking at the other search issues linked to above, none address the much-needed subject of this issue, searching the current chat room.  This is big—people need to see if a question has been asked before asking a question.  IMHO you should re-open this issue, as it is so important.

**Comment by grahamperrin** [comment]
@MadLittleMods or @mydigitalself a gentle bump: https://github.com/gitterHQ/gitter/issues/1618#issuecomment-287961182
