### ISSUE TITLE
No RPM package for Fedora / Red Hat / Centos.

### ISSUE THREAD

**Issue by mareg** [gitterHQ/gitter#1283]
Currently gitter app is distributed as a Debian-only package - would be nice to have a platform agnostic one and/or RPM package as well. Note: Linux has more flavours than Ubuntu/Debian.

**Comment by MadLittleMods** [comment]
@mareg Create the issue over on the desktop repo, https://github.com/gitterHQ/desktop - The desktop app is open source, so feel free to submit a PR if you are keen.

**Comment by Kaylen-Travis-Pillay** [comment]
https://ask.fedoraproject.org/en/question/65767/how-to-install-gitter-on-fedora-21/

This solution works wonderfully on Fedora 25!
