### ISSUE TITLE
Autostart on boot.

### ISSUE THREAD

**Issue by dpc** [gitterHQ/gitter#1286]
I rely on the Android app notifications to help my library users, and right now every time my phone reboots I need to remember to manually start gitter app, which I sometimes don't.

**Comment by ItamarShDev** [comment]
weird, always worked for me

**Comment by MadLittleMods** [comment]
To note some testing I did.

 - If you leave the app running when you restart the phone, it will properly start back up and send you notifications.
 - If you close the app, then restart the phone, it won't start back up.
 - And during normal use, if you close the app, it will run in the background and send you notifications

**Comment by dpc** [comment]
Hmm... So it is supposed to work? Weird. I had it installed on my phone, and then missed two weeks of notifications on the low-traffic channel. Maybe it's just something with my phone.

**Comment by MadLittleMods** [comment]
@dpc 

> The only thing that could be stopping those notifications is the online status[(caused by desktop app being open somewhere)] and if 3 notifications have already been sent

> [*source @trevorah*](https://gitter.im/gitterHQ/gitter?at=57517f02e8163f872c4da56d)

**Comment by dpc** [comment]
OK. Thanks. I'm closing for now.
