### ISSUE TITLE
Content/notifications not updating when switching between joined rooms 

### ISSUE THREAD

**Issue by dtgm** [gitterHQ/gitter#1287]
#### Environment
Win 10
I use firefox which was updated several days ago (48.0a2 (2016-06-06)), but also tried in chrome (Version 51.0.2704.84 m) and same issue.

#### When

I noticed issue after I updated gitter to version released about a few hours ago by refreshing gitter.
I use gitter daily and had no issues yesterday.

#### Problem

When I switch between rooms that I am already joined to or 1to1 chats, the header changes where the room name is, but the content remains from the previous room. To view the content, I must switch to a room and Ctrl+F5 to force a refresh of that room.

Also, notifications are not removed after refreshing the room. The number next to the people remain and their new text remains highlighted (green). I can type text and it appears in the chat, but notifications remain.

#### Not affected

Switching to rooms I haven't joined, like suggested rooms, works fine.

**Comment by MadLittleMods** [comment]
> Update on issues: AWS are experiencing issues that's impacting our infrastructure.
>
> https://twitter.com/gitchat/status/741002479760900096

**Comment by dtgm** [comment]
Ah, thanks. I don't use twitter. Is the issue represented on http://status.aws.amazon.com/ ?

**Comment by dtgm** [comment]
I guess it may be several issues with the servers in North Virginia (US-EAST-1 Region). Any know which one(s) specifically would be affecting gitter?

**Comment by MadLittleMods** [comment]
AWS did experience some issues with the US-East region around creating instances and ELBs. Everything should be recovered now.

> Update: Services all coming back to normal. Back to chatting :rocket: 
>
> https://twitter.com/gitchat/status/741024021584711680
