### ISSUE TITLE
War Room

### ISSUE THREAD

**Issue by ricardobaeta** [gitterHQ/gitter#1288]
My 2cents on an extreme use case.

You can chat on Gitter as easy as you know it: Choose a room and talk with who is in. This is great for engaging with communities, finding new ones, doing team work, learn, share and meet people like you.

Although, there are times when all you want to do is to chat with specific team members, on a specific topic and for specific a period of time. As an example, when something is really bad with your product you just want to collaborate and solve the problem. You don't want distractions neither you're interested in engaging in other conversations.

The idea is to be able to define a starting point on a conversation in a room and do something like clicking a button that would say **start live feed**. All members would be invited to join.

What you would get would be a link that you can access. The UI that you would get on that link would be the chat layout of that room starting from the timestamp defined on the creation of the **live feed** and nothing more. You wouldn't see the left menu and the same for the right panel.

Device-independency would be enhanced. You would get the chance to follow the **live feed* on your mobile phone. It would be an extension of Gitter. Notifications would be context-based.

**Benefits**

* Total focus on problem solving collaboration
* Exclusive environment with an optimised UI
* All conversation will be synchronized on the room where the **live feed** was started
* Ability to archive the entire **live feed** separately 
* Room permissions will stay the same on the **live feed**

**Disadvantages**   

* Not being able to start a one-to-one with a team member on the **live feed**
* If you're tracking at the same time a room for user support you won't get context

**Comment by mydigitalself** [comment]
If we consider that our primary use case is for public communities, I don't see this fitting into that or being executed on in the future.
