### ISSUE TITLE
Green fly-out banners [annoying]

### ISSUE THREAD

**Issue by strawstack** [gitterHQ/gitter#1295]
The green fly out banners pop up constantly, do not remain long enough to be readable, provide no useful information, and completely block whatever I'm doing in gitter until they decide to go away, and there is no way that I can find to dismiss or disable them.

**Comment by MadLittleMods** [comment]
@strawstack You can adjust your notification settings in your room so that only pop for mentions, etc if that is desired.

Are the desktop browser notifications sufficient for you? You should be prompted when you reload the page but can enable at any time. 

![](http://i.imgur.com/8v6aCpX.png)

**Comment by strawstack** [comment]
I already block those notifications. I would like to block the green ones. As seen here they're annoying and completely block everything I'm trying to read. 
![screen shot 2016-06-14 at 8 18 16 pm](https://cloud.githubusercontent.com/assets/3249652/16066043/4608b6fa-326d-11e6-8185-71e49e62b466.png)

**Comment by MadLittleMods** [comment]
@strawstack As a first step, it looks like you should set your notification settings to "Announcements" which will cut down on the number of notifications but you will still get the unread tracking.

**Comment by strawstack** [comment]
I can't find any setting page at all in the web interface. I had gitter installed temporarily but found that it insisted on auto-starting every time I turned on my Mac, which I found intrusive and ignorant. I'm pretty sure I'll just find look for a different service, unless there's some secret settings page buried deep somewhere.

**Comment by MadLittleMods** [comment]
In the OSX desktop app, you can disable launch on startup with the menu bar option.

![](https://i.imgur.com/RN6WgKx.png)

You can adjust your notification settings for each room by clicking on the vertical sliders icon (top-right) of the chat-header -> Notifications. You can also adjust your default notification settings for new rooms by clicking the "Configure Defaults" button in the bottom-right of the notifications modal.

![](http://i.imgur.com/A0wYd6d.png)

![](http://i.imgur.com/e134QRG.png)

**Comment by strawstack** [comment]
Thanks, that's exactly what I was looking for

**Comment by MadLittleMods** [comment]
@strawstack Do you want to keep this issue open or is your problem solved for the time being?
