### ISSUE TITLE
Web client lost part of history

### ISSUE THREAD

**Issue by Maccimo** [gitterHQ/gitter#1297]
Quite often web-client lost part of unread messages.
See message timestamps in attached screenshots.
Very annoying bug!

![gitter-skipped-replicas-bug-20-underlined](https://cloud.githubusercontent.com/assets/1935894/16080769/fa8ed488-3312-11e6-934d-2471d43af39f.png)
![gitter-skipped-replicas-bug-21-underlined](https://cloud.githubusercontent.com/assets/1935894/16080770/faae9a66-3312-11e6-8a0a-1e4a6e86cb92.png)

**Comment by MadLittleMods** [comment]
See https://github.com/gitterHQ/gitter/issues/1234

@Maccimo Is this after having a lot of unreads and scrolling down? Is this after clicking a permalink and moving back down to the latest?

**Comment by Maccimo** [comment]
@MadLittleMods Yes, #1234 seems to be the same bug description.

It's happens after going to the first unread message by clicking green label at the top (BTW, this is itself very annoying, why not scroll to the first unread by default?) and then scrolling down slowly.

The only difference is that clicking green label when it re-appear does not force lost messages to load and thus I forced to re-open same room in the new tab using permalink of last correctly loaded message.

**Comment by MadLittleMods** [comment]
Closing in favor of #1234
