### ISSUE TITLE
Repo room create failure when a non-org member attempts to creates a repo room

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/gitter#1302]
As reported by @erikdw.

This was the result of a bug introduced as part of the Gitter communities workstream. 

When a user tries to create a room for a repo that they have permission for, in certain circumstances the operation may fail when they are not members of the repo owner organisation on GitHub.

I've pushed a hotfix for this issue.

@erikdw, please could you confirm that the hotfix is working for me (or not).

**Comment by MadLittleMods** [comment]
I also mentioned @ericdw on Gitter, :point_up: [June 21, 2016 9:11 AM](https://gitter.im/gitterHQ/gitter?at=57694afd648385b8074c3274)

**Comment by erikdw** [comment]
Worked!  Thanks for the quick fix.
* https://gitter.im/mesos/storm
