### ISSUE TITLE
Change :/ to show different emoji

### ISSUE THREAD

**Issue by ljacqu** [gitterHQ/gitter#1307]
This is a minor thing, but when someone uses **:/** in Gitter, it results in the emoji :pensive: which is arguably not very representative (and I've seen it lead to confusion a couple of times). 

Would perhaps :confused: be a more suitable emoji for `:/` ?

**Comment by sgdc3** [comment]
#Revolution WE WANT THE CORRECT EMOJI!

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/1027 and https://github.com/gitterHQ/gitter/issues/905

We currently use Emojify.js which is where these translations come from. I made a PR that makes them much more accurate but it hasn't had any activity from the maintainers. We can run a fork of the project but just need to verify nothing is broken. If you want to speed along the process, review the PR and give it some testing, https://github.com/Ranks/emojify.js/pull/167

**Comment by sgdc3** [comment]
@MadLittleMods What happened?

**Comment by MadLittleMods** [comment]
@sgdc3 Release is rolling out now. You can see the changes that have been on [next](http://next.gitter.im/) for a little bit now.

**Comment by sgdc3** [comment]
@MadLittleMods Thank you! 

P.S: i found a critical bug! Gitter will explode if you don't fix it! The link on the bottom of http://next.gitter.im/ is broken! WE WANT RICK ROLL

**Comment by MadLittleMods** [comment]
@sgdc3 Please raise separate issues instead of mentioning it inside another. In this case, this is already filed: https://github.com/gitterHQ/gitter/issues/1148

**Comment by sgdc3** [comment]
@MadLittleMods NO U FIX IT NOW
