### ISSUE TITLE
Global notification settings

### ISSUE THREAD

**Issue by arun1595** [gitterHQ/gitter#1312]
I would like to have a feature to switch to a silent mode where I can mute all or some of the channels I am part of?

As of now, I have to turn off the notifications for every channel. It would be better to have a global setting to manage notifications.

**Comment by MadLittleMods** [comment]
See https://github.com/gitterHQ/gitter/issues/999

> This has been implemented and can be accessed from any notification modal -> Configure defaults:

![](http://i.imgur.com/MsnvUS0.png)

![](http://i.imgur.com/St2LBNp.png)

**Comment by arun1595** [comment]
Thanks. I didn't know that before.
