### ISSUE TITLE
Seeing random messages from other rooms in private rooms

### ISSUE THREAD

**Issue by robske110** [gitterHQ/gitter#1315]
I was in a group, then changed to a private room. Now i scrolled all the way up to the beginning of the private chat. And above the actual beginning there were random messages from other groups I visited/wrote in. I assume this is a cache issue.

Info:
- MacOSX Safari 9.1.1
- `next`

The actual private chat starts from  "kurze Frage our",

![screenshot](https://cloud.githubusercontent.com/assets/16020100/16420977/b130b0d6-3d53-11e6-9528-b4140d8c047a.png)
This is easily reproducible, just switch randomly through rooms, then go into a quite new private chat scroll up and random messages are there..
![screenshot](https://cloud.githubusercontent.com/assets/16020100/16421118/3102dc8a-3d54-11e6-9e81-a4b653b95af8.png)

![screenshot](https://cloud.githubusercontent.com/assets/16020100/16421163/5a9f2abc-3d54-11e6-99f7-87333d96712a.png)

**Comment by MadLittleMods** [comment]
> chat-cache is still experimental, better to turn it off
>
> [*source @mydigitalself*](https://gitter.im/gitterHQ/change?at=577295ae265214c1308c297d)

Can you still reproduce when `chat-cache` is turned off?

**Comment by robske110** [comment]
will test

**Comment by mydigitalself** [comment]
Any word? If you can't reproduce with `chat-cache` off, can you close please it's an experimental feature.

**Comment by robske110** [comment]
Sorry for not responding, yes this isn't appearing with chat-chace off
