### ISSUE TITLE
CORP Proxy setup..

### ISSUE THREAD

**Issue by necrose99** [gitterHQ/gitter#1316]
Company laptop on windows 10 , Need to add the proxy for work when at work. 

ie add location Proxy-http server , local proxy or autoconf script ie http://autocache.hp.com/
so far the desktop app stalls

**Comment by MadLittleMods** [comment]
@necrose99 What is your question/issue?

Are you referring to not being to use the desktop app? https://github.com/gitterHQ/desktop/issues/49

**Comment by necrose99** [comment]
yes

**Comment by MadLittleMods** [comment]
Closed in favor of  gitterHQ/desktop#49
