### ISSUE TITLE
Disable embedding on per-room basis

### ISSUE THREAD

**Issue by AaronVanGeffen** [gitterHQ/gitter#1322]
Automatic embedding of media items is both a blessing and as a curse. In some rooms embeds can be quite disruptive to the ongoing conversation. For instance, when linking a YouTube video, it suddenly fills up half of the viewport due to its height.

It would be a great addition if we could disable these on a per-room basis.

**Comment by IntelOrca** [comment]
Per-content type would be useful too, for example embedding of gists you might want to keep.

**Comment by MadLittleMods** [comment]
This would more likely be implemented as a user setting instead of a room setting, https://github.com/gitterHQ/gitter/issues/714
