### ISSUE TITLE
Deleted repo associated with room, now I can't create a new room with that name

### ISSUE THREAD

**Issue by emilydolson** [gitterHQ/gitter#1323]
I foolishly deleted a repository on github before deleting the associated gitter room (SCBCS/diversity). I'd like to make a new room with the same name (we still want to discuss the repo, it's just going to be hosted on Overleaf rather than github for now), but when I do I get the "There is already a Github repository or a room with that name" error. Is there a known solution to this?

Thanks in advance!

**Comment by MadLittleMods** [comment]
@emilydolson The room is still available. Will that work? https://gitter.im/SCBCS/diversity

**Comment by emilydolson** [comment]
It's not showing up on my list of rooms, and I get a 404 error when I click that link.

**Comment by MadLittleMods** [comment]
hmmm, works just fine for me.

The room has `security: private` but the security descriptor `sd` suggests a public repo that no longer exists though.

```
"sd" : {                                
        "externalId" : "62183246",      
        "linkPath" : "SCBCS/diversity", 
        "public" : true,                
        "admins" : "GH_REPO_PUSH",      
        "members" : "PUBLIC",           
        "type" : "GH_REPO"              
},                                      
```

I can delete the room but curious if @suprememoocow wants to take a look at the weirdness first.

**Comment by emilydolson** [comment]
Interesting. Yeah, feel free to delete it whenever it's convenient :). Thanks!

**Comment by MadLittleMods** [comment]
@emilydolson The room has been deleted :grinning:
