### ISSUE TITLE
Unable to create a channel/room for a repo

### ISSUE THREAD

**Issue by nischal62019** [gitterHQ/gitter#1331]
Hi,

I'm new to Gitter, trying to create a public room, tried to go through the create room flow, but it is neither allowing me to create a new channel nor allowing me to create a room on existing github repo.

When i tried to create a channel, i get message saying "There is already a github repository or room with that name"
![gitter](https://cloud.githubusercontent.com/assets/2035166/16609960/849dbc26-4375-11e6-8ffc-4f90521f05f0.png)
When i try to create a room on one of my repo i get the following message "Unable to create a Room"
![gitter2](https://cloud.githubusercontent.com/assets/2035166/16609996/b5dc9f3c-4375-11e6-851c-9183c1272b04.png)

Is this a bug or am i doing something wrong?

**Comment by MadLittleMods** [comment]
Another report, :point_right:  [July 6, 2016 6:13 AM](https://gitter.im/gitterHQ/gitter?at=577ce7cf50bacd3025590179)

**Comment by MadLittleMods** [comment]
This should be fixed now.

**Comment by nischal62019** [comment]
It works now, thanks
