### ISSUE TITLE
Wrong display for code markdown

### ISSUE THREAD

**Issue by Javix** [gitterHQ/gitter#1338]
When using a Markup in a web interface de Gitter for a code block as explained on [Gitter Markdown basics](https://gitter.zendesk.com/hc/en-us/articles/200176682-Markdown-basics), I still have the three back ticks present in the chat text:

![image](https://cloud.githubusercontent.com/assets/83579/16692652/0f4ce4c4-4532-11e6-8542-a2d292d5d344.png)

Is it a normal behaviour ? As for the screenshot present at [Gitter Markdown basics](https://gitter.zendesk.com/hc/en-us/articles/200176682-Markdown-basics), it is not the case.

Thank you

**Comment by MadLittleMods** [comment]
It would help if you gave the actual input you typed in the textarea.

If you put the backticks on their own line, it should work.

*Remove backslashes, only used for escaping within a code snippet*

```
\```
Background {#background}
\```
```

Output

```
Background {#background}
```

**Comment by Javix** [comment]
I typed in as I usually do in Githoob, i.e. 
* 3x backticks
* hit the enter
* type Background 
* hit the enter
* 3*backticks.

What would give the below display:
```
Background
```
but that was not the case :(

**Comment by MadLittleMods** [comment]
It works perfectly fine and we even auto-fill the last three backticks for you and switch you over to compose mode(`Ctrl + Enter` to submit).

![](http://i.imgur.com/ITaG8Kg.gif)

**Comment by Javix** [comment]
OK, it is little bit weird, may be it's because I was on a Windows PC... I'll close the issue, thank you for the feedback.

**Comment by MadLittleMods** [comment]
note: That gif was captured on a Windows 10 PC.
