### ISSUE TITLE
Keyboard shortcut for toggling chat/compose mode broken

### ISSUE THREAD

**Issue by LeonineKing1199** [gitterHQ/gitter#1339]
I'm unable to toggle chat or compose mode using the keyboard shortcut `Ctrl + /`.

Using Windows 7 and Chrome

**Comment by abhisekp** [comment]
Yeah! broken. It doesn't work when focused in textarea but it works if focus on the void.
> *sounds like gitter wants us to focus on void and meditate* :smirk: 

**System Specs**
**OS:** Ubuntu 16.04 (x64)
**Browser:** Google Chrome Version 51.0.2704.106 (64-bit)

**Comment by abhisekp** [comment]
Moreover, it is high priority because accessibility feature shouldn't be broken or taken away.
