### ISSUE TITLE
Cannot access Gitter Organization Chat after moving Organization from team5181 to LSRobotics

### ISSUE THREAD

**Issue by frjalex** [gitterHQ/gitter#1342]
Hi there!

We're a robotics team in a high school in Pennsylvania. We've been actively using Gitter. We used to have an organization chat channel/room located under gitter.im/team5181 since our previous organization name was team5181. However after we renamed our organization name on GitHub from team5181 to LSRobotics, our Gitter channel gitter.im/team5181 didn't move to gitter.im/LSRobotics, and all its contents become unaccessible.
Therefore, could you guys possibly move the room and all its data for us to the new location? The room contains important chat data so we would like it to be accessible again as soon as possible.

Thank you so much, Alex

**Comment by MadLittleMods** [comment]
We need to run a script on our side.

I have run the script and your rooms should be accessible under https://gitter.im/LSRobotics now.

---

Easy reference with links.

https://github.com/team5181 has been renamed to https://github.com/LSRobotics
