### ISSUE TITLE
Can't get messages older than April 2016 with the API

### ISSUE THREAD

**Issue by RomanZacharia** [gitterHQ/gitter#1345]
Hi, I'm trying to dump the full log from the room https://gitter.im/ethereum/EIPs (id 562f2e4216b6c7089cb86431) which was active since October 2015, but the oldest messages I can reach with the API is April 2016. Here is the request I make in python
`    def dump_messages(self):
        headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'Authorization': 'Bearer {}'.format(self.token),
        }
        room_id = '562f2e4216b6c7089cb86431' 
        url = 'https://api.gitter.im/v1/rooms/{room_id}/chatMessages?limit=999999999'.format(room_id=room_id)
        r = requests.get(url, headers=headers)

        return r.json()`
increasing the 'limit' value does not help.

**Comment by mydigitalself** [comment]
Hi

We do this for a very specific reason to stop people completely slamming the database and API by requesting too many messages. You can imagine a single call could result in tens of thousands of messages being pulled from the database and sent down the wire.

The correct way to do this is to paginate using before and afterIDs. See the docs https://developer.gitter.im/docs/messages-resource for examples on how to do this.
