### ISSUE TITLE
Emojis no longer work in tables

### ISSUE THREAD

**Issue by phlax** [gitterHQ/gitter#1346]
As of yesterday, it seems that emojis no longer work inside of markdown tables.

This has made our bot very sad.

**Comment by MadLittleMods** [comment]
@phlax Can you give some input you would expect to parse?

**Comment by phlax** [comment]
hi @MadLittleMods yep here is an example

```
|     :grey_question:|                uuid|               build|                 src|             tarball|                user
|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------
|  :white_check_mark:|             03b8200|:whale:[2.8-build-XXX](http://foo.bar/log/XXX/2.8-build.log)|:octocat: [unho/issue/4848](https://github.com/unho/pootle/tree/issue/4848)|:package:[Pootle-2.8.0b1.tar.bz2](http://foo.bar/file/XXX/Pootle-2.8.0b1.tar.bz2)| @unho/translate/noc

```
|     :grey_question:|                uuid|               build|                 src|             tarball|                user
|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------
|  :white_check_mark:|             03b8200|:whale:[2.8-build-XXX](http://foo.bar/log/XXX/2.8-build.log)|:octocat: [unho/issue/4848](https://github.com/unho/pootle/tree/issue/4848)|:package:[Pootle-2.8.0b1.tar.bz2](http://foo.bar/file/XXX/Pootle-2.8.0b1.tar.bz2)| @unho/translate/room

**Comment by MadLittleMods** [comment]
Probably related to https://github.com/Ranks/emojify.js/issues/154

**Comment by phlax** [comment]
@MadLittleMods it worked fine until a couple of days ago. Im wondering whether i need to remove the emojis for now

**Comment by MadLittleMods** [comment]
@phlax We did a recent release with new shortname alias translations which updated it to the latest from that repo. I have added a fix to move back to the old way emojify grabbed nodes which will be in an upcoming release.

**Comment by phlax** [comment]
@MadLittleMods great, thanks

**Comment by phlax** [comment]
@MadLittleMods i can confirm this is fixed - really appreciated, thanks
