### ISSUE TITLE
xo and xp emoji is replaced everywhere

### ISSUE THREAD

**Issue by scopatz** [gitterHQ/gitter#1348]
The xo emoji is replaces the string `xo` everywhere, even when it is part of a non-whitespace separated string, such as in "xontrib".  I am one of the core devs of the xonsh project and it is hugely distracting to have our project name be rendered as `EMOJInsh` everywhere.

See the following screenshot with the emoji replacement.

![screenshot 2016-07-20 at 11 56 04](https://cloud.githubusercontent.com/assets/320553/16995255/5e8a36d6-4e79-11e6-9a83-1fb3d894573c.png)

**Comment by MadLittleMods** [comment]
Hey @scopatz,

We used to only have `xd` but `xo` and `xp` were recently added which seem to be having more collisions. The regex in emojify should be updated anyway to not collide in the middle of words.

This is currently being worked on here https://github.com/MadLittleMods/emojify.js/pull/1

**Comment by scopatz** [comment]
Thanks for the update!

**Comment by MadLittleMods** [comment]
A fix has been rolled out that removes `xp`, `xo`, and `xd` anyway but it also has better detection for replacing emoticons in the first place.

**Comment by scopatz** [comment]
Thanks a million!
