### ISSUE TITLE
Ellipsis long room name instead of truncating

### ISSUE THREAD

**Issue by burukuru** [gitterHQ/gitter#1350]
As per subject, if we have a repository with the same name as the organisation, things can get confusing.

![2016-07-21-111211_351x441_scrot](https://cloud.githubusercontent.com/assets/3882632/17020175/2b30411c-4f38-11e6-9cc3-eb1361a654e2.png)

A better view would be: 
![screen-shot-2016-07-21-at-11 16 45](https://cloud.githubusercontent.com/assets/3882632/17020227/58eafcdc-4f38-11e6-8c52-ce56dedaa75b.png)

This happens for both the web client and the app for Linux.

**Comment by MadLittleMods** [comment]
This issue will serve as a solution for https://github.com/gitterHQ/gitter/issues/1281 as well (we tended towards the lock icon in that issue).

**Comment by MadLittleMods** [comment]
Just to follow-up how this was solved on 2016-8-12

 - If `roomName = groupName`, then do cunning ellipses thing
 - Hide `"Lobby"` (`defaultRoomName`) and only show the community name instead
 -  Still do the truncation we do today

![](http://i.imgur.com/2ZtfpcV.gif)



---

Here was a prototype with all room names being ellipsied which was pretty fun to play with but it was decided that it added too much clutter.

![](http://i.imgur.com/gL7TnkP.gif)
