### ISSUE TITLE
Issue/PR links in rooms don't work

### ISSUE THREAD

**Issue by balloob** [gitterHQ/gitter#1353]
When a user writes a link to an issue using the pound sign (`#2558`), it will link to the wrong url.

Example: https://gitter.im/home-assistant/home-assistant/devs?at=5795929e959ee82b3e555fd5

`#2558` links to https://github.com//issues/2558 instead of https://github.com/home-assistant/home-assistant/issues/2558

**Comment by mydigitalself** [comment]
This works perfectly fine for me when visiting the message you provided.

Hoving on the issue shows the correct card and clicking "Open in GitHub" opens the PR correctly.

Am I missing something, are you doing this differently?

**Comment by naazy** [comment]
I have this problem too (only when clicking the issue number in the gitter desktop app)

**Comment by mydigitalself** [comment]
@naazy which operating system are you using? I can't reproduce either on Chrome or the Mac OSX app.

@balloob are you also seeing this on the desktop app, or in a browser?

**Comment by naazy** [comment]
I use Mac el Capitan

**Comment by naazy** [comment]
Just realised it works when you paste in an issue link. But when you just type #1 and follow the link, it takes you to  'https://github.com/undefined/issues/1'

**Comment by mydigitalself** [comment]
@naazy what room are you doing that in?

**Comment by balloob** [comment]
Hmm my original example indeed works now but @naazy is right. It happens only when typing just the number instead of the url. It happens for sure in the home-assistant/devs channel I linked above

**Comment by mydigitalself** [comment]
@balloob when you type the number, are you getting an auto-complete list to pick from?

**Comment by bjansen** [comment]
> But when you just type #1 and follow the link, it takes you to 'https://github.com/undefined/issues/1'

I have the same problem in the room `ceylon/ceylon-ide-intellij` in the web app (Chrome OSX). Reloading the page fixes the problem.

**Comment by bjansen** [comment]
Steps to reproduce:

* type #1, the link is correctly recognized
* switch to another room and come back, the link is now https://github.com/undefined/issues/1
* reload the page, the link is correct again
