### ISSUE TITLE
Cannot re-grant access to private repos

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [gitterHQ/gitter#1355]
In an attempt to get an organization to show up on the new channel dialog dropdown, I signed out of gitter, revoked access on github, and then signed back in. Gitter directed me to grant the public repo permission, but it did not direct me to grant the private repo permission. 

The link https://gitter.im/login/upgrade?scopes=repo ["to add the private repo permission"](https://gitter.zendesk.com/hc/en-us/articles/200227051-Private-repository-chat-rooms) does nothing.

**Comment by MadLittleMods** [comment]
@MegaApuTurkUltra If the link simply redirects back to Gitter, then you already granted private repo scope for yourself.

You may need to grant access from your org to the private repo OAuth application though, see https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-

**Comment by MegaApuTurkUltra** [comment]
But there is no gitter private repo permission in the list

![](http://image.prntscr.com/image/4f7d09a6c79c40d2b2bbdc4c7b83af27.png)

The create room from repository dialog also isn't showing any repos.

**Comment by MadLittleMods** [comment]
If you have the public repo access application granted on your org, then you should be able to see public repos.

Usually revoking the OAuth app works just fine for another upgrade process.

I have removed the `repo` `githubScope` listed for your user on Gitter so I think the upgrade link should work again.

**Comment by MadLittleMods** [comment]
I assume this is working for you again.
