### ISSUE TITLE
Add room modal missing communities that you haven't joined any rooms in

### ISSUE THREAD

**Issue by prit17may** [gitterHQ/gitter#1359]
Some communities are not shown when opening the add new room popup.

### Reproduction

- Create a new community.
- note: There will be a default room named `Lobby`
- Leave or delete that room
- Try to add a new room (create room modal)
- The community that you just had created will not be listed

---

See  :point_up: [July 31, 2016 6:56 PM](https://gitter.im/gitterHQ/gitter?at=579e9017f1da4f376e1daf18) :point_up: [July 27, 2016 11:25 AM](https://gitter.im/gitterHQ/gitter?at=5798e08e0a62c16049f2f513)

**Comment by moigagoo** [comment]
Hi!

Contacting wrt to issue 2817. I can't create rooms in my community (called "moigagoo") because I deleted Lobby. Please create a room "moigagoo/nimage" for me.

**Comment by trevorah** [comment]
The fix should be live! ⚡ ⚡ 

Thanks for reporting this @prit17may!
