### ISSUE TITLE
Image upload using Paste from clipboard is not working properly

### ISSUE THREAD

**Issue by volnt** [gitterHQ/gitter#1360]
When uploading an image using paste from clipboard it creates an image with a constant URL.

The thumbnail URL is https://files.gitter.im/{ORGA}/{ROOM}/thumb/blob.png
The image URL is https://files.gitter.im/{ORGA}/{ROOM}/blob

I'm experiencing this issue on Ubuntu 15.10 with the web client running on Google Chrome 52.0.2743.82.

**Comment by volnt** [comment]
I just noticed that it's also a security issue on private rooms.

Anyone with the orga/room combo can access the image, it's not only available to connected users in the private room.

**Comment by MadLittleMods** [comment]
@volnt Normally uploads look like `https://files.gitter.im/gitterHQ/TB3t/foo.png` which makes the upload only accessible if you have the direct URL. We are currently looking into it.

**Comment by MadLittleMods** [comment]
Fixed by https://github.com/troupe/gitter-webapp/commit/854c83a58391c0233cc09d1e19252dd44a2615c1
