### ISSUE TITLE
Typeahead doesn't find some users by Real Name / displayName

### ISSUE THREAD

**Issue by ferventcoder** [gitterHQ/gitter#1364]
For some reason, either because the user is a twitter account, or because they are a new account, I can't find them with `@` responses. I'd love to see #1325 implemented or to get this functionality working appropriately. I've only noticed it more recently, so it's possible something recent with the iOS app broke this functionality or it is possible that it has just been more noticeable as more folks have joined to ask questions from Twitter.

![image](https://cloud.githubusercontent.com/assets/63502/17352570/1e000a08-58fd-11e6-8122-7c77ebadc8a6.png)

From the image above you can see that the user shows up by real name search in OS X, but not in iOS.

Twitter accounts also do not show up in the members list for the room (not in OS X app either).

## Reference information
From conversation starting at https://gitter.im/gitterHQ/change?at=57a130d60bd017c16e36bbf9 with @MadLittleMods.

OS X Gitter version: 1.177

iOS version: 9.3.2
Gitter iOS version: 3.6.1
No recent crash logs from Gitter in Diagnostics

**Comment by trevorah** [comment]
@ferventcoder is this still happening in that room? I just want to rule out any cache issues.

**Comment by ferventcoder** [comment]
Still occurring - hard to know if it is a caching issue or not though. I had a user in a room about 12 hours ago, and I just checked and it doesn't find them - their real name and user name is the same and neither pop up. They are also a github user, not a twitter user. I also just upgraded the iOS app yesterday evening. 

In this case though, it could be a different issue - folks come and go through sidecar in the room where I just checked (not the same room as the original isssue was reported from) - the user isn't actually a member of the room. But I believe if they just sent messages in the room, I should be able to respond.

I didn't have any recent new users in the other room asking questions I could check from. Perhaps the issues are related depending on how you poll for the users - using members may not work as folks using the web client could be transient.

**Comment by ferventcoder** [comment]
And when I say the user is not a member - they are not showing up as a member in iOS, let me verify in another client.

**Comment by ferventcoder** [comment]
Verified, not a member of the room, but in the OS X client, I can still use `@` to address those recent folks.

**Comment by trevorah** [comment]
@ferventcoder Yeah, the ios and desktop clients use slightly different logic. The ios client just uses a rest endpoint to query the room members, but the desktop client also mixes users from its own message cache.

Although it would be nice to the mixing at the api level (roughly `/rooms/:id/users?q=XXX`), it would suck to have that endpoint return those chatty users that are no longer members as other views use that endpoint for member searching. We could add a flag to the parameters but then we would start having to do database lookups on an endpoint that is used as a typeahead, which would make the typing experience too slow (and the cache would be invalidated on every new message).

I think the best solution for this is for the ios client to start having its own messages cache, like desktop.

------

On writing this I've just realised that the members view and typeahead use the same rest endpoint, so the missing user would be missing for both views on the same data. This could be a legitimate bug with that rest endpoint. @ferventcoder, whats the name of the room with the missing user?

**Comment by ferventcoder** [comment]
@trevorah the rooms are [chocolatey/choco](https://gitter.im/chocolatey/choco) and [chocolatey/chocolatey.org](https://gitter.im/chocolatey/chocolatey.org) (this is where the most transient users come in with sidecar set at https://chocolatey.org).

**Comment by trevorah** [comment]
I've just confirmed it. `@norenberg_twitter` doesnt show up in the members search api, but is totally a member of chocolatey/choco if you query the database directly.

**Comment by trevorah** [comment]
@ferventcoder I've just a server side fix now. Turns out there was an error in our error handling for the bulk updates to our search db that meant that the search results were out of date. Thanks for reporting and helping us out!

**Comment by ferventcoder** [comment]
Awesome. Thanks!
