### ISSUE TITLE
Window doesn't show.

### ISSUE THREAD

**Issue by lupus590** [gitterHQ/gitter#1366]
OS: Windows 10
Version: 1511
Build: 10586.494

Problem: Window with Gitter doesn't open with desktop app.

Taskbar and system tray icons show, aero peak works but window doesn't appear when clicked. Minimising all other windows shows desktop.

**Comment by MadLittleMods** [comment]
Hey @lupus590, try running through the steps here https://github.com/gitterHQ/desktop/issues/69#issuecomment-126656798

**Comment by lupus590** [comment]
I have two Gitter links, the guide you linked only said one.

**Comment by MadLittleMods** [comment]
That is fine. If you already have 2, then you probably don't need to open up `loggedin.html` and skip to the next step. As I mentioned there, "I am curious to know if you have 1 or 2 "Gitter" links there.".

You can still pop up another `loggedin.html` and try the steps there.

**Comment by lupus590** [comment]
> Following any of the links results in a blank page.
I can't, I just get a blank page when I click on the link to get the web kit tools.

**Comment by MadLittleMods** [comment]
@lupus590 I am not sure why they would be blank. You can try to enable logging and paste the results in a gist: https://github.com/gitterHQ/desktop#enabling-logging-on-windows

**Comment by lupus590** [comment]
Just upgraded to the build 1607 (the anniversary build), still not working. Haven't tried logging yet, will post log when I do.

**Comment by lupus590** [comment]
Log: https://gist.github.com/lupus590/de4fdd02b4fd2a05e79e91ac294bfd8c

**Comment by lupus590** [comment]
Gitter just downloaded an update (via windows toast notification), still no window.

**Comment by MadLittleMods** [comment]
@lupus590 That was the v3.1.0 update.

I am not sure what to try. It seems like the window is there somewhere because there are a bunch of normal assets coming through and you even mention it is in the task bar with aero peak.

Can you try right-clicking and maximize/minimize, etc? Trying the move/size after. Really sucks that the remote debugging tools are just blank for you because that is an easy programmatic way to get it back.

**Comment by lupus590** [comment]
Does Gitter leave config file behind on uninstall? If so then where can I clean those manually, I'm thinking of trying a complete fresh install.

**Comment by MadLittleMods** [comment]
@lupus590 On Windows, the app has files in:

 - `C:\Users\YOUR_USER\AppData\Local\Programs\Gitter`: App install location
 - `C:\Users\YOUR_USER\AppData\Local\Gitter`: Config, see https://github.com/nwjs/nw.js/wiki/app#datapath

**Comment by lupus590** [comment]
Your areo peak maximise worked, I edited my post to show.
