### ISSUE TITLE
Add contributor mention @/contributors

### ISSUE THREAD

**Issue by mananwason** [gitterHQ/gitter#1368]
Right now if I want to address the people who I invited to join my channel, I am not able to do it. I have to address them by @/all which is spamming everybody. I think adding @/channel would be a really nice enhancement.

**Comment by mydigitalself** [comment]
Can you elaborate a little on this a bit please, not sure I understand the request entirely.

**Comment by mananwason** [comment]
@mydigitalself There should be some setting wherein people who have push rights to the repo are the only ones that can be mentioned. So for example if I do something like @/channel people part of the repo should be notified, right now there's only the option of doing @/all mention where all the people who have joined the gitter chat will be notified.

**Comment by MadLittleMods** [comment]
Sounds like group/team mentions https://github.com/gitterHQ/gitter/issues/115

`@/contributors`

**Comment by mananwason** [comment]
Yes this sounds similar.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/115
