### ISSUE TITLE
Android app alerts don't fire

### ISSUE THREAD

**Issue by FezVrasta** [gitterHQ/gitter#1369]
Most of the times when I receive a message, there isn't any notification on the android notification center, once I open the app, the notifications appear.

**Comment by MadLittleMods** [comment]
When you say "once I open the app, the notifications appear", do you mean you see unreads/mentions in the app or are you getting actual Android notifications?

**Comment by FezVrasta** [comment]
It's been a while since last time I used the Android app... I don't actually remember the exact behavior sorry.

**Comment by MadLittleMods** [comment]
I am going to close. Feel free clarify so we can reproduce.

**Comment by SvitlanaBoiko** [comment]
I have the same problem (that wasn't fixed). 
I installed Gitter android app, and I can find out all new messages only after logging into the application.
Can you help me with this?

**Comment by rasendubi** [comment]
Same here. All desktop/web gitter instances are closed and I don't see any notification from my android client.
Notification neither appears when the application in the background, nor when it is open.

Application version: v3.1.1.
