### ISSUE TITLE
Community name with the same as the username

### ISSUE THREAD

**Issue by JoaquimLey** [gitterHQ/gitter#1372]
Bring back the ability to create a community with the same name as your username:

- Keeping everything nice and tidy under "your" community where you would then create your separate rooms for each project.
- Keeps the namespace close to the GH philosophy (owner/repoName)

**Working example:** https://gitter.im/orgs/mikepenz/rooms
Where "mikepenz" is the community name (which is the same as the username) and each room is a different project.

Therefore this user's room is **mikepenz/roomName** same as GH.

**Comment by MadLittleMods** [comment]
Reproduction here :point_up: [August 11, 2016 9:23 PM](https://gitter.im/gitterHQ/gitter?at=57ad333ebc688a1339112436)

**Comment by trevorah** [comment]
Thanks for suggesting this @JoaquimLey, the fix should be live now.

**Comment by JoaquimLey** [comment]
Thanks for including this @trevorah ;)
