### ISSUE TITLE
Can't create room: Validation failed

### ISSUE THREAD

**Issue by alexandrevicenzi** [gitterHQ/gitter#1374]
Well, the message only says Validation failed

On console there's a 400 error. Nothing else to help.

**Comment by MadLittleMods** [comment]
Hey @alexandrevicenzi,

**Comment by alexandrevicenzi** [comment]
Not sure what happened. It's working now, but I enabled next.

**Comment by MadLittleMods** [comment]
@alexandrevicenzi Most likely one of the things I mentioned. If you could post the request and parameters, I could nail it down.
