### ISSUE TITLE
Create room doesnt show repository

### ISSUE THREAD

**Issue by alexandrevicenzi** [gitterHQ/gitter#1375]
Create room doesnt show repository if the community name isn't the same as GitHub.

There's no way to associate a github repo if the community name isnt the same as github.
I cannot create a community with my github username beacause its in use or something. I get a 409 when I try to crate.

If it try to open [https://gitter.im/alexandrevicenzi/popop#createroom](https://gitter.im/alexandrevicenzi/popop#createroom) all I get is a 404.

**Comment by MadLittleMods** [comment]
Hey @alexandrevicenzi,

This is already covered here https://github.com/gitterHQ/gitter/issues/1372 and is something I am advocating on bringing back in some fashion internally.

**Comment by alexandrevicenzi** [comment]
@MadLittleMods Thanks.
