### ISSUE TITLE
Opening a private conversation with yourself.

### ISSUE THREAD

**Issue by alexknvl** [gitterHQ/gitter#1376]
If you try to open a private conversation with yourself, it opens a gitter window inside of the existing one instead. 

Reproduction steps:
1. Open search menu.
2. Search for your username.
3. Select your username (should be at the bottom).
4. It should open a gitter window inside the existing gitter window (see the image below).
5. You can do it as many times as you want recursively ;) [Here is an example of what it looks like](https://i.imgur.com/J0Dx8iX.png).

It affects both the desktop client app and http://gitter.im. I have not tested it on any mobile apps.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/1277
