### ISSUE TITLE
Clicking "Create and Finish" fails

### ISSUE THREAD

**Issue by joelday** [gitterHQ/gitter#1383]
The response for https://gitter.im/api/v1/groups is 400: Bad Request, with ```{"error":"Bad Request"}``` in the response body.

There is no progress indication, disabled state and error message.

**Comment by joelday** [comment]
Attempted to make a non-org based community with a name that matched that of a GitHub org. Didn't get a conflict response. Nonetheless, no context presented for failure. Thanks!

**Comment by MadLittleMods** [comment]
This was resolved here: :point_up: [August 19, 2016 5:15 PM](https://gitter.im/gitterHQ/gitter?at=57b785095ffbca3e3cf7ed65) by adding public repo access app to the org and associating it with that org.

> Looks like I had granted private permissions for the org, but not public, somehow. Didn't get prompted for it at any point. The org didn't show up in the "my orgs" list, but the org's repos showed up in the "my repos."
> Anyway, all good to go.
>
>:point_up: [August 19, 2016 5:15 PM](https://gitter.im/gitterHQ/gitter?at=57b785095ffbca3e3cf7ed65)
