### ISSUE TITLE
Gitlab username not fetched in Activity

### ISSUE THREAD

**Issue by scriptnull** [gitterHQ/gitter#1385]
I added a webhook in gitlab ( integration in gitter ) to see my activities from my gitlab.

Whenever there is a comment on any of the issues in the gitlab repository, We could see 
> "undefined pushed to [repositroy-name]"

![image](https://cloud.githubusercontent.com/assets/4211715/17854266/f9765916-688e-11e6-8dbd-6ca77ed3a1c3.png)

**Comment by MadLittleMods** [comment]
The response data from GitLab might have changed. Has this worked previously?

The integrations/services code is open source. Feel free to open a PR: https://github.com/gitterHQ/services/tree/master/lib/gitlab

See https://github.com/gitterHQ/services/blob/e4a42318dcf8004871ed00e2409503f2691f248e/lib/gitlab/index.js#L15

**Comment by mydigitalself** [comment]
You can probably take a look at the repo and send us a pull request...
https://github.com/gitterHQ/services

**Comment by scriptnull** [comment]
@MadLittleMods I am not sure, if it was working previously.

Anyway, I will open a PR.
