### ISSUE TITLE
Private room connected to private GitHub repository

### ISSUE THREAD

**Issue by KarolKaczmarek** [gitterHQ/gitter#1387]
Hi,

I've created room connected to private GitHub repo, however I'm not able to make it private (when I hover over the room name it says "Anyone can join" and I don't see the option to change that). 

I can click "add a new room" button and select "Private - only people added to the room can join" option, but in that case it's no longer connected to the repository (when I type #<id> it doesn't link to the correct PR/issue). 

Is there a way to create a private room which is connected to the private GitHub repository?

Thanks!

**Comment by MadLittleMods** [comment]
@KarolKaczmarek What is the URL for the room you created? It sounds like the room isn't actually associated with the repo.

Once you select a repo from the typeahead, it will automatically select the security based on the repo. If it is a private repo, then the security of the room will be private.

If you don't have private repo access granted on the org, the private repo won't show up in the typeahead.

![](https://i.imgur.com/ZSf4LTE.png)

Once the room is associated with repo, it will look like this:

![](https://i.imgur.com/H01ixIP.png)

**Comment by KarolKaczmarek** [comment]
I'm not seeing "Allow Private Repo Access" button even though my org has ability to create private repos. Do I need to be organization owner for this?

**Comment by KarolKaczmarek** [comment]
Example room which is connected to the private repo is here: https://gitter.im/privaterepo7/Lobby 
I still see "anyone can join" though.
![image](https://cloud.githubusercontent.com/assets/6466574/17909776/db55ff34-693a-11e6-8626-1077cfd34198.png)
and don't see "Allow private repo access" option under "All conversations"

**Comment by MadLittleMods** [comment]
@KarolKaczmarek Ahh, the link clears things up.

The issue typeahead in a room is powered by the security descriptor behind the room. The `Lobby` room we setup is automatically associated with the project you chose. When using the create room modal, if the project doesn't appear in the typeahead and chosen, then it won't be associated. 

Currently we don't suggest associating the same repo for a room in a repo community. Recently, we added the [`GROUP` type with `internalId`](https://github.com/troupe/gitter-webapp/pull/1975) but this isn't used on front-end yet. This would allow for a third "Inherit" option on the create room dialog. We would also need to adjust the `/v1/rooms/:roomId/issues` endpoint to understand that new type which is what the issue typehead is driven from.

For the time-being, you can create a `PowerShell` community linked to the `PowerShell` GitHub org. Then in the create room modal, start typing `privaterepo7` and select it from the typeahead.

**Comment by KarolKaczmarek** [comment]
Thanks!

**Comment by MadLittleMods** [comment]
@KarolKaczmarek I assume you re-opened to get the `GROUP` type going on the create room modal. For some peace of mind, this is being [tracked internally here](https://github.com/troupe/gitter-webapp/issues/2105).

**Comment by KarolKaczmarek** [comment]
@MadLittleMods Sorry, I reopened and got interrupted in the middle of writing the reason ;) Here it is:

I created the community based on github org and created room there. I was able to make it private and it's connected to the repository correctly (I can type #<ID> and have it linked to appropriate issue/repo). The problem is it says "All repository collaborators can join". We have GitHub team which is added to the repository with write permissions, we don't set any collaborators individually. I was able to add part of the team, but for most of the people it says that they don't have permissions or simply "error" when I add them and they don't receive invitation email... 

Do I need to set any special permissions to be able to invite everyone?

**Comment by MadLittleMods** [comment]
@KarolKaczmarek  If someone is on Gitter, we try to add them directly to the room and check from their perspective if they can access the repo (which will 404 without private repo scope). Have them grant private repo scope.

![](http://i.imgur.com/q2emdTa.png)
