### ISSUE TITLE
I renamed the repo and moved to a new org

### ISSUE THREAD

**Issue by goanpeca** [gitterHQ/gitter#1389]
Is it possible to remove a room that now I cannot delete (because I deleted the original repo I think)

Is it possible to delete this 
https://gitter.im/Python-Bucaramanga

?

**Comment by MadLittleMods** [comment]
It sounds like you want to delete a whole community, not a room. But you may just be referring to deleting the org room.

Did you rename the org? We can run a script on our side to update the group and rooms. This will keep your history in-tact, https://gitter.im/orgs/Python-Bucaramanga/rooms. What is the name of the new org?

**Comment by goanpeca** [comment]
I am not sure what needs to be done... I renamed the github organization, then created a new community based on that organization

github.com/Python-Bucaramanga  ->  github.com/PythonBucaramanga

But now if I go to https://gitter.im/pythonbucaramanga, I get a 404, why :-| ?

**Comment by MadLittleMods** [comment]
@goanpeca https://gitter.im/orgs/pythonbucaramanga/rooms did work. We match whatever case the group URI is saved as in the DB. But I have just adjusted your URI so it is cased as you prefer: https://gitter.im/orgs/PythonBucaramanga/rooms

I migrated messages from `Python-Bucaramanga/public` -> `PythonBucaramanga/public`

I removed the community and rooms for `Python-Bucaramanga`

**Comment by goanpeca** [comment]
![image](https://cloud.githubusercontent.com/assets/3627835/17918495/1673f148-698b-11e6-81fe-218b5d71dcd0.png)

:-\

**Comment by MadLittleMods** [comment]
> But I have just adjusted your URI so it is cased as you prefer: https://gitter.im/orgs/PythonBucaramanga/rooms
>
>https://github.com/gitterHQ/gitter/issues/1389#issuecomment-241955419

Per my comment, use https://gitter.im/orgs/PythonBucaramanga/rooms

**Comment by goanpeca** [comment]
Thanks :-)

**Comment by AllyMurray** [comment]
@MadLittleMods Was there functionality added to achieve this? I have also renamed an organisation, I have already added the renamed organisation to Gitter thinking I would be able to delete the old one. I may have gone about this wrong.

**Comment by MadLittleMods** [comment]
@AllyMurray Please create a separate issue instead of adding onto this one.

There isn't a way for a user delete a community yet. Refer to https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo

**Comment by bojdell** [comment]
@MadLittleMods Sorry if this isn't the right place to ask, but is there any way to associate a community to a GitHub repo after creating the community without linking it to a repo? I was browsing some other communities and noticed they all had a "REPO INFO" tab on the right sidebar. I would just delete the community and re-add it, but seems like that's not an option per your  comment above.

Specifically want to link these:
 - https://gitter.im/es-workshop
 - https://github.com/bojdell/es-workshop

**Comment by MadLittleMods** [comment]
@bojdell 

> Please create a separate issue instead of adding onto this one.
>
> https://github.com/gitterHQ/gitter/issues/1389#issuecomment-289559076
