### ISSUE TITLE
Windows 10, after press hide "-", windows of gitter does not appear

### ISSUE THREAD

**Issue by designofhumanity** [gitterHQ/gitter#1394]
Window of gitter not showing after minimize and restart (windows or maybe program)
![image](https://cloud.githubusercontent.com/assets/2714036/17961364/da7b65b6-6ab3-11e6-8eca-4df14b8c3062.png). Window shows only when hover mouse on Gitter then press right mouse button on area that appeared then select maximize and then only window shows
![image](https://cloud.githubusercontent.com/assets/2714036/17961401/307044f0-6ab4-11e6-914f-67ae0aaaa55a.png)

**Comment by MadLittleMods** [comment]
It's unclear to me what you are describing and looks like a Free Code Camp issue that would be better filed here https://github.com/FreeCodeCamp/FreeCodeCamp

**Comment by designofhumanity** [comment]
It is gitter!!!!!!!!!!!!!!!!!!!!!!

**Comment by MadLittleMods** [comment]
@designofhumanity It looks like you updated your image. Before it was just a picture of Free Code Camp in a browser.

You can try the steps in here https://github.com/gitterHQ/gitter/issues/1366

**Comment by MadLittleMods** [comment]
Closing in favor of the other issue you created: https://github.com/gitterHQ/gitter/issues/1395
