### ISSUE TITLE
Unable to create new community with same name as previously deleted one

### ISSUE THREAD

**Issue by rlee287** [gitterHQ/gitter#1402]
I created a community linked to my Github repo at `rlee287/pyautoupdate` (unfortunately I do not remember when I did this). It created a link to [pyautoupdate/Lobby](https://gitter.im/pyautoupdate/Lobby). I changed my mind and deleted the community immediately afterwards (without any activity on it), thinking that I would create it later once the project was more mature. When I try to create a new community linked to that repo now, Gitter tells me that the url `gitter.im/pyautoupdate` is already taken. When I visit https://gitter.im/pyautoupdate or https://gitter.im/pyautoupdate/Lobby, however, I get a 404 error. Is there anything I can do to recreate the community, or will I have to give Gitter a different address for the project?

**Comment by MadLittleMods** [comment]
You didn't delete the community, only the `Lobby` room. See https://gitter.im/orgs/pyautoupdate/rooms

You can still see it in the create room modal in the community select box and create rooms under it.
