### ISSUE TITLE
Add in-app webview

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1404]
Like Twitter. In the iOS app, if someone is sending you multiple links it takes a while to view them all sometimes because it opens in Safari/Chrome.

Nothing fancy, just a simple webview with an open in safari button.

**Comment by MadLittleMods** [comment]
@TheDiamondYT1 Which app are you referring to?

**Comment by TheDiamondYT1** [comment]
Im on about the iOS gitter app but adding to android app would be good too.

**Comment by MadLittleMods** [comment]
I would not want this personally(Android) but perhaps I am not used to the iOS patterns and this would be more of the deep tap to preview type of thing.

**Comment by TheDiamondYT1** [comment]
Well if you look at the android and ios twitter apps they both open links in a webview instead of the browser, which makes for faster link opening. Also in the facebook app.

**Comment by TheDiamondYT1** [comment]
I think you're on about 3D Touch? That only works on the home screen but it would be a nice feature to implement, maybe listing most recent chats?

**Comment by trevorah** [comment]
I can see how this would have been useful before ios 9, but now that you can tap the top right corner to go "Back to Gitter" after following a link, I dont think a webview is necessary:
![simulator screen shot 30 aug 2016 10 24 20](https://cloud.githubusercontent.com/assets/298742/18083702/1c01b1ac-6e9c-11e6-97e4-915ebd6251d1.png)

Also, I'd rather have safari handle all the security when visiting 3rd party sites. Plus people get paranoid that we could track everything that you do in that webview.
