### ISSUE TITLE
When mentioning ticket number in the private message it points to undefined

### ISSUE THREAD

**Issue by kenorb** [gitterHQ/gitter#1406]
When I type like:

    #123

in the private message to someone, it becomes a link which points to:

> https://github.com/undefined/issues/123

The same happened at [CodeMillApp/support](https://gitter.im/CodeMillApp/support) channel.

This is when using Gitter app for OSX (v1.177), this not happened when accessing channel through the website.

**Comment by tclarke** [comment]
Bump this, I'm seeing it as well.

**Comment by bjansen** [comment]
Is this the same problem as the one described here? https://github.com/gitterHQ/gitter/issues/1353#issuecomment-243445360

**Comment by MadLittleMods** [comment]
> We also recently [upgraded the issue decorator](https://github.com/troupe/gitter-webapp/pull/2137) to add some logic even if a repo isn't found for the room. (fallbacks in this order)
> 
>  - If room has `sd.type === 'GH_REPO'` : `https://github.com/' + sd.linkPath + '/issues/xxx`
>  - **If one to one room: `https://github.com/issues?q=xxx+%28involves%3A' + currentUser.get('username') + '+OR+involves%3A' + otherUser.username + '+%29';`**
>  -  If room has `sd.type === 'GH_ORG'`: `https://github.com/issues?q=xxx+user%3A' + sd.linkPath;`
>  - If is a GItHub user: `https://github.com/issues?q=xxx+involves:' + currentUser.get('username')`
>  - `https://github.com/issues?q=999`
> 
> https://github.com/gitterHQ/gitter/issues/1293
