### ISSUE TITLE
Request to move room to new organization

### ISSUE THREAD

**Issue by CraigElder** [gitterHQ/gitter#1407]
The repository https://github.com/Dronecode/MAVProxy has been moved to https://github.com/ArduPilot/MAVProxy.

Moving created a new badge link https://gitter.im/ArduPilot/MAVProxy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
on https://github.com/ArduPilot/MAVProxy but the gitter room is still located at https://gitter.im/Dronecode/MAVProxy 
Please rename https://gitter.im/Dronecode/MAVProxy to https://gitter.im/ArduPilot/MAVProxy
Thank you

**Comment by MadLittleMods** [comment]
@CraigElder https://gitter.im/ArduPilot/MAVProxy is good to go now.

And I setup a redirect from https://gitter.im/Dronecode/MAVProxy to https://gitter.im/ArduPilot/MAVProxy

**Comment by CraigElder** [comment]
Thank you!
