### ISSUE TITLE
Chat Frame not matching Room URL

### ISSUE THREAD

**Issue by viluon** [gitterHQ/gitter#1410]
The chat `iframe` holding the chat contents doesn't match the address bar URL for the room:

I am using Gitter Next, but the `chat-cache` feature is turned off.

![](https://i.imgur.com/aoRuBni.png) ![](https://i.imgur.com/FcRkMEE.png)

### Reproduction steps:

 1. Switch to any Gitter room (btw is it gitter or Gitter?)
 1. Reload the page
 1. The chat displayed seems to be cached for the earlier room, but everything indicates that you're in the room you switched to

This happens whenever one reloads the page, but does not occur when reloading with `Ctrl`+`F5` (which drops any cache kept for the webpage). Tested on latest release channel (48.0.2) Firefox. Also happens with JavaScript disabled. This gif might showcase the issue better:

![](https://i.imgur.com/XymwGoZ.gif)

---

:point_up: [August 30, 2016 2:55 AM](https://gitter.im/gitterHQ/gitter?at=57c53c0ee96ccc3a1063d9b7)

**Comment by MadLittleMods** [comment]
I am unable to reproduce and haven't heard any other reports of this. The only issues I know that produce similar bugs are https://github.com/gitterHQ/gitter/issues/1254 and https://github.com/gitterHQ/gitter/issues/1191

Can you try reproducing with a fresh FF install like the developer edition or Google Chrome? It might be an issue with a setting/plugin you are using.

**Comment by MadLittleMods** [comment]
>Doesn't happen on Chrome
>
> :point_up: [August 30, 2016 4:06 AM](https://gitter.im/gitterHQ/gitter?at=57c54ca2f9d724c34acdc440)

>Does not happen with Developer Edition either
>
> I guess it's a Firefox (addon) bug @MadLittleMods, you can label as wont-fix and close the issue if you wish
>
>:point_up: [August 30, 2016 4:07 AM](https://gitter.im/gitterHQ/gitter?at=57c54cee031de1dc53e1388a)

**Comment by viluon** [comment]
Active addons:
* Bloody Vikings!
* Cookies Manager+
* DownThemAll!
* DT Whois
* Enforce Encryption
* Ghostery
* HTTPS Everywhere
* I Don't Want to Miss a Notification!!
* Linkificator
* Master Password+
* MEGA
* Mind the Time
* multiple-highlighter
* Session Manager
* Shodan Firefox Addon
* Stylish
* Tab Groups
* Terms of Service; Didn't Read
* User Agent Switcher
* Wappalyzer

**Comment by InternetUnexplorer** [comment]
I can confirm I have this issue as well, it does not happen all of the time though.
I think it may be related to losing and regaining connection, as that is usually when it happens.

**Comment by MadLittleMods** [comment]
@InternetUnexplorer It sounds like you may be running into a separate issue and would prefer you create a new issue with your details.

**Comment by InternetUnexplorer** [comment]
@MadLittleMods My bad, I will do that.
Though it doesn't seem to be happening right now, so I will hold off on making a new issue until it occurs again.
(I haven't seen it happen in a bit actually, it may be fixed)

**Comment by grahamperrin** [comment]
> Chat Frame not matching Room URL

That was, for me, so frequent a problem with Gitter in multiple tabs in Firefox that I habitually restricted Gitter to no more than one tab. 

> … try reproducing with a fresh FF install like the developer edition …

For consideration, in Bugzilla for Mozilla – and [explicitly not](https://bugzilla.mozilla.org/show_bug.cgi?id=1245331#c8) a confirmed bug in Core: 

- [1245331 – Investigate how changing history state in iframe affects tab history](https://bugzilla.mozilla.org/show_bug.cgi?id=1245331)

– I make that suggestion loosely based on experience today with a new Firefox profile, and just one extension ([Diigo](https://addons.mozilla.org/en-GB/firefox/addon/diigo-web-highlighter-and-stic/) 5.1.0.38.1-signed.1-signed) wrongly attempting to bookmark a URL **from two steps back, in a domain, in the history of a tab**. (Not the gitter.im domain, and this version of the Diigo extension is not entirely bug-free on my FreeBSD-based system, however my nose tells me that some cooperative investigation may be appropriate.)

```
$ date ; freebsd-version ; uname -a 
Sun 13 Nov 2016 11:50:21 GMT
12.0-CURRENT
FreeBSD momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #14 1717ae3(drm-next-4.7): Fri Oct 28 13:49:49 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
$ pkg info firefox | grep ersion
Version        : 49.0_8,1
$ 
```

**Comment by MadLittleMods** [comment]
@grahamperrin This is most likely caused by `chat-cache` which is experimental and known to break things :point_up: [December 2, 2016 9:44 AM](https://gitter.im/gitterHQ/gitter?at=584196ef9750c95b4f892371)

**Comment by grahamperrin** [comment]
The URL mismatches were observed long before I knew of _next_ or `chat-cache`.
