### ISSUE TITLE
File upload does not work on Linux

### ISSUE THREAD

**Issue by mojaveazure** [gitterHQ/gitter#1413]
Every time I try to share a file with the Linux version of Gitter, I get an error saying that there was a problem connecting to the upload server. I am unable to replicate this issue with the same file using the Windows, Mac, and web (Chrome) versions of Gitter. I'm using Gitter v3.1.0 under Ubuntu 16.04 64-bit

**Comment by MadLittleMods** [comment]
@mojaveazure Does it work in the browser on linux?

The desktop app is open source if you want to take a look: https://github.com/gitterHQ/desktop

**Comment by mojaveazure** [comment]
It does work in the browser on Linux, but it's a little annoying having to open a browser just to send a file as the desktop app integrates with native notifications and is a nicer experience overall.

**Comment by MadLittleMods** [comment]
Can you create the issue on the desktop repo instead? https://github.com/gitterHQ/desktop

I was just curious if file upload worked in general on your system.

**Comment by mojaveazure** [comment]
Done.

**Comment by MadLittleMods** [comment]
Closed in favor of https://github.com/gitterHQ/desktop/issues/163
