### ISSUE TITLE
Use URL schemes for the apps.

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1417]
So when on the mobile site it will display a banner somewhere saying "Open in app" and you can dismiss it if you dont want.

This can be implemented in Android and iOS apps.

[Tutorial](http://fokkezb.nl/2013/09/20/url-schemes-for-ios-and-android-2/)

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/904

**Comment by TheDiamondYT1** [comment]
Oh sorry github should add a mobile site search :p
