### ISSUE TITLE
Branch name is processed as markdown in the activity tracker.

### ISSUE THREAD

**Issue by raghavrv** [gitterHQ/gitter#1420]
The branch name was `rename_results_`. As the `results` was surrounded by underscore, it seems to be italicized.

![image](https://cloud.githubusercontent.com/assets/9487348/18197758/3d2a238c-70f9-11e6-82e5-84b26ab6a210.png)

**Comment by MadLittleMods** [comment]
@raghavrv Can you file here instead https://github.com/gitterHQ/services/issues ? Looks like we need to escape names with any markdown-like syntax.

**Comment by MadLittleMods** [comment]
Closed in favor of https://github.com/gitterHQ/services/issues/80
