### ISSUE TITLE
Gitter API with javascript

### ISSUE THREAD

**Issue by herohamp** [gitterHQ/gitter#1421]
Is there a way to edit a Gitter message with JavaScript?

Also how can I run stuff when I send a message?

I plan on making a tampermonkey script remove the @username from when you type `/me`.

**Comment by MadLittleMods** [comment]
@herohamp See https://developer.gitter.im/docs/messages-resource#update-a-message on how to edit a message but you can only edit your own messages within a 5 minute window of sending.

To run stuff when a message is sent in a room, you can use the realtime-client: https://github.com/gitterHQ/realtime-client

We would prefer you didn't remove the username but perhaps you have some cool use for it, https://github.com/gitterHQ/gitter/issues/1004. Can you please share what you are planning to do?

**Comment by JordanB-1337** [comment]
We're just kind of messing around and having fun. It's a private chatroom, so it's not that big of a deal.

**Comment by herohamp** [comment]
yeah it was just funny tests

**Comment by JordanB-1337** [comment]
@MadLittleMods But thanks for the answer, though.
