### ISSUE TITLE
irc.gitter.im stylesheet

### ISSUE THREAD

**Issue by herohamp** [gitterHQ/gitter#1422]
is the stylesheet used in irc.gitter.im [stylesheet here](https://irc.gitter.im/css/irc.css) open source or would people get in trouble for using it? as it is a super cool stylesheet

**Comment by TheDiamondYT1** [comment]
[*cough*](https://github.com/gitterHQ/irc-bridge). I see no stylesheet but it is open source.

**Comment by MadLittleMods** [comment]
The IRC site isn't open source. @TheDiamondYT1 That is the IRC Bridge, not the site.

**Comment by TheDiamondYT1** [comment]
@MadLittleMods Oh, whoops
