### ISSUE TITLE
Ability to rename a room title

### ISSUE THREAD

**Issue by kmoore134** [gitterHQ/gitter#1424]
We are using gitter.im for TrueOS, as https://gitter.im/trueos/Lobby

This is fine, but what stinks is on the left menu where we can select between the Lobby and "GitHub commiter" chat, (https://gitter.im/trueos/), they both appear as just "TrueOS". It would be nice to be able to rename those, or have some other indication of what's public vs private.

**Comment by MadLittleMods** [comment]
-  [`trueos/Lobby`](https://gitter.im/trueos/Lobby): Community lobby
 - [`trueos`](https://gitter.im/trueos/): Org room

![](http://i.imgur.com/znAYf01.png)

---

This should of been resolved with the logic here: https://github.com/gitterHQ/gitter/issues/1350#issuecomment-243312475

But we didn't really expect people to have both the new world lobby rooms and old world org rooms in the same community.

I assume you created a new community with the create community flow, then clicked the `trueos` org at the bottom of the left menu to get into this situation. Or simply created a room called `Lobby` with your existing org. Is this your ideal setup or just how you happened to have things after working through our UI flows?

**Comment by MadLittleMods** [comment]
@kmoore134 Not on your side but that is what I was getting after if that was your ideal setup. What would you like them to be called?

**Comment by kmoore134** [comment]
Well, just anything to tell them apart really. Could the org room get renamed to "Project" or TrueOS (Org) something along those lines?

**Comment by MadLittleMods** [comment]
@kmoore134 No, org room is just a special org room that gets to exist under `trueos` URL.

You can create a new org room `trueos/Project` and we can move the messages over from other org room.

![](http://i.imgur.com/s6whPsH.png)

The lobby room is just a special public room that will get truncated to the community name in the left menu. Creating a room with any other name will show the room name.

**Comment by kmoore134** [comment]
Ok, I've created a private "Project" now. If we can move org contents over, that would be cool. Then can we remove the old org room?

**Comment by MadLittleMods** [comment]
@kmoore134 The messages should be moved from `trueos` to `trueos/Project`. You can delete the room yourself.

![](http://i.imgur.com/TO6uTgr.png)

**Comment by kmoore134** [comment]
Done, thanks for the help!
