### ISSUE TITLE
KaTeX font size too small

### ISSUE THREAD

**Issue by rjstone** [gitterHQ/gitter#1425]
Seems like the KaTeX font size is too small. Things like this don't display well:

```
 $$\frac{\frac{\sin}{\cos}}{\frac{1}{2}}$$
```

This is even worse:

```
$$\frac{1}{\frac{2}{\frac{3}{\frac{4}{\frac{5}{\frac{6}{\frac{8}{9}}}}}}}$$
```

Not sure how many people use this but might be worth improving a little by increasing font size. I think ideally the first case should be reasonably legible.

Screenshot:

![Screenshot](https://dl.dropboxusercontent.com/u/57161259/forum_images/gitter_latex_font_size.JPG)

:point_up: [September 7, 2016 6:04 PM](https://gitter.im/gitterHQ/gitter?at=57d09cf1fe284f6c30320396)

**Comment by MadLittleMods** [comment]
This can be solved by the font sizing options in KaTeX.

See https://en.wikibooks.org/wiki/LaTeX/Fonts#Sizing_text

```
$$\Huge\frac{1}{\frac{2}{\frac{3}{\frac{4}{\frac{5}{\frac{6}{\frac{8}{9}}}}}}}$$
```
