### ISSUE TITLE
Cannot create a room with a same name as an already existing repo

### ISSUE THREAD

**Issue by akuzminsky** [gitterHQ/gitter#1426]
I want to create a room for https://github.com/twindb/twindb_table_compare. I want use room name "twindb_table_compare", but get an error "You cannot create a channel with a same name that as an already existing repo". Is it expected? We do have rooms with same names as github projects that were created a while ago.

**Comment by MadLittleMods** [comment]
@akuzminsky You need to associate the room with the repo in order to create something with the same name. After choosing the community for the org, choose the repo from the typeahead in the room input.

![](http://i.imgur.com/Tnf1HDe.png)

![](http://i.imgur.com/OTtuUGe.png)

**Comment by akuzminsky** [comment]
@MadLittleMods, nothing pops up in the room name field when I type. Do I need to re-sync the community or something?

**Comment by akuzminsky** [comment]
Btw, why underscore isn't allowed in the room name?

**Comment by MadLittleMods** [comment]
@akuzminsky I don't see `twindb/twindb_table_compare`(or any `twindb` repos) coming back in your `/v1/user/:userId/repos` response which explains why you can't see it in the typeahead.

I am wondering if you have an application mismatch between your personal user and org on GitHub. Screenshots welcome 😀 

 - What do you see in your personal applications? https://github.com/settings/applications
 - What do you seen in your orgs third party access? https://github.com/organizations/twindb/settings/oauth_application_policy

**Comment by akuzminsky** [comment]
It looks like access for Gitter is allowed. `twindb_table_compare` is a public repo.

![image](https://cloud.githubusercontent.com/assets/1763754/18337593/d05435b6-7546-11e6-8749-45b19be14ac7.png)
![image](https://cloud.githubusercontent.com/assets/1763754/18337608/e531d600-7546-11e6-9875-14fc6b90056f.png)

**Comment by MadLittleMods** [comment]
@akuzminsky While the repo you are after is public, there is a mismatch between your applications.

Public and private personally and your org has only public. When we see you have private granted personally, we only use that private scope which isn't allowed on your `twindb` org.

You can grant private repo scope on the org or get rid of it personally.

The ideal scenario on our side would be to just check both tokens or even have a single token that we could upgrade the scope on as you go.

**Comment by akuzminsky** [comment]
@MadLittleMods , I solved the problem with twindb_table_compare. Thank you.

Now I create another room for https://github.com/box/Anemometer  and get same error (there is no dropdown list). 
![screen shot 2016-09-07 at 11 25 01 pm](https://cloud.githubusercontent.com/assets/1763754/18339192/f9224d0a-7552-11e6-9227-f822b66dfe59.jpg)

I revoked access to private personal repos (I can't grant access to private Box repos).

API call  https://gitter.im/api/private/gh/repos/box/anemometer succeeds, yet I can't create a room
![screen shot 2016-09-07 at 11 26 01 pm](https://cloud.githubusercontent.com/assets/1763754/18339230/2ffc4bfa-7553-11e6-8416-155689a11e0b.jpg)

**Comment by 3lvis** [comment]
I was able to fix this by removing all restrictions to 3rd parties.

<img width="770" alt="screen shot 2016-10-23 at 23 46 28" src="https://cloud.githubusercontent.com/assets/1088217/19629719/f578e4ba-997a-11e6-9030-9a6dfa144bd1.png">

https://github.com/organizations/ORGANIZATIONNAME/settings/oauth_application_policy

**Comment by stuartpb** [comment]
Yeah, I'm seeing this bug for public repos in an organization I've granted public repo access with.
