### ISSUE TITLE
Double take on 'OPEN IN GITHUB' wording

### ISSUE THREAD

**Issue by adrianblynch** [gitterHQ/gitter#1428]
When I click a Github link and the following appears:

<img width="543" alt="screen shot 2016-09-08 at 08 49 39" src="https://cloud.githubusercontent.com/assets/4160967/18341347/7c8832a6-75a1-11e6-8f58-d970ad25bef6.png">

I stop to think about whether or not it means open it in the Github client. It might well do that, I don't have the client installed, but if it doesn't and it always opens in the browser, could the wording be "OPEN ON GITHUB" or "GO TO LINK" or some such.

Not a big deal.

**Comment by MadLittleMods** [comment]
`Open in GitHub` just opens the link in the browser. We haven't heard any other comments on the language here.

The proposed wording is too general and not an improvement over current imo.
