### ISSUE TITLE
Auto page refresh with page in focus

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#1430]
I've been noticing since some days that my Gitter web interface auto refreshes fully sometimes.

What is it? Is it deliberate due to some update? or just some bug? :beetle:

In the support room, this was mentioned

> If you aren't looking at the page i.e. [**Page visibility API**](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) and there is an update it will refresh. 
>
> :point_up: [September 9, 2016 3:28 PM](https://gitter.im/gitterHQ/gitter?at=57d31b779a92399d6bef343d)

The bug :beetle: is, it happens right when I'm looking at the page.
It just happened twice in last 10 mins.
I was in a convo... i was reading others messages, then bam! :boom: &mdash; full page refresh.

**Comment by suprememoocow** [comment]
Thanks for the report @abhisekp.

Are you running next?

**Comment by MadLittleMods** [comment]
@suprememoocow *yes*

**Comment by suprememoocow** [comment]
Does the problem persist if you switch away from next onto the main production app?

Also, how frequently does this happen? Daily? Hourly? Every few minutes?

**Comment by abhisekp** [comment]
@suprememoocow I've not tested it in the stable release.
Also it happened with me before but it is not recurring frequently. That day it happened thrice though.
I've not experienced this bug since then.

**Comment by suprememoocow** [comment]
@abhisekp Thanks for the information. 

If this happens to you again, it would be super useful if you could open your chrome devtools, switch to the console tab, enable preserve log on navigation, and then run:

```
window.localStorage.debug='app:reload-on-update';
```

...and then reload your page.

Once you see this behaviour, grab a copy of your console logs and include it in the issue....

**Comment by MadLittleMods** [comment]
To note, `window.sessionStorage.getItem('forced_reload')` wasn't defined in either frame

:point_up: [September 9, 2016 4:42 PM](https://gitter.im/gitterHQ/gitter?at=57d32cbdc045e50a3686dbf9)

**Comment by suprememoocow** [comment]
Right, I've cleared up the logic behind auto-reload (it's being deployed to `next` as I write this). 

The logic should be a lot more bullet-proof than before. It works like this:

* When the client detects that it's out of date, it start a 15 minute timer. This ensures that the deployment is totally complete before the client reloads (we don't want them to reload and hit server where the deployment has not yet rolled out yet).
* After 15 minutes the client will begin waiting for the appropriate opportunity to reload. 
* The criteria for reloading are:
  * The client is eyeballs off (page visibility api)
  * The client is online (don't want to reload to when the client is disconnected)
* When the criteria have been met for 2 minutes, the reload will occur. If either criterion changes during this time, the timer is reset and the client will restart the wait.

Let's see if it works this time...

**Comment by alexwpotter** [comment]
Hey, just wanted to mention I ran into the same problem while using the webpage within [Franz](http://meetfranz.com/).
