### ISSUE TITLE
Creating links to long Data urls become links to https://goo.gl/7NDM3x

### ISSUE THREAD

**Issue by bwbw223** [gitterHQ/gitter#1432]
I was attempting to link to a really long data url while talking about the origins of the word "spam" and I linked to (contents of [this pastebin](http://pastebin.com/YyQCnFFj)) like `Have you heard of [spam](Data Url here)` and somehow, when clicked on, the link took me to https://goo.gl/7NDM3x instead of the data url...

**Comment by MadLittleMods** [comment]
@bwbw223 We link to rick roll when you try to script or data URI, see https://github.com/gitterHQ/gitter-markdown-processor/blob/3483cd0de6661d436df448b1d4df27afbb6252e0/lib/process-chat.js#L111

**Comment by bwbw223** [comment]
This is kind of annoying as I got kicked from a chat because of this

**Comment by bwbw223** [comment]
@MadLittleMods ^^
