### ISSUE TITLE
state syncronisation between client add and browser not working.

### ISSUE THREAD

**Issue by davidbuzz** [gitterHQ/gitter#1439]
**Environment:**

 - OSX with Desktop app  v1.177
 - Firefox 48 pointed at https://gitter.im

### Expected

I should see the same list of rooms that I'm signed into ( in both the desktop app, and the browser experience).  I don't.

I should see the same read/unread messages in each of the rooms I'm in.  I don't. 

After "catching up" ( by reading all the messages, or marking them all as red ) in one client, I'd expect the other client to display essentially the same state within some reasonable amount of time.  I don't.

The OSX Application also has a "Your Suggestions" section, that I'd expect to see in the browser.   I don't.   
... and If I don't see it in the browser because it's been dismissed , I'd expect it to be dismissed in both places.   I don't see that either.

**Comment by MadLittleMods** [comment]
Are you sure you are signed into the same account? Perhaps you signed into GitHub with one and Twitter in the other. Send a message from each user and check to make sure it is from the user you expect

![](http://i.imgur.com/rOTPe3h.png)

Can you share a screenshot from both the desktop app and browser when you are seeing differences?

**Comment by davidbuzz** [comment]
well, in that case.... now that it's been pointed out that I've been logged in as two separate user/s.... the actual issue is better described as "there is no obvious on-screen display of the logged-in username", AND "where is the logout button"?

**Comment by MadLittleMods** [comment]
We used to have that same user popover for the avatar next to the chat input but went away a bit ago and hasn't been restored yet. Which doesn't it make it obvious but easier to determine without having to send a message or look in the devtools.

A profile/preference area has been a tricky spot for us to get right and also ties into the sign out being too hard to find.

---

Sign out in the webapp

![](http://i.imgur.com/zlStvbv.png)


Sign out of the OSX app

![](https://i.imgur.com/kRkxuon.png)

**Comment by davidbuzz** [comment]
possibly also related:   https://github.com/gitterHQ/gitter/issues/859

**Comment by davidbuzz** [comment]
ok, well with that information... I was able to logout of the browser, then go to github.com and logout there, then reset my github password ( presumably expiring any previously used credentials in the process), then log back in to github, then pop back over the https://gitter.im, and it now looks the same as the native client.   easy.  (not )
