### ISSUE TITLE
Sign in/auth window resets after putting app in background

### ISSUE THREAD

**Issue by akuzminsky** [gitterHQ/gitter#1444]
The issue happens on iOS mobile app.
When I sign in I switch to a password manager to copy&paste username, password and 2FA code.

Every time gitter goes into background the auth window starts over.
Basically it makes it impossible to sign in.

**Comment by trevorah** [comment]
@akuzminsky We could be losing state if iOS closes the app due to memory pressure. If you close all other apps, does this still break?

**Comment by akuzminsky** [comment]
After closing other apps it works fine.

**Comment by trevorah** [comment]
I dont want to start tracking the github login state for the security concerns. The correct solution to this would be for the app to open up safari and let the login stuff happen there. Im going to close this for now though.
