### ISSUE TITLE
Android app drains battery too much

### ISSUE THREAD

**Issue by koresar** [gitterHQ/gitter#1446]
I spent like an hour in Chrome, but like 10 minutes in Gitter. And Gitter took twice more battery. ~19%

![screenshot_20160922-183847](https://cloud.githubusercontent.com/assets/1622575/18741896/deefc27a-80f4-11e6-9bef-b2daeed7f8b8.png)

---

Related to https://github.com/gitterHQ/gitter/issues/448

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/1147

**Comment by koresar** [comment]
More info. As you can see Gitter took radio active for 3 hours! But Chrome is only 1h 16min (right about the time I spent in the browser).
![screenshot_20160922-184831](https://cloud.githubusercontent.com/assets/1622575/18742075/b56597bc-80f5-11e6-86a9-248641be576a.png)
![screenshot_20160922-184843](https://cloud.githubusercontent.com/assets/1622575/18742081/bea3738a-80f5-11e6-8566-756d1d494303.png)
