### ISSUE TITLE
Gitter being funny

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1448]
The gitter site is acting up, messages are slow in sending and everyone keeps getting notifications saying it cant connect to the server. The IRC bridge is working better but not as well.

Also someone is spamming Gitter chat with porn

**Comment by mydigitalself** [comment]
What rooms are you seeing porn spam in? We're busy trying to clean it all up atm.

**Comment by texas2010** [comment]
@mydigitalself 
someone spamming in this room: 
https://gitter.im/gitterHQ/gitter
https://gitter.im/FreeCodeCamp/FreeCodeCamp
https://gitter.im/FreeCodeCamp/admin

**Comment by mydigitalself** [comment]
Yeah, got him, thanks.

**Comment by texas2010** [comment]
great  and thanks

**Comment by TheDiamondYT1** [comment]
You should have a list of all porn sites and check if it is being inserted into the chat and block it. Or, maybe keep it on the client side of the person posting the porn but not show it to others so they think that they are really posting it and dont try find workarounds,

**Comment by texas2010** [comment]
@mydigitalself, sorry. they spamming again right now.
