### ISSUE TITLE
Moving messages for a GitHub project that was renamed

### ISSUE THREAD

**Issue by vmunier** [gitterHQ/gitter#1449]
Hi,

The https://github.com/vmunier/sbt-play-scalajs GitHub project has been renamed to https://github.com/vmunier/sbt-web-scalajs.

Here are the corresponding Gitter rooms: 
https://gitter.im/vmunier/sbt-play-scalajs and https://gitter.im/vmunier/sbt-web-scalajs.

Would it be possible to move the messages from the `sbt-play-scalajs` room to the new `sbt-web-scalajs` room please?

Cheers,
Vincent

**Comment by MadLittleMods** [comment]
I have moved the messages from https://gitter.im/vmunier/sbt-play-scalajs to https://gitter.im/vmunier/sbt-web-scalajs and setup a redirect 🎉
