### ISSUE TITLE
Moderator request: remove part of the history for dev-ua

### ISSUE THREAD

**Issue by listochkin** [gitterHQ/gitter#1451]
Hello, I'm one of the moderators for [Dev-UA](https://gitter.im/dev-ua) community. We'd like to erase a portion of discussion from one of our rooms due to a number of sexist and racist remarks made by a few members of our community.

From: [September 27, 2016 12:24 PM](https://gitter.im/dev-ua/Main-Hall?at=57ea3ab8ab9ba81255e8f197) 
To: [September 27, 2016 4:56 PM](https://gitter.im/dev-ua/Main-Hall?at=57ea7aa0857ab70f7d464c19)

Thank you!

**Comment by MadLittleMods** [comment]
Done 😀
