### ISSUE TITLE
Duplicate rooms names in All Conversations list

### ISSUE THREAD

**Issue by sevenfourk** [gitterHQ/gitter#1453]
* I oversee this issue on incoming messages
* when I open gitter app to read it, I see other channel being renamed to another one
* now two same channel exists in my roster and both has the same unread message counts

![image1](https://cloud.githubusercontent.com/assets/75213/18925805/098e84f8-85be-11e6-8739-de30d6b05cdd.PNG)

**Comment by trevorah** [comment]
Seen it myself. Its an odd visual quirk when the room ordering changes. Its fixed with a restart, so its definitely not an issue with the underlying models.

Probably just a view being reused and not being rerendered.

**Comment by trevorah** [comment]
This should be live in a few days as v4.1.1.

**Comment by sevenfourk** [comment]
awesome, thanks guys.

**Comment by trevorah** [comment]
No worries @sevenfourk, thank you for reporting!
