### ISSUE TITLE
Unable to join some communities with twitter login

### ISSUE THREAD

**Issue by sri429** [gitterHQ/gitter#1454]
I am Unable to join some communities with twitter login. example FreeCodeCamp/FreeCodeCamp.
It says Only GitHub users can join this room.

**Comment by MadLittleMods** [comment]
Room owners have the option to restrict join access to only people signed in with GitHub. If you want to join rooms that have this restriction, sign out and sign back in with a GitHub account.

![](http://i.imgur.com/BMDOyF4.png)

---

Sign out

![](http://i.imgur.com/vTrY2ND.png)
