### ISSUE TITLE
How to update lurk propert on room ?

### ISSUE THREAD

**Issue by Odonno** [gitterHQ/gitter#1455]
I am using this endpoint (`user/{userId}/rooms/{roomId}`) to update `favourite` property of the room (for the current user signed in).

I hoped that I could update the `lurk` property through this endpoint but it didn't work. How to do that ?

**Comment by MadLittleMods** [comment]
@Odonno The `lurk` property is deprecated and is just derived from your notification settings.

```
PUT /v1/user/:userId/rooms/:roomId/settings/notifications
with
{ mode: "[all|announcement|mute]" }
```

**Comment by Odonno** [comment]
Thanks !
