### ISSUE TITLE
Why is there no skip parameter on search endpoints ?

### ISSUE THREAD

**Issue by Odonno** [gitterHQ/gitter#1456]
For example, when I am searching users or rooms, I don't know why the `skip` parameter does not work. There are a `q` and a `limit` properties but what if I want to make pagination ?

**Comment by MadLittleMods** [comment]
Both of these endpoints work with `skip`

```
/v1/rooms/:roomId/chatMessages?q=foo&lang=en&limit=30&skip=30
```

```
/v1/user?q=git&skip=10
```

---

Room search does take a `skip` parameter but it isn't taken into account further down the line.

```
/v1/rooms?q=a&skip=10
```

**Comment by Odonno** [comment]
What about `/v1/user/:userId/repos?q=a` ?

**Comment by MadLittleMods** [comment]
@Odonno `/v1/user/:userId/repos?q=a` does not have a `skip` parameter.
