### ISSUE TITLE
One-to-One notifications set to Announcements

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#1457]
### Introduction

It so happens that once upon a time, I was chatting with a lot of people. But suddenly my *chitter chatter* ended abruptly. People were curious what might be the reason of this sudden decline. Well, it was just the lack of notification. :bell: 

### Science and History

Human mind is a sophisticated form of advanced technology. But the worst part of it is it cannot do multitasking (parallel processing) although it can do tasks concurrently.

So that is the reason both computers and humans need INTERRUPT signal.
Human interruptions are mostly distracting statistically but in an environment like Gitter (*where developers meet*), productive endeavors are very common. 

As previously mentioned, Humans are inherently not adapted to interruptions. Hence, geniuses of the world have created the technological advancement known as **"Notifications"**. Notifications aid human-beings by adding as their 12th sense to get interrupted and chat with other humans.

-----
### The Bug

The one-on-one notification setting is auto set to "Announcements" instead of "All messages" even if the "Default Notification Settings" is set to "All Messages".

My default notification setting
> [![](http://i.imgur.com/b0AUAUP.png)](http://i.imgur.com/b0AUAUP.png)

**Comment by suprememoocow** [comment]
@abhisekp Thank you for this fantastic, detailed report! The fix for this should be in shortly..
