### ISSUE TITLE
Upload images through the api

### ISSUE THREAD

**Issue by Odonno** [gitterHQ/gitter#1459]
How to upload images through the api ?

I mean, I saw you are using transloadit to upload images but I don't know how to use it with an external client. Are you using the nodejs (https://github.com/transloadit/node-sdk) library or should I use the .NET SDK (https://github.com/nkranitz/transloadit-csharp-sdk) ?

**Comment by mydigitalself** [comment]
We don't support this with our API. If you want to do it yourself, you'd  have to integrate with transloadit or a similar service yourself and use markdown to embed the upload.

**Comment by MadLittleMods** [comment]
@Odonno It would probably be easier to just upload images to https://imgur.com/ and use the link generated.

**Comment by Odonno** [comment]
@MadLittleMods Yeah, thanks for the info, I'll try to use imgur.
@mydigitalself Ok, nice, I can do it using a markdown, that sounds good.
