### ISSUE TITLE
Add better information about permissions

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#146]
1. That admin access is needed to add hooks for example
2. For 404's of uncreated repo chats where you don't have access

**Comment by MadLittleMods** [comment]
We added a link to the 404 page to grant private repo scope

> Gitter
> 404. This is not the chat you're looking for. Sorry. :(
> 
> If you're looking to access a private repository, you will need to upgrade your GitHub authentication to allow us to access the list of your private repositories.
> 
> [Click here to do this now.](https://gitter.im/login/upgrade?scopes=repo)
