### ISSUE TITLE
Create new room: validation failed

### ISSUE THREAD

**Issue by kspearrin** [gitterHQ/gitter#1464]
Every time I try to create a new room for my repo at "bitwarden/home" I am getting "Validation failed". It seems to work for other repos under my organization.

![](http://i.imgur.com/CHiVlwo.png)

**Comment by MadLittleMods** [comment]
Hey @kspearrin,

Is this still an issue?

Can you share the request URL and POST parameters sent out when you try to create the room?

 - What applications do you have granted personally? (public, private)
 - What third party application access is granted on the org? (public, private)

I see you already did this but for future onlookers, you can also try making your org membership public, https://github.com/orgs/bitwarden/people


Reference,

 - https://github.com/bitwarden/home (no longer exists)
 - https://gitter.im/orgs/bitwarden/rooms

**Comment by avanderhoorn** [comment]
I'm seeing this same issue. My guess is that it has to do with repos that are called "home". 
<img width="720" alt="screen shot 2017-06-13 at 9 05 47 am" src="https://user-images.githubusercontent.com/585619/27092849-9feed184-5019-11e7-8b68-f5816560e01c.png">

**Comment by MadLittleMods** [comment]
@avanderhoorn `/community/home` is usually the community `homeUri` which is probably why you are getting this. https://gitter.im/Glimpse/home exists as your community home.

**Comment by avanderhoorn** [comment]
I get that its an issue, I guess I was hoping for a more useful error message. Had to dig and guess as to why what I wanted was an issue.

**Comment by MadLittleMods** [comment]
@avanderhoorn Create a new issue for improving the create room modal error message when you are trying to use a reserved room name that collides with the community `homeUri` 🙂
