### ISSUE TITLE
Eyeballs Disambiguation is incorrect

### ISSUE THREAD

**Issue by hardw0rk** [gitterHQ/gitter#1466]
According to Gitter, the eyeballs color means:

> So what does each color mean?
> 
> ```
> Green: Actively looking at the room
> Yellow/Orange: Not actively looking at the room
> ```
> 
> "Actively looking" equates to whether the window has focus and the room is open.

I created an group chat with over 30 members, but no one can see correct online status (always Yellow/Orange), even when someone is online currently. The problem happens always, not sometimes.

**Comment by mydigitalself** [comment]
The icon only turns green when somebody  has the room open and in focus, not when they are online.

**Comment by hardw0rk** [comment]
We tested many cases, but almost is `Yellow/Orange`. Rarely see someone is `Green`.

We almost use gitter via web. How long room open and in focus to see "Green" ?

**Comment by MadLittleMods** [comment]
@hardw0rk Almost immediately. If you have over 30 members, it will only show the first bit of users and won't sort by who is green, https://github.com/gitterHQ/gitter/issues/124
