### ISSUE TITLE
Dark Mode/Theme

### ISSUE THREAD

**Issue by Manish-Giri** [gitterHQ/gitter#1467]
This might be more of an enhancement/feature request, but I think a dark mode theme would be a nice feature to have for the gitter desktop chat app. 

I tried searching for any current/past issue about this, but couldn't find any.

**Comment by MadLittleMods** [comment]
See

 - https://github.com/gitterHQ/gitter/issues/1136#issuecomment-187607743
 - https://github.com/gitterHQ/desktop/issues/129

**Comment by TheDiamondYT1** [comment]
Would be nice in the gitter apps, aswell.

**Comment by janisozaur** [comment]
With gitter next now being all white, it burns out eyes and is harder to read than previous version. Please add an option to have some darker background.

**Comment by Manish-Giri** [comment]
Dark Theme is now available in the browser version(that I know of). Nice job!

**Comment by MadLittleMods** [comment]
See http://blog.gitter.im/2016/11/17/join-the-dark-side/
