### ISSUE TITLE
Possible Grammer Issue

### ISSUE THREAD

**Issue by epiciii** [gitterHQ/gitter#1472]
Hi, under the 5th challenge in the 'Getting Started' section it reads: "Our community has a popular Medium publication where we write publish tons of helpful articles..."

Should it read "Our community has a popular Medium publication where we write **and** publish tons of helpful articles..."?

Regards,

Eric

**Comment by MadLittleMods** [comment]
@epiciii This is for Gitter issues. It sounds like you are pointing out a typo in one of the Free Code Camp challenges. You should post the issue here instead https://github.com/FreeCodeCamp/FreeCodeCamp
