### ISSUE TITLE
Could not ban user, Ban failed

### ISSUE THREAD

**Issue by SerafimArts** [gitterHQ/gitter#1473]
Im an owner of group: https://github.com/orgs/LaravelRUS/people

After trying to ban `@vsshaposhnikov` user in https://gitter.im/LaravelRUS/chat chat I get the message:

![401 error](https://cloud.githubusercontent.com/assets/2461257/19527385/7779d666-9630-11e6-8467-136e352bb066.png)

Headers:

```
Request URL:https://gitter.im/api/v1/rooms/52f9b90e5e986b0712ef6b9d/bans
Request Method:POST
Status Code:401 Unauthorized
Remote Address:52.1.243.62:443
```

Then gitter throws me out of chat (unlogin).

---

See :point_up: [October 19, 2016 10:43 AM](https://gitter.im/gitterHQ/gitter?at=5807949bb827179842d84b93)

**Comment by mydigitalself** [comment]
Hey, sorry for the delay, just looking at this now -  is this still happening if you try to ban anyone at all?

**Comment by SerafimArts** [comment]
Same error with this user. But all OK with another.
![123123](https://cloud.githubusercontent.com/assets/2461257/19899896/c3018eb6-a072-11e6-8b0c-e7f3d70ab9f3.jpg)

**Comment by SerafimArts** [comment]
P.S. Not same. I does not lost an auth session.

**Comment by mydigitalself** [comment]
We can only ban users that are actually in the room, and `vsshaposhnikov` isn't in the room!

**Comment by SerafimArts** [comment]
He was... Long ago... It obtained already out.

It turns out the problem is solved, yep, thx =)
