### ISSUE TITLE
room unavailable and unleavable after github changes

### ISSUE THREAD

**Issue by ghiboz** [gitterHQ/gitter#1474]
hi all!
I changed my github plan (from basic to free) and all my repos become public..
after this, a private room that I created with the account is unavailable and is also impossible to leave it

the room is:
https://gitter.im/gRally/dev/DevCorner

the account that created this is
https://github.com/gRally

thanks

**Comment by MadLittleMods** [comment]
Solved a while ago, https://gitter.zendesk.com/agent/tickets/3634
