### ISSUE TITLE
Redirect Issues/Gitter Down?

### ISSUE THREAD

**Issue by gallexme** [gitterHQ/gitter#1476]
when i open gitter.im
it tries to redirect me to
https://fail.gitter.im/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1?host=gitter.im&status=502&request=GET%20/?host=gitter.im&status=502&request=GET%20/%20HTTP/1.1%20HTTP/1.1&host=gitter.im&status=502&request=GET%20/%20HTTP/1.1

**Comment by PyroChiliarch** [comment]
i started getting this about 5mins ago aswell
First i got 502 errors, then after a minute or 2 or restarting wiping cookies etc, i got something similar to you, a massive url

**Comment by Hunternnm** [comment]
I have the same problem

**Comment by PyroChiliarch** [comment]
i tried my brothers pc, it was fine the first time, but now is getting the same issue
(he dosn't use gitter)

**Comment by codesardine** [comment]
same issue here

**Comment by gallexme** [comment]
probably has something to do with the huge attack on dyndns
https://www.dynstatus.com/incidents/nlr4yrr162t8

**Comment by SerafimArts** [comment]
+1 Same.

P.S. gitter API are stable.
1) https://api.gitter.im/v1/ - OK (200)
2) https://stream.gitter.im/v1/ - OK (200)
3) wss://ws.gitter.im/ - OK (200)
4) https://gitter.im/api/v1/ - OK (200)
but:
5) https://gitter.im/ - Redirect (302) https://fail.gitter.im/ - FAIL (502)

**Comment by rreusser** [comment]
See: https://www.dynstatus.com/

Seems like @gallexme is probably correct. I think the recommended fix here is to work on something else or perhaps read a book. Maybe go for walk. There's likely nothing gitter has done to cause this or could do to fix this.

**Comment by gallexme** [comment]
this cant be, i got to work :/

**Comment by trevorah** [comment]
Yep, we're working on these dns issues at the moment. We're exploring every option rather than letting it pass.

Hopefully this message reaches github's servers...

**Comment by gallexme** [comment]
works for now :D

**Comment by trevorah** [comment]
All seems to be good now, we're just cleaning up our survival stuff now. I'm going to close this issue.

**Comment by SerafimArts** [comment]
@trevorah I hope that really "survival st*u*ff", and no "survival st*a*ff" :laughing:

**Comment by trevorah** [comment]
@SerafimArts haha no, we have a "Survival Mode" that limits the app if things get weird. It deactivates non-essential features and allows us to keep the minimum app running.
