### ISSUE TITLE
Gitter did not pickup an organization rename

### ISSUE THREAD

**Issue by alexandru** [gitterHQ/gitter#1481]
I renamed our GitHub organization from `monixio` to [monix](https://github.com/monix), however the rename wasn't picked up automatically by Gitter. Or more specifically:
- [https://gitter.im/orgs/monix/rooms](https://gitter.im/orgs/monix/rooms) yields a 404
- [https://gitter.im/monixio/monix](https://gitter.im/monixio/monix), the existing room I care about, has not been moved

This rename happened 2 hours+ ago, as I'm writing this. [Travis-ci.org](https://travis-ci.org/monix/), [Codecov.io](https://codecov.io/gh/monix/) have picked up the renaming, but not Gitter.

Note that this rename happened because the previous owner of the `monix` username gave up on it. The previous owner is now [@vanit](https://github.com/vanit) and he may have Gitter rooms or conversations needing a rename as well.

I tried logging out and back in with a fresh browser, but it didn't work. Does it take longer to refresh or something?

Thanks,

**Comment by MadLittleMods** [comment]
This was taken care of back on October 25th, https://gitter.zendesk.com/agent/tickets/3459

**Comment by alexandru** [comment]
@MadLittleMods yes, all is fine now, thanks.
