### ISSUE TITLE
Have option to show when you have read a message

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [gitterHQ/gitter#1485]
Some messaging clients allow one to choose to show when one has read a received message. For instance Facebook does this and also shows the timestamp.

For privacy reasons this is not necessarily the kind of thing you want to make compulsory or even enabled by default, but for those who want it it would be a nice feature.

**Comment by MadLittleMods** [comment]
You can see who has read a message under the checkmark icon in the top-right of every message.

![](http://i.imgur.com/MYOden0.png)
