### ISSUE TITLE
Text input box hidden when hotspotting etc. 

### ISSUE THREAD

**Issue by scottleibrand** [gitterHQ/gitter#1486]
Issue #1352 is back again. Still seeing it in 4.1.3. 
![img_8006](https://cloud.githubusercontent.com/assets/6982790/19827424/6a4575e2-9d5e-11e6-81ce-a983b14a638b.PNG)

**Comment by trevorah** [comment]
The original fix was set to only be applied to ios 9 with the hope that it wouldnt be needed for ios 10. Looks like its still needed in ios 10.

Assuming that you are running ios 10, i'll get the fix out for the next release.

Sorry about that @scottleibrand.

**Comment by scottleibrand** [comment]
Yes, and the problem came back about the time I upgraded to 10.  Thanks.
