### ISSUE TITLE
Request move of repository

### ISSUE THREAD

**Issue by aumayr** [gitterHQ/gitter#1488]
The repository https://github.com/aumayr/fava has been moved to https://github.com/beancount/fava.

Please rename https://gitter.im/aumayr/fava to https://gitter.im/beancount/fava

Thank you :)

**Comment by MadLittleMods** [comment]
Hey @aumayr,

Make your org membership public, https://github.com/orgs/beancount/people or have someone from that org with their membership public comment on this issue.

**Comment by aumayr** [comment]
Done  👍 (I made my org membership public)

**Comment by MadLittleMods** [comment]
@aumayr Sorry for the iteration. Also create the `beancount` community and room for the `beancount/fava` repo. We can transfer over the messages but the room members won't be moved over.

**Comment by aumayr** [comment]
Done 👍🏻

**Comment by MadLittleMods** [comment]
I have moved the messages over and setup a redirect, https://gitter.im/beancount/fava

**Comment by aumayr** [comment]
Thanks! 😊
