### ISSUE TITLE
Cannot access gitter.im/<homeUri> after leaving the room

### ISSUE THREAD

**Issue by dalcinl** [gitterHQ/gitter#1495]
@MadLittleMods You updated my community manually on 2016 Nov 01, but then I messed it again. After leaving the main ``homeUri`` room, I cannot access it anymore.  https://gitter.im/mpi4py gives me 404, however I can access https://gitter.im/mpi4py/mpi4py just fine.

**Comment by MadLittleMods** [comment]
The `homeUri` for your community is `mpi4py/home`. Visiting `mpi4py` and having it redirect depends on whether it has an org room.
