### ISSUE TITLE
URL/link blacklist

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1497]
Just like Twitters' t.co shortener, you could have a similar thing on Gitter to process and warn users about harmful or inappropriate links.

### Here's how i'd do it:

* Allow room owners to opt-out of the shortener for their room
* Allow users to suggest links to be added to the blocked list

Or if you don't want a URL shortener you could just add some kind of check after posting a message and if it contains links from the blocked list then the message would be removed. Once again, the room owner should be able to opt-out.

**Comment by MadLittleMods** [comment]
@TheDiamondYT1 What is your use case?

This sounds familiar to warning about outgoing links posted by banned users, see https://github.com/gitterHQ/gitter/issues/1468

**Comment by TheDiamondYT1** [comment]
@MadLittleMods Basically there should be a way to blacklist certain links so if they dont get sent in chats

This could also help block inappropriate images by blocking the origin site. 

Now of course someone could just use some link shortening service to get around the ban so maybe you could make the link show up on their client but not to anybody else?

**Comment by MadLittleMods** [comment]
@TheDiamondYT1 I already know what feature you want. I am more after what you are trying to stop. "This could also help block inappropriate images by blocking the origin site." goes a little ways but what rooms are suffering from this at the moment? (permalinks please)

I know the Ethereum community suffers from rogue links to illegitimate clones and viruses that have the Ethereum name on them but those domains are usually different.

**Comment by TheDiamondYT1** [comment]
I dont have any example, it was just an idea i had.

**Comment by MadLittleMods** [comment]
If you don't have a use, I am going to close for now. It's better to tackle an issue directly than by a generic feature.
