### ISSUE TITLE
Default notification setting should be "Announcements"

### ISSUE THREAD

**Issue by giacecco** [gitterHQ/gitter#1499]
"All: Notify me for all messages" is the default settings for notifications. I am sure you will agree with me that that does not make sense, and looks more like a bug than a feature. The natural default setting should be "Announcements: Notify me for mentions and announcements".

(was https://github.com/gitterHQ/desktop/issues/170)

**Comment by mydigitalself** [comment]
Hi, you do realise you can change your own default setting on the desktop/web app. From notification settings, there's a link at the bottom to change your default.

**Comment by timwis** [comment]
For what it's worth, I've been using gitter for about a year and never noticed that option. Quite handy! Always got annoyed when I'd join a room and then notice my phone blowing up the next day because I forgot to change the notification settings.
