### ISSUE TITLE
Add scroll bar to search result list

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1506]
Enhancement request. 

When there's not much chat – not much apparent in search results – the absence of a scroll bar can be a minor annoyance. 

The longer I spent in a recently-created set of rooms, the greater the frustration when I was forced to move from one result to another, without a scroll bar, without knowing when the list might end.

**Comment by MadLittleMods** [comment]
I see that it isn't visible on the clouds(purple) left menu.

The scroll bar has returned on our light theme revamp on [`next`](http://next.gitter.im/), just very light at the moment.

![](http://i.imgur.com/1N6ABTL.png)
