### ISSUE TITLE
Permalinks in notification email fail to take the reader to the specific point in time

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1507]
Context: https://gitter.im/trueos/Random?at=581284eb806316005dc98723

**Comment by MadLittleMods** [comment]
Clicking on that permalink brings me to the message appropriately and highlights it

![](http://i.imgur.com/X6FyakK.png)

**Comment by grahamperrin** [comment]
Yep, I rarely found a problem with any `?at=` URL

http://mailtracking.gitter.im/track/click/30050491/gitter.im?p=eyJzIjoicUh6Zi1KcmdDQTZxMHdPdXdZelJKeFFDeDBnIiwidiI6MSwicCI6IntcInVcIjozMDA1MDQ5MSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2dpdHRlci5pbVxcXC90cnVlb3NcXFwvTG9iYnkjdXRtX3NvdXJjZT1ub3RpZmljYXRpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249dW5yZWFkLW5vdGlmaWNhdGlvbnNcIixcImlkXCI6XCJkY2NlOWFhMmZhMDk0MzI4YmZkMmFjNjczNDE2MjgxYVwiLFwidXJsX2lkc1wiOltcIjdiNjdlMDdkZDgzNGZlY2JkY2NiMWU1MDE3NzllMDMyZWEwMWViODNcIl19In0 is exemplary of a notification via e-mail (last month, 2016-10-26) that my name was mentioned, with a keyword _personacrypt_

That link takes me to the wrong date (this month, yesterday, 2016-11-11) where it appears that nothing was written after 19:47. 

Symptoms now may be complicated by account closure, which I requested, but I'm certain that links (such as the one above) from notification e-mails did not work as expected _before_ the closure.

**Comment by MadLittleMods** [comment]
The open chat button (which I assume is where that link is from) will open that Gitter room but as redirected, doesn't have a permalink `?at` query string so it shouldn't go to where you were mentioned.

You can track this feature here, https://github.com/gitterHQ/gitter/issues/948#issuecomment-152497294
