### ISSUE TITLE
Change community name

### ISSUE THREAD

**Issue by apoydence** [gitterHQ/gitter#1513]
I created a room with the URL of https://gitter.im/apoydence/onpar#. However the name is onpar/onpar. Why is it not apoydence/onpar? Can it be renamed?

**Comment by MadLittleMods** [comment]
It looks like you created a community with a name of `onpar` and a URL/slug of `apoydence`. Then created a room off of that community called `onpar`.

There isn't a way for you to rename a community but I have renamed your community to `apoydence` manually.
