### ISSUE TITLE
Slide out notifications obscured by collapsed left menu on Next

### ISSUE THREAD

**Issue by sludge256** [gitterHQ/gitter#1517]
Notification messages are obscured by the left menu when using Next.

Default theme:
![default theme collapsed menu screenshot](http://i.imgur.com/ifR1SKU.png)

Dark theme:
![dark theme collapsed menu screenshot](https://cloud.githubusercontent.com/assets/10524623/20333333/b5c58cb2-ab66-11e6-9082-6fd2c821fa4d.png)

The issue does not appear to be present when the menu is expanded.
![dark mode open menu screenshot](http://i.imgur.com/k19lKWN.png)

**Comment by mydigitalself** [comment]
We've been wanting to remove these inline notifications for a while, it's supporting an entirely parallel notification system which desktop notifications does. So this has now been disabled in the next release.
