### ISSUE TITLE
Cannot create a new group

### ISSUE THREAD

**Issue by leozulfiu** [gitterHQ/gitter#1518]
When I want to finish the creation process of a new group I get this error.

![capture](https://cloud.githubusercontent.com/assets/16990590/20341083/e4fa25e6-abe4-11e6-8a91-13b92f77f6c1.PNG)

**Comment by sonyccd** [comment]
I am also having the same problem

**Comment by MadLittleMods** [comment]
@leozulfiu @sonyccd Post a screenshot of the last page with "Create and Finish" or in the devtools network panel, share the POST payload parameters sent out.

**Comment by leozulfiu** [comment]
Tried it again today. Works now!
