### ISSUE TITLE
Stripped down version of the site

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1519]
Have a verson of the site that has very minimal css that works on old browsers. An example of this would be going to [Gmail](https://mail.google.com) when you select the `Load basic HTML` link.

Github works on older browsers (Im posting this from a PS3!), so Gitter should too. 

Alternatively make a Gitter app for PS3 but i doubt that will ever happen.

**Comment by MadLittleMods** [comment]
We only support a couple versions of the major browsers.
