### ISSUE TITLE
Edit button seems to be disabled in the chat

### ISSUE THREAD

**Issue by Manish-Giri** [gitterHQ/gitter#1520]
The "edit" option for your own post seems to be disabled in the chat room - 

![untitled](https://cloud.githubusercontent.com/assets/11348778/20358421/bb893c78-abf9-11e6-8278-0da8d0cf110c.png)

**Comment by MadLittleMods** [comment]
@Manish-Giri You can only edit messages within the 5 minute edit window.

**Comment by Manish-Giri** [comment]
@MadLittleMods I'm aware of the time window, I've been using gitter for quite a while now. Today, I can't seem to edit my post, even within a second of posting it.

**Comment by MadLittleMods** [comment]
@Manish-Giri I am unable to reproduce on prod or next.

 - Are you sure it is your own message?
 - Does this happen in all rooms? (which room is it happening in?)
 - Which OS and browser?

**Comment by Manish-Giri** [comment]
@MadLittleMods I was suggested this by a user in the gitterHQ chat room 
> like your computer clock is actually in the past but on a different time zone or something. the logic is client-side, so that could potentially influence it.

Turns out my computer clock was on a different setting, that might probably be the reason.
