### ISSUE TITLE
Table zebra stripe needs styling on dark theme

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1521]
As reported by @kbrock, :point_up: [November 16, 2016 4:21 PM](https://gitter.im/gitterHQ/gitter?at=582cdbe14182d0a76b3395b0)

Table zebra stripe needs styling on dark theme

![](http://i.imgur.com/eaTf8sy.png)

```
a | b | c
--- | --- | ---
d | e | f
g | h | i
```

**Comment by mydigitalself** [comment]
Fixed in next build.
