### ISSUE TITLE
Popovers have white theme (issue and user)

### ISSUE THREAD

**Issue by Exerro** [gitterHQ/gitter#1529]
In the dark theme, clicking on an issue (in the form `#372`, for example) will bring up the issue preview in an apparently white theme:

![](http://i.imgur.com/sVQG70W.png)

**Comment by Exerro** [comment]
Someone pointed out that the same goes for usernames:
![](http://i.imgur.com/9FOHN5u.png)

**Comment by KrofDrakula** [comment]
Here's another example of the same:

![](https://files.gitter.im/gitterHQ/gitter/xwNL/dark-theme.png)
