### ISSUE TITLE
Deal with renaming on Github

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/gitter#153]
Sometimes repositories are renamed on Github. We need to deal with this situation better.

Reported by @hunterboerner

**Comment by trevorah** [comment]
So use-cases that we need to handle:
* [rename repo](https://help.github.com/articles/renaming-a-repository/)
* rename [user](https://help.github.com/articles/changing-your-github-username/)/[org](https://help.github.com/articles/renaming-an-organization/)
* [transfer of ownership](https://help.github.com/articles/transferring-a-repository/)
* [convert user into org](https://help.github.com/articles/converting-a-user-into-an-organization) (never throws a 404 :fearful:)
* [convert org into user](https://help.github.com/articles/converting-an-organization-into-a-user/) (not easy and involves several transfers that *could* be done quick enough to never throw a 404 :fearful:)

**Comment by Katbow** [comment]
Has this issue been fixed? I want to rename a repo that has a corresponding gitter, but I'm concerned I won't be able to rename the gitter room, and that the users would have to manually move to the new room.

**Comment by MadLittleMods** [comment]
@Katbow Once you renamed the repo on GitHub, we can move the messages over manually to the new room. This wouldn't transfer the users as it is a new room.

**Comment by QwertzHz** [comment]
I renamed my org and now I can't get into the old room or create a new one via "Your Organisations".

**Comment by MadLittleMods** [comment]
@QwertzHz Can you try visiting the renamed org manually via URL?

**Comment by QwertzHz** [comment]
I fixed the issue by un-renaming the org, deleting the room, re-renaming
the org, and recreating the room.
