### ISSUE TITLE
Gitter Next message bar covers action icons (Firefox)

### ISSUE THREAD

**Issue by someth2say** [gitterHQ/gitter#1533]
With new Next look, in FireFox (developer edition), when channel message is too large, it hides action icons (globe, favorite, settings and user). Even if I mouse-over, it rapidly shows and hides icons repeatedly.

Icons become reachable if I zoom out, even if the channel message still does not fit.

See capture before...
![capture 1](https://cloud.githubusercontent.com/assets/13310156/20429085/c80bee8e-ad8c-11e6-929d-563396d4ae3e.PNG)
and after zooming:
![capture 2](https://cloud.githubusercontent.com/assets/13310156/20429086/c80c8240-ad8c-11e6-9e79-84d2b08b77b0.PNG)

![](http://i.imgur.com/YDa3M0Y.gif)

**Comment by zoltanalmodo** [comment]
hi guys,

i have the same problem and some other folks too in firefox 50.0
and i cannot reach the settings icons. it seems like that part of the website is of - screen somehow.

any solutions other than zooming in / out the whole webpage?

thanks
z
