### ISSUE TITLE
Request to move room to new organization

### ISSUE THREAD

**Issue by jck** [gitterHQ/gitter#1540]
https://github.com/jandecaluwe/myhdl has been moved to https://github.com/myhdl/myhdl

**Comment by MadLittleMods** [comment]
For some extra info, see https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo

I have moved `jandecaluwe/myhdl` to `myhdl/myhdl`
