### ISSUE TITLE
Notifications on Android ignore my do not disturb

### ISSUE THREAD

**Issue by JimLewis** [gitterHQ/gitter#1541]
I am getting notifications on Android even when my general do not distrub is on.  

Also, when I turn on notifications on Android, I get all forms of notifications. The only notifications I want from Gitter are the popup sort on the screen. I never want vibrate. However, some apps I want to vibrate, hence, it is enabled. I just don't want Gitter using it.

**Comment by MadLittleMods** [comment]
- What version of Android are you on?
 - What device do you have?
 - Take a screenshot to show what kind of do not disturb you are considering "general"

You can track this issue for adjusting the way a certain app sounds off or vibrates, https://github.com/gitterHQ/gitter/issues/462

---

 - On a Moto E running Android 5.1, the sleep mode do not disturb works just fine with Gitter.
    - I see there is also Settings -> Sound & notification -> Interruptions -> Downtime but that is not set
 - On a Google Pixel running Android 7.1, the native `Do not disturb`(Settings -> Sound -> Do not disturb) works just fine with Gitter.

**Comment by MadLittleMods** [comment]
Closing because lack of response and not able to reproduce.
