### ISSUE TITLE
Request to move room to new organization

### ISSUE THREAD

**Issue by danieldietrich** [gitterHQ/gitter#1551]
The repository https://github.com/javaslang/javaslang-circuitbreaker has been moved to https://github.com/RobWin/javaslang-circuitbreaker.

@MadLittleMods could you please create a redirect similar to what you did [here](https://github.com/gitterHQ/gitter/issues/1407#issuecomment-243256605)? Thank you!

/cc @RobWin

**Comment by MadLittleMods** [comment]
https://gitter.im/RobWin/javaslang-circuitbreaker is ready to go (https://gitter.im/javaslang/javaslang-circuitbreaker redirects).
