### ISSUE TITLE
Show number of people in the room

### ISSUE THREAD

**Issue by asmeurer** [gitterHQ/gitter#156]
It would be nice if somewhere it showed the number of people in the room, and maybe also the number of active people (green circles).

**Comment by MadLittleMods** [comment]
If you click the globe in the top right(next to the favorite icon), you can go to the Community page which displays the number of people in the room.

```
https://gitter.im/orgs/orgname/rooms
```

![](http://i.imgur.com/1zx0OFT.png)

**Comment by trevorah** [comment]
Note that this is only available on [next](next.gitter.im).

**Comment by MadLittleMods** [comment]
This was added a bit ago:

![](http://i.imgur.com/83MhOzF.png)

Feel free to create another issue about showing a count of active "green circle" users.
