### ISSUE TITLE
How to differentiate a user from a community with the same name?

### ISSUE THREAD

**Issue by mdbs99** [gitterHQ/gitter#1561]
My problem is exactly the opposite of #1372 

I've tried to create my first chat. I thought that I need to create a community first, not a room. So I've created a community using my user id and typed a name (my first name).
The "problem" is that the room names are showed like that: "My Name"/room_name.
I would like to see like "mdbs99/room_name".

![image](https://cloud.githubusercontent.com/assets/1459306/21085820/5173e186-bffd-11e6-9e9c-232005c19514.png)

**Comment by mdbs99** [comment]
Besides that, I can't access the URL https://gitter.im/mdbs99/home
I guess the system do not know if "mdbs99" is an user or community.

**Comment by MadLittleMods** [comment]
The `mdbs99` community has `homeUri: 'mdbs99'` but it should be `homeUri: 'mdbs99/home'` given it conflicts with your own user on Gitter.

I have updated it for you and created an issue internally about fixing up the issue that caused it, https://github.com/troupe/gitter-webapp/issues/2546

**Comment by mdbs99** [comment]
@MadLittleMods that's great. It's working now, thanks.

If you will allow me one more question, how can I update the name of my communities?

**Comment by mdbs99** [comment]
@MadLittleMods I saw the issue #1513 now.
If you could update my commuty name to just "mdbs99", I'll appreciate that . Thanks.

**Comment by MadLittleMods** [comment]
@mdbs99 Done 😀

**Comment by mdbs99** [comment]
@MadLittleMods thank you!
