### ISSUE TITLE
Emails notification are not sent

### ISSUE THREAD

**Issue by jcubic** [gitterHQ/gitter#1570]
From some time I don't get email notifications, in room options in notification section i have set "All: Notify me for all messages" but I don't get the emails.

**Comment by mydigitalself** [comment]
We're busy migrating our email notifications onto a new provider platform and are experiencing some delivery issues at the moment.

**Comment by kmscode** [comment]
FYI. I'm still experiencing this problem as well.

**Comment by bvaughn** [comment]
This is a pretty high-impact (in a bad way) issue to be continuing for so long. Any update from Gitter about when email notifications may start working again? I think it's been about a month and a half since I last received one.

**Comment by jcubic** [comment]
I've switch to desktop app, so I've now get sound notifications instead.

**Comment by seekM** [comment]
When can we expect it to work again?

**Comment by chilimangoes** [comment]
Adding my voice to the list of people who would really like to see a fix for this. I haven't been getting email notifications for months now.

**Comment by synkarius** [comment]
I would also love to see this fixed.

**Comment by pitr-ch** [comment]
@mydigitalself Please fix this! I like Gitter but this very annoying.

**Comment by melrief** [comment]
Same here, it's very annoying

**Comment by francium** [comment]
Since I started using gitter, in January, I did receive 1 email (surprising -- considering this bug is still open) on Feburary 13 about an unread message. But since then, I have not received any other emails.

**Comment by bfistein** [comment]
Anything? This is pretty frustrating

**Comment by hishamhm** [comment]
Same situation here. No notifications since Dec 8 2016, except for a single one on Feb 13 2017. This has impacted the community use of the project room really badly.

**Comment by mydigitalself** [comment]
Hi folks, sorry, we've announced this a number of times on Twitter & GitterHQ/gitter. 

We're in the process of migrating our email provider over to a new one, and have had some issues due to our volumes effectively being too high for the new provider and we need to build a non-spam reputation with them! We're probably going to start un-migrating it back again.

*sigh*

**Comment by mydigitalself** [comment]
We've successfully un-migrated back to our previous provider, if you still don't get email notifications, please comment & reopen. 

Sorry, that was a super painful process and will look to re-migrate again in the future without the same thing happening again.

:shame:

**Comment by pitr-ch** [comment]
@mydigitalself Thank you very much for restoring the notifications!
