### ISSUE TITLE
Request to resolve community and user URI conflict

### ISSUE THREAD

**Issue by 4U6U57** [gitterHQ/gitter#1573]
Same problem as #1561.

I created a community with the same name as my username (@4U6U57) to host rooms for my personal repos. This has resulted in an error, as attempting to access my community "Home" resolves to https://gitter.im/4U6U57, which redirects to https://gitter.im/home/explore because it thinks I'm trying to start a private chat with myself. Likewise, trying to access https://gitter.im/4U6U57/home results in a 404.

Request that you change my community `4U6U57`'s `homeUri: '4U6U57/home'`.

**Comment by MadLittleMods** [comment]
Done 😀 https://gitter.im/4U6U57/home
