### ISSUE TITLE
source code for gitter archives?

### ISSUE THREAD

**Issue by lmj0011** [gitterHQ/gitter#1577]
I asked this in the gitter dev room, but it's unlikely to get answered there.
https://gitter.im/gitterHQ/developers?at=58774bb6074f7be763bf8cea

I would like to make an archive page like gitter's for a chat app I'm working on.
Was wondering if anyone could direct me to the source code for it.
https://gitter.im/gitterHQ/developers/archives/all

**Comment by MadLittleMods** [comment]
@lmj0011 That area of code is not open source. We are using [`cal-heatmap`](https://github.com/wa0x6e/cal-heatmap) for the heatmap. More specifically, this fork https://github.com/gitterHQ/cal-heatmap/tree/fix-d3-version
