### ISSUE TITLE
Multiple icons showing in notifications bar Linux/Gnome

### ISSUE THREAD

**Issue by chrislanejones** [gitterHQ/gitter#1582]
My top bar is showing four icons at the top.

![screenshot from 2017-01-15 08-47-19](https://cloud.githubusercontent.com/assets/20934134/21963002/b70e2b06-daff-11e6-9a9b-052624030e81.png)

**Comment by MadLittleMods** [comment]
@chrislanejones Each one is probably its own instance. We don't limit you to one instance because of how we currently do updates.

**Comment by chrislanejones** [comment]
That fixed the problem, thanks!
