### ISSUE TITLE
Huge tweet display on url to account

### ISSUE THREAD

**Issue by RWOverdijk** [gitterHQ/gitter#1583]
I think this screenshot says it all.

https://www.dropbox.com/s/z8e0eeeubcyzwc7/Screenshot%202017-01-14%2023.10.33.png?dl=0

**Comment by MadLittleMods** [comment]
Closing as duplicate of https://github.com/gitterHQ/gitter/issues/1399

Sorry, re-read and is a general issue instead of just gists.

**Comment by RWOverdijk** [comment]
Psh, that teaches me to listen to you haha.
