### ISSUE TITLE
Gitter room with /username/repo-name url (like Github repo)

### ISSUE THREAD

**Issue by tomav** [gitterHQ/gitter#1585]
Hi, I've seen some user having their github project url having the same pattern they have on Github:
* https://gitter.im/webpack/webpack
* https://github.com.im/webpack/webpack

or

* https://gitter.im/plouc/mozaik
* https://github.com/plouc/mozaik

I'm unable to get it working.
I tried for my repo https://github.com/tomav/docker-mailserver and had https://gitter.im/docker-mailserver

This is not what I expected.

Question:
- how can I reset all communities/room created for my `tomav` username
- how can I create community/room with the model explained above?

Thanks guys, pretty good work on that project!

**Comment by MadLittleMods** [comment]
You need to create a community associated with the `tomav` GitHub user (I think we will pick it up if you name the community as yourself). Then create rooms under that `tomav` community.

---

Relevant issues
 - https://github.com/gitterHQ/gitter/issues/1372

**Comment by tomav** [comment]
Thanks, works perfectly.
