### ISSUE TITLE
Not joined, search result link error

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1588]
1. https://gitter.im/trueos/random
2. refrain from joining
3. seek _atom_
4. click the content of the result
5. nothing happens
6. click the date of the result
7. nothing happens
8. copy the URL of the date of the result

https://gitter.im/?at=587d39d396a565f844091fa8 is not a point within the room. 

Originally observed with Firefox, the issue was reproduced with QupZilla then Chromium.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/1482
