### ISSUE TITLE
Request to move room to new organization ochrons/boopickle

### ISSUE THREAD

**Issue by ochrons** [gitterHQ/gitter#1589]
Repo https://github.com/ochrons/boopickle is now at https://github.com/suzaku-io/boopickle and I'd like to have the connected Gitter channel transferred as well.

**Comment by ochrons** [comment]
Ping @MadLittleMods what's the process on getting this change implemented?

**Comment by MadLittleMods** [comment]
@ochrons https://gitter.im/suzaku-io/boopickle is ready to go 🎉
