### ISSUE TITLE
Request move repo room to new organization ochrons/diode

### ISSUE THREAD

**Issue by ochrons** [gitterHQ/gitter#1590]
Repo https://github.com/ochrons/diode is now at https://github.com/suzaku-io/diode and I'd like to have the connected Gitter channel transferred as well.

**Comment by ochrons** [comment]
Ping @MadLittleMods what's the process on getting this change implemented?

**Comment by MadLittleMods** [comment]
@ochrons https://gitter.im/suzaku-io/diode is ready to go 🎉
