### ISSUE TITLE
Logout seems ineffective

### ISSUE THREAD

**Issue by polyvertex** [gitterHQ/gitter#1592]
On the web interface, it seems my session remains up even after a logout (i.e. the "green led" on my avatar is still there).

* I can't recall having any error message or different kind of behavior while logging out
* I have logged out from every device
* I have then cleaned up the cache/cookies from my browser to ensure i's not just an image cache thing then relaunched my browser
* It's the first time it happens and it seems my account have been up for about a couple of days maybe (estimated)
* I use my GitHub account to log-in

**Comment by MadLittleMods** [comment]
@polyvertex What happens if you press sign out now? It should move you back to the home page. Refresh, what happens then?

Just to clarify, if you press sign in on Gitter, and you are already signed into GitHub, it will just move you along without having to go through the GitHub sign in process.

**Comment by polyvertex** [comment]
@MadLittleMods at this very moment the site seems unreachable (timeout at connection; I'm aware you guys are experiencing issues with the platform so bad timing I guess). But to clarify, when I sign out, it does come back to the home page and may I need to chat in a room again, I would need to sign in first (all good). It's just that if I display a particular chat room I'm registered in, *while being signed out*, my avatar still have the green icon like if I were connected.

If you precisely need the info you asked, I will try once the site is up then report here.

**Comment by polyvertex** [comment]
To follow on previous comment, I just tested so:

> What happens if you press sign out now? It should move you back to the home page. Refresh, what happens then?

It goes back to gitter's home page. I hit refresh, it stays on home page and I would have to sign in again in order to chat in a room. The avatar remains green though.

> Just to clarify, if you press sign in on Gitter, and you are already signed into GitHub, it will just move you along without having to go through the GitHub sign in process.

In this case yes. I'm not asked for my password and I get signed in just fine.

**Comment by MadLittleMods** [comment]
Do you have the [IRC bridge](https://irc.gitter.im/) hooked up?

Keep in mind it could just be a stuck eyeball (it happens).

**Comment by polyvertex** [comment]
Nope, no IRC bridge.
I'm not sure why you closed it but just to clarify, the issue still stands.

**Comment by MadLittleMods** [comment]
> Keep in mind it could just be a stuck eyeball (it happens).

Also, I don't see any presence/eyeballs for your user, ` NODE_ENV=prod ./scripts/utils/list-user-presence.js --username polyvertex` -> `[]`

**Comment by polyvertex** [comment]
FYI eyeball's "behavior" just got back to normal after my last sign out a few minutes ago.
