### ISSUE TITLE
Gitter not working

### ISSUE THREAD

**Issue by OFFLlNE** [gitterHQ/gitter#1593]
I tried restarting browser. Deleting history. Restarting computer. NOTHING helps.

It seems like JS is not working and nobody can see me writing anything.
Did not find any solutions on the internet either.

Smiles, issue highlights, unread messages nothing works.
Tried Firefox and Chrome. Inside console:
![image](https://cloud.githubusercontent.com/assets/8721312/22330734/666681d8-e3d0-11e6-9a53-18c7357580b0.png)

**Comment by teldosas** [comment]
Same here

**Comment by phlax** [comment]
8(

**Comment by jducoeur** [comment]
Ditto.  Loads of problems trying to read -- in particular, when I switch rooms, the headline changes but the content does not.  (That is, I switch to "scala/scala" and the title bar changes, but the conversation for "scala-js/scala-js" is still showing.)  And when I read through new stuff, the green markers go away, but the "unread" counter in the left bar doesn't go down.

Note that, in the latter case, the records clearly *are* being marked as read on the server -- if I reload, the unread counter has zero'ed out.  So the issue clearly has something to do with it throwing exceptions client-side while reading.

Something's very, very broken this morning...

**Comment by mydigitalself** [comment]
Folks, check our Twitter: https://twitter.com/gitchat/status/824604730496278529

**Comment by smaiLee** [comment]
I'm sorry, but why do you close the issue if it is still broken?

**Comment by mydigitalself** [comment]
@smaiLee because Twitter is our SSOT for incidents, not GitHub issues.
