### ISSUE TITLE
After being removed from a room, I have a permanent notification.

### ISSUE THREAD

**Issue by fluffywaffles** [gitterHQ/gitter#1595]
I was removed from a Gitter room when I lost access to a private repository. When I was removed, there was an unread mention in the channel and so there was a waiting notification. Now, I still have a mention notification that will not go away.

If I try to go to the room, I see a blank window with a button to "Join room." If I try to leave the room from the left-hand collapsible menu, it does nothing.

Sad.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/1442

I know this is sometimes used on purpose where an admin mentions a trouble-user and bans them causing a stuck notification annoyance.

**Comment by fluffywaffles** [comment]
I'm fairly certain I wasn't banned? I think I was just removed from the room. I don't see why that would count as a ban.

**Comment by fluffywaffles** [comment]
I believe the error occurred due to changing my GitHub username.

That said, today Gitter suddenly allowed me to leave the room. So... I guess this is resolved in some sense? I no longer have this issue. There may still be a bug here.

**Comment by MadLittleMods** [comment]
If you renamed your user, signing out and signing back in would resolve some things.
