### ISSUE TITLE
Activity log dead for all repos.

### ISSUE THREAD

**Issue by abhsag24** [gitterHQ/gitter#1596]
the activity log isn't being updated since yesterday and this an issue on all repos which i work on. 
for example channels:  https://gitter.im/NIT-dgp/General , https://gitter.im/coala/coala

**Comment by DzmitryShylovich** [comment]
Looks like it was fixed

**Comment by mydigitalself** [comment]
Yip, sorry we had to disable some auxiliary services owing to the issues we had last week.
