### ISSUE TITLE
Docker Hub integration Broken

### ISSUE THREAD

**Issue by prudhomm** [gitterHQ/gitter#1600]
I have integrated docker hub notifications (image push) in the room feelpp/feelpp. Unfortunately when images are pushed there are no notifications in the Room activity.
It seems that DockerHub integration is broken

**Comment by MadLittleMods** [comment]
See https://github.com/gitterHQ/gitter/issues/1596

**Comment by MadLittleMods** [comment]
Update https://twitter.com/gitchat/status/826484930611908609

Still seeing issues?
