### ISSUE TITLE
Can not create new room in desktop app (modal buttons hidden in footer)

### ISSUE THREAD

**Issue by jmcmurry** [gitterHQ/gitter#1602]
It does not seem possible to create a new room using the desktop application; the "create room" button is missing. The gitter.im web interface works fine for this.

<img width="636" alt="screen shot 2017-02-02 at 1 32 26 pm" src="https://cloud.githubusercontent.com/assets/3658863/22570729/67dffe28-e951-11e6-9030-b5a410913534.png">

**Comment by MadLittleMods** [comment]
I am guessing this is the safari-based macOS app on an older version of OS X. This is a bug with any modal.

You can download the NW.js version of the app that shouldn't have the issue, https://update.gitter.im/osx/Gitter-3.1.0.dmg

**Comment by jmcmurry** [comment]
Indeed; thanks. That works.
