### ISSUE TITLE
Repo room organization change

### ISSUE THREAD

**Issue by adelbertc** [gitterHQ/gitter#1603]
Hello,

I recently changed the GitHub organization for [frameless](https://github.com/typelevel/frameless) from `adelbertc` to `typelevel`. There was also a corresponding Gitter room back when the project was under `adelbertc` - I was wondering if the room name would reflect the organization change automagically or if there needs to be some manual process e.g. this ticket. If the latter, please consider this ticket my request for a rename from `adelbertc/frameless` to `typelevel/frameless`.

Thanks!

**Comment by MadLittleMods** [comment]
Renames require manual action, see https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo

Done https://gitter.im/typelevel/frameless

**Comment by adelbertc** [comment]
@MadLittleMods Ah gotcha, thanks!
