### ISSUE TITLE
Activity pane disappears

### ISSUE THREAD

**Issue by polyvertex** [gitterHQ/gitter#1604]
On the web interface, the `People + Activiy` pane occasionally "disappears". It is quite easy to reproduce at least on [this](https://github.com/fmtlib/fmt) and [that](https://gitter.im/Keypirinha/Keypirinha) room by pressing `F5`. Pane disappears approx. 2 times out of 3, at the end of the refresh process.

If I happen to be signed-in and that I am owner of the room, the following message will appear instead of just having an empty pane:

```
Activity

We haven't seen any activity yet.

Configure your integrations →
```

* I have double-checked the Gitter integration in the related GitHub repo and have simulated a test successfully (the result is visible when the Activity pane gets displayed properly)
* It does not seem to be related to the use of a particular browser (tested with Chrome, Firefox and IE)
* Not sure it's related to #1601 as I observe different symptoms

**Comment by bronger** [comment]
We observe the same in https://gitter.im/join2, no matter which client.  Moreover, it *always* disappears for us eventually.

**Comment by polyvertex** [comment]
"It works for me" now. @bronger?

**Comment by mydigitalself** [comment]
This was a side effect of the infrastructure issues we experiencing over the weekend and we disabled some functionality that puts additional load on our servers in order to make sure that basic chat functionality was working. 

It should all be just fine now.
