### ISSUE TITLE
Request to move room to new organization ochrons/boopickle

### ISSUE THREAD

**Issue by aubreypwd** [gitterHQ/gitter#1605]
I'd like to have `wp-todo/Lobby` moved to and renamed to `aubreypwd/wp-todo`.

**Comment by aubreypwd** [comment]
And for some reason I can't seem to delete the room `.vimpwd` and I'm sure I own the community `aubreypwd`? Can you delete that room, not sure why I can't.

**Comment by MadLittleMods** [comment]
Done https://gitter.im/aubreypwd/wp-todo

---

`aubreypwd/.vimpwd` has this security descriptor and looks like you may have deleted the GitHub repo. I have deleted that room

 "sd" : {
                "type" : "GH_REPO",
                "members" : "GH_REPO_ACCESS",
                "admins" : "GH_REPO_PUSH",
                "public" : true,
                "linkPath" : "aubreypwd/.vimpwd",
                "externalId" : null
        }

**Comment by aubreypwd** [comment]
Thanks!
