### ISSUE TITLE
Request: Rename fp-ethereum/Lobby to evm-lang-design/evm-lang-design

### ISSUE THREAD

**Issue by raineorshine** [gitterHQ/gitter#1607]
[evm-lang-design](https://github.com/evm-lang-design) is a new community for language enthusiasts interested in designing for the Ethereum platform. The name was recently changed by community consensus from fp-ethereum to the broader evm-lang-design.

Could you rename the fp-ethereum/Lobby room to evm-lang-design/evm-lang-design (or evm-lang-design/Lobby if necessary) so that it reflects this change?

Thanks!

**Comment by MadLittleMods** [comment]
https://github.com/fp-ethereum doesn't seem to exist anymore and wasn't a rename to https://github.com/evm-lang-design.

I see you are the first member to chat so I'll trust you are an admin, https://gitter.im/fp-ethereum/Lobby?at=588b71fae836bf70109befa3

Please create the `evm-lang-design` community on Gitter

**Comment by raineorshine** [comment]
I renamed github.com/fp-ethereum to github.com/evm-lang-design. Is there a way to rename the gitter room so that the members are retained? Thanks!

**Comment by MadLittleMods** [comment]
> I created the evm-lang-design communty. The Lobby room was created automatically so that one will be fine. You can transfer all the messages from fp-ethereum/Lobby to evm-lang-design/Lobby whenever you're ready. Thanks!
> 
> -Raine

The messages have been moved to https://gitter.im/evm-lang-design/Lobby and I have setup a redirect.

**Comment by raineorshine** [comment]
Thanks!!!
