### ISSUE TITLE
Request to rename/move room AsynkronIT/gam

### ISSUE THREAD

**Issue by rogeralsing** [gitterHQ/gitter#1608]
We would like to rename this channel `AsynkronIT/gam`  to `AsynkronIT/protoactor`

**Comment by MadLittleMods** [comment]
Done https://gitter.im/AsynkronIT/protoactor

I see that [`AsynkronIT/gam`](https://github.com/AsynkronIT/gam) redirections to [`AsynkronIT/protoactor-go`](https://github.com/AsynkronIT/protoactor-go) on GitHub. Just noting the slight difference in naming.

**Comment by rogeralsing** [comment]
Many thanks!
