### ISSUE TITLE
Deleting community request.

### ISSUE THREAD

**Issue by kkimdev** [gitterHQ/gitter#1612]
Hi, could you delete https://gitter.im/m19g ?  I would like to use another account as the moderator, but since there is nothing, I think deleting and recreating is more straightforward.

Thank you.
Kibeom

**Comment by MadLittleMods** [comment]
@kkimdev You can add new admins to the community. In any room under the community(just create one), Room Settings -> Permissions -> Edit community permissions (bottom left of modal footer)

**Comment by kkimdev** [comment]
Thanks!
