### ISSUE TITLE
Request to rename repo

### ISSUE THREAD

**Issue by dragostis** [gitterHQ/gitter#1614]
I've moved dragostis/pest to pest-parser/pest and would like the Gitter channel to be renamed as well.

**Comment by MadLittleMods** [comment]
Hey @dragostis,

Create the `pest-parser` community and we can move the room over.

**Comment by dragostis** [comment]
@MadLittleMods Done.

**Comment by MadLittleMods** [comment]
https://gitter.im/pest-parser/pest is ready to go and redirect has been set up :tada:
