### ISSUE TITLE
Deleting an account and removing files

### ISSUE THREAD

**Issue by csarven** [gitterHQ/gitter#1620]
Is there a way to remove media files under own account e.g. `https://files.gitter.im/{user}/{mediaPath}`?

I drag and dropped an image in a private chat. I later deleted the message, however URL to the image persists. Is there a way to remove it?

Would deleting an account consequently remove those URLs as well?

**Comment by mydigitalself** [comment]
Hi there, you can currently delete uploads - @omame are you able to delete from s3 ?

**Comment by omame** [comment]
Hi @csarven,

Would you mind [creating a request](https://gitter.zendesk.com/hc/en-us/requests/new) with all the details about the file you want to remove?

I'm closing this issue for now: we will continue there.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/332
