### ISSUE TITLE
No notifications sent

### ISSUE THREAD

**Issue by pditommaso** [gitterHQ/gitter#1621]
I'm not receiving any more notifications from Gitter for direct  messages or unread threads either via email or mobile app. 

I've double checked the notification settings, close all browser windows and re-install the android app. No way. Notifications are not sent. 

This is very annoying.

**Comment by mydigitalself** [comment]
Mobile notifications won't get sent if you have an active desktop connection - this is something we may look to change in the future. Perhaps you have a client open somewhere via IRC?

Email notifications have been a long running problem as we've had some delivery volume issues, this should now be fixed.

**Comment by pditommaso** [comment]
No, I haven't.

**Comment by mydigitalself** [comment]
I checked your online status with an internal tool we have, an according to it, you're online. Unfortunately that tool doesn't say where exactly, so I may have to dig deeper into that.

**Comment by pditommaso** [comment]
Well, now I was. I've just closed it if it can help .

**Comment by mydigitalself** [comment]
I ran that tool a little while ago, still showing as online now, perhaps some data has got out of sync somewhere.

**Comment by pditommaso** [comment]
Closed everything everywhere.

**Comment by MadLittleMods** [comment]
Related issues

 - https://github.com/gitterHQ/gitter/issues/1463
 - https://github.com/gitterHQ/gitter/issues/1479
 - https://github.com/gitterHQ/gitter/issues/1369
 - https://github.com/gitterHQ/gitter/issues/894

**Comment by mydigitalself** [comment]
Have you used another computer somewhere else perhaps and left it running? I can see there's a session sitting open from Feb 14th in a web browser in a room called `nextflow-io/nextflow` and that session is effectively swallowing notifications.

**Comment by pditommaso** [comment]
Not at my knowledge. Can't you provide the IP of all currently open
connections?

p

**Comment by mydigitalself** [comment]
Not for websocket connections, they are all proxied via a load balancer that doesn't offload that information. Will have to see what else I can find.

**Comment by pditommaso** [comment]
Can't you force a connection close either?

**Comment by MadLittleMods** [comment]
@pditommaso Try the following. If you are up to dump the app data for us to investigate, try this before: http://stackoverflow.com/a/17876731/796832

> The fix is to clear the app data in settings.
>
>@pitaj, https://github.com/gitterHQ/gitter/issues/1289#issuecomment-225465446

**Comment by pditommaso** [comment]
@MadLittleMods I can upload the app data. What it supposed to be the package name of the Gitter app to be used in the command: 
```
adb backup -noapk com.your.packagename
```

**Comment by MadLittleMods** [comment]
@pditommaso `im.gitter.gitter` (from https://play.google.com/store/apps/details?id=im.gitter.gitter)

**Comment by pditommaso** [comment]
Update: since yesterday I'm getting email notification for unread messages. The problem persists for the mobile notifications. I still didn't manage to dump the app data.

**Comment by MadLittleMods** [comment]
@pditommaso We got emails working again 5 days ago, https://github.com/gitterHQ/gitter/issues/1570#issuecomment-285735129

If you can't dump the data, that's fine. Try clearing the app data, https://github.com/gitterHQ/gitter/issues/1621#issuecomment-286011917

**Comment by pditommaso** [comment]
Clearing the app data solved the issue. Thanks!

**Comment by smiller171** [comment]
You really need to change the way this works. It appears that my Mac is eating my notifications _when it's asleep_ so I can't get mobile notifications.
