### ISSUE TITLE
GitLab logo is out of date

### ISSUE THREAD

**Issue by WarheadsSE** [gitterHQ/gitter#1625]
[The image used to present GitLab](https://cdn02.gitter.im/_s/b230113/images/home/gitlab-logo.jpg) on the home page is out of date. Please update using logos available at [https://about.gitlab.com/press/](https://about.gitlab.com/press/)

Used on the homepage, https://gitter.im/?redirect=no,  in the "Designed for community collaboration" section

![The image used to present GitLab](https://cdn02.gitter.im/_s/b230113/images/home/gitlab-logo.jpg)

**Comment by MadLittleMods** [comment]
Ready to go in [hotfix 18.8.6](https://github.com/troupe/gitter-webapp/pull/2551/commits/2070ce3afddae3df77f746bd81e1a20570d04b83) which will roll out later this week.

Thanks to @lukebabb for putting together the new image 😀 

![](http://i.imgur.com/XtaxdtO.gif)
