### ISSUE TITLE
Request to change room organization

### ISSUE THREAD

**Issue by alexarchambault** [gitterHQ/gitter#1631]
Hi,
I'd like to move the [`alexarchambault/coursier`](https://github.com/coursier/coursier) room to the [`coursier`](https://github.com/coursier/) organization, if that can be done.

Thanks!

**Comment by MadLittleMods** [comment]
Hey @alexarchambault,

Create the `coursier` community and we can move the room over

**Comment by alexarchambault** [comment]
@MadLittleMods Done, I created the coursier community: https://gitter.im/coursier.

**Comment by MadLittleMods** [comment]
@alexarchambault https://gitter.im/coursier/coursier is ready to go 🎉
