### ISSUE TITLE
Didn't receive e-mail notification from room in the community not integrated with any repo

### ISSUE THREAD

**Issue by vasily-v-ryabov** [gitterHQ/gitter#1635]
Room: https://gitter.im/pywinauto-russian-users/Lobby

There was message on March, 07 but I noticed about it when I logged in on March, 21 after e-mail notification from [another room](https://gitter.im/pywinauto/pywinauto).

I checked that all notifications were enabled for pywinauto-russian-users/Lobby. So it looks like a bug.

**Comment by MadLittleMods** [comment]
@vasily-v-ryabov Emails weren't going out at that time.

We got emails working again on March 10th, see https://github.com/gitterHQ/gitter/issues/1570#issuecomment-285735129
