### ISSUE TITLE
Typing "something[1]" pastes a random link from other messages

### ISSUE THREAD

**Issue by oprypin** [gitterHQ/gitter#1638]
If I type a message with these contents into Gitter:

    something[1]

It turns into something like this:

> [1](http://example.org)

Where the destination of the link is basically random - not something I've ever typed.

---

It is also possible to add a link into the "pool" of possible links, by typing a message like this even in a completely different Gitter channel:

```
[1]
[1]: http://example.org/
```

Then if you repeat the steps above, you have a chance of seeing this link in it.

So yeah, this is a bit of a vulnerability &ndash; one could see other people's links.

---

This was discovered [by accident](https://gitter.im/nim-lang/Nim?at=58d40718b809ca5f4a75c670).

**Comment by mydigitalself** [comment]
@MadLittleMods if you can figure this out ⭐️  ✨  etc....

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/gitterHQ/gitter/issues/1041

**Comment by oprypin** [comment]
Just a vulnerability that allows reading other people's links, including private rooms, live for 1.5 years, no big deal.

**Comment by mydigitalself** [comment]
That's my point in the comment on the other issue, was previously never identified as coming from other messages.
