### ISSUE TITLE
Request move repo room to new organization scalameta/scalafmt 

### ISSUE THREAD

**Issue by olafurpg** [gitterHQ/gitter#1644]
Repo https://github.com/olafurpg/scalafmt is now https://github.com/scalameta/scalafmt. 

The Gitter room needs updating https://gitter.im/olafurpg/scalafmt to https://gitter.im/scalameta/scalafmt

**Comment by olafurpg** [comment]
Ping @MadLittleMods

**Comment by MadLittleMods** [comment]
https://gitter.im/scalameta/scalafmt is good to go and a redirect has been setup.

**Comment by olafurpg** [comment]
I can confirm that olafurpg/scalafmt now correctly redirects to scalameta/scalafmt, thanks a lot 😄
