### ISSUE TITLE
Request: Rename sbt/sbt-dev to sbt/sbt-contrib

### ISSUE THREAD

**Issue by eed3si9n** [gitterHQ/gitter#1646]
Hello. sbt is a build tool for Scala programming language.
We have a room for sbt contributors, and would like to rename https://gitter.im/sbt/sbt-dev to https://gitter.im/sbt/sbt-contrib for consistency across Scala tool chain (we also have sbt/zinc-contrib and scala/tooling-contrib)

Thanks!

**Comment by MadLittleMods** [comment]
https://gitter.im/sbt/sbt-contrib is ready to go :tada:
