### ISSUE TITLE
Change my community URL

### ISSUE THREAD

**Issue by arthurokonkwo** [gitterHQ/gitter#1648]
I created a new community in Gitter (https://gitter.im/nacossdevenugu) but I want to edit the URL to (https://gitter.im/nacossdevelopers) but I can find where to do that.

Please is there a way I can achieve this ?

**Comment by arthurokonkwo** [comment]
Can someone help me with this issue

**Comment by MadLittleMods** [comment]
https://gitter.im/nacossdevelopers is ready to go :tada:

**Comment by arthurokonkwo** [comment]
please can you make a final change to https://gitter.im/nacoss  so I can create rooms for developers and designers
