### ISSUE TITLE
Unknown Year in Topics (date)

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1656]
Here, for example: 

![no year](https://cloud.githubusercontent.com/assets/192271/24580388/5eca05be-16ff-11e7-9bfd-46eacd41fc2f.png)

– October of which year? 

A hint will be required. 

(In the example above, I know that it was 2016 only because I also know that Topics were not a feature of Gitter in 2015.)

**Comment by MadLittleMods** [comment]
There is a `title` tooltip on the date.

![](http://i.imgur.com/iexaihZ.png)

**Comment by grahamperrin** [comment]
OK, I have it now. 

In the opening screenshot the pointer was maybe a pixel away from the required area. 

Originally I did try a few times, never noticed the tip. Now it works consistently (if I point far enough for the pointer arrow to change to an I-beam, and wait long enough); I guess that all previous attempts were rushed. 

Also/alternatively it's possible that I instinctively moved the pointer to **point at the date without appearing as an I-beam**; because (compared to the gloved hand behaviour for time stamps in some other areas of Gitter) the I-beam felt wrong. 

I'm tempted to close this as PEBKAM but I'll leave it open in case there should be attention to the pointer inconsistencies.

**Comment by MadLittleMods** [comment]
I'm going to close. The `text`/I-beam cursor appears for any text.

When permalinks are introduced, it will be a `pointer`/hand.
