### ISSUE TITLE
I can't enter the private room that I left

### ISSUE THREAD

**Issue by 243750496** [gitterHQ/gitter#1661]
I created a room  with  private permission  and then leave  it 
Then i re-create one with same  name but  failed  
And  i try to search it but found  no result 

So i guss the private room i created have be hidden and can't join and delete it but i am the  owner  and  there's only  i in it so 
Any solutions?

**Comment by mydigitalself** [comment]
i'm afraid not. why did you leave it?

**Comment by 243750496** [comment]
By mistake  sorry:) my room is  Anti Zone Developer 
Could u please help me

**Comment by MadLittleMods** [comment]
@243750496 Can you please link the room? Also any verification that you were the owner?

**Comment by 243750496** [comment]
problem slove sorry for the delay ， i created a new community , so no problem,but it''s certain that if u are the only one who is in the private room and leave it 
1st: you will never find and enter it.
2nd:u can not create a new one with same name
so it's certain it is a problem or an issue with function missing or it's a bug.

so solution is : allow finding and show up the private room but can't enter the room without permission, unless u are the owner of it though u leaved it.

**Comment by MadLittleMods** [comment]
@243750496 I am still curious, can you please link the room that you can no longer join?

**Comment by 243750496** [comment]
i ordered gitter official to delete the old community , so  will i recreate one then leave it as i had done before now?

**Comment by MadLittleMods** [comment]
Nevermind. It seems like your issue was solved.

**Comment by 243750496** [comment]
failed to create Room: Developer in AntiZone  it's a bug a real bug since previously deleted community already, i mean official delete the community but i create a new one with same community name and link  with github, but that old community contain a buggy room, but after deleted and recreate the buggy room followed to my new community , so i hope u can help me delete it
![bug](https://cloud.githubusercontent.com/assets/6311930/25009283/bc693418-2098-11e7-9ba4-00ece6210348.png)
![bug2](https://cloud.githubusercontent.com/assets/6311930/25009284/bca631ce-2098-11e7-850c-1ae31b34b89a.png)


 thx! other bug is already sloved.

**Comment by MadLittleMods** [comment]
@243750496 Just a heads up, that it's been a bit difficult to understand what you are trying to convey and missing information.

So it looks like you left https://gitter.im/Anti-Zone/Developer which is a private room and you can't get back in? The security descriptor on that room indicates that if you are an admin of the community(GitHub org member of https://github.com/orgs/Anti-Zone/people), then you should be able to get back in.

Please make your org membership public, https://github.com/orgs/Anti-Zone/people

What happens if you visit this URL? Can you see the room and get back in? https://gitter.im/Anti-Zone/Developer

**Comment by 243750496** [comment]
![img_1317](https://cloud.githubusercontent.com/assets/6311930/25032967/76e9aed6-210b-11e7-907f-e5103c38d5fb.PNG)

**Comment by MadLittleMods** [comment]
@243750496 Visit it on the desktop where you know you are signed in

**Comment by 243750496** [comment]
![404](https://cloud.githubusercontent.com/assets/6311930/25034495/7532b700-2119-11e7-8429-de54a25c375d.png)

**Comment by MadLittleMods** [comment]
@243750496 I added you as an extraAdmin manually so you should be able to join https://gitter.im/Anti-Zone/Developer again regardless.

**Comment by 243750496** [comment]
not found but it does exist 


![777](https://cloud.githubusercontent.com/assets/6311930/25935876/c0537b36-3657-11e7-86b7-33be2209e00d.png)
![888](https://cloud.githubusercontent.com/assets/6311930/25935877/c0879af6-3657-11e7-8eec-8c518c753e7a.png)

**Comment by MadLittleMods** [comment]
@243750496 😕 I added you as a manual member of the room. Refresh, do you see it now?

**Comment by 243750496** [comment]
@MadLittleMods still can not enter the room the error still the same

**Comment by MadLittleMods** [comment]
@243750496 I suspect you are logged into `243750496` on Gitter.

Authenticating as you and visiting https://gitter.im/Anti-Zone/Developer shows me the room.

**Comment by 243750496** [comment]
sloved

**Comment by 243750496** [comment]
by the way if i leave the prive room shall i see a list of the private room belongs to me? or just show nothing ? i mean if i leave by mistake shall i have able to reenter it without putting request here?

**Comment by MadLittleMods** [comment]
@243750496 What made this solved? Were you not signed in as `243750496`.

If you leave the room, I suspect you might not be able to get back in.

**Comment by 243750496** [comment]
i signed with my account 243750496 then open the link so entered successfully , previously i copy the link to enter it but not login in my account 243750496 so failed and get 404
