### ISSUE TITLE
how to link the github organization to my gitter community 

### ISSUE THREAD

**Issue by 243750496** [gitterHQ/gitter#1662]
I want  all my company to be administer of the  community i create in gitter 

I know i can set  while i create the community.
But  i forgot at that time
So any way to remedy it? Thx

**Comment by mydigitalself** [comment]
You can only do this when you create a community, right now you can't change it after the fact.

**Comment by 243750496** [comment]
If So Could u please delete the community and let  me  re-create one  thx  a lot

**Comment by mydigitalself** [comment]
It would help if you provided the URL of the community.

**Comment by 243750496** [comment]
Join the chat in Anti Zone/Public
https://gitter.im/Anti-Zone/Public?utm_source=ios&utm_medium=link&utm_campaign=ios-share-link

Btw: i want to delete the whole community not  just delete the  room

**Comment by mydigitalself** [comment]
Done.
