### ISSUE TITLE
Alfresco android mobile import from github to android studio

### ISSUE THREAD

**Issue by KeyurPatel94** [gitterHQ/gitter#1664]
@jmpascal
Error:(62, 0) Could not find property 'home' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.
<a href="openFile:/home/keyurpatelc2/AndroidStudioProjects/alfresco-android-app/alfresco-mobile-android/build.gradle">Open File</a>

and the other issue is ------------------>
Error:Failed to resolve: com.samsung.android.sdk:pen:1.0.2
<a href="openFile:/home/keyurpatelc2/AndroidStudioProjects/alfresco-android-app/alfresco-mobile-android/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: com.samsung.android:sdk:1.0.0
<a href="openFile:/home/keyurpatelc2/AndroidStudioProjects/alfresco-android-app/alfresco-mobile-android/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by KeyurPatel94** [comment]
@jmpascal

**Comment by mydigitalself** [comment]
Er, do you have the wrong repo, I have no idea what you are talking about.
