### ISSUE TITLE
Change my community URL

### ISSUE THREAD

**Issue by arthurokonkwo** [gitterHQ/gitter#1667]
I created a new community in Gitter (https://gitter.im/nacossdevenugu) but I want to edit the URL to (https://gitter.im/nacossdevelopers)  which @MadLittleMods did https://github.com/gitterHQ/gitter/issues/1648, but now the members of the community want to create rooms for developers.

**please can you make a final change to https://gitter.im/nacoss so I can create rooms for developers and designers**

**Comment by arthurokonkwo** [comment]
hello, please can we make this final change?

**Comment by arthurokonkwo** [comment]
Please change **https://gitter.im/nacossdevelopers** to **https://gitter.im/nacoss**

**Comment by MadLittleMods** [comment]
https://gitter.im/nacoss is ready to go
