### ISSUE TITLE
Request for assistance - Using Gitter at GitHub Satellite Workshop 5/23 

### ISSUE THREAD

**Issue by brianamarie** [gitterHQ/gitter#1671]
Hello! 👋 @MadLittleMods advised I open an issue in this repository to request help on May 23rd. We are hosting a 'Build a Chatbot' workshop at [GitHub Satellite](https://githubuniverse.com/satellite/), and are using Gitter as the main chat service. If all goes well, we won't need any help at all. 

However, there is potential for thing to go a bit south. For example (in an unfortunate looping incident in testing) the bot account got hellbanned. :bowtie: 

If this were to happen during the workshop, it would be fantastic to have someone from Gitter 'on call' so we could get the account unlocked as soon as possible and unblock the other workshop sessions. Is this something that seems plausible?

**Comment by MadLittleMods** [comment]
@brianamarie I meant, if your bot gets hellbanned, just create an issue on this repo which is the best way to for me to notice.

**Comment by brianamarie** [comment]
@MadLittleMods Ah, gotcha. 👍 Will do.
