### ISSUE TITLE
Notification settings does not work

### ISSUE THREAD

**Issue by UgurAldanmaz** [gitterHQ/gitter#1672]
I configure notification settings as "Notify me for mentions and announcements". Settings detail says that:

```
Your settings:

* Show unread item counts
* Notify when you're mentioned
* Notify on @/all announcements
```

But I'm receiving email notifications, even if I'm not mentioned or message which not contains @/all.

Thank you for this great app!

**Comment by MadLittleMods** [comment]
"Announcements" has "Show unread item counts". Currently emails are tied to unreads. 

You can track https://github.com/gitterHQ/gitter/issues/1205

**Comment by UgurAldanmaz** [comment]
Thank you for answering. Sorry for duplication. I have searched but could not find similar issues.
