### ISSUE TITLE
How about changing the badges

### ISSUE THREAD

**Issue by aleen42** [gitterHQ/gitter#1673]
I have created a cute badge for Gitter by using the repository I have created before. This badge can be used used to replace the badge before. The repository, [**badges**](https://github.com/aleen42/badges) aims to create a collection of flat badges, so that they can be widely used in documenting and also be more and more standard.

![gitter](https://cdn.rawgit.com/aleen42/badges/master/src/gitter.svg)

**Comment by MadLittleMods** [comment]
- The font(perhaps size) looks a bit off to me.
 - The logo looks a bit too scrunchy. It looks like you are using an image atm and would be better to use SVG. Here are some smaller logos but not small enough for the badge currently, http://jsfiddle.net/MadLittleMods/LaoctLy3/

---

https://github.com/troupe/gitter-badges

**Comment by aleen42** [comment]
@MadLittleMods Can you give a screenshot of what it likes in your screen, and the badge has actually used SVG, if you scale it up, it will become more clear. By the way, the link has been missed

**Comment by MadLittleMods** [comment]
@aleen42 

![](http://i.imgur.com/vB003gq.png)

Ahh, I see the logo is a base64 SVG embedded into a `<image>`.

**Comment by aleen42** [comment]
So is there any suggestion ?

**Comment by MadLittleMods** [comment]
@aleen42  Same suggestions apply, https://github.com/gitterHQ/gitter/issues/1673#issuecomment-293826947

**Comment by aleen42** [comment]
@MadLittleMods Okay, if you have any idea, or a good logo for Gitter, use the tool to build it.
