### ISSUE TITLE
failed to create Room: Developer in AntiZone 

### ISSUE THREAD

**Issue by 243750496** [gitterHQ/gitter#1674]
failed to create Room: Developer in AntiZone  it's a bug a real bug since previously deleted community already, i mean official delete the community but i create a new one with same community name and link  with github, but that old community contain a buggy room, but after deleted and recreate the buggy room followed to my new community , so i hope u can help me delete it
![bug](https://cloud.githubusercontent.com/assets/6311930/25009283/bc693418-2098-11e7-9ba4-00ece6210348.png)
![bug2](https://cloud.githubusercontent.com/assets/6311930/25009284/bca631ce-2098-11e7-850c-1ae31b34b89a.png)

 thx! other bug is already sloved.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/1661
