### ISSUE TITLE
Move personal repo to organization repo

### ISSUE THREAD

**Issue by feross** [gitterHQ/gitter#1677]
Hey Gitter team! 👋

We are about to rename `feross/webtorrent` (a personal repo) to `webtorrent/webtorrent` (an organization repo).

How do we ensure that our chat history and members at https://gitter.im/feross/webtorrent are not lost?

**Comment by MadLittleMods** [comment]
Hey @feross,

After you do the rename on GitHub, create a `webtorrent` community on Gitter. Then post back here and we can rename the room, https://gitter.im/feross/webtorrent to `webtorrent/webtorrent`.

**Comment by feross** [comment]
Done! I created a community (https://gitter.im/webtorrent/home) as you requested.

**Comment by MadLittleMods** [comment]
@feross https://gitter.im/webtorrent/webtorrent is ready to go :tada:

**Comment by feross** [comment]
Awesome, thanks @MadLittleMods!
