### ISSUE TITLE
https://github.com/gitterHQ/gitter appears to misdirect readers to https://gitter.im to file issues

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1679]
1. https://gitter.im/gitterHQ/gitter
2. click _gitterHQ/gitter_
3. in the new tab, observe the repo description

> Discuss and file Gitter issues here https://gitter.im

For _filing_ issues, https://github.com/gitterHQ/gitter/issues will be a better direction.

**Comment by MadLittleMods** [comment]
Are you more after this sort of language?

> # Gitter [![Gitter](https://badges.gitter.im/gitterHQ/gitter.svg)](https://gitter.im/gitterHQ/gitter)
>
> - For support and discussion around issues, feature requests, etc, https://gitter.im/gitterHQ/gitter
> - For filing issues, https://github.com/gitterHQ/gitter/issues

---

Currently it looks like this:

![](http://i.imgur.com/X87SLKM.png)

**Comment by grahamperrin** [comment]
Thanks, 

> … Currently it looks like this: …

Foremost, it's like this: 

![gitterhq-gitter discuss and file gitter issues here - chromium](https://cloud.githubusercontent.com/assets/192271/25163419/229e11d6-24c2-11e7-95be-1b128408cbd6.png)

– and if the page title is ignored (many people rush things without reading what's uppermost), then the "… here https://gitter.im" debatably _first_ and foremost. 

Open to misinterpretation. Certainly I read it as 

>> Discuss and file Gitter issues here https://gitter.im

To a degree, I guess that you're constrained by the design of GitHub. 

(Apologies for not including a screenshot in the opening post. It's useful for me to gain other people's perceptions.)

**Comment by MadLittleMods** [comment]
It seems fine to me.

@grahamperrin Do you have something better in mind?

**Comment by grahamperrin** [comment]
Maybe a change from: 

> Discuss and file Gitter issues here

to: 

> The web interface to Gitter

A narrower phrase will, I guess, allow a wider gap between the tail of the phrase and the beginning of the URL. 

![gitterhq-gitter](https://cloud.githubusercontent.com/assets/192271/25245511/8b0ebf78-25fc-11e7-8ff1-3883ff00677e.png)

I guess that highlighted area can present nothing other than a URL. If I'm wrong – if a prefix is possible – then maybe prefix the URL with: 

> Chat:

**Comment by MadLittleMods** [comment]
I don't think that is an improvement. This is just how GitHub displays the website field next to the description as you mentioned.

I have updated it to this:

> Discuss and file Gitter issues. 

![](http://i.imgur.com/Gef79ao.png)
