### ISSUE TITLE
Community name vavr-io taken?

### ISSUE THREAD

**Issue by danieldietrich** [gitterHQ/gitter#1681]
Hi,

due to an actual trademark conflict with Oracle Corp. I have to rename my project "Javaslang" to "Vavr". The Github org name changed to [vavr-io](http://github.com/vavr-io).

However, I can't create the Gitter community 'vavr-io'. I thought they might be already taken but when I search Gitter for 'vavr-io' the result is empty.

Could you please assist me by renaming my community & room http://gitter.im/javaslang/javaslang to http://gitter.im/vavr-io/vavr?

I've read that renaming is not possible. It would be great if we could create http://gitter.im/vavr-io/vavr then and move the messages. Is it also possible to move the followers?

Thanks in advance,

Daniel

**Comment by MadLittleMods** [comment]
Hey @danieldietrich 

https://gitter.im/vavr-io/home is ready to go :tada:

**Comment by danieldietrich** [comment]
@MadLittleMods that is awesome, thank you Sir! 👍🏼😊👍🏼
