### ISSUE TITLE
Reconnect webhook

### ISSUE THREAD

**Issue by DominiqueMakowski** [gitterHQ/gitter#1682]
Hi, I created a [room](https://gitter.im/NeuroKit-py/Lobby) for my [package](https://github.com/neuropsychology/NeuroKit.py).

 It says that It is webhooked to it on Gitter, but recent activity does not appear. Moreover, on the github page, the webhook does not appear... how can I reconnect the room with the package?

Thanks

**Comment by MadLittleMods** [comment]
Easiest to just delete the webhook and try setting it up again.

**Comment by MadLittleMods** [comment]
You can also manually add the webhook URL, `https://github.com/org/repo/settings/hooks`

**Comment by DominiqueMakowski** [comment]
It worked by manually adding the webhook. Thanks.
