### ISSUE TITLE
Want to change name and URL of gitter room

### ISSUE THREAD

**Issue by mantagen** [gitterHQ/gitter#1683]
Similar to: https://github.com/gitterHQ/gitter/issues/1200

`foundersandcoders/FAC1Nazareth`

The name should be

`foundersandcoders/FACN1`

The first was miswritten, and we'd like to change to the latter. Obviously we could just open a new room, but we'd lose all history from the original, which is far from ideal.

Thanks

**Comment by MadLittleMods** [comment]
Hey @mantagen,

Please make your org membership public https://github.com/orgs/foundersandcoders/people so we can ensure you are actually an admin of this community.

**Comment by jsms90** [comment]
@MadLittleMods Hey, I've just made my membership public

Please can you change the channel name as @mantagen described? :+1:

**Comment by MadLittleMods** [comment]
@mantagen @jsms90 Sorry for the delay 😞 

https://gitter.im/foundersandcoders/FACN1 is setup and ready to go 🎉
