### ISSUE TITLE
Restore lost community

### ISSUE THREAD

**Issue by mukhlismdt** [gitterHQ/gitter#1685]
Hi! I created community https://gitter.im/feloids. then I didn't mean to remove my own name and now it was lost. Could you please add new feature or just restore my lost community?

Thank you.

**Comment by MadLittleMods** [comment]
https://gitter.im/feloids still exists and you are an admin.

You can create new rooms under it by click the "Add a room" button at the bottom of the conversation list in the left menu.

**Comment by mukhlismdt** [comment]
no. i mean i cant manage it. add room or else.

**Comment by mydigitalself** [comment]
@mukhlismdt when you click on the add a room button 

![screen shot 2017-04-26 at 08 44 28](https://cloud.githubusercontent.com/assets/1491887/25423441/99ac45f0-2a5c-11e7-995b-5d2a6176138c.png)

What options do you see in the `Community` dropdown?

**Comment by mukhlismdt** [comment]
@mydigitalself hi. here is whole page ss.

![feloids - gitter](https://cloud.githubusercontent.com/assets/15173312/25442933/945c616a-2ad0-11e7-8c15-3acb439ab5f9.png)

**Comment by mukhlismdt** [comment]
@mydigitalself hi. thankyou. my bad. im new on gitter.
