### ISSUE TITLE
Single click on system tray should bring Gitter.im desktop window to foreground.

### ISSUE THREAD

**Issue by MicahZoltu** [gitterHQ/gitter#1686]
For most Windows desktop apps with a System Tray component, single-clicking on the system tray icon will bring the window to the foreground if it is already open, or if it is not already open it will open it.  A single click on the system tray icon _does_ open the app if it is closed; however if the app is already open a single click on the system tray icon _does not_ cause the window to be moved to the foreground.

This is a nuisance since it means I have a different UX based on current state of the app.  So if I see the system tray icon showing I have new messages, I need to identify whether or not Gitter is already open in order to determine what the appropriate interaction to view those messages is.

Note: Slack and Rocket.chat both have the desired behavior of single click always brings the window to the front (whether previously open or not).

**Comment by MadLittleMods** [comment]
@MicahZoltu Open this on the desktop repo please, https://github.com/gitterHQ/desktop

Feel free to make a PR

**Comment by MadLittleMods** [comment]
Moved to https://github.com/gitterHQ/desktop/issues/195
