### ISSUE TITLE
Subdomain Takeover due to unclaimed GitHub Page on engineering.gitter.im

### ISSUE THREAD

**Issue by ajdumanhug** [gitterHQ/gitter#1692]
After looking for subdomains on Gitter, I found out that `engineering.gitter.im` is pointing to an unclaimed GitHub Page.

Shown below is a screenshot of `engineering.gitter.im` pointing to a GitHub Page.
![screen shot 2017-05-02 at 12 16 38 am](https://cloud.githubusercontent.com/assets/9420289/25586016/f6e6e708-2ecf-11e7-9db8-e0260bbe8d43.png)

**Steps**:
- First, I created a new GitHub Repository
- Next, I pointed the GitHub Repository to engineering.gitter.im
- Then, I edited the `README.md` file to put the text shown in the image below:

![screen_shot_2017-05-02_at_12_25_41_am](https://cloud.githubusercontent.com/assets/9420289/25586017/f6f6bb2e-2ecf-11e7-98c5-f9d30d20e290.png)

**Remediation**:

Just remove the `engineer.gitter.im` DNS entry.

If you need me to release `engineering.gitter.im` in my GitHub Repo, let me know and I'll delete the GitHub Repository.

Note: I also reported it on GitLab through HackerOne with the report [#225331](https://hackerone.com/reports/225331)

**Comment by suprememoocow** [comment]
Thanks for the report, @ajdumanhug!

I've corrected the problem on our side by removing the DNS entry.

It's a good lesson in making sure not to leave unused DNS entries around!

**Comment by ajdumanhug** [comment]
Hi @suprememoocow,

Great! 
I'd like to know what would happen to my report regarding this issue on HackerOne? I also reported on GitLab. 

Additionally, files.gitter.im is vulnerable too to subdomain takeover.  It is pointing to CloudFront.
![screen shot 2017-05-02 at 12 51 20 am](https://cloud.githubusercontent.com/assets/9420289/25590741/55f827f2-2ee4-11e7-9074-adfe7fcaa700.png)

Best Regards,
Allan

**Comment by suprememoocow** [comment]
Hi @ajdumanhug 

I believe that Brian, the security lead from GitLab is dealing with the report in HackerOne.

In the interests of de-duplication and privacy, please could you use the GitLab HackerOne interface for any future reports.

Regarding `files.gitter.im` it is not unclaimed but does not have an index file, so may appear to be unclaimed. As an example, here is a file I recently uploaded.

https://files.gitter.im/gitterHQ/KXy2/Cancun-Overhead.jpg

Thanks again,
Andrew

**Comment by ajdumanhug** [comment]
Hi @suprememoocow,

Brian resolved the report I submitted on HackerOne and gave information regarding files.gitter.im.

Thanks, @suprememoocow!
