### ISSUE TITLE
Move/redirect lhorie/mithril.js to MithrilJS/mithril.js

### ISSUE THREAD

**Issue by isiahmeadows** [gitterHQ/gitter#1695]
Could we get a redirect from https://gitter.im/lhorie/mithril.js to https://gitter.im/MithrilJS/mithril.js? I'm an admin/committer to the project, and our Gitter room has been fairly active for years, but we just moved from the original author's personal account to a dedicated org.

**Comment by MadLittleMods** [comment]
Hey @isiahmeadows,

https://gitter.im/mithriljs/mithril.js is setup and ready to go :tada:
