### ISSUE TITLE
small typo in localized Gitter Email Notifications

### ISSUE THREAD

**Issue by adam-tokarski** [gitterHQ/gitter#1696]
Hi, I'm not sure from where is translated subject of Gitter Notifications which I'm receiving, but this subject comes in my native language (Polish) and there is small typo:

> Nieprzeczytane wiad**m**omości w kata-authoring-help

should be
> Nieprzeczytane wiadomości w kata-authoring-help

(which means "unread messages in kata-authoring-help").

**Comment by suprememoocow** [comment]
Thanks for the report @adam-tokarski!

Care to send a PR to make the change? https://github.com/gitterHQ/gitter-translations/blob/master/messages/pl.js

**Comment by adam-tokarski** [comment]
Sure!

**Comment by adam-tokarski** [comment]
[PR](https://github.com/gitterHQ/gitter-translations/pull/50)
