### ISSUE TITLE
Change gitter room name and url

### ISSUE THREAD

**Issue by stevehu** [gitterHQ/gitter#1698]
I did a search and it looks like there is no way that I can change the gitter room name and url at the moment through the admin interface. I am wondering if you could help to change one room name as we are forced to change github repo name by Oracle. I have other rooms but only this one got a lot of discussions and I don't want to lose them. 

The old room name is light-java and the url is https://gitter.im/networknt/light-java
And the new room name is light-4j and the url should be https://gitter.im/networknt/light-4j

Thanks.

**Comment by MadLittleMods** [comment]
@stevehu https://gitter.im/networknt/light-4j is setup and ready to go.

We can rename your other rooms if you prefer. Give a straight-forward list:

```
 - current-room-link -> desired-room-uri
    - Link to old GitHub location
 - ...
```

**Comment by stevehu** [comment]
@MadLittleMods Thanks a lot for your help. You guys provide fantastic services.
