### ISSUE TITLE
Request to move rooms under to new organization

### ISSUE THREAD

**Issue by andreykurilin** [gitterHQ/gitter#1704]
Hi! 

Where I can find a description(workflow) of moving community under GitHub organization? 

I mean, our team uses https://gitter.im/rally-dev community and we want to move it under https://github.com/xrally org. As far as I understand, all rooms after that will be renamed (https://gitter.im/rally-dev/Lobby will become https://gitter.im/xrally/Lobby), but what will happen with old URLs? Will it be redirecting? Also, what will happen in case of using IRC tunnel with old room name?

**Comment by MadLittleMods** [comment]
@andreykurilin See https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo

We can redirect the old URLs to the new rooms.

People will need to add the new room to their IRC clients to continue receiving and sending messages.

**Comment by andreykurilin** [comment]
@MadLittleMods Thanks for the reply!

The original community was aligned neither to organization nor to a repository, so have one more question: moving https://gitter.im/rally-dev under https://github.com/xrally organization will affect rooms membership or not?

**Comment by MadLittleMods** [comment]
@andreykurilin We can rename the room in place so it won't affect membership. But depending on the room permissions, if some are set to inherit the community admins, some new admins could be introduced because anyone who is a member of https://github.com/xrally org will be an admin of the community.

**Comment by MadLittleMods** [comment]
Closing in favor of https://gitter.zendesk.com/agent/tickets/5482
