### ISSUE TITLE
Profile picture only updating in some places

### ISSUE THREAD

**Issue by isiahmeadows** [gitterHQ/gitter#1706]
I changed my GitHub profile picture recently, and here's where it updated/didn't update on the Gitter browser UI:

- Picture next to message: updated.
- Picture next to chat window: updated.
- Picture in "People" on right: updated.
- Picture in upper right: not updated.
- Picture on username/picture hover: not updated.

I tried doing each of the following, and the above has not changed before or after any of the following steps:

- Reloading browser.
- Refreshing page.
- Signing out and back in.
- Signing out, clearing cache + Gitter cookies, signing back in.

The only thing that worked to fix the issue was switching to [Gitter Next](http://next.gitter.im/), but after switching it back off, it reverted to the previous partially-updated behavior.

-----

And the closest to my issue is #1639, but I decided to file a new bug since that one was closed a couple months ago, and the subsequent conversation was over a non-reproducible issue.

**Comment by MadLittleMods** [comment]
Thanks for the detailed report @isahmeadows 😀 

It looks like we do use versioned avatars in the user popover so I'm not sure why it wouldn't be updated 😕

```
https://avatars-staging-05.gitter.im/gh/uv/x/some-username?s=128
``` 

What is the URL for the "Picture on username/picture hover: not updated." (compared to others that are updated)?

**Comment by isiahmeadows** [comment]
Okay...now that it's been a full week, I can no longer repro it.
