### ISSUE TITLE
Writing a hashtag turns into HUGE heading

### ISSUE THREAD

**Issue by Fryguy** [gitterHQ/gitter#1714]
This is a request to detect a one-liner lead with a `#` without a space, as a hashtag, and to not render it with markdown.

---

Technically, it's not a bug, as the markdown processor sees text like 

```markdown
#winning
```

as a header, and turns it into 

# winning

---

However, most people don't write a markdown header into the chat with nothing else.  When they are typing like that they intend for it to be a silly comment like a hashtag, but instead get huge text rendered and are very confused.

Additionally, a typical way to do a markdown header is to put a space after the `#`, so the markdown processor is being a bit lenient in this regard.  (Aside, even GitHub's markdown processor doesn't recognize the `#` without a space after it as a header, so even to type it for demonstration above, I had to add a space)

---

Perhaps, extending on this request, it could even just be turned into a link to Twitter. For example:

[#winning](https://twitter.com/hashtag/winning?src=hash)

---

This is not the same as #488, which seems to be requesting co-opting hashtags for comment labeling purposes.

**Comment by Fryguy** [comment]
A colleague mentioned escaping to me, but, IMO a user shouldn't have to know that (and newbies have no idea why it happens, let alone how to fix it).

**Comment by MadLittleMods** [comment]
Open this up on https://github.com/gitterHQ/marked

I could see doing this for single-line messages without a space between the hash and text.

**Comment by Fryguy** [comment]
Oh cool...I didn't realize `marked` was under the gitterHQ org

**Comment by Fryguy** [comment]
Ok, moved to https://github.com/gitterHQ/marked/issues/9 .  Should this one be closed, then?
