### ISSUE TITLE
Request to rename a room

### ISSUE THREAD

**Issue by kaqqao** [gitterHQ/gitter#1723]
I have a room called [`leangen/Lobby`](https://gitter.im/leangen/Lobby) that _I think_ is a repository room for [`leangen/graphql-spqr`](https://github.com/leangen/graphql-spqr).
Would it be possible to rename it so it reflects the repository i.e. rename it to `leangen/graphql-spqr`? If it is not already a repository room, can it be converted into one?

Would this lose the messages or make the members have to rejoin?

Thanks!

**Comment by MadLittleMods** [comment]
@kaqqao https://gitter.im/leangen/graphql-spqr is ready to go 🎉

**Comment by kaqqao** [comment]
Brilliant ✨ Thanks a bunch!
