### ISSUE TITLE
Add mobile buffer flush

### ISSUE THREAD

**Issue by swarley** [gitterHQ/gitter#1725]
Add mobile buffer flush when switching tabs.

**Comment by MadLittleMods** [comment]
@swarley Is this with the iOS or Android app? Perhaps just straight mobile browser?

I suppose you are after refreshing to speed things back up again. Probably a better approach to clean things up as we go (or fix that up)

**Comment by swarley** [comment]
Truly sorry I actually didn't even mean to send the issue in because I was still testing for replication. Looks like we have some first person evidence that this is actually a chrome on Android issue.
