### ISSUE TITLE
OSX client - notification settings missing apply button

### ISSUE THREAD

**Issue by alibby** [gitterHQ/gitter#1729]
I attempted to change my notification settings on the OSX client.   Being new to gitter,
I didn't realize the "Notification Settings" modal  was missing an "Apply" button.  After
several unsuccessful attempts to change my notification settings I attempted via the 
web interface and noticed there is an apply button.

**Comment by MadLittleMods** [comment]
> I am guessing this is the safari-based macOS app on an older version of OS X. This is a bug with any modal.
>
> You can download the NW.js version of the app that shouldn't have the issue, https://update.gitter.im/osx/Gitter-3.1.0.dmg
>
> https://github.com/gitterHQ/gitter/issues/1602#issuecomment-277104073


See

 - https://github.com/gitterHQ/gitter/issues/1602
 - https://github.com/gitterHQ/gitter/issues/1574
 - https://github.com/gitterHQ/desktop/issues/189
