### ISSUE TITLE
Request to rename community label

### ISSUE THREAD

**Issue by tongueroo** [gitterHQ/gitter#1735]
I created gitter.im/tongueroo community but labelled the community accidentally "Ufo" instead of tongueroo.  Seems like the way to rename the community is to request it at this point.

* Request to rename community #1623
* Request to rename community #1703
* Request to rename community label #1734

Could like to rename the community to tongueroo. Thanks in advance!

**Comment by MadLittleMods** [comment]
https://gitter.im/tongueroo/home is ready to go :tada:
