### ISSUE TITLE
Unable to Logout

### ISSUE THREAD

**Issue by MarieLondon** [gitterHQ/gitter#1736]
I have two GitHub accounts and I logged into Gitter with the wrong GitHub account. How can I log out?

**Comment by MadLittleMods** [comment]
Webapp (profile dropdown in the top-right)

![](http://i.imgur.com/W3SbZy5.png)

macOS (menu bar)

![](http://i.imgur.com/lTh7fHF.png)

Windows (task bar icon)

![](http://i.imgur.com/hqi7ann.png)

**Comment by MarieLondon** [comment]
Someone closed the ticket regarding me logging out of the Gitter Application without giving me the opportunity to reply! 
![screenshot 2017-06-28 19 27 26](https://user-images.githubusercontent.com/23316695/27664982-83dca3ec-5c38-11e7-925b-907547fac0f5.png)

**Comment by MadLittleMods** [comment]
@MarieLondon Per the 3 images, you are on Windows, you can sign out via the task bar icon pictured.

> Windows (task bar icon)
> 
> ![](http://i.imgur.com/hqi7ann.png)
> 
> https://github.com/gitterHQ/gitter/issues/1736#issuecomment-311559790

Or in the context menu in the top left of the window

![](http://i.imgur.com/Zs4oMOs.png)

**Comment by MarieLondon** [comment]
I am not seeing that option at all.

Sent from BlueMail<http://www.bluemail.me/r?b=9856>
On Jun 28, 2017, at 8:21 PM, Eric Eastwood <notifications@github.com<mailto:notifications@github.com>> wrote:

@MarieLondon<https://github.com/marielondon> Per the 3 images, you are on Windows, you can sign out via the task bar icon pictured.

Windows (task bar icon)

[https://camo.githubusercontent.com/1434499b804e6fe78509a7a91cbcd22fec6c8c90/687474703a2f2f692e696d6775722e636f6d2f68716937616e6e2e706e67]<https://camo.githubusercontent.com/1434499b804e6fe78509a7a91cbcd22fec6c8c90/687474703a2f2f692e696d6775722e636f6d2f68716937616e6e2e706e67>

#1736 (comment)<https://github.com/gitterHQ/gitter/issues/1736#issuecomment-311559790>

Or in the context menu in the top left of the window

[https://camo.githubusercontent.com/5dae63dd5b035aad06b1e3e8c3f83dd47575dc76/687474703a2f2f692e696d6775722e636f6d2f5a73346f4d4f732e706e67]<https://camo.githubusercontent.com/5dae63dd5b035aad06b1e3e8c3f83dd47575dc76/687474703a2f2f692e696d6775722e636f6d2f5a73346f4d4f732e706e67>

**Comment by MadLittleMods** [comment]
@MarieLondon I see in your screenshot from the previous post, the "Gitter" context menu in the top-left under the main application bar. You can also check for the Gitter task bar icon in the bottom-right of your entire screen and right-click to see the options.
