### ISSUE TITLE
Accidentally deleted organization; Cannot recreate

### ISSUE THREAD

**Issue by StanleyGoldman** [gitterHQ/gitter#1737]
I didn't quite understand how gitter worked. I was trying to create a new room,
I realize I ended up deleting the organization. I didn't realize the implications.
Can you undo my action or release the name so I can create another organization in the same url?

https://gitter.im/github-for-unity/rooms

**Comment by MadLittleMods** [comment]
@StanleyGoldman https://gitter.im/github-for-unity/ still exists. If you are an [`github-for-unity` GitHub org member](https://github.com/orgs/github-for-unity/people), you can create a new room under it by clicking the "Add a room" button at the bottom of the conversation list and select it from the community drodpown.

**Comment by StanleyGoldman** [comment]
I see you are on gitter yourself, I'll catch you there.

**Comment by MadLittleMods** [comment]
See :point_up: [June 28, 2017 12:22 PM](https://gitter.im/gitterHQ/gitter?at=5953e5e4ad9c781843ad38ab)
