### ISSUE TITLE
[feature] Codepen integration 

### ISSUE THREAD

**Issue by LukyVj** [gitterHQ/gitter#213]
Hey, as I suggested on my gitter message : 
I speak in the name of @Bullgit : We would love to see a codepen integration into Gitter.
I think everybody would agree with it.
Cheers

**Comment by suprememoocow** [comment]
Hey @LukyVj, I'm finishing up on this work now and it's looking good. Hopefully we'll roll it into next.gitter.im tomorrow. I've also added a whole bunch of other embed providers, including:

* JSFiddle
* Speakerdeck
* Behance
* Dribbble
* Codepen
* GitHub Gists
* Vine
* Flickr
* 500px
* Google Maps
