### ISSUE TITLE
Activity stream should include repo name if subscribed to more than one

### ISSUE THREAD

**Issue by stephanh** [gitterHQ/gitter#215]
Github updates don't include the repository name in its notifications in the activity stream.When the channel is subscribed to multiple repos it is hard to know which repo was updated. It would be good if gitter would include the repository name if the channel is subscribed to multiple repos.

**Comment by gnarf** [comment]
This would be awesome.  We have a few repos but the same community works with all of them currently, I don't want individual channels for each repo and having multiple repos in the current activity feed doesn't mention which repo.

:+1:

**Comment by LB--** [comment]
:+1:

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/services/issues/47 on the services/integrations repo.
