### ISSUE TITLE
Make logging out of the OSX app easier

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/gitter#217]
At the moment, it's not that obvious.

**Comment by mydigitalself** [comment]
This is much more obvious in the new app to be launched soon, going to close.

**Comment by mikeislearning** [comment]
I still have no idea how to log out in the Gitter app

**Comment by mydigitalself** [comment]
OSX: Click on the menu bar icon, Choose Sign Out.
Windows/Linux: Gitter menu, Choose Sign Out.

**Comment by mikeislearning** [comment]
I do not see such an option on OSX
![screen shot 2015-07-01 at 2 38 17 pm](https://cloud.githubusercontent.com/assets/3151928/8449820/e4fb4b88-1ffe-11e5-96cd-0b27d167cc18.png)

**Comment by mydigitalself** [comment]
That's the **dock** icon. The menubar icon is the one in the top strip where the time, battery, wifi, etc... sits.

**Comment by mikeislearning** [comment]
Ah! Thanks.
Kind of a weird place to not have the sign out option in the actual app though. Never seen that before.
I appreciate the help though :)

**Comment by saiko-chriskun** [comment]
I see no signout option in the menubar.

<img width="286" alt="screen shot 2015-08-26 at 12 50 55 pm" src="https://cloud.githubusercontent.com/assets/857940/9485791/489fe7ca-4bf1-11e5-803b-0307626248fa.png">

**Comment by saiko-chriskun** [comment]
Attempted to signout by revoking github access and everything broke.

<img width="662" alt="screen shot 2015-08-26 at 12 56 32 pm" src="https://cloud.githubusercontent.com/assets/857940/9485848/ff767220-4bf1-11e5-904f-9d27b07fdb92.png">

**Comment by d235j** [comment]
This still is an issue; a menu item for logout would be nice. Multiple account support would also be handy.
Looks like the correct workaround is to remove the Gitter item in Keychain Access, at least on Mac. That forced a logout for me.

**Comment by mydigitalself** [comment]
@d235j the signout button is on the menubar **icon**.

![signout](https://cloud.githubusercontent.com/assets/1491887/14458746/476e0dcc-00ab-11e6-88cb-371047936c03.png)

**Comment by brj** [comment]
What about logging out of the web client?

**Comment by MadLittleMods** [comment]
@brj On the new left menu, the sign out action is under the "All Conversations" heading.

![](http://i.imgur.com/ApHOjVQ.png)

**Comment by brj** [comment]
Thanks @MadLittleMods! I feel like an idiot now.

**Comment by omaraf** [comment]
@MadLittleMods it did not work for me, only @mydigitalself method worked.

**Comment by KyleFromOhio** [comment]
I just spent 20 minutes trying to find the logout button on the OSX app.  It should be under the profile avatar icon like every other app in the world. I ad to come here to find out how to do it. I logged in using my twitter account but the room i was trying to reach was restricted to Github login so needed to logout and back in.

**Comment by jonefeewang** [comment]
it is really hard to find the "log off" menu.(I don't think it is a good design). If you are mac version, it is here:
![image](https://cloud.githubusercontent.com/assets/3032599/26384207/3c29bfb0-406a-11e7-8b1d-fea7d36b1dac.png)
