### ISSUE TITLE
Ability to delete a room

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#218]

**Comment by svincent** [comment]
:+1:

**Comment by caspervonb** [comment]
+1

**Comment by bobbyrne01** [comment]
:+1:

**Comment by roll** [comment]
:+1:

**Comment by VahidGh** [comment]
:+1:

**Comment by goanpeca** [comment]
:+1:

**Comment by toddgeist** [comment]
:+1:

**Comment by jcakes69** [comment]
:+1:

**Comment by FreeCodeCamp** [comment]
+1

**Comment by Elusive138** [comment]
+1

**Comment by famousgarkin** [comment]
:+1:

**Comment by duanmua** [comment]
:+1:

**Comment by tonypujals** [comment]
:+1:  I misspelled a room name, no history yet -- *really* want to (and should be able to) delete it!

**Comment by tomcashman** [comment]
+1

**Comment by trevorah** [comment]
This should be live in the next few days. You can enable [Gitter Next](http://next.gitter.im) to see it now.

1.
![screen shot 2015-06-04 at 17 57 51](https://cloud.githubusercontent.com/assets/298742/7989699/4a2bfa42-0ae3-11e5-83bc-071fd2d34f91.png)
2.
![screen shot 2015-06-10 at 15 16 52](https://cloud.githubusercontent.com/assets/298742/8084610/d98ea8e8-0f83-11e5-84d2-96fb25feb53d.png)
3.
:skull:

**Comment by trevorah** [comment]
It's live :tada:

**Comment by mmelendrez** [comment]
:+1:

**Comment by mydigitalself** [comment]
@mmelendrez this has been available for ages

**Comment by mmelendrez** [comment]
where is the option located? I can send you a screenshot of what I'm looking at I've checked every menu I can see.

**Comment by mmelendrez** [comment]
I can leave rooms and hide rooms but not delete rooms

**Comment by mydigitalself** [comment]
Are you perhaps not an owner of the room?

**Comment by mmelendrez** [comment]
Mmmm, it's a group but I have my own room that I still don't have that option on

**Comment by mydigitalself** [comment]
<img width="253" alt="screen shot 2016-07-20 at 21 51 48" src="https://cloud.githubusercontent.com/assets/1491887/17002640/302ebf82-4ec4-11e6-9ae8-fedba16606db.png">

That's what you should see. If you don't, you're not an owner of the room.

**Comment by mmelendrez** [comment]
this is my view
![capture](https://cloud.githubusercontent.com/assets/2855130/17002729/5823d306-4e92-11e6-8d63-8029f8dfd43d.PNG)

**Comment by mydigitalself** [comment]
Something is way not right with your whole view. What version of IE are you using?

(Why are you using IE anyway 😉)

**Comment by mmelendrez** [comment]
I know right?! Military issued computer, heavily regulated on what we can and can't use. Older version of IE... Let me check

**Comment by mmelendrez** [comment]
We are allowed Firefox but again older version. I'll try that one

**Comment by mydigitalself** [comment]
> I know right?! Military issued computer, heavily regulated on what we can and can't use. Older version of IE...

Ah, that would explain it and sorry you're subjected to that!

Did you manage to come right with FireFox?

**Comment by mmelendrez** [comment]
Yep - firefox won. The menu you were highlighting wasn't available in IE but it was on the right hand side of the screen in the gitter chat in firefox. Oddly, I went back to IE this morning and actually, even though you can't see the buttons - they are there, if I hover over the area where I would hover in firefox for the menu a text box comes up telling me what the button is and if I press it then the options come up. Weird. But hey, got it figured out. Thanks!

**Comment by mydigitalself** [comment]
@mmelendrez do you know what version of IE it is you are using?

**Comment by mmelendrez** [comment]
IE version 11
Firefox 47.0
