### ISSUE TITLE
Sound for notifications

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#220]

**Comment by mydigitalself** [comment]
This is coming out in the new desktop clients very soon, so going to close. Keep an eye on Twitter for when they are released. Note it can be switched off as well if it irritates anyone.

**Comment by akoeplinger** [comment]
@mydigitalself are there plans to add sounds to the web version as well?

**Comment by mydigitalself** [comment]
@akoeplinger nope, but out desktop apps will work across Linux, Windows and Mac soon.

**Comment by cricketsloan** [comment]
Please, our whole group switched to gitter and we are all missing notices

**Comment by mydigitalself** [comment]
@cricketsloan why don't you install one of the apps then?

**Comment by cricketsloan** [comment]
We are using Gitter Version 1.162 (1.162) for OSX with the sound notification set to on.  But no one gets sound.  When we googled the problem, this thread showed up.  We get banners but not sound.  

Thanks

**Comment by mydigitalself** [comment]
Ah, the sounds aren't in the Mac App yet, they are coming soon.

**Comment by webmasterkai** [comment]
How soon is "soon"? Still no Mac update a couple months later.

**Comment by MadLittleMods** [comment]
@webmasterkai The desktop app is open source, PR welcome: https://github.com/gitterHQ/desktop/blob/87d146572b43e07a96847770fcc76c31bc683122/nwapp/utils/notifier.js#L18

**Comment by webmasterkai** [comment]
Sweet, thanks for the link. I didn't see that at first.



—
Kai

**Comment by IngwiePhoenix** [comment]
I do pretty much everything via sound due to being almost blind.

Everything BUT Gitter makes a sound on my mac. So, I usually miss _everything_...

So please make this happen so I don't miss when people need me - thanks! :)

**Comment by mydigitalself** [comment]
Sorry @IngwiePhoenix we don't have an ETA on this, we may be re-rewriting the Mac app as we aren't overly happy with nw.js. Certainly aware of the issue, just fairly resource constrained at the moment. Keep an eye on this issue for updates.

**Comment by unho** [comment]
We would really appreciate if the web version supports sound notifications as well.

**Comment by MadLittleMods** [comment]
For the webapp, see https://github.com/gitterHQ/gitter/issues/735
