### ISSUE TITLE
IRC integration - join IRC rooms from Gitter

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#249]

**Comment by ahgittin** [comment]
https://github.com/finnp/gitter-irc-bot works brilliantly for this; in [Apache Brooklyn](http://brooklyn.io) we are now mirroring:

* #brooklyncentral
* https://gitter.im/brooklyncentral/brooklyn

notifications and markdown and files all behaviour beautifully.  nice work @finnp and @gitterHQ .

i'd say this issue can be closed (unless gitter have plans to offer this automatically as part of their service which would be cool)

**Comment by mydigitalself** [comment]
Awesome to hear, we will certainly look to adding this capability natively in the future, but for now lets close this particular issue.
