### ISSUE TITLE
Linux App

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#251]
- [ ] Test state of current build on Ubuntu
 - [ ] register package on apt
 - [ ] Setup ubuntu vms

**Comment by AmmarAliShah** [comment]
A screenshot of the work in progress would be great

**Comment by troupe-admin** [comment]
I'm quite sure @malditogeek had one at some point...

**Comment by AmmarAliShah** [comment]
When will the ubuntu app be reaady?

**Comment by trevorah** [comment]
It will be ready when it is ready. At the moment we have just released the windows app alpha, so we are busy reacting to feedback from that. We will let you know as soon as we have any updates.

**Comment by mydigitalself** [comment]
The first Beta of our Linux app is available for testing and would greatly appreciated your help. This version has been released as a deb package and we will make additional distributions available once we've ironed out any issues that arise from this version.

Please visit https://github.com/gitterHQ/desktop to download and file any issues and you are welcome to join us in https://gitter.im/gitterHQ/desktop to chat about it.

**Comment by AmmarAliShah** [comment]
I'm giving the Linux Beta app a test. Will report back with problems

**Comment by codeadict** [comment]
Awesome will try it

**Comment by saleemrashid1** [comment]
Looks like this has been released! Nice, 'cos I always start using stuff at the right time!

**Comment by saleemrashid1** [comment]
Shame it is in `*.deb` form (probably use `alien` to convert it), no longer use Debian, now on Fedora.

**Comment by trevorah** [comment]
Would you prefer a `*rpm`?

**Comment by saleemrashid1** [comment]
Would be nice but no too big a deal!

**Comment by saleemrashid1** [comment]
`alien` doesn't work because there is a "broken" `libudev.so.0` dependency and I don't dare run `--skip-broken` on my nice healthy Fedora system!

**Comment by saleemrashid1** [comment]
I might try and fork it and add an `rpm` build task but no promises have been made. :wink:

**Comment by trevorah** [comment]
I've been rewriting the build to be a lot simpler, so you might want to wait until then...

We currently use fpm to create the packages, so you might want to get to grips with that first.

**Comment by saleemrashid1** [comment]
yep, have read the `gulpfile.js` but am slightly tired ATM so will re-read in the morning.

**Comment by lig** [comment]
When you stated that you have generic Linux build, you should provide simple binary release via `.tar.gz` format. After that you may start on building deb or rpm or anything else. At this moment you only able to put `Ubuntu` release on your `apps-panel`. That's it. You have no Linux release for now. You only have Ubuntu one.

**Comment by saleemrashid1** [comment]
You can do `ar x gitter.deb` and `tar xf data.tar`

**Comment by saleemrashid1** [comment]
Then you get `opt` folder

**Comment by saleemrashid1** [comment]
Read the [`README`](/gitterHQ/desktop/blob/master/README.md) and stop moaning. If you want, you can build it yourself. If you want, you can do
```
ar x gitter.deb
gzip data.tar
mv data.tar gitter.tar.gz
```

**Comment by saleemrashid1** [comment]
BTW, `deb` is a **Debian** package file not just an *Ubuntu* package file

**Comment by lig** [comment]
Is it confirmed to work on Debian now? I believe its not.

`data.tar` contains `opt` dir and some debian specific files that not
intended to be there. More over `gitter.desktop` file is bound to the
debian package paths.

On Mon, Mar 23, 2015 at 8:54 AM, Saleem Rashid <notifications@github.com>
wrote:

> BTW, deb is a *Debian* package file not just an *Ubuntu* package file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitterHQ/gitter/issues/251#issuecomment-84821377>.
>



-- 
Serge Matveenko
mailto: serge@matveenko.ru
github: http://lnkfy.com/1
linkedin: http://lnkfy.com/S
http://spbpython.guru/

**Comment by saleemrashid1** [comment]
`data.tar` doesn't, but the `deb` file contains the debian control data. `gitter.desktop` doesn't matter, just change it!

**Comment by lig** [comment]
data.tar does contain opt dir for real

    $ ls
    gitter_2.3.1_amd64.deb
    $ ar x gitter_2.3.1_amd64.deb 
    $ ls
    control.tar.gz  data.tar.gz  debian-binary  gitter_2.3.1_amd64.deb
    $ tar xf data.tar.gz 
    $ ls
    control.tar.gz  data.tar.gz  debian-binary  gitter_2.3.1_amd64.deb  opt  usr
    $ ls opt/
    Gitter

**Comment by saleemrashid1** [comment]
You need to run `after-install.sh` to get it to work, these aren't debian specific

**Comment by saleemrashid1** [comment]
This fixes the `libudev.so.0` error

**Comment by myroslav** [comment]
I'm running the Gitter in Fedora with 

```
GITTER_ROOT=/path/to/Gitter/extract/root
LD_LIBRARY_PATH=$GITTER_ROOT/opt/Gitter/linux32:$LD_LIBRARY_PATH $GITTER_ROOT/opt/Gitter/linux32/Gitter
```

i.e. I do not install it systemwide, I just extact it and run it, no post-install needed.

**Comment by lig** [comment]
On Mon, Mar 23, 2015 at 5:50 PM, Myroslav Opyr <notifications@github.com>
wrote:

> i.e. I do not install it systemwide, I just extact it and run it, no
> post-install needed.
>

I do the same. See
https://ask.fedoraproject.org/en/question/65767/how-to-install-gitter-on-fedora-21/#65768
:)


-- 
Serge Matveenko
mailto: serge@matveenko.ru
github: http://lnkfy.com/1
linkedin: http://lnkfy.com/S
http://spbpython.guru/
