### ISSUE TITLE
IRC edits

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#274]
I've categorised this as both a bug and an enhancement as the behaviour appears to be buggy yet it's due to a shortcoming of IRC not being able to support message edits.

If somebody edits a message, should we sent it again?

You can imagine this might become a bit painful if somebody does minor spelling edits multiple times though, but in general I think it's a fairly decent solution.

Feel free to discuss.

**Comment by malditogeek** [comment]
IRC edits are available in the new IRC Bridge: https://github.com/gitterHQ/irc-bridge

Currently running on `irc-next.gitter.im` port 7777 (same token, NO SSL) but coming to production soon.
