### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/gitter#275]
We need to ensure a person is logged in before allowing them to use transloadit.

https://app.getsentry.com/gitter/gitterim-backend/group/22655038/

**Comment by MadLittleMods** [comment]
I believe this is solved because an anonymous user can't upload a file anymore. See [my comment in #327](https://github.com/gitterHQ/gitter/issues/327#issuecomment-126847163).
