### ISSUE TITLE
Compose mode bug

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#285]
Reproducible every time:

Send a message to someone
Edit the message
Click toggle compose mode
(Note focus now shifts to the primary input not the edit input)
Click back into edit message
Send the message

Every subsequent ENTER doesn't create a new line

**Comment by MadLittleMods** [comment]
This seems to work fine now. I can send a message, edit it, and send more messages in compose mode.

You can't use compose mode to edit a message though, see https://github.com/gitterHQ/gitter/issues/416
