### ISSUE TITLE
Ability to hide interface elements

### ISSUE THREAD

**Issue by fuadsaud** [gitterHQ/gitter#296]
Sometimes I feel like there's too much clutter in the interface. If I want to focus solely on the chat or maybe something like a gist that's embedded in the conversation, I feel like the sidebars unnecessarily take up too much space and attention away.

Maybe it would be good to have the ability to hide these elements individually or creating a focus/fullscreen mode that hides everything but the conversation viewport away

 What do you guys think?

**Comment by mr-c** [comment]
+1 to collapsing left pane

**Comment by dcsan** [comment]
definitely. however maybe they want to keep them since thats where "call to action" prompts go... (and ads in future maybe)

**Comment by n370** [comment]
+1 to collapsing left pane

**Comment by abhisekp** [comment]
@dcsan showing ads is fine for larger screen size but for smaller browser size, it's inconvenient.

**Comment by cbj4074** [comment]
:+1: to collapsing *both* panes at will.

**Comment by sapioit** [comment]
Leaving a comment to be kept up to date. I am interested in this, as well. Thank you for your time!

**Comment by MadLittleMods** [comment]
Currently on `next` you can collapse the right toolbar with the button in the top-right of the chat header

![](http://i.imgur.com/L3oRBbq.png)

![](http://i.imgur.com/yCx2VkX.gif)

**Comment by sapioit** [comment]
Awesome. Just my 2 cents, the left-menu should be hidden, by default, in my opinion... maybe even both of them, since the one on the right doesen't includes critical data (like the chat does).

**Comment by wichert** [comment]
Is this really fixed? I can see the toggle in the standalone app, but the web-version does not seem to have it.

**Comment by abhisekp** [comment]
@wichert Are you in the [**future**](next.gitter.im) yet?

**Comment by MadLittleMods** [comment]
@wichert What browser are you using? The [features mentioned above](https://github.com/gitterHQ/gitter/issues/296#issuecomment-228398878) are in production.

**Comment by wichert** [comment]
@abhisekp I'm not sure what you mean with future, but I'm looking at next and see no option to collapse the left purple column:

![image](https://cloud.githubusercontent.com/assets/199657/17056619/d4b197f4-5014-11e6-9574-cdf4d5d36969.png)


@MadLittleMods This is on both Chrome 51 and Safari 9.1.2

**Comment by MadLittleMods** [comment]
@wichert You need to sign in to see it.

**Comment by wichert** [comment]
@MadLittleMods Ah, that was the magic hint!

**Comment by abhisekp** [comment]
@wichert It seems you don't want to chat. But it is fine. I've been trying hard to stay away from people since a year. But failed every time :pensive: Gitter just gits me in. 
Best to stay logged out! :smirk: 
.
.
.
.
_jk_
