### ISSUE TITLE
Open Source Your IRC Bridge

### ISSUE THREAD

**Issue by martindale** [gitterHQ/gitter#314]
I love what you guys have done with the IRC bridge (even the onboarding flow is great, which I loaded in Lynx!  Thanks!) and would like to see how it's implemented, so I can use it for other projects as well!

Could you please open source it?

**Comment by acidjazz** [comment]
Having the same issue in IRSSI myself:

```
[(msgs)] /connect irc.gitter.im 443 -ssl
[01:41] [gitter] >>> Irssi: Looking up irc.gitter.im
[01:41] [gitter] >>> Irssi: Connecting to irc.gitter.im [54.165.2.93] port 443
[01:41] [gitter] >>> Irssi: Connection to irc.gitter.im established
[01:41] [gitter] >>> Irssi: Connection lost to irc.gitter.im
```

Usually I would connect here and then do /PASS {token} etc , or I can specify the token in /connect but still it just disconnects w/out any reported errors

**Comment by acidjazz** [comment]
I figured out the issue with this, actually @TimothyGu did 

```
/connect -ssl irc.gitter.im 6697 TOKEN nick
```

Using this format I was able to connect

**Comment by TimothyGu** [comment]
It would be helpful if the port number is documented somewhere on the IRC homepage.

**Comment by martindale** [comment]
@mydigitalself the issue appears to be closed without a link to the source code.  I propose this issue be re-opened until it is made available.

**Comment by mydigitalself** [comment]
@martindale fair point, we were hoping to get around to this sooner, but have been caught up with other work.

**Comment by malditogeek** [comment]
@martindale @overra You can track the progress of this on https://github.com/gitterHQ/irc-bridge which is the new bridge. 

The current bridge relies on some private API endpoints and as Mike said is a modified IRCd.js. The new one on the other hand is not based on IRCd.js; it's built on top of our API client [node-gitter](https://github.com/gitterHQ/node-gitter) and the IRC connections are handled by a very small server that doesn't have all the traditional IRC functionality as we don't need it.

Another advantage is that you can run the bridge locally on your own server or in localhost so feel free to clone it and give some feedback. Cheers.

**Comment by troupe-admin** [comment]
It needs a new name...

**Comment by lepinkainen** [comment]
/network add -nick <nick> gitter
/server add -ssl -ssl_verify -auto -network gitter irc.gitter.im 6697 <token>
/connect gitter

This worked for me in irssi.

**Comment by martindale** [comment]
@malditogeek thank you very much for putting effort into getting that out the door.  You didn't have to, but this will be very helpful for a great many projects.  Thanks.
