### ISSUE TITLE
Owner for long repo names hard to distinguish in left menu search results

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#322]
If you, for example, have forks of a repo they will appear to be the same repo.

**Comment by trevorah** [comment]
We should use the cool squashy names widget that we use for room names in https://gitter.im/explore/tags/javascript,php,ruby

**Comment by trevorah** [comment]
Whoops, I forgot to read the last two words. I thought it said "Owner for long repo names hard to distinguish in left menu". I'll check if there is an issue for that.

**Comment by mydigitalself** [comment]
I've seen one, but nobody could justify it properly and I really haven't
heard anyone ask about this since so I'm not convinced it's a huge priority
or win.

**Comment by trevorah** [comment]
https://github.com/gitterHQ/gitter/issues/385 right?

**Comment by mydigitalself** [comment]
yip

**Comment by mydigitalself** [comment]
This is no longer relevant as the search results have moved to the right menu and show the owner avatar.
