### ISSUE TITLE
stop the kicking free for all in org rooms

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#335]
At the moment, org rooms allow anyone to kick anyone else from the room. This can get especially bad with large orgs.

Either we **a)** dont allow kicking, just mirror the org user list on github, or **b)** give privileges to teams with [administrative permissions](https://github.com/blog/674-introducing-organizations).

**Comment by mydigitalself** [comment]
Is this truly a problem? I haven't heard a single complaint about this. Going to close, if it's an issue, then please comment/reopen.
