### ISSUE TITLE
Add visual indicator for username menu

### ISSUE THREAD

**Issue by orliesaurus** [gitterHQ/gitter#346]
![](https://dl.dropbox.com/s/3n8ayf0g8gh0tak/Screenshot%202014-09-02%2014.29.20.png?dl=0)

I would totally see a little down pointing arrow to explain that this is actually opening a menu, next to my nick!

**Comment by waltfy** [comment]
Just implementing this now. Logic was pretty much there already. Thinking about taking this opportunity to make proper use of octicons. Meaning that we can forget some of the classes that we have and just drop in something like:

`<i class='octicons octicon-heart' />`

:rocket:?

**Comment by trevorah** [comment]
shipped.
