### ISSUE TITLE
Keyboard shortcuts don't work when you Alt-Tab to focus the chat window

### ISSUE THREAD

**Issue by fiznool** [gitterHQ/gitter#348]
This is only happening in the Chrome App.

Tested on Ubuntu 14.04.

**Comment by MadLittleMods** [comment]
Keyboard shortcuts seem to work just fine for me on everything when alt-tabbing to the window.

Keep in mind that the shortcuts are different from Windows to Linux. *ex.* "Focus the chat input" is `ctrl + shift + c` on Windows but `ctrl + alt + c` on Linux

### Windows 8.1

 - Web app on Chrome(and Firefox).
 - Desktop nw.js app.

### Ubuntu 14.04 (via VirtualBox)

 - Web app on Firefox
 - Desktop nw.js app

Please re-open if you are still having the issue.
