### ISSUE TITLE
Chrome App loses chat window focus when Alt-Tabbing away

### ISSUE THREAD

**Issue by fiznool** [gitterHQ/gitter#349]
If you have the chat window focussed in the Chrome App, try Alt-Tabbing away from the window, then back in again. Tested on Ubuntu 14.04.

You'll notice the chat area is no longer focussed. This, along with #348 make using the chat client in the Chome App difficult, as every time you Alt-Tab back into the chat client, you need to click in the chat area with the mouse to write anything.

**Comment by MadLittleMods** [comment]
Duplicate of #348.
