### ISSUE TITLE
500 error when searching users

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#359]
Go to https://gitter.im/api/v1/user?q=J%C3%B6rg+R and bask in the wonder of the 500 error.

You can reproduce this locally.

https://app.getsentry.com/gitter/gitterim-backend/group/18168960/

**Comment by waltfy** [comment]
Special characters seem to break it e.g. ë.

**Comment by trevorah** [comment]
Fixed once https://github.com/troupe/gitter-webapp/commit/cc442a035e9962a013ac6b87e4f7bb7fe465b3a4 is live
