### ISSUE TITLE
Ability to set individual room notification settings in the ios app

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#367]
At the moment you have to use the desktop app to change this.

via @Helmi

**Comment by georgiel** [comment]
+1 +1

**Comment by MadLittleMods** [comment]
Here is the same issue for Android gitterHQ/gitter#848

**Comment by trevorah** [comment]
Currently blocked until the current ios app passes apple's reviews. Defaults arent there until the new defaults api is there too.
