### ISSUE TITLE
Markdown reordering

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/gitter#369]
For example:

1. This is the first item in a list

And something else

2. This is the second item in a list

What do we see?

**Comment by samccone** [comment]
nice @waltfy did you PR this fix into your marked fork?

**Comment by waltfy** [comment]
@samccone I thought this was just Markdown's default behaviour?

**Comment by samccone** [comment]
yep it is! I was wondering what the fix was for this bug.  Looks like I can still make it happen 

type 1. one (hit enter)
type 2. two (hit enter)

**Comment by waltfy** [comment]
In my eyes that isn't a bug. They are in fact separate messages.

**Comment by samccone** [comment]
fair #wontfix is totally valid here

**Comment by waltfy** [comment]
I believe so... I'll leave the issue open until we have some more input from people. But @suprememoocow's Markdown the output is correct and expected. If you want to add text in between the list item, the text must be indented.
