### ISSUE TITLE
Gitter-badger doesn't handle README.org readme files correctly 

### ISSUE THREAD

**Issue by gitter-badger** [gitterHQ/gitter#371]
As spotted by @vermiculus.

Repository https://github/com/vermiculus/swift has a README.org file, but the pull-request attempted to create a new README.md file, even though GitHub correctly reports the README.org file as the readme for the repo.

**Comment by trevorah** [comment]
Fixed and open sourced in github.com/gitterHQ/readme-badger

**Comment by vermiculus** [comment]
:+1:
