### ISSUE TITLE
Chat archives broken for org rooms

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#386]
If you go to something like https://gitter.im/gitterHQ/archives/all, you get an empty graph:
![screen shot 2014-10-27 at 11 18 14](https://cloud.githubusercontent.com/assets/298742/4789905/fb845f44-5dca-11e4-9e03-499fc27be762.png)

via @suprememoocow & @jdaudier

**Comment by mydigitalself** [comment]
Also, I'm not convinced that Google Indexing is working properly any more. Tried searching Google for something and didn't see an expected result.

**Comment by trevorah** [comment]
Looks like this was fixed by @lerouxb's good work.
