### ISSUE TITLE
ORG mode READMEs don't create badges correctly

### ISSUE THREAD

**Issue by gitter-badger** [gitterHQ/gitter#392]
As discussed here: https://github.com/vermiculus/pm/pull/1

Some repos with org mode readmes create a new Readme.md file instead of using the Readme.org file as they should

**Comment by trevorah** [comment]
Thanks for the list @vermiculus, we now support all of the markups (except creole, which cant render image links). We've open-sourced it [here](https://github.com/gitterHQ/readme-badger).
