### ISSUE TITLE
Can't login with two-factor authentication in iOS app

### ISSUE THREAD

**Issue by thoemmi** [gitterHQ/gitter#396]
I'm using two-factor authentication at Github. 

Steps to reproduce:
1. Open Gitter
2. Tap "Existing User Login"
3. The webbrowser control opens
4. I enter my username and password
5. I'm forwarded to a second page for two-factor authentication
6. I haven't set up a two-factor authentication app, so I click "Send code to backup number"
7. I enter the code I received via SMS
8. I get to Github's homepage

At this point I'm logged in to Github and can browse their website. However, I expect that after a successful authentification the webbrowser control closes and that I can use Gitter on the iPhone.

**Comment by OmgImAlexis** [comment]
Basically having the same issue only I get to the 2 factor screen and enter my code. Then it just sit there as the verify button doesn't work and just gets highlighted when I click on it.

**Comment by OmgImAlexis** [comment]
@trevorah any updates on this?

**Comment by trevorah** [comment]
Closed via https://github.com/gitterHQ/gitter/issues/967.

@thoemmi let me know if this is still an issue for you and I'll reopen this.
