### ISSUE TITLE
IRC bridge does not always receive messages

### ISSUE THREAD

**Issue by Oobert** [gitterHQ/gitter#397]
The IRC bridge does not always receive messages from a room. 

I have irssi always running on computer that is always on at my house. I log into it via SSH (putty) to use. I have noticed that sometimes that irssi does not get everything that is posted to a room. 

This screen shot is an example this issue. Kirisu's and scottcorgan's messages where never recieved in irssi. The irssi client was still connected, did not disconnect at all during the night. Just to make sure, I sent the "." from irssi and it showed up in my browser. 

side note: no I don't keep the browser open. I just did to check if I missed anything.
side note 2: messages I send from a browser connection do not show up in irssi.

![capture](https://cloud.githubusercontent.com/assets/2422846/4936934/ca464ee6-65be-11e4-8195-41e8ff7ad7cf.PNG)

**Comment by mydigitalself** [comment]
@oobert do you think we can close this one now or is it still an issue for you?

**Comment by Oobert** [comment]
Yeah I think we can close it. If I can prove it isn't my connection, I will open it with new info.

**Comment by mydigitalself** [comment]
Thanks!

**Comment by rossabaker** [comment]
This is happening to me.  I see the connection to 54.86.157.241, without any disconnects, and I am missing messages.  xchat-2.8.8 on Linux.  I need to reconnect about once per day.

**Comment by wedens** [comment]
Same problem on weechat 1.1.1

**Comment by malditogeek** [comment]
@Oobert @rossabaker @wedens I'm trying to narrow this down and find out where are we losing messages. Currently `irc.gitter.im` goes through an Amazon ELB in TCP mode so I created a DNS record that points directly to one of the IRC boxes to see if this is an ELB related issue. 

Would be great if you can update your IRC configurations to use the host `irc-001.gitter.im` and **disable SSL** (SSL termination happens in the ELB and we are removing by-passing it just to test)

**Comment by rossabaker** [comment]
Thanks!  I'm cut over, and will report back if and when I see it happen.

**Comment by rossabaker** [comment]
I'm experiencing it right now on irc-001.gitter.im.  I am on the gitterHQ/gitter channel, and will try not to reconnect, in case I can provide more diagnostic info.

**Comment by rossabaker** [comment]
New finding: it's a per-channel problem.  #non/cats has gone silent, but I saw a notification on #gitterHQ/gitter as a result of my last post.

**Comment by adelbertc** [comment]
Having issues with this as well (using [IRCCloud](https://www.irccloud.com/) ). Worked for a while when I first joined, but `#non/cats` has gone silent for me as well. Seemed to work fine at first for an hour or so?

If there's anything I can do to help please let me know - loving Gitter, but also still want my IRC :-)

**Comment by malditogeek** [comment]
An update on this. I've been working on a new IRC bridge, smaller, faster and open sourced at https://github.com/gitterHQ/irc-bridge

You can connect to the new bridge at `irc-next.gitter.im` on port 7777 with the same token and NO SSL (SSL will be back once this goes into production). Hopefully we can move this production for everyone soon but I'll really appreciate if you connect to this new instance and give some feedback. Feel free to open issues at https://github.com/gitterHQ/irc-bridge

Will re-open this issue until the new bridge goes into production.

**Comment by OlegYch** [comment]
the new server is kinda sluggish, takes around 15 seconds to receive a message

**Comment by OlegYch** [comment]
i see the same problem with new server, after some time i don't receive any messages (at least on some channels) while i still can send messages

**Comment by OlegYch** [comment]
there was a  "<gitter> [>> gitter]  Server restarting..." message in log an hour ago

**Comment by OlegYch** [comment]
actually, nevermind, it was a problem on my end, will test a bit more..

**Comment by malditogeek** [comment]
:tada: The new [irc bridge](https://github.com/gitterHQ/irc-bridge) is finally in production. You can connect again to `irc.gitter.im` using SSL. This issue should be fixed. If you experience any other problems, open an issue at https://github.com/gitterHQ/irc-bridge

**Comment by KlongNu** [comment]
I still have this issue sometimes but rarely

**Comment by brunodp** [comment]
I'm experiencing this issue right now.

**Comment by dalejung** [comment]
I'm having the same issue. Using textual on mac. I can send messages, but I don't receive messages from the room.

**Comment by mydigitalself** [comment]
@malditogeek ^^

**Comment by benfleis** [comment]
same issue, Adium + irc. it doesn't drop all messages, but dropped 2 of 3 in a sequence (within a minute). will do what I can to help debug :)

**Comment by rom1504** [comment]
might be better to open an issue in https://github.com/gitterHQ/irc-bridge/issues ?
I don't have this problem since the new irc bridge though.

**Comment by mydigitalself** [comment]
So I think we've managed to figure out the issue with @benfleis 

If you have both IRC as well as web/desktop open and receive a 1:1 private message from somebody, the web/desktop consumes the messages and it never reaches the IRC bridge.

If anyone else is experiencing different behaviour (i.e. not in 1:1 private rooms and they don't have another client open) then please let us know.
