### ISSUE TITLE
Remove or Hide Suggested Rooms

### ISSUE THREAD

**Issue by jeffmcneill** [gitterHQ/gitter#399]
Suggested rooms are marginally useful, they should be removed from account more than a few days old, or at least hidable

**Comment by valleybay** [comment]
Anything happening with this? It's terribly distracting.

**Comment by jeffmcneill** [comment]
im in 14 rooms and still see thesenonsense recommended room every time i open the app. mercy for paying customers, or will stop being one

**Comment by mk-pmb** [comment]
When using AdBlock Plus (`gitter.im## #left-menu-list-suggested`), you might have to temporarily close your gitter tabs while updating the filters list. Hiding the suggested channesl while the char was active made my Firefox unresponsive.

**Comment by mydigitalself** [comment]
Hey folks. 

Sorry we haven't had the opportunity to look at this yet, we've been swamped with improving performance for all as well as Android, Windows & Linux desktop support.

Will look to see how we can address this next Monday.

Can anyone else confirm they still see the suggested rooms if they have >=10 items in the left menu? As per my tests:
http://cl.ly/image/110E3o0m3C2S
http://cl.ly/image/2A0c14312y1I

**Comment by mydigitalself** [comment]
- [ ] Fix double modal issue
- [ ] Verify join_room event metadata
- [ ] Add close button that remembers state as a user setting

**Comment by waltfy** [comment]
@mydigitalself can't seem to reproduce the double modal issue.

**Comment by waltfy** [comment]
The foundations for a better solution have been initialised. For now you will be able to get rid of the suggested rooms, forever. You won't, however, be able to get them back. Choose wisely for now.

:rocket:
