### ISSUE TITLE
move repo to new org loses chat history

### ISSUE THREAD

**Issue by minrk** [gitterHQ/gitter#405]
We moved ipython/nbviewer to jupyter/nbviewer, and the chat history for ipython/nbviewer is lost. Is there a way for gitter to track repos moving to new owners?

**Comment by lossyrob** [comment]
+1 on this. GeoTrellis is moving to LocationTech, so when we switch the repository from `geotrellis/geotrellis` to `locationtech/geotrellis`, it would be great to not lose all our history/members.

**Comment by minrk** [comment]
@trevorah awesome, thanks!

**Comment by trevorah** [comment]
No problem! @suprememoocow did all the hard work...

**Comment by adamliter** [comment]
Hi, I was wondering if there is a general way to move the chat history from one room to another. For example, is there any way to move the chat history for a particular repository to a channel?
