### ISSUE TITLE
Firefox: Readby popover can fall off the screen

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#412]
https://files.gitter.im/gitterHQ/gitter/w1yH/thumb/Screenshot-from-2014-11-20-18_31_03.png

As reported by @omerzimp in FF you can sometimes get the readby popover to point downwards such that it falls off the visible canvas.

**Comment by MadLittleMods** [comment]
I am going to close this as I haven't heard any reports of this.
