### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#425]
1. Deal with the use case where somebody walks away from the computer and doesn't receive a notification on their mobile.

2. Simplify notification settings. Should just be three, rather than the lurk confusion.

3. Perhaps have a toggle button in the room. 

4. Global default. Also consider defaults for when people join rooms. Are they different for public rooms to org rooms? Are they different depending on your role?

5. Allow adjustments to room notification settings on  mobile.

**Comment by robyurkowski** [comment]
A minor thing (asked to share from the channel):

There's no `/unlurk`. Lurking is about the only way I can eke a productive days' work, but there are channels where I do want to receive notifications from. They're just too busy to keep on loud all day. I know I can adjust the setting inside the Notifications pane, but this would be an appreciated shortcut.

**Comment by georgiel** [comment]
+1

**Comment by Zoltu** [comment]
+1 to mobile notifications when logged in from computer.  I leave myself logged in on my computer at all times.  Unfortunately, this makes the mobile app pretty useless since it doesn't give me any notifications.

**Comment by MadLittleMods** [comment]
Related to: [*@/all pings lurkers*](https://github.com/gitterHQ/gitter/issues/520) #520

**Comment by Zoltu** [comment]
Was this close as `fixed` or `won't fix`?

**Comment by MadLittleMods** [comment]
@Zoltu Not sure, I noticed as well @cutandpastey claims to not have done it.

**Comment by mydigitalself** [comment]
I think perhaps there was a commit that referenced this issue that closed it?

> Simplify notification settings. Should just be three, rather than the lurk confusion.

That's done and shipped and perhaps that closed it?

**Comment by cutandpastey** [comment]
@mydigitalself @MadLittleMods sorry, my bad. We did ship things related to the issue but it was @suprememoocow 's work.

**Comment by MadLittleMods** [comment]
1. We [now](https://github.com/troupe/gitter-webapp/pull/1660) use the page visibility for eyeballs which works a bit better to cover more situations. Also see https://github.com/gitterHQ/gitter/issues/143
 2. Notifications now have three settings, "All", "Announcements", or "Mute", http://i.imgur.com/oAGLNhp.png
 3. See https://github.com/gitterHQ/gitter/issues/302 but this can be split out better if someone is keen on this feature.
 4. Default notification settings has been implemented for some time now, see https://github.com/gitterHQ/gitter/issues/1312
 5. You can adjust notification settings on [Android](http://i.imgur.com/n0QxrCq.png) and iOS. You can also use the slash commands `/notify-all`, `/notify-announcements`, `/notify-mute` in the chat input. See https://github.com/gitterHQ/gitter/issues/848 and https://github.com/gitterHQ/gitter/issues/367
