### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#428]
Consider offering a chrome extension. This could light up if there's a Gitter room for a repo no matter what page you are on in GitHub (i.e. not just the readme).

If we introduced chats on issues (#246) this would be a great way to start a live chat around an issue.

We could include a button to create an issue asking the owner to create a gitter room if one doesn't exist.

**Comment by svincent** [comment]
I'm looking at taking a crack at #222. Would that issue and this one overlap?

**Comment by mydigitalself** [comment]
Yeah, let me close this one as a duple, would be awesome!
