### ISSUE TITLE
Support for badging reStructuredText README files

### ISSUE THREAD

**Issue by acdha** [gitterHQ/gitter#443]
README files using reStructuredText are fairly common at least in the Python world. It would be nice if the code which generates the badging pull request had a fallback looking for README.rst if README.md doesn't exist.

[The code I used for mine is very simple](https://github.com/acdha/image-mining/blame/98ce194b127c2ab6134ccee034d7c0e905c51a75/README.rst#L35-L37) – note only the need to URL encode the image link since at least the GitHub reST processor silently strips the space from the URL, leaving the text as "JoinChat":

```rst
.. image:: https://badges.gitter.im/Join%20Chat.svg
    :target: https://gitter.im/…
    :alt: Join Chat on Gitter.im
```

**Comment by trevorah** [comment]
Thanks for this @acdha. Our rst support is now live and we've [open-sourced the library](https://github.com/gitterHQ/readme-badger).

Please let us know what you think!

**Comment by acdha** [comment]
Awesome, thanks!
