### ISSUE TITLE
It's possible to send a blank message from mobile

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/gitter#447]
As reported by @jdaudier 

![blank](http://cl.ly/image/2o3K330q093Q/Image%202014-12-04%20at%205.19.19%20pm.png)

**Comment by jigneshthummar** [comment]
Steps to repoduce issue

Put spacebar 
Dont click on enter to send 
Instead enter click on avatar icon @left and it will send blank message

Its not possible to send blank message by hitting enter

Checked with xiaomi MI4 and Moto E but unable to reproduce using Nexus 7
