### ISSUE TITLE
Validate github username before link it

### ISSUE THREAD

**Issue by staabm** [gitterHQ/gitter#454]
atm every word prefixed with an "@" is interpreted as a github username and a link to a possible not-existant user is rendered.

gitter should be smarter and only link to github when the user actually exist.
Links with non-existing usernames are rendered as a 404 from github, so shouldn't be too hard to detect that.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/811
