### ISSUE TITLE
Organisation looks and behaves like a common user

### ISSUE THREAD

**Issue by evenius** [gitterHQ/gitter#458]
I recently converted a user to an organisation, but gitter won't recognise the change and now the only option is a simple one-on-one conversation
![screen shot 2014-12-10 at 18 15 44](https://cloud.githubusercontent.com/assets/1070211/5380469/b0979f64-8098-11e4-90d1-53443b59bb2e.png)
![screen shot 2014-12-10 at 18 15 38](https://cloud.githubusercontent.com/assets/1070211/5380471/b0bda894-8098-11e4-996b-eef65bf36e35.png)
![zens](https://cloud.githubusercontent.com/assets/1070211/5380470/b0bd01aa-8098-11e4-8a54-7e0cc0978371.png)

**Comment by mydigitalself** [comment]
Hi there, apologies for some reason only just saw this issue now. We currently don't deal with converting users into Organisations at all, I assume this is still causing you issues?

**Comment by evenius** [comment]
Correct :)

**Comment by mydigitalself** [comment]
Right. This is quite a mind bender, will have a think about it and see what we can do. Does that Org have any useful content in it, i.e. could we just delete the user object on our side, which would effectively sort the issue out.

**Comment by evenius** [comment]
Yea, I'm already following the repo, so it'll be nice to see whatever the solution turns out to be!
There is nothing important on that Org/user, so deletion is all good for me for what's its worth (if I can reinstate it as an org)

**Comment by mydigitalself** [comment]
It's a bit more fiddly than I thought, will take a few days but should have it done for you by Monday. Sorry for the inconvenience, it's a bit of a weird case for us!

**Comment by evenius** [comment]
Just checking if there's any update on this issue?

**Comment by mydigitalself** [comment]
Hi Jonathan,

Funny you should ask, started investigating this yesterday and think I
should be able to have it sorted out by the end of today for you.

Mike

**Comment by mydigitalself** [comment]
Ok, I think it should be successfully sorted out now, let me know.

**Comment by evenius** [comment]
Nice, thank you so much :)
Or well, I checked it out, and something has definitely changed, though I don't think it's fixed. Is it still a user? (added screenshots)

![screen shot 2015-01-15 at 14 51 08](https://cloud.githubusercontent.com/assets/1070211/5758584/f1838a5c-9cc6-11e4-910d-173cd0aceb5e.png)

![screen shot 2015-01-15 at 14 51 01](https://cloud.githubusercontent.com/assets/1070211/5758623/2a98de32-9cc7-11e4-8f21-1e17d8bfb246.png)

**Comment by mydigitalself** [comment]
Try  now...

**Comment by mydigitalself** [comment]
By try now, I mean click on Zensum in your orgs list in your left menu, and
after that, everything should (maybe) be fine.

**Comment by evenius** [comment]
Great, that seems to have done it!

I'm guessing you already got a pretty good idea on what caused this, but if there's any information I can provide just let me know.
Thank you for all the help :+1:

**Comment by mydigitalself** [comment]
No problem, sorry it took so long to address. What caused it is basically
it's a use case we don't deal with at all. We still don't deal with it
natively, but I've built some scripts we can manually run that will clean
up the situation.
