### ISSUE TITLE
archive page's right menu is squashed on small/mid size windows

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#460]
![screen shot 2014-12-11 at 12 18 42](https://cloud.githubusercontent.com/assets/298742/5394036/32861ca2-8130-11e4-87b1-1a691eddfd3f.png)

**Comment by mydigitalself** [comment]
This shouldn't have this behaviour, it should always display in full size on the archive page.

**Comment by trevorah** [comment]
The styles for the right menu are still in trp3.less and the archive page tries to override them. If we "bem" it and have a two classes like `right-menu` and `right-menu--collapsable` in their own less file, then this will be less likely to break in future.

Whoever picks this up, give me a shout beforehand.
