### ISSUE TITLE
Android icon on dark background needs improving

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#465]
Its edges are hard to define.
![screen shot 2014-12-11 at 17 39 32](https://cloud.githubusercontent.com/assets/298742/5398725/c1594d56-815c-11e4-9587-a25b48c3652b.png)
![screen shot 2014-12-11 at 17 39 54](https://cloud.githubusercontent.com/assets/298742/5398727/c34d74a2-815c-11e4-951a-aa1bad3ba6e9.png)

**Comment by MadLittleMods** [comment]
Even though the current Android App uses a green/darkblue styled theme, I think using the classic Gitter pink/magenta would look a lot better. *just a note:* the current Android icon goes against "natural lighting", where the the sun would illuminate it from the top (gradient is backwards).

<img src="http://i.imgur.com/ZKr1xpm.png" width="256">

---

I was able to find many variations on the Gitter logo metrics. The spacing, size, and length relationship is a bit different between these images. Some of these differences, I guess, are for crisp pixel perfection.

Image | Page (source) | `descendant / x-height` | `barWidth / spacing` | `ascendant / x-height`
----- | ------------- | ----------------------- | -------------------- | ----------------------
![](https://camo.githubusercontent.com/b64eda325781b468f632158fb3c13e32958e195b/687474703a2f2f692e696d6775722e636f6d2f385a58304d34582e706e67) | https://github.com/gitterHQ/gitter | 76.9% | 120% | 34.61%
![](http://i.imgur.com/TrYBtFi.png) | https://gitter.im/ (not signed in) | 81.81% | 66.67% | 36.36%
![](http://blog.gitter.im/content/images/2015/03/logo-text-blue-pink.png) | http://blog.gitter.im/ | 56.25% | 100% | 31.25%
![](https://lh5.ggpht.com/5vP7AGutA557OvSrapxvH3ewClOTJf2yQ9OZ2ZFX6vdU4zA8KYoTCkmGeqqObRm68PPb=w128) | https://play.google.com/store/apps/details?id=im.gitter.gitter | 78.41% | 100% | 32.37%
![](https://avatars0.githubusercontent.com/u/5990364?v=3&s=120) | https://github.com/gitterHQ | 75.86% | ~100% | ~32.75
![](https://d262ilb51hltx0.cloudfront.net/fit/c/100/100/0*Vrsgi6r4Y0T_P9nd.png) | https://medium.com/@gitter | 79.16% | 100% | 33.33%


![](http://i.imgur.com/wKEBsiq.png)

**Comment by trevorah** [comment]
Some more guidelines: https://www.google.com/design/spec/style/icons.html#icons-product-icons
