### ISSUE TITLE
Sending from multiple line message from Android app is confusing (compose/normal mode)

### ISSUE THREAD

**Issue by jtrinklein** [gitterHQ/gitter#472]
In the Android app, sending a chat message when in multi line input mode is confusing. 

Repro steps:
- type \`\`\` then enter to begin multi line chat mode
- type message contents
- note that message is not able to be sent with enter key 

I would expect some sort of message that explains you have to tap in the chat area to send the message.

**Comment by MadLittleMods** [comment]
See:

 - gitterHQ/gitter/issues/793
 - gitterHQ/gitter/issues/873
