### ISSUE TITLE
Change how @ suggestions functions.

### ISSUE THREAD

**Issue by LumenTeun** [gitterHQ/gitter#473]
Whenever I use the @ function, it's usually to refer to someone who has recently said something in the chat and I'm sure a lot of people use it the same way. Therefore, wouldn't it be better if the suggestions listed user in order of who typed last? Just a thought.

**Comment by trevorah** [comment]
@LumenTeun the @ suggestions now list users in order of who typed last. Thanks for the suggestion!

**Comment by LumenTeun** [comment]
Awesome! :+1:
