### ISSUE TITLE
Link to chat messages

### ISSUE THREAD

**Issue by sokra** [gitterHQ/gitter#48]
The date text in a chat message should be a link, that links to this message.

i. e. https://gitter.im/gitterHQ/gitter#message-52c6f0e428b5af6e6b000014

**Comment by despairblue** [comment]
:+1:

**Comment by Elusive138** [comment]
+1

**Comment by allquixotic** [comment]
+1

**Comment by suprememoocow** [comment]
Hi folks, we've done an initial release of this to [staging](http://next.gitter.im) and I'm hoping to roll it into very production soon. For this first iteration, you can access a permalink by clicking on the sent date in a chat message. If you want to quote the link (in a chat message, use Alt-click)

Please be aware that until we roll this feature out fully, the permalinks will only work for other users on Gitter Next.

Feedback is most welcome.

Have a great weekend. 
Andrew

**Comment by ahmadia** [comment]
whoo hoo!  Thanks @suprememoocow :)

**Comment by suprememoocow** [comment]
Deployed! Refresh to get permalink functionality!
