### ISSUE TITLE
Avatars are blurry on non-retina displays

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#485]
![screen shot 2014-12-29 at 09 34 56](https://cloud.githubusercontent.com/assets/298742/5567535/8acd48ce-8f3e-11e4-863f-aa572ba6e616.png)

Looks to be an image size / display size mismatch.

**Comment by waltfy** [comment]
It seems that the correct size is loaded and displayed. It seems from GitHub directly, the images are blurry anyway?

https://avatars7.githubusercontent.com/waltfy?v=3&s=30

**Comment by waltfy** [comment]
At at second look, the way the avatar widget works is bound to a `String` that determines the size. It shouldn't be too hard to change it but it is a bit of work.
