### ISSUE TITLE
Leave vs hide?

### ISSUE THREAD

**Issue by trusktr** [gitterHQ/gitter#490]
How do we see rooms we've hidden but haven't left? As far as I can tell, leaving inherently behaves the same as hiding a window as far as the GUI is concerned (though I understand I might still be seen online in the hidden rooms).

**Comment by mydigitalself** [comment]
You won't be visible in rooms you've left. Additionally, when somebody sends a new message in a room you've hidden, it will reappear in your left menu.

There isn't a way to see all hidden rooms, but you can obviously still find the room by searching for it (top right).

**Comment by trusktr** [comment]
Seeing which room are hidden would be convenient for the purpose of leaving
some if so desired, without having to memorize them all.

*/#!/*JoePea

**Comment by iki** [comment]
@mydigitalself  I can find the room, but didn'r find how to unhide it. Is there a way to unhide it?

**Comment by MadLittleMods** [comment]
@iki Just visit the room again
