### ISSUE TITLE
How do we trigger gitter to make a PR to add the badge to a repo?

### ISSUE THREAD

**Issue by trusktr** [gitterHQ/gitter#491]
I noticed this option is given when creating a new room, but if I skipped the option, how do I trigger this later?

**Comment by mydigitalself** [comment]
If you go to the Settings button (near the top right) and click on Share this chat room, you can do it from there.

**Comment by trusktr** [comment]
Cool, it worked, though the text field looks empty, so I just assumed
clicking in it selected the invisible text, and copying it surely did work.

*/#!/*JoePea

**Comment by mydigitalself** [comment]
Hey again, would you mind sending a screenshot, the text field certainly shouldn't look empty...

**Comment by trusktr** [comment]
Uh, just happened to search for it in the Chrome Webstore, and scored! xD

**Comment by trusktr** [comment]
Plus, when I go to gitter.im, there's no immediate indication of a Mac OS X app.

**Comment by trusktr** [comment]
Searching for "gitter" in the app store didn't yield anything.

**Comment by mydigitalself** [comment]
You can find it here: https://gitter.im/apps it should normally be promoted
in all of our emails, but isn't available in the App Store due to the way
it embeds Safari and hope to solve this in the future. We can also do a
better job of promoting it in app...

**Comment by trusktr** [comment]
It says "Android coming soon" but I see one in Google Play by Troupe. Is that by someone else?

**Comment by trusktr** [comment]
The official OS X app seems identical to the Chrome app. I'm guessing for the most part they are the same web app.

**Comment by mydigitalself** [comment]
The Android app hasn't officially been released, but yes it is available for testing. It's pretty stable we haven't had any major issues reported.

**Comment by trusktr** [comment]
Oh, ok cool.
