### ISSUE TITLE
We need a Windows/Windows Phone application for Gitter

### ISSUE THREAD

**Issue by SuperJMN** [gitterHQ/gitter#492]
I'm a Windows Phone user. Once again, we can see an iPhone app, an incoming Android app and absolutely no love for Windows and Windows Phone. 

It's not that it's difficult to develop for Windows/Windows Phone. We are lots of users. Please, support us.

**Comment by RReverser** [comment]
Working on unofficial one - first Windows RT version will be released in few days, and will start working on Windows Phone after it.

**Comment by RReverser** [comment]
Here is Windows app (just released first version): http://apps.microsoft.com/windows/en-us/app/gitty/16998cba-b1d7-4d82-a8d0-131a40009168

**Comment by SuperJMN** [comment]
Installed and looking GREAT! I'm waiting for the Windows Phone version. Thanks a lot!

**Comment by RReverser** [comment]
@SuperJMN You're welcome. First release is somewhat limited in functionality, more to come. Please rate it in the Store if you like it (so others can easily find it, too).

**Comment by SuperJMN** [comment]
Voted it already!

Enviado desde mi Windows Phone
________________________________
De: Ingvar Stepanyan<mailto:notifications@github.com>
Enviado: ‎03/‎01/‎2015 13:44
Para: gitterHQ/gitter<mailto:gitter@noreply.github.com>
CC: José Manuel Nieto<mailto:superjmn@outlook.com>
Asunto: Re: [gitter] We need a Windows/Windows Phone application for Gitter (#492)

@SuperJMN You're welcome. First release is somewhat limited in functionality, more to come. Please rate it in the Store if you like it (so others can easily find it, too).

---

**Comment by RReverser** [comment]
@SuperJMN Hm, weird, doesn't display it. Anyway, thanks for feedback! Good to know someone is already using it.

**Comment by SuperJMN** [comment]
I have double check it. I only rated the application as 5-stars. Now I have also writing a review. It says “Thanks, your review will be published soon”.


Maybe it’s being filtered before getting published!


I’ve started using it and I believe I will stop using the page. It’s fast, clean and simple. I love it!






Enviado desde Correo de Windows





De: Ingvar Stepanyan
Enviado el: ‎sábado‎, ‎3‎ de ‎enero‎ de ‎2015 ‎20‎:‎52
Para: gitterHQ/gitter
CC: José Manuel Nieto Sánchez





@SuperJMN Hm, weird, doesn't display it. Anyway, thanks for feedback! Good to know someone is already using it.

**Comment by agauniyal** [comment]
@RReverser , make it a Universal app. It isn't hard to do since MSDN has articles for it and then you'll be supporting all windows devices at the same time.

**Comment by agauniyal** [comment]
@RReverser , any chance you might open source it?

**Comment by RReverser** [comment]
> make it a Universal app. It isn't hard to do since MSDN has articles for it and then you'll be supporting all windows devices at the same time.

Are you telling me?) It is created as a Universal app, and Windows Phone app will be developed as part of it, but it doesn't mean it doesn't require extra work on developing separate UIs (obviously same one doesn't look that good on phone) and using slightly different APIs and tricks for different platforms (despite common misconception, APIs are different in the signatures and behaviors depending on platform). Anyway, I'll let you know when its ready.

> any chance you might open source it

Sorry, but no.

**Comment by agauniyal** [comment]
Allright :smile:  I thought you've created separate versions. Anyways thanks , great app :+1: .

**Comment by RReverser** [comment]
@mydigitalself Hey Mike, why did you close this issue? Would be nice to have as a tracking issue for those who also wonders about Windows RT/Phone version.

**Comment by mydigitalself** [comment]
@RReverser Hey Ingar. It's pretty standard bug management, the issue has been fulfilled. People can always find this issue by searching, but you can't just leave issues open that are actually addressed. Otherwise on our side we just end up with all of these incorrectly open issues in our issue tracking.

**Comment by RReverser** [comment]
@mydigitalself Yeah, but it wasn't fulfilled as Windows Phone version originally mentioned in issue, doesn't exist yet.

**Comment by mydigitalself** [comment]
Fair enough, well that's noted in the comments now. Having a ticket that
covers such a huge range of scope isn't really helpful for bug management ;)

**Comment by RReverser** [comment]
@mydigitalself Makes sense :)

**Comment by boopathi** [comment]
:+1:  Waiting for the windows phone app!

**Comment by AbdealiJK** [comment]
I'm eager for the windows phone app too !

**Comment by wassim-azirar** [comment]
I'm working on a application for Windows Phone 8 XAML. 
The app is open source and called [GitterClient](https://github.com/wassim-azirar/GitterClient).

As for know you can :
- Get the list of channels
- Join a channel
- Send a message

I'm going to realese more features in the next 2 (or 3) weeks.
You are welcome to contribute to this project.

**Comment by SuperJMN** [comment]
When it's it going to be released to the Store? Thank you 😊!

**Comment by mydigitalself** [comment]
@Odonno is working on one, wpbeta.me/modern-gitter

**Comment by wassim-azirar** [comment]
I stopped working in this project.
@Odonno has made a great progress. Yiu chat with him at :
https://gitter.im/Odonno/Modern-Gitter

**Comment by Odonno** [comment]
@mydigitalself @wassim-azirar Thank you guys ! 

Indeed, the app is now fully functional. I will release it soon and I hope to improve it as far as I can, communicating with the awesome Gitter team.

And for those who could read this message, Modern Gitter will support Windows 10 as soon as the App Store submission is open.

**Comment by Odonno** [comment]
And here it is, Windows Phone app is now released here https://www.windowsphone.com/fr-fr/store/app/modern-gitter/05dc3195-9dc2-4a91-9531-5d451e6e706e
