### ISSUE TITLE
Better auto-linking error message in private chats (was: doesn't work for pull requests)

### ISSUE THREAD

**Issue by iangilman** [gitterHQ/gitter#493]
When you type `#550` or whatever, it automatically makes a link to that issue, which is awesome. However, if `#550` is a pull request, the link doesn't work, since it assumes it's an issue. Would be sweet if it could tell the difference (presumably by asking the GitHub API).

**Comment by trevorah** [comment]
Hmm, I cant seem to reproduce this. It works for me:
![screen shot 2015-01-09 at 12 34 21](https://cloud.githubusercontent.com/assets/298742/5679775/25e6f61e-97fc-11e4-9e16-03e97e495bf4.png)

Is your message with `#550` in it still broken?

**Comment by iangilman** [comment]
Aha... my mistake... it's not issues vs. pull requests, it's when you're chatting with someone privately. Here's what happened: 

1. I was chatting with someone in https://gitter.im/openseadragon/openseadragon and we were discussing issues, and of course the issue links were working just fine.
1. We wanted to discuss more in-depth, so we started a private conversation and continued to discuss issues and PRs. 
1. In our private conversation, the PR link was broken. 

I now realize that Gitter has no idea what project you're talking about in a private conversation, so of course it doesn't know which project you're referencing. 

So... maybe instead of giving you a broken link, it should somehow indicate that you can't reference issues by number in private conversations. This is an opportunity to educate the user on how to link to project issues from within a private chat. Speaking of which, it would be cool if you could do something like `openseadragon/openseadragon/550` to link to a project you're not in the chat room for.

**Comment by trevorah** [comment]
You can link to any issue/pr with `openseadragon/openseadragon#550` (this works in GitHub as well).

I agree with the idea that issue mentions without the repo prefix like `#550` in non-repo rooms should give a better error message though.

**Comment by iangilman** [comment]
Thanks for the corrected linking format; great to see that works.

So yes, I think the only action item here is a better message (showing the proper formatting for referencing repositories). I've edited the title (again) to reflect that.

**Comment by MadLittleMods** [comment]
Move discussion to https://github.com/gitterHQ/gitter/issues/757
