### ISSUE TITLE
/ commands auto-complete suggestion length

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#494]
The auto-complete list for the / commands uses a global auto-complete limit as used by @ mentions and # mentions. What this means is that the entire list of / commands doesn't display.

We should allow this limit to be optional such that all / commands display without impact the number of @ and # suggestions.

**Comment by waltfy** [comment]
I have changed the limit of the list to match the commands list length. We do have to be careful though, I still think we need a limit. Perhaps we can have a command such as `/help` that would list an explain all commands?
