### ISSUE TITLE
Notification banner doesn't let me scroll to new messages.

### ISSUE THREAD

**Issue by agauniyal** [gitterHQ/gitter#497]
Here's a screenshot : https://www.dropbox.com/s/f1tgvy752dp80en/Screenshot%202015-01-05%2010.10.14.png?dl=0

The upper green banner prevents scrolling to see new messages completely. Not even manual scrolling helps. They are completely blocked out.

**Comment by mydigitalself** [comment]
Hi, I don't quite understand the issue, the banner may cover a couple of lines of messages, but you shouldn't be prevented from scrolling.  Is it possible to capture a video of what you are experiencing if I'm not understanding something correctly?

**Comment by agauniyal** [comment]
No no , not the banner itself. Did you see the screenshot I have posted , Where I have posted in bold letters " Follow up if you ... " , and then " @/all ^ ". That's the last message i can access. But if you see carefully , there are 1 or 2 messages beneath that message that aren't being scrolled. The scrollbar on the side of chat still has some white space left below , that confirms this too.

**Comment by agauniyal** [comment]
![bug](https://cloud.githubusercontent.com/assets/7630575/5627658/699d7906-95c1-11e4-950b-46926edea123.gif)

**Comment by mydigitalself** [comment]
That's very weird indeed, what browser/os combination are you running?

**Comment by agauniyal** [comment]
Windows 8.1 x64 + Firefox 34.0.5 ( I guess latest ).

**Comment by agauniyal** [comment]
Not yet fixed , but I had deleted that repo so I haven't / will not be able to reproduce this for now.

**Comment by MadLittleMods** [comment]
Closing as we use a different banner now and I suspect this isn't an issue anymore.
