### ISSUE TITLE
iOS resolution on iPhone 6

### ISSUE THREAD

**Issue by brandenbyers** [gitterHQ/gitter#498]
Any chance you will be updating the iOS app for native iPhone 6 resolution soon?

I mentioned this on gitter.im/gitterHQ. In case you're not familiar with what I'm referring to, when not native for iPhone 6, everything is zoomed in and mildly pixelated to fit the screen. Here is what it looks like on my phone (if you see can't a difference, see other images below).

<img src="https://cloud.githubusercontent.com/assets/7098232/5617387/de7373be-94d3-11e4-8fb4-b2a8baf57117.PNG" width="330px" >

It may not seem like a big deal, but when every other app used is native resolution by now, it is a bit of an eye-sore to switch to an app that has a bigger and pixelated top bar and a bigger keyboard. Switching from retina to non-retina monitors is a similar experience. The gitter app looks great, so it would be nice to let that shine on the newer iPhones too!

Here is an example of the keyboard in the gitter app along with a comparison to the keyboard in any native resolution app (Messages app in this example).

<img src="https://cloud.githubusercontent.com/assets/7098232/5617441/79753596-94d4-11e4-97f3-b5ed6dc85e27.PNG" width="330px" > <img src="https://cloud.githubusercontent.com/assets/7098232/5617443/7f48732a-94d4-11e4-803f-4f333ca5d535.PNG" width="330px" >

**Comment by trevorah** [comment]
Thanks for raising this, I'll take a look at when we next do some ios work (probably https://github.com/gitterHQ/gitter/issues/281).

**Comment by trevorah** [comment]
This is now fixed with 2.1.1, which is now live. Thanks for pointing this out @brandenbyers!
