### ISSUE TITLE
Large chat topic obscures the first few chat messages.

### ISSUE THREAD

**Issue by hrj** [gitterHQ/gitter#502]
In [this room](https://gitter.im/radkovo/jStyleParser), the chat topic is huge and spills over several lines. My first few messages in the room were not visible, because they were obscured by the topic's div. I didn't realize that my messages were posted to the room and yet not visible. I ended up spamming the room by typing the message multiple times.

**Comment by trevorah** [comment]
And again:

![screen shot 2015-06-12 at 17 33 02](https://cloud.githubusercontent.com/assets/298742/8134704/34efbaaa-1129-11e5-8586-d76b766e6511.png)

**Comment by trevorah** [comment]
Looks like this has been fixed for good:
![screen shot 2015-11-10 at 15 20 40](https://cloud.githubusercontent.com/assets/298742/11066115/b69766fa-87be-11e5-9bf4-3b7c29da6198.png)
