### ISSUE TITLE
Avatar shrinking is inconsistant

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#506]
At the moment, large windows are like:
![screen shot 2015-01-09 at 16 34 22](https://cloud.githubusercontent.com/assets/298742/5683192/b78989bc-981d-11e4-9765-03a5098bc760.png)

So far so good. Small windows are like:
![screen shot 2015-01-09 at 16 34 49](https://cloud.githubusercontent.com/assets/298742/5683210/dec398ce-981d-11e4-80d4-e3ee2f62b120.png)

The avatars shrink, but the padding only changes for the chat input which breaks alignment and no space is saved for the chat items. Mobile is like:

![screen shot 2015-01-09 at 16 53 29](https://cloud.githubusercontent.com/assets/298742/5683489/3a06bcfa-9820-11e4-8090-1cbf6c3c2a7a.png)

Which is fine.

So to fix the the small web view, we can either:
1. Stop shrinking the avatars on small/mid size web view
2. Shrink the avatars as usual, but shrink the padding as well (like mobile)

My vote is for option 2 and remove more of the web/mobile discrepancies.

/cc @mydigitalself and @waltfy

**Comment by mydigitalself** [comment]
The expected behaviour should be 2, when I originally designed it, it was
exactly aligned with the shrunken padding.

**Comment by trevorah** [comment]
Looks like this has been fixed.
