### ISSUE TITLE
Clicking a link https://gitter.im/apps in chat breaking History API

### ISSUE THREAD

**Issue by zxqfox** [gitterHQ/gitter#507]
When I'm pressing this link it shows me 404 instead of opening new window. And when I reloading it — it shows me a page with app links. And after reload I pressing back button and nothing happens.

How to repeat:
- Write a `https://gitter.im/apps` in the chat.
- Click on it (bug n. 1)
- Reload page (Ctrl/Cmd+R)
- Press back button (bug n. 2)

Feels like a router bug or something.

Expected:
On the `/apps` should be page with apps instead of 404 (user not found?)

**Comment by MadLittleMods** [comment]
Not sure when this was fixed but `https://gitter.im/apps` now opens in a new page.

Also using the "Get Gitter Apps" link under the user dropdown acts just fine.

**Comment by zxqfox** [comment]
Thanks! ;-)
