### ISSUE TITLE
Post integrations notification in chat space too

### ISSUE THREAD

**Issue by agauniyal** [gitterHQ/gitter#508]
Integration notifications such as from github , travis etc , that are usually shown in activity feed often remain unseen , so let the integration message appear once at their time of initiation on the chat feed too. They could be styled like 'code' to make them appear distinct. Or atleast provide an option to do so?

**Comment by mydigitalself** [comment]
We used to do them this way but they annoyed most people as they are often entirely out of context with the conversation. Some rooms where there's a lot of activity just became a mess and it ruined the conversations.

We will consider making this an option in the future though as part of an overall revamp of integrations, so going to close this issue.

**Comment by smecsia** [comment]
We would love to see this feature as an option too. Current implementation is very imperceptible, so for now we have to use Slack. Do you have any plans to implement this?
