### ISSUE TITLE
The archives on our free private channel #bullgit does not work

### ISSUE THREAD

**Issue by 0x04** [gitterHQ/gitter#511]
> @mydigitalself Unless the org is on a paid plan, you'll only get 2 weeks of history

But we have absolute no history:
![](http://puu.sh/erj1X/269aa6e7fd.png)

**Comment by mydigitalself** [comment]
Can confirm this is an issue, will look to fix it by next Monday.

**Comment by mydigitalself** [comment]
Actually, just found this was already reported, so closing this ticket in favour of #386
