### ISSUE TITLE
Add a "bookmark" feature

### ISSUE THREAD

**Issue by jdanyow** [gitterHQ/gitter#516]
It would be nice if there was a way to bookmark comments in a conversation so they can easily be referred back to later on.  

Here are some thoughts on what this would entail:
* a way in the conversation UI to add a bookmark, possibly with a name but maybe automatic name by default.
* a way in the conversation UI or sidebar to view/search/edit/click the list of bookmarks
* list of bookmarks should show the bookmark name and possibly the date/time the bookmarked content was written.  Maybe the author too.
* clicking a bookmark would scroll the conversation UI to the bookmark.
* hovering over the bookmark might display a popup containing the bookmarked piece of the conversation as well as some of the surrounding conversation.

**Comment by nateritter** [comment]
+1

**Comment by MadLittleMods** [comment]
A bit related to #365.

:+1:

**Comment by MadLittleMods** [comment]
Move conversation #365
