### ISSUE TITLE
Change to app login flow

### ISSUE THREAD

**Issue by saibotsivad** [gitterHQ/gitter#519]
When I first launch the Mac desktop app, it starts what appears to be a sandbox browser and asks for my Github login credentials.

This makes me nervous, because I don't know who I'm actually giving my credentials to. (E.g., from a security perspective there's no URL present, and the sandboxed browser is unknown to me.)

It should be possible to have the login process go to the github page in the users browser of choice, so that they are not forced to trust an app with their login credentials.

**Comment by taion** [comment]
:+1:

This is keeping me from using the Mac app.

**Comment by drichardson** [comment]
+1

**Comment by saibotsivad** [comment]
At my workplace today we got into a lengthy discussion about this topic when we started using some other application which uses a similar login flow. The discussion brought up two links which I'll share here:

* In case you don't understand the security concern, read this article. Stealing passwords via oauth and the native web is [pretty trivial](http://welcome.totheinter.net/2011/01/12/stealing-passwords-is-easy-in-native-mobile-apps-despite-oauth/).
* Even the oauth wiki [lists it as a concern](http://wiki.oauth.net/w/page/27249271/OAuth%202%20for%20Native%20Apps) (See under "embedded browser > cons" the item "user still enters credentials in native app").

Note that we don't have this issue at my workplace--our services are all available via a browser, so normal browser oauth flow is possible.

**Comment by trevorah** [comment]
@saibotsivad even if we displayed the github oAuth url, would you trust it? Or is that just security theatre?

The mechanism of using a one time only token for logging in via a third party is a great idea, and thankfully it already exists. I would suggest using github's [two factor authentication](https://help.github.com/articles/about-two-factor-authentication/).

**Comment by drichardson** [comment]
@trevorah I think you misunderstood the problem. It has nothing to do with the URL being displayed. The core issue is that the gitter application is the one collecting the credentials and has the ability to see them in the clear.

This request isn't simply about asking gitter to show a github URL. As you point at, that would prove nothing. The request is that the oauth flow goes through a web browser, which, presumably, we trust since we're entering credentials into it all the time.

Two factor authentication does nothing to resolve the issue of credential visibility to the app.

**Comment by taion** [comment]
I'm very much in agreement with what @drichardson says above.

**Comment by saibotsivad** [comment]
@trevorah I believe that the [first link](http://welcome.totheinter.net/2011/01/12/stealing-passwords-is-easy-in-native-mobile-apps-despite-oauth/) I shared explains the problem pretty well.

The issue is that the login process is occurring in an embedded browser, which makes the credentials visible to the third party.

One of the main purposes of OAuth is to never expose your username/password to a third party. E.g. on a normal website login, you would get kicked over to the OAuth providers website to sign in. Since the third party does not have access to that window, they cannot intercept the users credentials, and the user can be confident that the third party only has the authorization given them.

However, if a user enters their login credentials into an embedded browser, the third party has access to the window and can inject middleware via JS or other means, and therefore when the user enters their credentials into the embedded browser they do not know if the third party had access to those credentials.

**Comment by saibotsivad** [comment]
One applicationI use that does things differently is [trailer](https://github.com/ptsochantaris/trailer) (desktop github notifications), which uses token access instead. It links to the Github "New personal access token" page, where the user generates a token that they then paste into the app, and the app then uses that token.

The page it links to is this one https://github.com/settings/tokens/new but I noticed that you can link to that page and also set specific scopes, if needed, e.g. https://github.com/settings/tokens/new?scopes=user:email,write:org

I don't know that this is necessarily a great option, since it requires a lot of clicking around (e.g. non-technical people would probably not use it), but I think most people who use Github would be comfortable with it.

**Comment by MadLittleMods** [comment]
> the @gitchat login page could be the perfect github pishing page....
> ![](https://pbs.twimg.com/media/Ci8BYPTUUAUlgr8.jpg)
>
> [*source @bumi*](https://twitter.com/Bumi/status/733806781500035072)
