### ISSUE TITLE
Pleeeeeeease. Stop replacing code quotes with literature quotes.

### ISSUE THREAD

**Issue by trusktr** [gitterHQ/gitter#521]
Gitter is for discussion on code libraries, not literature. Can you guys `pleeeeeeeeaaaase` stop replacing `"` with `“` and `'` with `‘`? It making it super bothersome to write and edit code. Thanks!

**Comment by suprememoocow** [comment]
We don't do quote substitution, but OSX has a setting which will enable this (and we can't change). Here's how to turn it off: (Disabling smart quotes in Mavericks)[https://derflounder.wordpress.com/2014/02/01/disabling-smart-quotes-in-mavericks/].

If you're running the Gitter OSX App, you can toggle it from Edit | Substitutions | Smart Quotes

**Comment by trusktr** [comment]
Wow, thanks!
