### ISSUE TITLE
Left column expands when focusing on chat message box

### ISSUE THREAD

**Issue by freshlogic** [gitterHQ/gitter#522]
http://cl.ly/2X350p370M2n

**Comment by waltfy** [comment]
@freshlogic what is your use case? — If you're searching, when you lose focus of the search box and the search input is clear we simply collapse it again.

**Comment by freshlogic** [comment]
I leave Gitter running all day on a smaller 3rd monitor. I don't need the left column at all, but I want to see things in the "Activity" section.

Basically I need some way to collapse the left column while always having the right column be open.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/296

**Comment by MadLittleMods** [comment]
This is no longer a problem.
