### ISSUE TITLE
share copy button hover state is pink

### ISSUE THREAD

**Issue by samccone** [gitterHQ/gitter#523]
![](http://dl.dropbox.com/u/36928599/Screenshots/0o~.png)

**Comment by samccone** [comment]
:pig:

**Comment by waltfy** [comment]
Thanks @samccone!

**Comment by waltfy** [comment]
Hi @samccone, what browser were you using? Also, do you have Flash installed? We use [zeroclipboard](http://zeroclipboard.org/) which relies on Flash. :see_no_evil:

**Comment by samccone** [comment]
This is in the embedded app, so safari I suppose (unless you guys switched to NWK .. then chromium) And yep I do have flash. :moneybag:

**Comment by waltfy** [comment]
We are in the process of switching to `NW.js` (former `NWK`) soon, so I'll see if I can reproduce this issue there.

**Comment by mydigitalself** [comment]
Sam we can't reproduce this and we're switching over to NWK, so we'll just close this yo.

**Comment by samccone** [comment]
kk :+1:
