### ISSUE TITLE
Search results are missing actual text

### ISSUE THREAD

**Issue by QuLogic** [gitterHQ/gitter#525]
When you do a search in the sidebar, there is some context information for each match. The text around the match is shown normally, and there is an `<em class="highlight">`, but the `em` is empty, so you don't actually see the highlighted text.

See attached image, searching for "welcome", and clearly a whole bunch of people are saying "you're welcome", but all you see is "you're":
![screenshot from 2015-01-18 19 25 52](https://cloud.githubusercontent.com/assets/302469/5794704/d617b12a-9f47-11e4-8a2a-33a95e4963a6.png)

**Comment by malditogeek** [comment]
Hey @QuLogic 

That's really strange... can you please provide some more details? Browser, OS, platform.

It's working for me:

![screen shot 2015-01-19 at 00 32 39](https://cloud.githubusercontent.com/assets/14751/5794743/8133f278-9f73-11e4-8c4c-281b2b8530c4.png)

If your browser supports extensions, try disabling them and see if the problem persists. I suspect it might be an invasive extension.

**Comment by QuLogic** [comment]
Firefox 35.0 on Fedora 21. I restarted with add-ons disabled, but that did not fix it.
