### ISSUE TITLE
Integrations dialog does not open in desktop clients and pops new browser tab

### ISSUE THREAD

**Issue by brixen** [gitterHQ/gitter#526]
I attempted to set the Integrations on the rubinius/rubinius room in the OS X client, but the dialog would not display. I was able to set the Integrations through the browser web interface.

**Comment by MadLittleMods** [comment]
I experience the integrations option in the dropdown opening a new tab in the browser (both old and new mac app)

**Comment by MadLittleMods** [comment]
This is as expected and much easier to handle it this way for some of the integrations that need oauth authentication such as GitHub. It also isn't as nice to sign in and use your other accounts credentials inside the desktop app frame from a security standpoint.
