### ISSUE TITLE
Ok, so I was lazy. Why punish me?

### ISSUE THREAD

**Issue by bmcorser** [gitterHQ/gitter#528]
I clicked the "badge me, bro!" button and a my `README.md` got a badge inserted. Thing is, I use `README.rst` for compatibility with PyPI (and so, probably, do many Python developers) so there was no `README.md`.

GitHub supports both Markdown and rST, but prefers Markdown.

Upshot is my nice, detailed readme got replaced by one that was empty except for a Gitter badge. It was most distressing: https://github.com/bmcorser/bade/commit/7c11e4d09d1a3de3747ee1703e8e3f185a0ca42f

Auto-badging by PR is a nice idea. Why not support rST too?

**Comment by mydigitalself** [comment]
Thanks for the most awesome issue submission ever. 

Will look to add support for `README.rst` in the very near future.

**Comment by bmcorser** [comment]
Haha, no problem. I felt like writing something so I was on the hunt for the badger's repo ... but it's not open-source?

**Comment by gitter-badger** [comment]
@bmcorser My rst support should be live in the next day or so.

Also, you were right to question the open-source nature of my internals. They should be open-source! So here they are: https://github.com/gitterHQ/readme-badger. 

Hooray for badgers!

**Comment by bmcorser** [comment]
The badger seems to know about rST now, but it picked the second heading:

https://github.com/bmcorser/git-little-picture/pull/1/files

So I wrote some JS!

https://github.com/gitterHQ/readme-badger/pull/1
