### ISSUE TITLE
Cannot access Github domain via browser when Running Gitter Chrome App

### ISSUE THREAD

**Issue by ESOComputing** [gitterHQ/gitter#529]
I just started using the Gitter Chrome app on my Windows 7 laptop the other day and rather like it. However, whenever I have it open chrome won't open any sites hosted on the github domain. I cannot go to github or gitter either. All other websites are accessible. This only effects connectivity to the GITHUB server in the Chrome Browser. Github is still accessible within other browsers while running the app. The same thing occurs when running the Gitter app on Chromium-Browser within Linux. All other sites are fully accessible.

**Comment by mydigitalself** [comment]
Hi,

We're actually going to discontinue the Chrome App in favour of a Windows app. There's a beta available at https://github.com/gitterHQ/desktop

Mike
