### ISSUE TITLE
Collapse/Pause all gifs (option)

### ISSUE THREAD

**Issue by iancrowther** [gitterHQ/gitter#535]
would be cools to be able to collapse all in on click

**Comment by mydigitalself** [comment]
Dude... /collapse :)

**Comment by iancrowther** [comment]
oooo sweet :cake:

**Comment by mydigitalself** [comment]
Sorry, I was entirely incorrect about this, it just collapses the last one.

**Comment by MadLittleMods** [comment]
This has been implemented `/collapse-all`

Closed in favor of https://github.com/gitterHQ/gitter/issues/668
