### ISSUE TITLE
Allow messages to directly reference (reply to) other messages

### ISSUE THREAD

**Issue by Elusive138** [gitterHQ/gitter#536]
This depends on permalinks as requested in #48.

The idea is to allow messages to optionally specify another message to reply to, which then allows users to follow the reference. This helps keep track of conversations and replies when there are many different conversations in parallel in the same room, possibly spread over a long time period.

An example implementation is the Stack Exchange chat. Over there, there's an arrow to the right of every message that inserts a `:messageid ` into the textbox when clicked. Posting a message with that ID there will cause it to contain a reference to the message replied-to, as in [this example](http://chat.stackexchange.com/transcript/message/19670650#19670650) - this gets rendered as an arrow (and automatic `@name`) that takes you to the permalink of the replied-to message when clicked (or scrolls up to it if it's still in scope).

We have used the SE replies to great effect while carrying out multiple conversations at the same time in the same room - something similar in gitter would be great.

**Comment by allquixotic** [comment]
+1

**Comment by quintesse** [comment]
Isn't this already implemented? If you do Alt+click on the timestamp of a message a link to that message is inserted in your text box.

**Comment by Elusive138** [comment]
The implementation of #48 also included quoting/reply functionality (that was fast! thanks, gitter team!). It doesn't auto-ping the replied-to user, but that's easy enough to do manually (and might be a good thing).

@quintesse It wasn't at the time of issue creation. It is now.
