### ISSUE TITLE
Twitter plugin renders tweet content as markdown

### ISSUE THREAD

**Issue by samccone** [gitterHQ/gitter#539]
![screen shot 2015-01-23 at 7 28 44 pm](https://cloud.githubusercontent.com/assets/883126/5885184/2dc0fd36-a336-11e4-8ef9-d698f3a316b3.png)

sorry for breaking stuff :(

**Comment by mydigitalself** [comment]
Ah, have you built some sort of custom Twitter webhook whatsit?

**Comment by samccone** [comment]
Staticshowdown does 🎄

**Comment by malditogeek** [comment]
@samccone is the code available somewhere? Everything in the Activity tab is considered markdown, so maybe adding a `>` in front for the tweet content will solve it.

**Comment by samccone** [comment]
looks like they fixed it. thought it was something you guys provided. 

:ship:

**Comment by mydigitalself** [comment]
@samccone where did you find this thing, would love to have a play

**Comment by mydigitalself** [comment]
Ah, I see, it's in their room... got it.
