### ISSUE TITLE
Do the hubot adapters for Gitter still work?

### ISSUE THREAD

**Issue by gep13** [gitterHQ/gitter#540]
Hello,

I have been trying to use both this:

https://github.com/kcjpop/hubot-gitter

and this:

https://github.com/huafu/hubot-gitter2

on a Heroku app that I have deployed.  Does anyone know if either of these still work?  I can see log messages from the adapter when I do ```heroku logs``` but I never get a response from the bot.

Any ideas on what I can do to fault find this, or validate what is going on?

Thanks!

**Comment by gep13** [comment]
As requested, here is some more information...

These are the commands I have issued:

```
heroku login
cd C:\heroku
mkdir chocobot
cd .\chocobot
yo hubot
npm install --save hubot-gitter2
git init
git add .
git commit -m "Initial commit"
heroku create
heroku config:set HUBOT_GITTER2_TOKEN=***
heroku config:set HEROKU_URL=https://protected-taiga-1464.herokuapp.com
heroku config:set HUBOT_GITTER2_TESTING_ROOMS=chocolatey/choco
git push heroku master
```

And once it is running, I can see the following in the call to ```heroku logs```:

![image](https://cloud.githubusercontent.com/assets/1271146/5888442/c5bd47a0-a3f6-11e4-9495-d81b34ea366d.png)

And from looking at the source code for the adapter, I can see that this marries up with some of the log statements, so I know at least "something" in the adapter is running.  However, when I try to do either ```hubot ping``` or more correctly ```chocobot ping``` in the chat room, I get nothing back, but I do see some additional log messages:

![image](https://cloud.githubusercontent.com/assets/1271146/5888452/1313a526-a3f7-11e4-9d6a-b4906b89152f.png)

So it appears to be that the adapter is listening, but I never get a response.

Any ideas?

**Comment by gep13** [comment]
And here is me running it locally:

![image](https://cloud.githubusercontent.com/assets/1271146/5888466/846f57ec-a3f7-11e4-802a-395878ba1cbe.png)

**Comment by mydigitalself** [comment]
What GitHub user underpins that account? Do you maybe want to try and add him to my test room mydigitalself/thoughts ?

**Comment by gep13** [comment]
The personal access token that I am using, for testing purposes just now, is my own one.  Sure, let me jump into that room.

**Comment by gep13** [comment]
@mydigitalself Ok, I have no idea what to say here...

I have just been through all the above steps again this morning, and I can happily report that it now seems to be working:

![image](https://cloud.githubusercontent.com/assets/1271146/5890996/75f3ee7c-a473-11e4-9be7-cb75bfa52ea1.png)

Thanks for your help!

**Comment by mydigitalself** [comment]
Hah! Hate it when that happens. Glad you got it working.

**Comment by gep13** [comment]
Thanks! We have started going a little nuts now as well, adding loads of additional scripts :smile_cat:
