### ISSUE TITLE
latex macro $$\partial$$ not recognized

### ISSUE THREAD

**Issue by ketch** [gitterHQ/gitter#541]

**Comment by mydigitalself** [comment]
We use KaTeX for this (https://github.com/Khan/KaTeX), it may well be an issue there, we can try to investigate, would you be able to send an example input with expected output please?

**Comment by ketch** [comment]
Sure; it is a standard symbol used for partial derivatives.  The input is simply $$\partial$$ and the result should look like this: 
![image](https://cloud.githubusercontent.com/assets/697763/5904696/6c1a7690-a59b-11e4-8c72-32072a41c3fb.png)

**Comment by mydigitalself** [comment]
@suprememoocow I get this:

KaTeX parse error: Expected 'EOF', got '\partial' at position 8: \partial̲: \partial

And now I'm out of my depth.

**Comment by dcsan** [comment]
I'm new to Latex and just trying some very simple inputs, 

` $$ \today $$ `

gives

> KaTeX parse error: Expected 'EOF', got '\today' at position 6: \today̲: \today

**Comment by MadLittleMods** [comment]
I just tested `$$\partial$$` and it results in the correct partial symbol mentioned above.

I am not sure what is happening with @dcsan example `$$\today$$`

**Comment by mydigitalself** [comment]
I'm not sure KaTeX supports \today - is that a valid latex macro?
https://github.com/Khan/KaTeX/releases
