### ISSUE TITLE
Allow Images/GIFs to be hidden

### ISSUE THREAD

**Issue by ferventcoder** [gitterHQ/gitter#542]
This is similar to hiding an image in hipchat. 

When shown there is a place on the right to hide it:
![image](https://cloud.githubusercontent.com/assets/63502/5892712/85de67ac-a48e-11e4-9a2f-37a11a332ac9.png)

And when hidden, appears like this:
![image](https://cloud.githubusercontent.com/assets/63502/5892717/af0efcea-a48e-11e4-87ff-30307dea3a5e.png)

**Comment by gep13** [comment]
:+1:

**Comment by ferventcoder** [comment]
This may already be done!

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/5893463/0e730d04-a4ab-11e4-8970-a443fcc595b6.png)

**Comment by ferventcoder** [comment]
Sometimes you just have to look around.
