### ISSUE TITLE
API endpoint to check for a room's existence and create/join permissions

### ISSUE THREAD

**Issue by svincent** [gitterHQ/gitter#544]
**User Stories**

* As a 3rd party developer, I want an endpoint that I can use to check if a room exists so that I can a tool that signals to an end user whether or not the resource exists.

* As a 3rd party developer, I want to check if I have permissions to join/create a room without joining/creating it so that I can create a tool that accurately signals what actions the end user can perform.

---

**Background**

I'm currently taking a crack at #222 (Gitter browser extension) and I'm running a problem: as far as I can tell I can't check if a room exists without first attempting to join it. Joining a room to test existence a couple problems.

1. This creates unnecessary load on the service and potential spam in that each check would have the user join and (if necessary) leave the channel to see if it exists.
2. If the user has permission to create the channel, the channel will be created in the event that it doesn't exist. ([Join a Room](https://developer.gitter.im/docs/rooms-resource#join-a-room))
3. Problem 2 is complicated by the user's inability to delete a room (#218)

I'd like to have my browser extension hit a single endpoint to see if a) the room exists and b) what the user's permissions are for the room. Ideally, this would also support application-level requests (#543).

**Comment by svincent** [comment]
I spoke with @mydigitalself a bit and he proposed a simple workaround: send a GET request to bitter.im for the room. I experimented with this a little and observed the following:

* Returns `200` for correctly cased, public rooms/orgs
* Returns `302` for incorrectly cased, public/private rooms/orgs. Response also includes a `Location` header with the correctly cased path
* Returns `401` for private rooms, nonexistent rooms

**Comment by MasseGuillaume** [comment]
you can also use HEAD to avoid receiving the content of the request:

` curl --head https://gitter.im/gitterHQ/developers`

**Comment by MadLittleMods** [comment]
You can check if a room exists with `POST /v1/rooms` with `{ "uri":"gitterhq/sandbox" }`, https://developer.gitter.im/docs/rooms-resource#join-a-room
