### ISSUE TITLE
How to disable emails

### ISSUE THREAD

**Issue by trusktr** [gitterHQ/gitter#553]
but keep in-app notifications?

**Comment by mydigitalself** [comment]
There's an unsubscribe link towards the bottom of the email notifications.

**Comment by trusktr** [comment]
@mydigitalself I believe I clicked on that link, and it took me to the settings for the specific chat room.

I want to disable emails for *all* rooms entirely. Can that be done?

**Comment by mydigitalself** [comment]
Yes. Look further down. There's a link that says unsubscribe from all.

**Comment by trusktr** [comment]
Ah, thanks, I missed it.

**Comment by du5t** [comment]
For reasons of accessibility and compatibility with email clients, I highly recommend you guys include a non-HTML unsubscribe link, as it does not appear in plain text components of the email. This may be an intercom.io issue, but it falls to the user to dig through the email source if they haven't an HTML render of the email body--not exactly an enjoyable or convenient process.

**Comment by MadLittleMods** [comment]
@du5t Can you create a separate issue to add a unsubscribe link to the plain text email?
