### ISSUE TITLE
accessing a private organisation room

### ISSUE THREAD

**Issue by nmcb** [gitterHQ/gitter#554]
This may be a newbie question instead of an issue.

I'm trying to access a private organisation room, being one of the owners, but gitter tells me that I don't belong to the organisation.  "You've tried to access act-genomically's private organization room and you do not belong to this organization". Am I missing something?

Thanks,
[nmcb](https://github.com/nmcb)
[act-genomically](https://github.com/act-genomically)

**Comment by troupe-admin** [comment]
Can you send a screenshot of what are you seeing please?

**Comment by nmcb** [comment]
Sure, from the gitter client; the gitter site displays the same error.

![screen shot 2015-02-01 at 23 01 33](https://cloud.githubusercontent.com/assets/1698211/5994061/4d88c7c0-aa66-11e4-9210-a153cebb5f5c.png)

**Comment by troupe-admin** [comment]
Hmm, indeed. Will investigate, thanks.

**Comment by mydigitalself** [comment]
Can't understand why this would happen, I can see the room exists, so that's not the issue.

Do you know what sort of permissions you have in that org, and do you know, perhaps if that org has turned this on recently by any chance? https://github.com/blog/1941-organization-approved-applications

**Comment by nmcb** [comment]
Yup, it is a new organisation, just setting it up since last week.  I did setup the organisation to:

1. Restrict applications on organisation level, though approving Gitter for public repos.  
2. Added the Gitter service to a _private_ repository (with a Gitter integration token).

See both 1 and 2 in the screenshots below. I would be most happy to get the organisation chat room working, but falling back on the private repo chat room is feasible as a workaround for the moment.  Currently we're working from only one private repo.

Thanks for your support, hope this helps,
~nmcb

![screen shot 2015-02-02 at 13 26 37](https://cloud.githubusercontent.com/assets/1698211/6000627/470fcb62-aae0-11e4-833e-12d649b0989f.png)

![screen shot 2015-02-02 at 13 34 16](https://cloud.githubusercontent.com/assets/1698211/6000631/4d688918-aae0-11e4-87c7-116853417380.png)

**Comment by mydigitalself** [comment]
Have you granted us private repo access on your personal account previously?

http://cl.ly/image/2X130V121b2W

From: https://github.com/settings/applications

**Comment by nmcb** [comment]
You fixed it. 

I already granted private repo access on my personal account, but i needed to "extend" the private repo access and grant gitter access to the organisation's private repos as well.  Thanks for helping me to the right configuration!

![screen shot 2015-02-02 at 15 03 34](https://cloud.githubusercontent.com/assets/1698211/6001740/2b8c4688-aaed-11e4-86fc-6f18524bc8ae.png)

**Comment by mydigitalself** [comment]
No problem, glad you got it sorted out. Enjoy!
