### ISSUE TITLE
iPad support for iOS app

### ISSUE THREAD

**Issue by rhukster** [gitterHQ/gitter#559]
Excuse me putting this here.  Not sure if there is a better location.

I would just like to make a request for iPad support in the iOS app.  Great that you have iPhone support, but iPad is just a better device for this kind of thing, and it's quite clumsy in Safari compared to the native app.

**Comment by gordonwoodhull** [comment]
+1

**Comment by rickydazla** [comment]
:+1:

**Comment by dictav** [comment]
:+1:

**Comment by totai** [comment]
:+1:  :+1:

**Comment by olezko46** [comment]
+1

**Comment by ukudala** [comment]
@trevorah 
Hi Gitter team - voicing support for iOS 9 multitasking

**Comment by meatballs** [comment]
:+1:

**Comment by AlfonsoUceda** [comment]
:+1:

**Comment by nlutsenko** [comment]
Taking into account that iOS p and OS X apps are there - iPad support should be trivial. 
Is there an open source repo for iOS app that I missed?

**Comment by MadLittleMods** [comment]
@nlutsenko The iOS app is not open source at the moment.

**Comment by bsungur** [comment]
:+1:

**Comment by rhukster** [comment]
Still no movement on this? It's been a year since I originally posted this. Your iPhone app is pretty solid, it's really shouldn't be that much extra work to develop an iPad view :)

**Comment by rickydazla** [comment]
Looks especially silly on iPad Pro!

**Comment by davidradkowski** [comment]
Still no joy 😔

**Comment by trevorah** [comment]
It's on its way:
![simulator screen shot 24 may 2016 18 20 05](https://cloud.githubusercontent.com/assets/298742/15513676/9b956b2c-21dd-11e6-8c22-349e69891dfe.png)

**Comment by rhukster** [comment]
looking forward to it!! 👍

**Comment by trevorah** [comment]
It should be live now as v3.4.0. If you like it, please leave us a nice review in the app store 😊
