### ISSUE TITLE
Mobile app data usage

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#560]
Investigate as reported by @billbonney

**Comment by trevorah** [comment]
> What’s up with Gitter’s data usage. If I enable it to use cellular data on my iPhone, it eats data like candy. I went from 8% usage on a 2GB plane to 24% is <24hrs.

**Comment by billbonney** [comment]
When i looked at the stats, it said only 3.1MBytes, but another app (my own, d'oh) was at 480MB and  I am not sure why. I've disabled the bad one, and reenabled Gitter. I'll report back in 24Hrs to see usage. Hopefully this was a non-issue. Thx

**Comment by billbonney** [comment]
it's 6.6MB after ~24Hrs on cellular data only. I'll run for the next week and keep an eye on it (but will have WiFi on as well wheat home)

**Comment by billbonney** [comment]
Ok, so after weeks work of use, it doesn't seem to be an issue. I'll keep an eye on it. recommend closing for now. Thx
