### ISSUE TITLE
Last message occasionally end up in text field on reload

### ISSUE THREAD

**Issue by tjconcept** [gitterHQ/gitter#561]
(opened issue as requested in #61)

**Comment by tjconcept** [comment]
Observed: it's not always the last message that gets inserted.

**Comment by trevorah** [comment]
Sorry I missed this!

I've never seen this behaviour before. Is it your own message? We store a message draft in localstorage so that if you reload or navigate away and back, your text field is repopulated with the draft. When you send the message, the draft *should* be wiped.

This could be something to do with firefox on linux and its slow localstorage. Are you using firefox on linux?

**Comment by tjconcept** [comment]
Yes, it is my own messages, and I also run Firefox on Linux (Ubuntu, utopic).

Slow localstorage? I haven't heard about that?

**Comment by trevorah** [comment]
Yeah, its a weird one. It could be unrelated though. Next time this happens, could you attach the contents of your localstorage please? The relevant entries should be the ones prefixed with `drafty_`.

**Comment by tjconcept** [comment]
Sure it's pretty frequent. Also, it resets the scroll position higher than I actually left it.

**Comment by tjconcept** [comment]
I am now able to reproduce this consistently, but I am not sure it is the exact same issue though. It might be a combination.

1. Go to any room where you have left a message withing 10 minutes (edit threshold)
2. Click arrow up key (brings recent message into text area)
3. Hit <kbd>ESC</kbd> (closes text area)
4. Navigate to any other room
5. Navigate back to former room

The message I edited now appears in the text area at the bottom each time I navigate to this room. The only way to fix it, is to manually delete it.

From another programmers view it seems the <kbd>ESC</kbd> is not doing as much cleanup as it should.

The local storage looks like this:
![debug](https://cloud.githubusercontent.com/assets/801895/6430550/69883c44-c00f-11e4-8c2c-9bfeddd745bd.png)

**Comment by trevorah** [comment]
@tjconcept good spot!
