### ISSUE TITLE
Changing to suggested rooms results in a 404

### ISSUE THREAD

**Issue by jrmd** [gitterHQ/gitter#567]
Lets say im on the laravel room so the url is `/laravel/laravel` if i change room it will result in a 404 because the url would be like `/laravel/user/repo` (user and repo are placeholders)

**Comment by mydigitalself** [comment]
Hey, few questions:
1) What browser/platform
2) Have you refreshed/reloaded Gitter entirely recently, there were some patches today that went out that addressed a similar issue.

**Comment by jrmd-** [comment]
OSX Yosemite, Chrome

And i have refreshed and just checked and its still an issue

**Comment by mydigitalself** [comment]
Ah right, thanks for the clarification, was trying to reproduce and was scratching my head. 
@suprememoocow

**Comment by MadLittleMods** [comment]
The [new left menu has rolled out](http://blog.gitter.im/2016/05/12/a-new-look-for-gitter/) and the "Your Suggestions" section works properly
