### ISSUE TITLE
Mac app in fullscreen mode (10.10) - Following creates an unremovable black Space

### ISSUE THREAD

**Issue by bloomingbridges** [gitterHQ/gitter#570]
I use the native client in fullscreen mode (aka on a different virtual desktop) to keep the noise to a minimum. Today, someone posted an inline tweet, which comes with a follow button. Upon pressing that button two things happen:

1) The respective link gets opened in my browser window
2) The app creates another fullscreen window, showing nothing at all and refusing to close as long as the client is running (see images attached).
![screen shot 2015-02-11 at 15 11 59](https://cloud.githubusercontent.com/assets/1463168/6148330/e1aa19da-b200-11e4-8395-a0b01eee2f1d.png)
![screen shot 2015-02-11 at 15 12 14](https://cloud.githubusercontent.com/assets/1463168/6148332/e6ca93ea-b200-11e4-884d-f81336d68b64.png)

**Comment by MadLittleMods** [comment]
With the old Safari mac app, I can't reproduce exactly this.

When I have the old app fullscreened and click the "Follow" button, it creates a new empty white window that will close without any issues. It does also open the link in the primary browser.

With the new nw.js app, this isn't a problem and just opens up in a primary browser as expected. Stay tuned for the next release.
