### ISSUE TITLE
Source high-lighting is incorrect

### ISSUE THREAD

**Issue by quintesse** [gitterHQ/gitter#571]
For example for our language Ceylon the following code in GitHub looks like this:

```ceylon
shared dynamic AppInterface {
    shared formal void listen(Integer port, Anything() callback);
}
```

but on Gitter it looks wrong. What source high-lighter are you using? And can we help to get it up-to-date?

**Comment by mydigitalself** [comment]
It's highlight.js (https://github.com/isagalaev/highlight.js). Will investigate.

**Comment by lucaswerkmeister** [comment]
I believe isagalaev/highlight.js#825 would fix this issue.

**Comment by lucaswerkmeister** [comment]
It just got merged (speedy!), please update your installation :r

**Comment by lucaswerkmeister** [comment]
(hm, I guess we have to wait for the next release unless you build from hl.js sources…)

**Comment by mydigitalself** [comment]
Busy working on it now, under highlight.js 8.5.0 it's coming out like this: http://cl.ly/image/101R0m1c2R2n

previously, it was like this: http://cl.ly/image/2n1f0r2s1I2e

not entirely what the github result looks like, but certainly better?

**Comment by lucaswerkmeister** [comment]
I think the code was misidentified as another language… in Ceylon, the first word (`shared`) should be highlighted, and I didn’t define any special highlighting for method names (identifiers before opening parentheses, here: `listen`).

**Comment by lucaswerkmeister** [comment]
> I think the code was misidentified as another language…

Correction: highlight.js 8.5.0 doesn’t have Ceylon yet, it was released before it got merged.

**Comment by mydigitalself** [comment]
aha! that would explain it!

**Comment by mydigitalself** [comment]
will have to wait for the next release, we were behind because of a fork for a similar reason and would prefer to stay on their release cycle for the sake of sanity.

**Comment by lucaswerkmeister** [comment]
Version 8.6 was released a while ago, could you update now?

**Comment by mydigitalself** [comment]
It will be done in a few weeks time, unfortunately Highlight.js has some inefficiencies in it's automatic language detection - quite literally, it takes the code and attempts to highlight it against **every** known language and then ranks the scoring. This means we have to massage it into place a little and isn't a simple drop-in replacement.

**Comment by mydigitalself** [comment]
I'm going to close this issue because it's an ever-evolving beast.

**Comment by lucaswerkmeister** [comment]
Okay, sure.
