### ISSUE TITLE
Highlight messages that mention you

### ISSUE THREAD

**Issue by quintesse** [gitterHQ/gitter#572]
It would be nice if messages that `@mention` you would get a special back ground color to highlight them. That way they easily stand out when you are scrolling through long chats and/or the archives.

**Comment by PWKad** [comment]
Please take this on, I can't find the other issue around this that we mentioned before but it is very hard to find what the red @ symbol is referencing in very active rooms.

**Comment by MadLittleMods** [comment]
Currently `@mentions` will have a orange tinge but not on the whole message.The orange tinge goes away if you navigate away from that room and come back.

![](http://i.imgur.com/o7ItwWP.png)

**Comment by quintesse** [comment]
Yes, it's much better already, although still a bit easy to miss when you're scrolling a lot. And the new "mention" tag that pops up to take you directly to any messages that mentioned you and have scrolled of the page is great as well.

**Comment by PWKad** [comment]
From my perspective this issue is resolved, really like this feature.  Thanks a ton!

**Comment by MadLittleMods** [comment]
`@mentions` now have a orange tinge background and orange border on the right:

![](https://i.imgur.com/F5x7wey.png)
