### ISSUE TITLE
When clicking on the #gitterhq/gitter link on the user's home, the interface is duplicated inside the chat <iframe>

### ISSUE THREAD

**Issue by msikma** [gitterHQ/gitter#574]
I found this out by coincidence while looking for the support link. When on the user's home page, there's a link to [#gitterhq/gitter](https://gitter.im/gitterHQ/gitter). After clicking this link, the interface is [reloaded and duplicated](http://i.imgur.com/cuN71RR.png) inside of the chat `<iframe>`.

When linking to a chatroom in a chat message, the link seems to work fine. Only this link on the user's home doesn't seem to work as intended.

Chrome 40.0.2214.94, OSX 10.9.5.

**Comment by trevorah** [comment]
Confirmed. Looks like this is a failing part of the `#pretty` a-b test. Thanks for spotting this @msikma!

**Comment by suprememoocow** [comment]
Hotfix being deployed! Thanks for the report @msikma!

**Comment by msikma** [comment]
Very swift action, the best kind! :+1:
