### ISSUE TITLE
Issue #397 (IRC bridge does not always receive messages) is still reproducible

### ISSUE THREAD

**Issue by wedens** [gitterHQ/gitter#575]
https://github.com/gitterHQ/gitter/issues/397

**Comment by mydigitalself** [comment]
Hi, we've been investigating the situation for the past week and hope to have a solution shortly.

**Comment by adelbertc** [comment]
Just noticed there's a new ticket for this, posted on the old ticket [here](https://github.com/gitterHQ/gitter/issues/397#issuecomment-75112665).

Let me know if I can do anything on my end to help!

**Comment by rom1504** [comment]
I noticed the message coming from irc take a random amount of time to get to gitter, between 1 minute and 4 hours. That's a big problem, I can't use the irc bridge until it's fixed.

**Comment by OlegYch** [comment]
6697 seems to be dropping closing a lot, and i cant even login to it atm

**Comment by malditogeek** [comment]
:tada: The new [irc bridge](https://github.com/gitterHQ/irc-bridge) is finally in production. You can connect again to `irc.gitter.im` using SSL. This issue should be fixed. If you experience any other problems, open an issue at https://github.com/gitterHQ/irc-bridge
