### ISSUE TITLE
Transferred ownership of repository - channel disappeared

### ISSUE THREAD

**Issue by mottosso** [gitterHQ/gitter#577]
Hi Gitter team,

I just transferred ownership of abstractfactory/pyblish into pyblish/pyblish and saw my channel vanish from Gitter. Is there any way I could restore the chat, it's archive and members?

Thank you kindly,
Marcus

**Comment by mydigitalself** [comment]
Sure, I'll sort that out for you now.

**Comment by mydigitalself** [comment]
Done.

**Comment by mottosso** [comment]
Wow! Thank you very much!

As an aside, is there any way I can backup my chat archive?

**Comment by mydigitalself** [comment]
Well it's stored on our servers forever and replicated across multiple databases, but if you want you could probably use our API (https://developer.gitter.im) to download the messages as JSON and do with them whatever you like.

**Comment by mottosso** [comment]
I understand, I just got a little scare after this particular incident and would feel safer knowing I had access to the data from a secondary location.

I'll have a look at cloning the archive using your API. Thanks again.

**Comment by agutnichenko** [comment]
Hi Gitter team, Actually I faced the same problem but can't find out how to restore lost messages via API. Can someone please clarify it to me? Thanks in advance, Anna

**Comment by MadLittleMods** [comment]
@agutnichenko Create a new separate issue with the old URL to the project and what you transferred/renamed to.
