### ISSUE TITLE
Add a list of rooms available for an org

### ISSUE THREAD

**Issue by paltman** [gitterHQ/gitter#581]
This would make it easy for me to just join a channel than having to leave the UI go to the repo and click a badge.

We'd ([Pinax](http://github.com/pinax)) would love to use it on all our repos, but find it cumbersome to jump around in channels in the client.

**Comment by mydigitalself** [comment]
This is certainly something we're looking to do and will update here when we have something.

**Comment by posita** [comment]
HipChat provides has a "Lobby" metaphor that you might want to check out.

**Comment by MadLittleMods** [comment]
@paltman @posita Are you looking for something like the org pages? ex. https://gitter.im/orgs/gitterHQ/rooms

Just click the globe in the top-right when you are in a rooom connected to an org.

**Comment by posita** [comment]
One distinct difference is the ability to see private rooms to which I have access. These are not displayed in Gitter's `.../[org]/rooms` UI as far as I can tell. Private rooms are displayed in HipChat's lobby interface.

**Comment by MadLittleMods** [comment]
@posita Private rooms show up as long as long as you are allowed to see them.

![](http://i.imgur.com/CAbXHi8.png)

**Comment by posita** [comment]
> @posita Private rooms show up as long as long as you are allowed to see them.

@MadLittleMods, not on my account for my org. Separate issue?

**Comment by posita** [comment]
@MadLittleMods, new issue filed as #992.

**Comment by MadLittleMods** [comment]
Closing as org directory pages cover this: https://gitter.im/orgs/gitterHQ/rooms

The new left menu also has a list of rooms that you can join in the org:

![](http://i.imgur.com/hvDwbqp.png)
