### ISSUE TITLE
Search on explore

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#582]
1. owner/repo names should be valid "tags", eg search for "gitterHQ" should show gitterHQ owned repositories

2. canonical name should show a valid result, eg gitterHQ/gitter currently redirects with the / in it and 404's

**Comment by trevorah** [comment]
Something like `gitter.im/explore?q=gitterHQ/gitter` would be better suited to queries rather than the current url scheme (`gitter.im/explore/tags/gitterHQ/gitter`).

**Comment by trevorah** [comment]
Also, we should switch to a natural search. We would still use tags behind the scenes, but from a users point of view it should just be a query, not a list of tags.

This raises something. Could we use the explore search as part of the app search?

**Comment by SethTisue** [comment]
I've noticed that if I'm already a member of a room called e.g. "akka/akka", then typing that string in the search field will find the room, but I'm _not_ a member of the room, I get no search results. typing just "akka" finds it, but I would expect searching the fully qualified name to work.

**Comment by Risto-Stevcev** [comment]
+1 I agree. It should be able to work with the owner/repo name, ie. `ramda`, `cyclejs`, `most`, `scalajs`, `purescript`, etc. and it should return the obvious match rather than no results.

**Comment by MadLittleMods** [comment]
Search has been removed from explore in favor of a set of tag-pills to toggle:

![](http://i.imgur.com/eZUbM5s.png)

You can still use custom tags by adjusting the URL manually: https://gitter.im/explore/tags/foo

If you want to search for rooms by name, you can use the search on the main site.

**Comment by rosivanov** [comment]
@MadLittleMods  Tags are cool but I feel lack of usual search input. Now I have to play with tags (somtimes with ctrl+f) to finde a room I need.

**Comment by MadLittleMods** [comment]
@rosivanov The new left-menu solves the search input use case, http://blog.gitter.im/2016/03/15/introducing-our-new-ui/ - Search has been moved to the left-menu and opens to this state when you directly visit explore.

If you want to find rooms with a certain tag, you can adjust the URL manually, `https://gitter.im/explore/tags/css`

**Comment by rosivanov** [comment]
@MadLittleMods  Sorry I still don't see a search http://joxi.ru/52aJDoNuGaagjA

**Comment by abhisekp** [comment]
@rosivanov Read the blog and discover the new menu :sparkles:

**Comment by rosivanov** [comment]
@abhisekp apologize for my dumb, finaly i get it, thanks.
