### ISSUE TITLE
Order of my messages is messed up

### ISSUE THREAD

**Issue by sheela-na-geek** [gitterHQ/gitter#584]
When I write multiple messages one after another, I constantly see them to appear in reverse/random order. If I refresh the page, they arrange correctly.

Chromium Version 41.0.2272.35 (64-bit), Linux

**Comment by mydigitalself** [comment]
This will most often happen if your system clock is out of whack. 

1. Is your timezone set correctly? We've seen people who have the incorrect time zone set and then adjusted their clock manually to compensate. This creates chaos, destruction and mayhem.

2. Is your system clock correct? Do you set it via ntp?

**Comment by sheela-na-geek** [comment]
Thanks, problem was with my ntp setup.

**Comment by mydigitalself** [comment]
No problem, good to hear.
