### ISSUE TITLE
404. This is not the chat you're looking for error

### ISSUE THREAD

**Issue by drKraken** [gitterHQ/gitter#585]
When i click on not added to gitter repo i get error nice, but when i click on gitter logo i get two menus on left side
<a href="http://tinypic.com?ref=21b6lqc" target="_blank"><img src="http://i58.tinypic.com/21b6lqc.png" border="0" alt="Image and video hosting by TinyPic"></a>
So is it bug or feature?

**Comment by mydigitalself** [comment]
How did you originally get the 404?

**Comment by drKraken** [comment]
when i click on private organization that do not allow gitter to use it , i get this error, and then when i click on gitter logo i get previous.
<a href="http://tinypic.com?ref=eg4wth" target="_blank"><img src="http://i59.tinypic.com/eg4wth.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/912
