### ISSUE TITLE
Cannot create repository room after transferring ownership

### ISSUE THREAD

**Issue by mlms13** [gitterHQ/gitter#586]
The repository [fponticelli/restx](https://github.com/fponticelli/restx) was transferred and renamed to [abedev/abe](https://github.com/abedev/abe). In the process, the [Gitter room for fponticelli/restx](https://gitter.im/fponticelli/restx) broke (404), which makes sense and isn't really a problem. However, I'm also not able to create a [Gitter room for abedev/abe](https://gitter.im/abedev/abe), even though the project is open source.

**Comment by mydigitalself** [comment]
How on earth did you get it to redirect on GitHub? We've never seen that before, normally they return a 404 if a repo gets moved.

Anyhoo, I've moved the room for you. Note that merely visiting a room url won't create it, you need to create the room in Gitter by clicking on **Create a room** (bottom left).

**Comment by mydigitalself** [comment]
Ah, the UI redirects, but the API does not, which is our problem.

**Comment by trevorah** [comment]
Github details: https://github.com/blog/1508-repository-redirects-are-here

Issue: https://github.com/gitterHQ/gitter/issues/153

**Comment by mlms13** [comment]
Thanks for the quick response, you guys are awesome.
