### ISSUE TITLE
New Organisation not appearing in my list

### ISSUE THREAD

**Issue by eddiejaoude** [gitterHQ/gitter#589]
How long does it take before an Organisation appears in my available list?

It has been over 12 hours, is there caching?

Thanks.

**Comment by mydigitalself** [comment]
Hey Eddie,

GitHub released a new feature recently that allows Organisations to restrict Application access. For some unknown reason they have enabled this by default for all new Orgs.

If you go to https://github.com/organizations/YOURORGHERE/settings/oauth_application_policy and switch this off, then problem should go away. We do have a very short-lived cache, so maybe wait a few minutes after this until refresh.

Can you close this issue if it fixes your problem? Would also be great to email support@github.com explaining the confusion.

Cheers
Mike

**Comment by eddiejaoude** [comment]
Thanks, that worked. How can I just enable it for Gitter, rather than disable it?

Screen shot to help others...
![screen shot 2015-02-26 at 11 19 50](https://cloud.githubusercontent.com/assets/624760/6391026/8351c54a-bda9-11e4-9e5d-efa21189fead.png)

**Comment by mydigitalself** [comment]
I hate this feature so very much!

If you turn it back on, then go back to your own personal application settings (https://github.com/settings/applications) and any Gitter ones you see there, click on View and then scroll down and you can Grant it access to the Org.

**Comment by eddiejaoude** [comment]
Ok thanks! :+1:

**Comment by hobi** [comment]
I wanted report this same issue, but I discovered I have to go to this page (https://github.com/settings/applications#authorized) -> view each app and set manually access.

It is really bad feature. :(

**Comment by mydigitalself** [comment]
@hobi yeah you can turn the entire feature off per organisation.
