### ISSUE TITLE
jsFiddle snippet doesn't show content

### ISSUE THREAD

**Issue by VMBindraban** [gitterHQ/gitter#590]
If you enter a jsFiddle url  (`http://jsfiddle.net/mZzhy/`) into the chat it will normaly show a snippet.

Because gitter serves the webpage from https Chrome will not load snippets from http requests.
This will result into a large empty block in the chat. 

However Chrome will show a small shield next to the bookmark button to allow loading "unsafe" scripts.
jsFiddle supports https but doesn't redirect older links automatically to https.

Testen in Chrome Version 40.0.2214.115 (64-bit), Ubuntu 14.10.

Solution is to replace the http with https when embeding the url.

**Comment by trevorah** [comment]
Thanks for spotting this @VMBindraban.

I've disabled the jsfiddle embeds for now. On monday we're going to be discussing making the integrations a lot cooler so im not going to be making any new changes until then.

**Comment by mydigitalself** [comment]
Will close this issue as jsFiddle don't support https embedding... yeah...
