### ISSUE TITLE
Can't drag images onto gitter in OSX app

### ISSUE THREAD

**Issue by alanshaw** [gitterHQ/gitter#591]
If I drag into text area I get the path, if I drag into chat history the whole window is replaced with the image contents.

![screen shot 2015-02-26 at 10 19 29](https://cloud.githubusercontent.com/assets/152863/6390052/1b48dd56-bda1-11e4-98b4-fa5c985f0eee.png)

**Comment by suprememoocow** [comment]
Hi @alanshaw looking into this now

**Comment by suprememoocow** [comment]
For some reason the shape of [DataTransfer](http://www.w3.org/TR/2011/WD-html5-20110113/dnd.html#datatransfer) is different in every browser AND, it seems, Safari and the WebView. Hotfix building and deploying now. Sorry for the inconvenience!

**Comment by alanshaw** [comment]
Working now thanks!
