### ISSUE TITLE
ALT + click for quoting does not work

### ISSUE THREAD

**Issue by tjconcept** [gitterHQ/gitter#598]
<kbd>ALT</kbd> + click does nothing.

Seen on Chrome and Firefox (Ubuntu).

**Comment by Aaike** [comment]
same issue for me :+1:

**Comment by mydigitalself** [comment]
I believe it's a reserved keystroke on Ubuntu, perhaps we should assign it to something else on that platform?

**Comment by lucaswerkmeister** [comment]
At least on Linux Mint (Cinnamon), Alt+Drag moves the window, so the click probably never even reaches the browser. (The cursor also turns into the Drag cursor on Alt+Click.)

> perhaps we should assign it to something else

In addition to that, it would be great if the time stamp was a regular link that you can click to get a permalink. This seems to be somewhat standard by now (e. g. Github. Twitter, Facebook).

**Comment by lucaswerkmeister** [comment]
Workaround: spam <kbd>Alt</kbd> and click individually – the desktop manager sees the events as different, but with some luck they appear simultaneous to the browser :D

**Comment by Aaike** [comment]
another solution is to just click the date which will set the browser url

then paste that into a message , you can use markup to style it like the following:

:point_up: [Look up for my message](https://gitter.im/gitterHQ/nodejs?at=5521380e4ceaec8225f94277)

**Comment by lucaswerkmeister** [comment]
Huh, I could swear that didn’t work when I checked about a month ago… thanks

**Comment by mydigitalself** [comment]
Closing as "Won't fix" as there will be a UI change coming up that will allow this behaviour in a different way.
