### ISSUE TITLE
cannot /part over irc

### ISSUE THREAD

**Issue by wenzowski** [gitterHQ/gitter#605]
There appears to be a something wrong with the `irc.gitter.im` bridge: I was able to `/join #gitterHQ/gitter` but am now unable to `/part` it.

Connected via [IRCCloud](https://www.irccloud.com/).

Any suggestions?

**Comment by mydigitalself** [comment]
@malditogeek can you check this against the new IRC server please and maybe get in touch with @wenzowski to beta it?

**Comment by malditogeek** [comment]
@wenzowski hi! I'd recommend you to check the new IRC bridge available at `irc-next.gitter.im` port `7777` with the same token but NO SSL (it'll be available again after beta)

This new bridge is open source and available at https://github.com/gitterHQ/irc-bridge if you fancy checking the code or running it locally.

Closing this issue for now.

**Comment by wenzowski** [comment]
works beautifully, thanks
