### ISSUE TITLE
Confirm leaving room when clicking in the left menu

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#607]
- [x] single close button
- [x] popover with leave/hide

**Comment by malditogeek** [comment]
Code in troupe/gitter-webapp#260

**Comment by malditogeek** [comment]
![screen shot 2015-03-18 at 17 19 42](https://cloud.githubusercontent.com/assets/14751/6714985/7f236e5c-cd93-11e4-829f-a5625ab8e6c1.png)
