### ISSUE TITLE
Shrink chat header for more vertical space

### ISSUE THREAD

**Issue by Helmi** [gitterHQ/gitter#608]
It'll be great if the header wasn't in the way all the time. I think auto shrinking it could be a good idea. The icon could be smaller then and the text only contain the room name. Everything else (like description, star, preferences icon) could be revealed on hover. This would also declutter the interface. #ux

**Comment by trevorah** [comment]
This would be cool, but we would have to be careful to not lose the users context. The room logo adds a lot.

Im really up for limiting the height of the header though, but thats mainly down to the code pain of making the header cope with expanding with multi-line descriptions.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/253

**Comment by MadLittleMods** [comment]
The header is now a single line and pretty slim:

![](http://i.imgur.com/Um3Fioi.png)
