### ISSUE TITLE
Notification settings will not be saved

### ISSUE THREAD

**Issue by akkie** [gitterHQ/gitter#609]
If I change my notification settings then they will not be saved. After saving, the entry "Notify when somebody mentions me" it's always selected and I get no new notifications if someone post a new message.

So if I try to change the settings to: "Notify me for all messages"

Then it  sends first a PUT to: https://api.gitter.im/v1/user/12345/rooms/54337afe163965c9bc209532/settings/notifications

with 
````
{"push":"mention"}
````

And as second a PUT to: 
https://api.gitter.im/v1/user/12345/rooms/54337afe163965c9bc209532

with 
```
{"lurk":true}
```

**Comment by trevorah** [comment]
Hmm, good spot @akkie. Thanks for pointing this out.

**Comment by kbrock** [comment]
I'm finding this frustrating too.

1. update notifications to "only notify me when my name is called" - this worked.
2. update to "always notify me" - stays in previous mode.

**Comment by kbrock** [comment]
thanks for help @mydigitalself - looks like in the ui changing that value is updated ajax style, and the "enable lurker mode" button disables the original change.

solution:

1. update notification to "always notify me"
2. don't click anything, just close
