### ISSUE TITLE
Issue with poor performance on Linux/Firefox

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#61]
hi! I use Firefox 26.0 under Arch Linux x86_64, nouveau, KDE. On webpack room ff eats completely one CPU core. Now when I'm answering you it eats ~40% of one CPU core (Intel i5 760). Trying to start ff in safe mode doesn't change anything. What additional info is interesting for you?

--

Note the user also experiences occasional accidental dragging of objects as a result of this eg: http://gaydenko.com/tmp/gitter01.jpg

**Comment by tjconcept** [comment]
Don't know if this is at all related, but I'm occasionally experiencing that the last sent message is re-added in the text field on a reload (in FF).

**Comment by mydigitalself** [comment]
I don't think that's related, would you mind opening a new issue for that
please? Sounds like the unsent message cache is not clearing sometimes.

**Comment by MadLittleMods** [comment]
Is this issue still valid, anyone reproducing nowadays? We are on Firefox 40.0.2(stable) now.
