### ISSUE TITLE
[For your consideration] Current font face is slightly hard to read

### ISSUE THREAD

**Issue by axltxl** [gitterHQ/gitter#610]
Hello, I'm giving Gitter a try and all seems to be great , nevertheless, I have found the font face used for rendering the website a little bit hard to read since it is somewhat thin. For the record, I am using Chrome on elementaryOS. My suggestion for you guys would be to consider a more solid yet cool font face such as `Roboto`, maybe `Droid Sans`. Thank you in advance.

**Comment by mydigitalself** [comment]
After much consideration, we've updated the font. This is currently on Next (http://next.gitter.im to enable). 

We ended up going with Adobe's Source Sans Pro btw.

**Comment by trevorah** [comment]
Like so:
![screen shot 2015-04-24 at 17 21 04](https://cloud.githubusercontent.com/assets/298742/7323433/656c3748-eaa6-11e4-95be-2c0df63927ac.png)

**Comment by axltxl** [comment]
It looks lovely!, keep up the good work guys! :wine_glass:
