### ISSUE TITLE
Badges are too short

### ISSUE THREAD

**Issue by QuLogic** [gitterHQ/gitter#613]
This was sort of mentioned in passing in #226. A side effect of not using Shields.io is that the Gitter badges are not consistent with most others. I probably couldn't care less about the drop shadow, but I don't really like the mismatched shape and incorrect baselines.

**Comment by trevorah** [comment]
From the shields.io standard: https://github.com/badges/shields

> As you can see below, without increasing the footprint of these badges, I've tried to increase legibility and coherence, removing useless text to decrease the horizontal length in the (likely) scenario that more of these badge thingies crop up on READMEs all across the land.
![](https://github.com/badges/shields/raw/master/spec/proportions.png)

Also, heres the thread/reasoning behind travis-ci switching to shields.io: https://github.com/travis-ci/travis-ci/issues/630#issuecomment-38054967

**Comment by bardiharborow** [comment]
See my issue at badges/shields#426.

**Comment by trevorah** [comment]
The changes are now live! All existing badges should now match the shields.io standard.

**Comment by vassilevsky** [comment]
![](https://camo.githubusercontent.com/4f1193e29c9e5ee6bd5436a53274686e894881af/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3131333936362f53637265656e73686f74732f52616d626f74682e6a7067)
