### ISSUE TITLE
Notifications are repeated on each edit

### ISSUE THREAD

**Issue by tjconcept** [gitterHQ/gitter#614]
Each time I edit a message, my colleagues get another notification.

With my poor spelling skills that could amount to a fair amount of spam.

**Comment by trevorah** [comment]
The case against this would be that there are some edits that you would want to be notified about - changes in time etc. Although if it is such a small change, you would think that people wouldnt make the change in something as subtle as an edit.

**Comment by tjconcept** [comment]
I thought about that as well, but as you say, you should have some idea that a new message would be better suited for changes like that. Imagine a peer looking at the room: he reads the initial message, but does not notice the subtle change in a time.
It definitely think it is *less* surprising to only dispatch a single notification.

**Comment by MadLittleMods** [comment]
I can't reproduce this now. Notifications are only sent on the initial send.
