### ISSUE TITLE
Transferred ownership

### ISSUE THREAD

**Issue by matthewp** [gitterHQ/gitter#616]
Hi Gitter, love your service.

I transferred bitovi/steal to stealjs/steal and lost our archives :(  Is there any way this could be restored?

**Comment by matthewp** [comment]
Oh, I see I'm not the only person who has made this mistake: https://github.com/gitterHQ/gitter/issues/577

Can you restore the chat, archives and members?  That would be fantastic!

**Comment by trevorah** [comment]
Would you be ok with losing the content that you have in stealjs/steal? If so, I can just rename bitovi/steal.

**Comment by matthewp** [comment]
Yep, no one's posted anything in there yet anyways, thank you so much.

**Comment by trevorah** [comment]
done!

**Comment by matthewp** [comment]
You are crazy awesome.

**Comment by trevorah** [comment]
No problem!
