### ISSUE TITLE
[Feature] Add... simple game

### ISSUE THREAD

**Issue by loostro** [gitterHQ/gitter#625]
While working, there are times when you just have nothing to do and you're bored:
* you're waiting for vagrant machine to provision
* you're waiting for Travis/Scrutinizer/any other Continous Integration build to finish
* you're waiting for a response from your teammate, who was online just an hour ago, but now he's apparently AFK

Whatever the reason, you can't just go away from computer, becouse as soon as you're done waiting, you have to continue work.

And, for some reason, you're bored googleing for `funny catz photos`...

You wish there was something to do on gitter.. maybe a simple game? Tetris? Space invaders?
The game could be written in Javascript and all it's data and computation on client-side (so gitter servers don't get unnecessary additional load).

Just an idea... oh wait, my box is up and ready. CYA!

**Comment by mydigitalself** [comment]
Great idea, but a little out of scope for what we're trying to do and highly unlikely to be prioritised unless we get drunk during a hackathon. Going to close the issue I'm afraid.

**Comment by loostro** [comment]
@mydigitalself I guess I'll have to get used to `google.com --> funny catz photos`. oh well...
