### ISSUE TITLE
CORS blocked

### ISSUE THREAD

**Issue by Gioyik** [gitterHQ/gitter#628]
I am trying to create a new room for my repo but the list never appears. I see the console and this is the output:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.gitter.im/v1/user/XXXXXXX/repos. (Reason: CORS request failed).

**Comment by trevorah** [comment]
Hmm, I cant reproduce this. What browser are you using?

**Comment by Gioyik** [comment]
Firefox Developer Edition and Firefox Nightly

**Comment by trevorah** [comment]
This is really weird; I cant reproduce it.

Do you have any special security settings? Have you tried restarting the browser?

**Comment by suprememoocow** [comment]
Hi @Gioyik, are you using any sort of enterprise http proxy service that may be modifying the HTTP request in any way?

**Comment by Gioyik** [comment]
No, today I tested again I still have this issue that doesn't let me create new rooms for my repos. Check the output in the console log: http://pastebin.com/cnsyMDYb

Today I am seeing a new error:
> This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] talk

But it's different from the main problem. If you see at the end of the log it says:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.gitter.im/v1/user/53b1dc99107e137846ba5025/repos. (Reason: CORS request failed). <unknown>

I attach you an screenshot:
![screenshot_2015-04-01_12-01-46](https://cloud.githubusercontent.com/assets/1834718/6946607/33b205c6-d867-11e4-8345-765a33a5613f.png)

Let me know if I can help in something to identify the cause of this problem.

**Comment by trevorah** [comment]
1. Does this fail in other (stable) browsers on your machine?
2. Does this [github api cors example](http://georgeosddev.github.io/markdown-edit/) (make sure to have "Use Github API for converter" selected) correctly post markdown to the github endpoint?

**Comment by bcwadi** [comment]
I am also getting the same error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://***.***.***.***:8080/SignalRSvc/signalr/poll?transport=longPolling&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAITiZVPHLmU6NMVM%2Btz2mVwAAAAACAAAAAAADZgAAwAAAABAAAABV7b59FkvcmRMh1w9NNsXMAAAAAASAAACgAAAAEAAAANcAxWwMI2ZX6NjKSNwLnCUoAAAA9cM3p%2FMbfWB%2F7o37aiysSHeZgaqnGOYqz9ebwyKbnbVGXyUjW4sARxQAAAApq7ZmcKiI9xFXXzNUBSZUYmX%2Fwg%3D%3D&messageId=d-A41124BB-R%2C4%7CS%2C0%7CT%2C1%7CU%2C0&connectionData=%5B%7B%22name%22%3A%22signalrhub%22%7D%5D&tid=5&_=1433147696451. (Reason: CORS request failed).

Is there any solution for this?

**Comment by trevorah** [comment]
@bcwadi whats the host in that error? The "http://...:8080" is the most important part.

**Comment by mydigitalself** [comment]
Saw this a couple of weeks ago where the guy's DNS traffic was basically being proxied, changing to Google's public DNS servers (8.8.8.8 and 8.8.4.4) fixed the issue for him.

**Comment by bcwadi** [comment]
I am using a self hosted SignalR proxy hub as service client side for the asp/net application.
Everything is working fine in other browsers except Firefox and the error i am getting is "TypeError: access to strict mode caller function is censored" even after following the strict mode js code.
Hence thought to check with debugger mode to login to a module mannually and i am getting the above error.

As Firefox doesn't show where the error but directly displays the error, and even no option to disable the strict mode. So thought this also might be problem which can solve might issue.

**Comment by MadLittleMods** [comment]
Is anyone still experiencing this?
