### ISSUE TITLE
Give personal user data and not organization data

### ISSUE THREAD

**Issue by mlaco** [gitterHQ/gitter#629]
I would like to sign in to a Gitter chat using my GitHub account, but there is no option not to extend permissions for my organizations too, which is something I cannot do.

**Comment by mydigitalself** [comment]
Hi there,

This is how GitHub's API scoping works. You can get your Organisation to opt out of this for ALL applications, take a look at this article over here and shout if you have any further questions.
https://github.com/blog/1941-organization-approved-applications

Cheers
Mike

**Comment by mlaco** [comment]
Thank you.
