### ISSUE TITLE
Leave/Hide menu skips to top-left position when mouseout while fade-in

### ISSUE THREAD

**Issue by o-nix** [gitterHQ/gitter#631]

**Comment by trevorah** [comment]
Confirmed:
![screen shot 2015-03-24 at 17 08 57](https://cloud.githubusercontent.com/assets/298742/6807810/b2c6aee0-d248-11e4-95b7-da5a1f5f5962.png)

Looks like the when the cross disappears, the popover looses its anchor and rerenders to the default position. Nice spot @o-nix!

**Comment by MadLittleMods** [comment]
This has been fixed for a while and we have moved to slightly different aesthetics.
