### ISSUE TITLE
Gitter badge not following shields.io conventions

### ISSUE THREAD

**Issue by shytikov** [gitterHQ/gitter#636]
First of all, thank you for gitter! We love it. True story.

And we also love github's ~~penis extension~~ badges feature. And use it a lot (maybe more than we should), but Gitter badge is so different, and it so out of the line with others, so I'm seriously considering strip it down from my readme files.

Could you please add badge that follows standards of the http://shields.io? using the same size, color, shadows, etc. Please?

I have seen issues related to this couple times already: #613, #226... Can you once and for all close this question by releasing proper badge? You even have example how it [should look like](https://github.com/gitterHQ/gitter/issues/226#issuecomment-42435823). What stopping you from finishing this feature in the right way?

I'm begging you to create proper badge, I promise to put it at the first place among my badges! Always!

**Comment by mydigitalself** [comment]
Haha, great post.

We'll look at this again in the future, I promise. In the meantime, being a man of many talents (apologies for the assumption) there's nothing stopping you from changing the image in the readme ala:

```https://img.shields.io/badge/GITTER-join%20chat-green.svg```

Which would result in the following piece of wonderment:
![Badge](https://img.shields.io/badge/GITTER-join%20chat-green.svg)

Or if you're a fan of square corners (I personally am ambivalent towards them) you can even ninja it like so:
```https://img.shields.io/badge/GITTER-join%20chat-green.svg?style=flat-square```

Resulting in the following that will leave fans of `border-radius` screaming like banshees.
![OMG SQUARE](https://img.shields.io/badge/GITTER-join%20chat-green.svg?style=flat-square)

**Comment by shytikov** [comment]
:+1: thanks I'm updating my project... Will try to close my eyes on imperfection of the badges on other's projects.

**Comment by mydigitalself** [comment]
If you purchase a pair of rose-tinted glasses, they will probably look ok.

**Comment by shytikov** [comment]
:) Sorry for such an emotional post. There are a lot of imperfection in this world, I just thought that the badge is the simplest to fix among them :)

Thank you for taking this with humor :)

**Comment by bardiharborow** [comment]
:+1:

**Comment by zxqfox** [comment]
I'd say:

`https://img.shields.io/badge/GITTER-JOIN_CHAT_%E2%86%92-1dce73.svg`
![Gitter — Join Chat](https://img.shields.io/badge/GITTER-JOIN_CHAT_%E2%86%92-1dce73.svg)

**Comment by ctubio** [comment]
meh

`https://img.shields.io/badge/gitter-join%20chat-1dce73.svg`
![meh](https://img.shields.io/badge/gitter-join%20chat-1dce73.svg)

**Comment by bardiharborow** [comment]
See badges/shields#354.

**Comment by dregad** [comment]
For those of you who, like me, don't like the fact that the gitter badge does not have the same look&feel as others, I just found out that the *shields.io* badge is now available:

https://img.shields.io/gitter/room/gitterHQ/gitter.svg
![](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)

**@gitter team**: are you planning to implement the *user count* feature discussed in https://github.com/badges/shields/issues/354#issuecomment-134562225 ?

**Comment by trevorah** [comment]
We're finally pushing a fix!

Its live right now and is closest to @ctubio's suggestion.

**Comment by dregad** [comment]
Cheers !

Does this mean you're not going to do the user count thing ? Or is that tracked somewhere else ? I thought it was a nice feature.

**Comment by trevorah** [comment]
Not right now. At the moment you have to have an auth token to make any api request.

**Comment by dregad** [comment]
OK, thanks for the feedback.

Now it just remains to be seen if @shytikov will actually (and always) put the gitter badge first as he promised ;-)

**Comment by uditha-atukorala** [comment]
@trevorah Is there a way to get the old badge back?

We want the gitter badge to stand out so we include it separately to other badges (e.g. [nukedzn/node-tcl](https://github.com/nukedzn/node-tcl)) and now it just looks ordinary (and ugly IMHO).

**Comment by trevorah** [comment]
Nope, you'll have to make your own.

**Comment by uditha-atukorala** [comment]
Any possibility of getting a copy of the old SVG in that case?

**Comment by trevorah** [comment]
https://web.archive.org/web/20151203074344/https://badges.gitter.im/Join%20Chat.svg

**Comment by uditha-atukorala** [comment]
:+1:

**Comment by Code-Lyoko** [comment]
Gitter badge *with* shields.io's logo:
![Gitter](https://img.shields.io/badge/gitter-join_chat-1dce73.svg?logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB4PSIwIiB5PSI1IiBmaWxsPSIjZmZmIiB3aWR0aD0iMSIgaGVpZ2h0PSI1Ii8%2BPHJlY3QgeD0iMiIgeT0iNiIgZmlsbD0iI2ZmZiIgd2lkdGg9IjEiIGhlaWdodD0iNyIvPjxyZWN0IHg9IjQiIHk9IjYiIGZpbGw9IiNmZmYiIHdpZHRoPSIxIiBoZWlnaHQ9IjciLz48cmVjdCB4PSI2IiB5PSI2IiBmaWxsPSIjZmZmIiB3aWR0aD0iMSIgaGVpZ2h0PSI0Ii8%2BPC9zdmc%2B&logoWidth=8)
`https://img.shields.io/badge/gitter-join_chat-1dce73.svg?logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB4PSIwIiB5PSI1IiBmaWxsPSIjZmZmIiB3aWR0aD0iMSIgaGVpZ2h0PSI1Ii8%2BPHJlY3QgeD0iMiIgeT0iNiIgZmlsbD0iI2ZmZiIgd2lkdGg9IjEiIGhlaWdodD0iNyIvPjxyZWN0IHg9IjQiIHk9IjYiIGZpbGw9IiNmZmYiIHdpZHRoPSIxIiBoZWlnaHQ9IjciLz48cmVjdCB4PSI2IiB5PSI2IiBmaWxsPSIjZmZmIiB3aWR0aD0iMSIgaGVpZ2h0PSI0Ii8%2BPC9zdmc%2B&logoWidth=8`
