### ISSUE TITLE
Websockets are down.

### ISSUE THREAD

**Issue by Nijikokun** [gitterHQ/gitter#637]
Immediately after the update on **Sunday March 29th, 16:00:00** websockets went down after upgrading (refreshing the page) to the new release.

As of **16:31:00** they are still down.

**Comment by trevorah** [comment]
Thanks @Nijikokun, we're currently looking into it.

**Comment by Nijikokun** [comment]
Looks like they are working properly as of **16:43:00**

Thanks @trevorah for the quick fixes

**Comment by trevorah** [comment]
Sorry about that!

**Comment by suprememoocow** [comment]
Sorry, yes it was a websocket server side upgrade that went wrong. Full postmortem to follow once we've got to the bottom of it. Thanks for raising the issue @Nijikokun
