### ISSUE TITLE
Better spacing for sequential messages

### ISSUE THREAD

**Issue by Nijikokun** [gitterHQ/gitter#638]
When inputting multiple messages you often get *lost* in a wall of text due to the fact that there is no additional gap, margin, or seperator between sequential messages by the same user.

The following is in fact two seperate messages:

![](https://www.dropbox.com/s/g0eqj1vjonom1il/Screenshot%202015-03-30%2012.27.25.png?dl=1)

Something as simple as a `10px` margin can solve this issue:

![](https://www.dropbox.com/s/iwl241uk3v53bke/Screenshot%202015-03-30%2012.28.49.png?dl=1)

**Comment by trevorah** [comment]
Done! Thanks for the suggestion @Nijikokun. We've rolled this into some bigger typography changes:

![screen shot 2015-05-13 at 00 12 06](https://cloud.githubusercontent.com/assets/298742/7600624/ca6de6d4-f904-11e4-9c77-5864026e8d3a.png)

Hope you like it!
