### ISSUE TITLE
Embed chat room on a webpage

### ISSUE THREAD

**Issue by finom** [gitterHQ/gitter#641]
Hi there. It would be nice to have embedding feature. Looks like very simple to do and requires just alternative URL + some CSS changes.

Thanks.

**Comment by justinbmeyer** [comment]
+1.  Or, alternatively, is there an open API to get messages and I will create a embed-able JS client myself.  Thanks!

**Comment by finom** [comment]
Guys, any news about this issue?

**Comment by MichaelLeeHobbs** [comment]
+1 embedable or api

**Comment by MadLittleMods** [comment]
You can use an iframe with the `~embed` "flag" appended.

[See demo](http://jsfiddle.net/MadLittleMods/5u9h14Lc/)

```html
<iframe src="https://gitter.im/gitterHQ/gitter/~embed">
```

@justinbmeyer You can use the [Gitter Developer API](https://developer.gitter.im/) specifically the [messages resource](https://developer.gitter.im/docs/messages-resource) to grab messages.

**Comment by finom** [comment]
@MadLittleMods
The only feature I need is to send messages. For now I can see "Sign up for free" button even if I'm logged in.

**Comment by MadLittleMods** [comment]
@finom The iframe method is limited and you can't "log in" or send messages with it.

**Comment by finom** [comment]
@MichaelLeeHobbs you mean it's limited deliberately?

**Comment by mydigitalself** [comment]
This is not something that we officially support yet, ~embed is designed for the front page.

**Comment by finom** [comment]
@mydigitalself I think it will be nice to add the only authorization feature and it will be enough.

Thanks guys for your great work.

**Comment by MichaelLeeHobbs** [comment]
@finom I have a working page with embed gitter chat here: http://www.michaelleehobbs.net/fccnews/#/chat

page source: https://github.com/MichaelLeeHobbs/fccnews

It seems to work well but I haven't really tested it thoroughly.

**Comment by dcsan** [comment]
hello camper @MichaelLeeHobbs !
what does the ~embed flag actually change? it looks pretty similar...

**Comment by mydigitalself** [comment]
~embed is designed purely for our front page and it has no capability to interact with the conversation.

**Comment by idleberg** [comment]
Are there any parameters available to pass to the iframe? I would like, for instance, to enable the activity feed in the sidebar.

**Comment by mydigitalself** [comment]
@idleberg not at the moment, no. we'll see how people get on with it the way it is now and look to improve based on popular feedback.

**Comment by mydigitalself** [comment]
Closing as this is now available via https://sidecar.gitter.im

**Comment by finom** [comment]
Awesome! Also I'd like to make possible to embed activity (not chat) on my website. It's cool to see what's going on in internet about my project.

**Comment by justinbmeyer** [comment]
@mydigitalself Is there an API if you wanted to build this with a custom look and feel?
