### ISSUE TITLE
Repository not visible in create room repo list

### ISSUE THREAD

**Issue by suprememoocow** [gitterHQ/gitter#644]
[As reported by ](https://gitter.im/gitterHQ/gitter?at=551ae0c61f582983259ee380) @patmaddox in gitterHQ/gitter.

**Comment by suprememoocow** [comment]
First impression is that is appears to be some strangeness in the [List User Repos](https://developer.github.com/v3/repos/#list-user-repositories) GitHub API method, which we use for listing all the user's repos.

#### Can we see the repo with GitHub's List User Repositories API? 
```shell
$ curl --silent https://api.github.com/user/repos?per_page=100 -u $TOKEN:x-oauth-basic  -H "Accept: application/vnd.github.moondragon+json"  | jq '.[] | .full_name' | grep -i RubySteps/rubysteps.github.io | wc -l
       0
```

#### Is it a paging issue?
```shell
$ curl --silent https://api.github.com/user/repos?per_page=100 -u $TOKEN:x-oauth-basic  -H "Accept: application/vnd.github.moondragon+json" | jq '.[] | .full_name' | wc -l 
    96
```
-- No. 96 repos means it's not a paging issue as we're requesting 100 results per page.

#### Can we see any repos for the RubySteps org using our token?

```shell
$ curl --silent https://api.github.com/user/repos?per_page=100 -u $TOKEN:x-oauth-basic  | jq '.[] | .full_name' | grep -i RubySteps/
       0
```
-- No. 

#### Does our token grant us access to see the RubySteps repo?

```shell
$ curl --silent https://api.github.com/user/orgs?per_page=100 -u $TOKEN:x-oauth-basic  | jq '.[] | .login'| grep RubySteps
"RubySteps"
```
-- yes

#### Can we see the repo using our token?
```shell
$ curl --silent https://api.github.com/repos/RubySteps/rubysteps.github.io -u $TOKEN:x-oauth-basic
{
  ...
  "name": "rubysteps.github.io",
  "full_name": "RubySteps/rubysteps.github.io",
  ...
}
```
-- Yes. What's more, Pat has full access to this repo (`admin`, `push` and `pull`).

@patmaddox, just to be sure, please could you confirm that either [Third Party Application Access](https://github.com/organizations/RubySteps/settings/oauth_application_policy) is set to **"No Restrictions"**, or you've granted the Gitter application access to the RubySteps org?

I'll continue investigating and I'll get in touch with GitHub and see if they can help

**Comment by suprememoocow** [comment]
A few more notes:

1. The Moondragon API is still working as `https://api.github.com/user/repos?per_page=100` is returning repos for some of the users other organisations.
2. Using the old, non-Moondragon API, `curl --silent https://api.github.com/orgs/RubySteps/repos?per_page=100 -u $TOKEN:x-oauth-basic`, we're able to see the repos, which further indicates that the problem is related to Moondragon and not a Third Party Application Access issue.

**Comment by suprememoocow** [comment]
I've emailed GitHub support and am awaiting a response from them...

**Comment by MadLittleMods** [comment]
According to the email reply, this should be fixed now (as of April 6th).

`read:org` scope will now include public organization-owned repositories. Previously, public organization-owned repositories weren't included so that organization memberships wouldn't be leaked.

**Comment by davidonlaptop** [comment]
Would not work for me. My public organization's public repositories would not show in the create repo room list. The oauth policy was set to "Access restricted" with "Gitter Public Repo Access" activated.

Here's how I resolved it:

1.  Click remove restrictions button in myrepo/settings/oauth_application_policy
2. Create the room from Gitter UI
3. Re-active the restrictions
