### ISSUE TITLE
Delete request.

### ISSUE THREAD

**Issue by trusktr** [gitterHQ/gitter#645]
Can you delete the room `trusktr/famous`?

**Comment by mydigitalself** [comment]
Sure thing, done. Any particular reason?

**Comment by trusktr** [comment]
Thanks! The reason was that Famous/famous finally made their own channel.

On Thursday, April 2, 2015, Mike Bartlett <notifications@github.com> wrote:

> Closed #645 <https://github.com/gitterHQ/gitter/issues/645>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitterHQ/gitter/issues/645#event-271641260>.
>


-- 
/#!/JoePea
