### ISSUE TITLE
Add feature to preview channels before joining them.

### ISSUE THREAD

**Issue by drpotato** [gitterHQ/gitter#651]
Before participating in a channel, it would be nice to simply preview it.

For example, when I click on one of the suggested rooms I would prefer to be see the chat and not join it immediately. I realise there's no real consequence in joining and then leaving almost immediately but Slack has this kind of behaviour when clicking on linked channels. Also, this may lead to people lurking in channels which would be undesirable.

Please shoot me down if you think this is a dumb idea.

**Comment by mydigitalself** [comment]
No, it's a great suggestion.

**Comment by MadLittleMods** [comment]
You no longer automatically join a room after visiting it, we now have a "Join Room" button:

![](http://i.imgur.com/28rkAsC.png)
