### ISSUE TITLE
Inherited repo channel permissions are incorrect

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#656]
Steps to reproduce:

1) Create a channel owner/repo/channel on a public repo
2) Choose "repo" permission (not public)
3) Once the channel is created, try add someone not in the owner org, notice error
4) Also notice lock next to channel name thinks it's an org channel (also note spacing typo)

**Comment by mydigitalself** [comment]
A valid workaround is to choose "Public" permissions for (2) and you are able to add the user just fine.

**Comment by trevorah** [comment]
I've removed the option from the modal for now, but we have 80 rooms in prod with these permissions, the biggest of which has 43 members.

We can migrate them later to a private channel when we next touch the permission logic.
