### ISSUE TITLE
Correct irc.gitter.im quote attribution

### ISSUE THREAD

**Issue by patcon** [gitterHQ/gitter#658]
!["Stay hungry, stay on IRC" - Steve Jobs](https://imgur.com/EB8JbFa.png)

It was Stewart Brand's from the back cover of "The Whole Earth Catalog" :)

!["Stay hungry. Stay foolish." - Stewart Brand](http://media.longnow.org/files/2/stay_hungry_stay_foolish.jpg)

**Comment by MadLittleMods** [comment]
We are going to be making changes to this page in the future and changing/removing some of these quotes.
