### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by rizowski** [gitterHQ/gitter#660]
I cleaned all my application rights from github and tried to authenticate with Gitter. For some reason all I get now is a 500 error. The only application that works for me anymore is mobile. Desktop and Web clients are shot. I don't know why.

Clearing the cache has seemed to have not worked, the only option that I can do anymore is collect cookies and clear them to logout. haha

**Comment by mydigitalself** [comment]
Right...

You will need those application rights back again.

For Web app, visit https://gitter.im/logout to force a log out. 

Which Desktop app are you using?

**Comment by rizowski** [comment]
Ooops sorry, I forgot to mention that I tried to get those application rights by logging out and logging back in. I am using both the Mac and Windows Gitter desktop apps. Although, clicking on the link to logout, I am also getting a 405. The only way I have been able to "logout" is by deleting the session cookies.
[image of errors](https://www.dropbox.com/s/a37yrzwvqui7es8/Screen%20Shot%202015-04-14%20at%206.40.35%20AM.png?dl=0) But going to any chatroom in general throws a 500 even with the github rights renewed.

**Comment by mydigitalself** [comment]
I think I understand why. I had previously granted us Private Repo scope and perhaps you haven't granted that back again? What does your list of Applications looks like under GitHub's https://github.com/settings/applications

**Comment by rizowski** [comment]
Just public. Is there a way that I can explicitly allow that or is that something you guys control?

**Comment by mydigitalself** [comment]
It's basically a mismatch on our side. We need to keep track of what rights you've granted us and because we don't get an event back from GitHub that you've revoked rights, we've got our knickers in a knot as we're trying to authenticate you with another.

Let me try something quickly and see if it works... try now...

**Comment by rizowski** [comment]
Sweet, looks like it is working now. Thank you kind sir.
