### ISSUE TITLE
Cannot access anything, seems auth related

### ISSUE THREAD

**Issue by bguiz** [gitterHQ/gitter#663]
I am permanently getting this error, and there's nothing I can do to get rid of it: 
"Something went wrong. We're sorry. :("

However, if I open up a private browsing window in my browser, this does not happen. I can navigate to any discussions and view them (but not participate) because I am not logged in. Once I log in, however, I am back to the above error.

**Comment by bguiz** [comment]
The title of the page is "Gitter - Error 500"

**Comment by mydigitalself** [comment]
Have you done anything funny with your GitHub tokens perhaps?

Can you send me a screenshot of this please?
https://github.com/settings/applications

**Comment by bguiz** [comment]
In an attempt to fix it, I have removed all tokens for gitter,
And then. Private browsing mode, logged in again, reauthorising with
github.

I currently have a single authorisation for gitter public repositories
access.

Is there a way for my account to reset all authorisations on gitter's end?
I tried http://gitter.im/logout, to no avail

**Comment by mydigitalself** [comment]
So did you only revoke the private token after this first started happening?

**Comment by bguiz** [comment]
That's correct. Revoked both public repo access token and private repo
access token, after this started happening.

How can I "reset" my account?



W: http://bguiz.com

**Comment by mydigitalself** [comment]
This hasn't really happened before, I've tried to manually reset your account on our side.

You may have to visit gitter.im/?redirect=no first and then sign in from the front page. You'll have to grant private repo access again separately (ahhh, GitHub scopes...).

Let me know if that works for you, it's a pretty unusual case so not 100% sure I've done it correctly, but believe I have.

**Comment by bguiz** [comment]
Thanks for doing the reset - it worked for me without using the redirect
link you provided above. Also, I didn't have to re-authenticate with Github
- it just went through right away.

Anyway, this confirms that it was an authentication related issue. I have a
couple of feature requests coming out of this:

- include a reset or logout button available
- display an authentication error instead of a generic 500 error when this
is what causes it

W: http://bguiz.com

**Comment by mydigitalself** [comment]
No problem. What I'm struggling with is what caused it in the first place as we do have code that's supposed to deal with this type of thing automatically. The 500 is basically the result of an unhandled expception, so if we can figure out the circumstances that caused this, we'd either be able to handle it better automatically or provide options to re-authenticate/reset.

Will dig into the logs and try see if we can trace it back.

I just wanted to triple check that you never revoked anything prior to this happening?

**Comment by bguiz** [comment]
Yeah, didn't revoke any access prior to this happening. I did create and
revoke a few access tokens (for Travis CI), that were unrelated to Gitter.
AFAIK, that should not have affected Gitter, as Gitter never would have
been aware of those tokens.

Thanks again for manually resetting my access. Perhaps, on the 500 error
page (and perhaps other ones too) provide an option saying something along
the lines of "if you think that this is authentication related, please
click here to reset/ logout"

W: http://bguiz.com

**Comment by uetchy** [comment]
Same problem here.
![screen shot 2016-08-10 at 3 31 19 pm](https://cloud.githubusercontent.com/assets/431808/17544026/ab879f4a-5f0f-11e6-9820-e16c927266e1.png)

1. I've revoked access tokens because gitter seems don't show any my repository.
2. Sign-in on private mode then got this screenshot.

**Comment by uetchy** [comment]
They also gave me 401 Unauthorised error (in Developer Console).

**Comment by MadLittleMods** [comment]
@uetchy If you change to a room, do you still get the "Something went wrong" message in the chat frame?
