### ISSUE TITLE
Windows Gitter app keeps crashing/exiting

### ISSUE THREAD

**Issue by MilosStanic** [gitterHQ/gitter#664]
Hi, 

My windows Gitter app has been crashing since forever. I've been using it for months, and it keeps crashing/exiting without warning or error message.

**Comment by mydigitalself** [comment]
What version are you on Milos?

**Comment by MilosStanic** [comment]
Gitter version v.2.3.2 , Windows 7 64bit. I updated the gitter application several times since it came out, and all versions kept crashing.

**Comment by MadLittleMods** [comment]
We are going to be doing some bug fixes on the 64 bit builds.
