### ISSUE TITLE
After removing the app I constantly get launchd messages in Console

### ISSUE THREAD

**Issue by aexmachina** [gitterHQ/gitter#666]
Here's the error message:

`16/04/2015 9:50:56.961 pm com.apple.xpc.launchd[1]: (com.troupe.gitter.mac.GitterHelperApp[2071]) Could not find and/or execute program specified by service: 149: Could not find a bundle of the given identifier through LaunchServices: com.troupe.gitter.mac.GitterHelperApp`

**Comment by mydigitalself** [comment]
Hmmm, odd. @suprememoocow any idea?

**Comment by timfallmk** [comment]
This seems to be related to the mysterious `launchAgent` that gets installed with the app. Also applies to #355

**Comment by suprememoocow** [comment]
Hi @aexmachina 

Would you mind trying to fix this by unchecking "Launch at Startup" from the Gitter menu, then checking it again?

Thanks
Andrew

**Comment by suprememoocow** [comment]
Alternatively, you could run 

```sh
launchctl remove com.troupe.gitter.mac.GitterHelperApp
```

To remove the launch agent....
