### ISSUE TITLE
Collapse all function `/collapse all`

### ISSUE THREAD

**Issue by Haroenv** [gitterHQ/gitter#668]
Some codepens can be hidden and take a lot of cpu, so `/collapse all` would be a good feature, collapsing all media open at that moment.

**Comment by Haroenv** [comment]
Apparently this has been fixed. Thanks!

**Comment by MadLittleMods** [comment]
@Haroenv Thanks for maintaining the issue.

This was added 14 days ago https://github.com/troupe/gitter-webapp/commit/2c897bbb38131334576bccd430509c69ea374df2

`/collapse-all`: Collapse all chats in room
