### ISSUE TITLE
Compensate for clock skews

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#673]
If your clock is skewed, message ordering can get really messed up. We should be able to compensate for this on the client?

**Comment by spudowiar** [comment]
Use WebSockets (maybe implemented through Faye? - I don't know, I've never used Faye) and send a message to sync the clock every few seconds.

**Comment by suprememoocow** [comment]
When you send a message we already compare the client time and the server time and issue a warning if it's large. At the moment, we just issue a warning in the console, but we can actually use the value to offset the message times.
