### ISSUE TITLE
Clicking close button for private chat shows single option menu

### ISSUE THREAD

**Issue by tjconcept** [gitterHQ/gitter#674]
I think it is unnecessary to show the menu with "hide" as the only option when trying to close a private chat. It makes sense with rooms though.

**Comment by mydigitalself** [comment]
One thing that does aid in is the accidental closing of a room, which is the main reason that menu was introduced. Going to close this as this is intentional.

**Comment by tjconcept** [comment]
Okay, fair. Thanks for your response :)
I do think though, that a brief "rejoin" message would be a better solution to that problem.
