### ISSUE TITLE
Wrong format for timespans when system language isn't English

### ISSUE THREAD

**Issue by dfyx** [gitterHQ/gitter#675]
First things first: I'm not even sure where gitter gets the info about my preferred locale. I just guess it uses my system language.

My system language is German which causes exactly one place in gitter's UI to switch to German. The info how old a message is, gets formatted as `vor 2 hours` which is a weird mix between the German `vor 2 Stunden` and English `2 hours ago`. Everything else is in English.

**Comment by trevorah** [comment]
Same. I've seen this with Japanese set as my preferred language. The prerender seems fine, but then the browser javascript kicks in and renders some weird mix that seems similar to @dfyx's english/german hybrid.

Prerender:

![screen shot 2015-04-27 at 11 43 27](https://cloud.githubusercontent.com/assets/298742/7346131/49fdf9b8-ecd3-11e4-97c8-9d1b1ae28597.png)

~1 second later:

![screen shot 2015-04-27 at 11 43 18](https://cloud.githubusercontent.com/assets/298742/7346133/4eeec218-ecd3-11e4-9a4c-4736b431f6e3.png)

**Comment by trevorah** [comment]
I've just done a quick bisect, and it looks like the changes to accept the new realtime-client broke this (https://github.com/troupe/gitter-webapp/commit/864e47d3837fc2cd4c5a0715f7f6b1a2dd731125).

@suprememoocow its a big commit, but my guess is that our old friend moment.js is the one having a giggle.

**Comment by dfyx** [comment]
Doesn't seem to be an issue anymore. The new layout always shows the time instead of "x minutes ago".
