### ISSUE TITLE
Extended charset suport for Source Sans Pro

### ISSUE THREAD

**Issue by Alex-Bond** [gitterHQ/gitter#677]
Hi!

Can you include Source Sans Pro form with russian letters? https://github.com/adobe-fonts/source-sans-pro
Cuz right now when we typing in russian is shows in Helvetica font.

**Comment by mydigitalself** [comment]
Have a fix for this, just need to do some further testing and will probably get it onto next.gitter.im next week.

**Comment by mydigitalself** [comment]
Hey there,

We've deployed this change onto Gitter Next. If you aren't on Next, here are instructions to enable:

For Browsers:
Visit http://next.gitter.im
Flick the switch
Refresh your Gitter page

For Mac App:
Do the above in Safari, then close and open your Gitter App

For Windows & Linux apps
On the Gitter menu, you will find an option to enable Gitter Next

Please let us know if this is better for you, as we're not really that familiar with reading cyrillic characters. We will roll this out to everybody in the next few days, but just wanted to get some feedback on it first.

Thanks
Mike
