### ISSUE TITLE
Grouping channels

### ISSUE THREAD

**Issue by LukyVj** [gitterHQ/gitter#678]
Group channels on the left menu.

For example, at bullgit, we have about 10 channels and we'd love to be able to stack them into a "bullgit folder" on the left menu.

**Comment by reimersjan** [comment]
+1

**Comment by Haroenv** [comment]
++++++

**Comment by MadLittleMods** [comment]
This has been addressed on the new left-menu work done recently with the minibar on the very left that we added. It is currently behind the [`left-menu` feature toggle](http://next.gitter.im/) and we recommend you don't use it at the moment but will be available when we cut the next release.

![](http://i.imgur.com/hdpHrdX.png)
