### ISSUE TITLE
People list with names

### ISSUE THREAD

**Issue by quintesse** [gitterHQ/gitter#684]
A bunch of icons is pretty annoying, you have no way to see at a glance who is actually who. Even worse because the only way to get their names is to hover over the icons one by one which is a very slow process.
A preferences option to show the list more like an IM chat list (icon + name) would be much much appreciated.

**Comment by malditogeek** [comment]
Hi @quintesse, totally agree. This is already in progress and will be shipped soon, probably start of next week.

**Comment by quintesse** [comment]
Great! :)

**Comment by quintesse** [comment]
Btw, not sure how you guys implemented this in the end, but taking into account a related issue like #451 it would be a good option to have the most active users listed first (green first, then orange by last time they were active)

**Comment by mydigitalself** [comment]
@quintesse in the up-coming release the roster is still a small number of avatars (up to 25), but you can then open that up to explore more and see full names and usernames. this way we preserve space on the right and allow you to explore deeper.

In terms of ordering, we're going to be doing some more work on that soon to sort by activity.

**Comment by quintesse** [comment]
Thanks for the feedback @mydigitalself !
It must be because we haven't defined any integrations yet, but for us the bar on the right is mostly empty :)

**Comment by trevorah** [comment]
@quintesse Here's a little preview of the explorable people list:

![screen shot 2015-05-12 at 13 52 41](https://cloud.githubusercontent.com/assets/298742/7587507/c30eed12-f8ae-11e4-99b2-50b60c1a8e79.png)

**Comment by quintesse** [comment]
Ok, and will it show their online status as well? Would it perhaps be possible to show their last online time?

**Comment by trevorah** [comment]
@quintesse we wont be showing online status or time in this release.
