### ISSUE TITLE
Retry button

### ISSUE THREAD

**Issue by tombentley** [gitterHQ/gitter#687]
My internet connection is not the best and connections often get broken. In gitter I see this as a message I sent going red. I then have no indication that an attempt is being made to retry sending the message, nor any way to initiate such a resend (if I need to, I don't know whether I do because there's no indication!)

An indication that resend is being attempted would be good. Also an idea about what went wrong would be nice (in hangouts in gmail I see actual HTTP status codes).

**Comment by tombentley** [comment]
Actually there *is* a way to initiate a resend: Edit the message (within the 10 minute deadline), but you have to change it by at least one char.

**Comment by mmic-bjohnson** [comment]
:+1: I, too, would like to see a "Retry" option for messages that fail to be sent the first time.

**Comment by abhisekp** [comment]
:+1: My connection sometimes fails too :smile:
