### ISSUE TITLE
Disable syntax highlighting

### ISSUE THREAD

**Issue by lucaswerkmeister** [gitterHQ/gitter#689]
Stacktraces and certain other plain text look hideous with syntax highlighting applied. It would be nice if a special language `text` and/or `plain` would disable syntax highlighting:

````markdown

This is the output I get:
```text
compiler.classes:
    [mkdir] Created dir: /home/lucas/git/ceylon/ceylon-compiler/build/classes
    [javac] Compiling 479 source files to /home/lucas/git/ceylon/ceylon-compiler/build/classes
    [javac] /home/lucas/git/ceylon/ceylon-compiler/src/com/redhat/ceylon/ceylondoc/Section.java:25: error: package com.redhat.ceylon.compiler.typechecker.model does not exist
    [javac] import com.redhat.ceylon.compiler.typechecker.model.Class;
    [javac] ^
``​`

````

**Comment by trevorah** [comment]
As luck would have it, @mydigitalself is doing some stuff around this area right now. We'll see if we can add a cheeky enhancement.

**Comment by mbtesting** [comment]
yip, implemented ```text now and also the codepen auto-detection to toggle compose mode now kicks in when the language is specified. still WIP, hoping to get it into production next week. unfortunately the updated highlight.js seems a little slow and trying to fine tune it a bit. it's language detection is very primitive and it effectively highlights the text in **each** language it supports, then scores it. so it's basically taking the block of text and doing a load of regex against it something like 120 times.... :S

**Comment by lucaswerkmeister** [comment]
Sounds promising…

**Comment by mydigitalself** [comment]
This is actually shipped onto Gitter Next now btw and should be in wider production very soon. The markdown parser was upgraded as well and has better language detection now too.

**Comment by lucaswerkmeister** [comment]
great, thanks!

**Comment by lucaswerkmeister** [comment]
Closing this, seems to have been deployed to Main some time ago.
