### ISSUE TITLE
Font size in compose pane too large

### ISSUE THREAD

**Issue by dsyer** [gitterHQ/gitter#690]
The font sizes in the history and the compose panes are different, and I don't see a way to control them. The result is that I can barely read the history when the composition text is comfortable, or else I can read the history and only type a few words before the compose window scrolls.

**Comment by mydigitalself** [comment]
Can you please send a screenshot to visualise this please, perhaps we have different terminology, but the chat input and the chat display have the same font size, so maybe I'm missing something?

**Comment by dsyer** [comment]
added screenshot (can you see what I mean?)

Date: Wed, 13 May 2015 09:32:39 -0700

**Comment by mydigitalself** [comment]
I would if I could see the screenshot... am I being dumb, it's late here...

**Comment by dsyer** [comment]
I don't think GitHub issues accept attachments. I'll put it in a gist or something.

**Comment by dsyer** [comment]
Is this better?

![selection_002](https://cloud.githubusercontent.com/assets/124075/7618324/4e9a5768-f9a9-11e4-9ebb-4f1c578f1170.png)

**Comment by dsyer** [comment]
I know what causes this. If you set the font size via `chrome://settings/fonts` (like I did) it messes around with gitter. I don't know why, but that's how to reproduce it. I'm using Chromium 41.0.2272.76.

**Comment by mydigitalself** [comment]
Ah right, thanks for the clarification, I've been scratching my head trying to reproduce this.

**Comment by mydigitalself** [comment]
How exactly do you change it there?

**Comment by dsyer** [comment]
I think if you just select "Tiny" as the default size in the dropdown?

**Comment by mydigitalself** [comment]
Ah, when opening chrome://settings/fonts it shows some modal with other settings. Dismissing that shows the settings I was looking for.

Found the problem. The chat input text is specified in px whereas everything else is in em, so that would make sense as to why that's happening. Thanks for pointing it out, will look to get a fix out for this.

**Comment by MadLittleMods** [comment]
The font sizes are no longer different when setting the browser font size to different values. But it also doesn't respond to the browser relative size setting. @dsyer Was this also desired?

**Comment by dsyer** [comment]
I don't know what you mean. I can see things are different now: the general serif font in history and compose seem to scale nicely. But the monospace (code snippets) in the history are horrendous (too large generally) when I scale up the main window fonts.

**Comment by MadLittleMods** [comment]
@dsyer I was commenting that I no longer see the difference outlined in your screenshot above when adjusting the browser font size setting.

Create a new issue about the code snippets and fences reacting to the browser font-size setting while the rest of the message stays the same size regardless.
