### ISSUE TITLE
Unable to exit rooms in iOS app 

### ISSUE THREAD

**Issue by Smulligan85** [gitterHQ/gitter#696]
Once I enter a room via the iOS or desktop app, I can't exit the room via the ios app. I can only exit via the desktop app.

**Comment by trevorah** [comment]
This is on the backlog, and we're working on the ios app at the moment. Internal issue link for secret peeps: https://github.com/gitterHQ/gitter-ios-app/issues/43

**Comment by watsoncj** [comment]
Still broken. Seems important to fix since it makes people hesitant to explore rooms.

Here's a workaround:

- Send `/leave` message
- Double click bottom home button
- Swipe gitter app to close
- Reopen gitter app

**Comment by MadLittleMods** [comment]
@watsoncj It is in the new version of our iOS app which is in beta atm but will be rolled out soon when Apple approves.

**Comment by trevorah** [comment]
It's just been approved, so Im going to close this.
