### ISSUE TITLE
add option to hide menu bar icon

### ISSUE THREAD

**Issue by romeovs** [gitterHQ/gitter#697]
I really do not use it and it clutters up my space.

It would be nice to have an option to hide the menubar icon of the gitter app on Mac OS.

**Comment by mydigitalself** [comment]
You mean like this?
![menubar](https://cloud.githubusercontent.com/assets/1491887/7722670/5445c66c-feda-11e4-882b-cc96d20eac23.png)

**Comment by romeovs** [comment]
Wow, emberassing.

I totally missed that sorry!

**Comment by mydigitalself** [comment]
Classic quote from my father:
"For every mistake made for not thinking, 1000 made for not looking". 
:)

**Comment by romeovs** [comment]
nice one!

not that I didn't look. I just over-looked the settings in that specific menu 😊

**Comment by mydigitalself** [comment]
Yeah I think there's an inherent "properly" in that quote somewhere ;)  probably it's mostly a man thing, like when I open the fridge and I'm like, WHERE'S THE MILK. WHY ISN'T THERE ANY BLOODY MILK IN THE FRIDGE and my wife is like, it's right there in the door you bloody idiot.
