### ISSUE TITLE
Can't click on links that are in the latest message

### ISSUE THREAD

**Issue by fannarsh** [gitterHQ/gitter#699]
The link gets functional as soon as a new message appears in the chat.
I'm experiencing this in both a group and person-to-person chat rooms.
And I'm on Mac OS X, Gitter Version 1.162 and running Next

**Comment by mydigitalself** [comment]
Hey :) yip aware of the issue we just pushed a **massive** infrastructure marionette 2.0 change to next and there are a couple of dangly bits to fix that we've started picking up. Will have a fix for this one out tomorrow.

**Comment by fannarsh** [comment]
I'm not experiencing this anymore so I believe it's save to close this.
