### ISSUE TITLE
Unable to leave room for Organization I am no longer a member of

### ISSUE THREAD

**Issue by tyrsius** [gitterHQ/gitter#703]
When trying to leave a room, I get an unknown error. I am no longer allowed to access the room. The `leave` option doesn't even show up, just the `hide` option. It causes an a 403.

![Error Screenshot](http://i.imgur.com/YOje49o.png)

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/808

**Comment by MadLittleMods** [comment]
Closed in favor of https://github.com/gitterHQ/gitter/issues/808
