### ISSUE TITLE
To Big header when repository has long description

### ISSUE THREAD

**Issue by Flyingmana** [gitterHQ/gitter#707]
in https://gitter.im/magento/magento2 we have a very long description of the repository, that causes to hide some messages on the top.

Fixing the height of the header, maybe with an scrollbar would solve this for example.

Sadly I dont find the correct repository for this, else I would send a PR for this.

**Comment by mydigitalself** [comment]
Hi, we're aware of the issue, it only blocks the very first message of the chat, once you've got many messages it really doesn't harm anything. Will look to fix it soon.

Just a suggestion: double click on the description and set the topic to something shorter, not sure you need that full disclaimer there as part of the chat?

**Comment by Flyingmana** [comment]
thank you, was not aware it is editable inside of gitter, have forwarded it :)
