### ISSUE TITLE
Font quality problem when using FireFox ...

### ISSUE THREAD

**Issue by pekr** [gitterHQ/gitter#708]
There is a problem with font quality when using FireFox. At least on my machine, so sorry for possible confusion, if it works for others.

Here's the screenshot:

![gitter-font-quality-problem](https://cloud.githubusercontent.com/assets/956496/7913378/d1a9c09c-086f-11e5-887b-d3a266f3e6be.jpg)

Windows 8.1, 64bit. Other websites look OK, so hopefully not a rendering/scaling problem ...

**Comment by mydigitalself** [comment]
Ah, this is a Firefox/Windows font rendering issue we've seen once before.

https://twitter.com/gitchat/status/601326242839801856

The previous person who experienced this changed some of their settings with https://github.com/renkun-ken/MacType.Source

**Comment by pekr** [comment]
Well, changed the about:config FF section to suggested settings, installed all those suggested fonts, but there's no precise description of how to further tweak FF. 

So, unless this is fixed (we are in 2015 and if all other sites work correctly, I really expect it being a problem of Gitter and imo no such tweaks should be needed), I am reverting to the desktop app ...

**Comment by mydigitalself** [comment]
We use a particular web font (Source Sans Pro). This works perfectly fine on Mac & Linux in Firefox and it works perfectly fine on Windows 8.1 in Chrome and actually works just fine on Windows 7 and Firefox. We still believe it's a rendering issue in Firefox on Windows 8.1 and may have something to do with that particular web front. 

We're trying to figure out what exactly is causing the issue, but thought we'd point out that something similar had been experienced by somebody and he did seem to solve the issue by that link I provided. 

We'll still carry on trying to find out of the issue, but it's certainly not something **we** seem to have control of.

**Comment by mydigitalself** [comment]
Voila: https://bugzilla.mozilla.org/show_bug.cgi?id=1155039

Firefox bug. Seems their OTF font rendering isn't working without hardware acceleration on Windows 8. We could probably work around this by using TTF, but OTF is certainly a better font format to use.

**Comment by pekr** [comment]
Not sure if you fixed something, or if after the restart of the PC above fonts + settings made a difference, but I can get nice output in FF now. So, closing the ticket ...
