### ISSUE TITLE
BUG: Was not asked to have a Badge PR posted to repo

### ISSUE THREAD

**Issue by onebree** [gitterHQ/gitter#709]
Desktop, Firefox ESR 31.6.0

I created a room for a public repository. I did not see a checkbox asking if I wanted a PR for the Gitter badge. I visit the repository, and there is such a PR.

I did not intend to release the information for this channel immediately, in case I wanted to remove it.

I have since sent a support ticket to have the room, if possible removed.

**Comment by gitter-badger** [comment]
I have removed the fork and the pull request.

**Comment by trevorah** [comment]
Thanks @gitter-badger

**Comment by onebree** [comment]
:+1:

**Comment by mydigitalself** [comment]
Would just like to point out the checkbox which appears everywhere we send pull requests.

![screen shot 2015-06-02 at 08 50 24](https://cloud.githubusercontent.com/assets/1491887/7947121/f7abb80a-0972-11e5-808c-fd8b6f07a91e.png)

**Comment by onebree** [comment]
@mydigitalself I did not get that checkbox. I listed my browser, because IDK if it is related to scripts crashing (which tends to happen to me on Firefox at work).

**Comment by mydigitalself** [comment]
That checkbox is hard-coded onto that screen, it's impossible not to get it if you got that screen and successfully created the room. 

If you can reproduce otherwise, I'd happily investigate further.

**Comment by TheDiamondYT1** [comment]
Isint @gitter-badger A bot? If so, how did it just say "i removed the fork"?

**Comment by trevorah** [comment]
@TheDiamondYT1 please dont comment on issues that have been closed for a year unless it is constructive.
