### ISSUE TITLE
Message resource(API) should contain a field to indicate a message was sent via an app

### ISSUE THREAD

**Issue by dasher** [gitterHQ/gitter#710]
The message resource should contain a field in the meta to indicate an app sent a message, rather than a user.

Ideally a non-null field indicates the message was sent via an app rather than by a user.

This would help routing and escalating messages between systems without having to resort to creating "system" users or by prefixing messages in devops situations.

**Comment by MadLittleMods** [comment]
@suprememoocow Are you looking to mark a field essentially as "sent by robot"?

What is your use case?

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/1076
