### ISSUE TITLE
Gitter next not jumping to old unread /all mention

### ISSUE THREAD

**Issue by timlind** [gitterHQ/gitter#715]
![screen shot 2015-06-05 at 2 56 19 pm](https://cloud.githubusercontent.com/assets/237741/8006336/15661fe4-0b93-11e5-9d8e-2c6e0378f3c6.png)

**Comment by trevorah** [comment]
Thanks Tim!

**Comment by suprememoocow** [comment]
Thanks @timlind!

**Comment by suprememoocow** [comment]
Ok, that's fixed on staging. Thanks once again for the bug report Tim...
