### ISSUE TITLE
Plaintext email notifications need a space before the URL

### ISSUE THREAD

**Issue by bamos** [gitterHQ/gitter#718]
![image](https://cloud.githubusercontent.com/assets/707462/8056356/2e632fe8-0e75-11e5-8a64-90df9a5c6ce4.png)

**Comment by mydigitalself** [comment]
Thanks for the report, amazed nobody else has spotted this. Fix in develop, will deploy early next week alongside some other fixes.

**Comment by bamos** [comment]
Hi, it looks like this is still an issue in plaintext notifications about private messages.

**Comment by MadLittleMods** [comment]
@bamos  See https://github.com/gitterHQ/gitter/issues/880
