### ISSUE TITLE
Search bar is not perfect in safari

### ISSUE THREAD

**Issue by navee7** [gitterHQ/gitter#719]
In Safari, when the search bar is clicked, the white background extends beyond the close button..

In IE, Search bar is not clickable... Y is that?? I'm using IE 10

The link is 
http://materializecss.com/navbar.html

**Comment by trevorah** [comment]
Is this a bug for the gitter app, or for materialize?

**Comment by navee7** [comment]
Its for materialize

**Comment by mydigitalself** [comment]
These issues are for Gitter the app, not for materialize. You can chat with those folks here: https://gitter.im/Dogfalo/materialize

**Comment by navee7** [comment]
Sorry..
