### ISSUE TITLE
Visual indication when disconnected

### ISSUE THREAD

**Issue by tombentley** [gitterHQ/gitter#722]
It would be nice if there was a obvious "You're disconnected" message when you're in a room and the webapp is unable to keep the conversation up to date. Otherwise it's possible to think there's no conversation happening when there is, but you just happen to be disconnected for some reason.

A way to "retry now" would also be good. 

Basically make it work like gmail :-)

This is somewhat related to #687, except this is about when you're just reading, that's about when you're posting.

**Comment by MadLittleMods** [comment]
This is now implemented. You can enable `next` and the `connectivity-indicator` feature toggle to see it now: http://next.gitter.im/

![](https://i.imgur.com/zfEZ7cT.gif)

You can follow https://github.com/gitterHQ/gitter/issues/687 for the retry feature.

**Comment by tombentley** [comment]
Thanks!
