### ISSUE TITLE
"Ghost" room after project renamed on github

### ISSUE THREAD

**Issue by jeankirchner** [gitterHQ/gitter#723]
We recently renamed our project in github, and for some reason I can't leave the corresponding room on Gitter.

The room is "guia-de-servicos" in the image bellow, which is the project that we renamed to something else.
![image](https://cloud.githubusercontent.com/assets/576918/8105860/1f2d64a4-1013-11e5-9c51-02baeaf72343.png)

Also, since the room is there, once I try to view it again, an 404 error happens, image bellow:
![image](https://cloud.githubusercontent.com/assets/576918/8105889/62371ca4-1013-11e5-9926-ada8a079d2b4.png)

And when I try to click on "x -> Hide" (there is no leave option), nothing happens and the "ghost" room stays there, but an javascript error in the console, image:
![image](https://cloud.githubusercontent.com/assets/576918/8105940/baa11b42-1013-11e5-9466-ace4189cd5bb.png)

**Comment by mydigitalself** [comment]
Yeah, unfortunately GitHub's API doesn't support renames - yet.

Can we delete the old room entirely on our side that will remove all the old chat history from guia-de-servicos

**Comment by jeankirchner** [comment]
We'd like to keep the history if possible, or perhaps transfer it to the new chat room that we're using for our project: servicosgovbr

**Comment by mydigitalself** [comment]
So if we moved all the chat messages from guia-de-servicos (repo room) into servicosgovbr (org room) that would work for you?

**Comment by jeankirchner** [comment]
Yes, that'd be great :D

Thanks very much.

**Comment by mydigitalself** [comment]
That's pretty odd, I can't find the old room in the database, do you still see it in your left menu? What was the original full URL of the repo?

**Comment by jeankirchner** [comment]
Hi, I was checking if someone else in my team had talked to Gitter to do that already, and see if the channel was deleted or the history moved already. But they didn't.

The original URL was: https://github.com/servicosgovbr/guia-de-servicos

If it's not possible anymore, that's alright.

**Comment by mydigitalself** [comment]
Hi there, it looks like the room was removed when our new code detected the new room was created. Can you confirm the ghost room is now gone?

**Comment by jeankirchner** [comment]
Yes, it is :)

Thanks for your help!
