### ISSUE TITLE
Feature Request: Nested chat room names

### ISSUE THREAD

**Issue by rizowski** [gitterHQ/gitter#724]
I hope I didn't miss this being recommended somewhere but here is my idea:
I have noticed on the desktop and on the mobile app, there is a lot of noise when looking through your chat room listings. I have noticed that they are all namespaced `{username | groupName}/{repoName}`. It would be nice to have all the related chat rooms under one username / groupname in some kind of dropdown. It would make it a shorter list to look at and they can be grouped under the org or username they belong to.

Example:
```
Rizowski
  | - eslint-watch
gitterHQ
  | - gitter
  | - desktop
DarthFubuMVC
  | - fubumvc
  | - Serenity
```

**Comment by mydigitalself** [comment]
Hey, thanks for the suggestion, we've been thinking about this for quite a while now and will look to have a solution in the near future.

**Comment by tjconcept** [comment]
:+1:

**Comment by MadLittleMods** [comment]
We are looking at alternative solutions to address the same need.

**Comment by MadLittleMods** [comment]
See https://github.com/gitterHQ/gitter/issues/678#issuecomment-187423984
