### ISSUE TITLE
No wrapping for source code snippets

### ISSUE THREAD

**Issue by jfschwarz** [gitterHQ/gitter#725]
Apparently you introduced text wrapping for source code block snippets in ```s. I do not get why, since code with longer lines is now practically unreadable.

I'd really like to see this change reverted.

**Comment by mydigitalself** [comment]
That's very odd, certainly not intentional and going through the code changes around that area and can't find anything that would be causing that.

Thanks for reporting, will investigate further.

**Comment by mydigitalself** [comment]
Fix will be deployed to next.gitter.im in about 10 mins and then into production either later today or tomorrow.
