### ISSUE TITLE
Org 404 page doesn't show if the org room has >25 users

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#737]
The order of the logic to display the Org 404 page with the list of repos is obviously kicking in AFTER the logic that detects if there are 25 people in the org room.

**Comment by malditogeek** [comment]
@mydigitalself who had the issue? have you seen this happening to someone else?

Can't reproduce it locally: 

![screen shot 2015-06-23 at 14 55 47 2](https://cloud.githubusercontent.com/assets/14751/8307766/6113215c-19b8-11e5-98fb-a1f268c87bec.png)

**Comment by mydigitalself** [comment]
What's even stranger is that when I received the message, it was a full
screen Upgrade to Pro message, not a modal.

Ah, no... you are unauthenticated in the screenshot on the right. Sign in
as a test user not in the org and then visit /dawgs.
