### ISSUE TITLE
Show opening/closing issues in realtime between chat messages

### ISSUE THREAD

**Issue by Odonno** [gitterHQ/gitter#746]
Tracking system based on issue is precious, but it could be far better with Gitter.

It could be great if users (and collaborators) can instantly see the opening / closing of issues in the chat.

Not like the right panel where you can follow the link to GitHub, but to see in one line of chat (between other messages). It does look easier (with title of the issue and the icon : red/green).

The goal is to allow people to follow the workflow of the development from Gitter. What was recently done ? What was recently created ?

**Comment by mydigitalself** [comment]
We used to have this capability and found that it interfered with the conversation. We will revisit this in the future when we revisit our integrations platform. I'm going to close this particular issue as it's on our radar in general

**Comment by Odonno** [comment]
No problem, but do you have data that prove that it is not valuable ?

In my case, I would like a message that tells me if I want this one or another feature in the app, like a popup...
