### ISSUE TITLE
Wrong parser

### ISSUE THREAD

**Issue by githubjeka** [gitterHQ/gitter#747]
![image](https://cloud.githubusercontent.com/assets/874234/8355369/88c79e30-1b57-11e5-939d-790ebb6fbbc1.png)

When I send four or more space before any text then it will be parser as code block.

**Comment by Lixquid** [comment]
This is actually part of the original [Markdown Spec](http://daringfireball.net/projects/markdown/syntax#precode)

**Comment by githubjeka** [comment]
:) I don't know. Thanks.
