### ISSUE TITLE
Add feedback button

### ISSUE THREAD

**Issue by mitchhentges** [gitterHQ/gitter#749]
To figure out where I could leave feedback for Gitter, I had to manually look it up. It would be far more convenient if there was an option in the top-left menu. Besides, that would also place an emphasis on Gitter's priority on support and improvement

**Comment by mydigitalself** [comment]
The support button - bottom right takes you to our support page where a lot of people give us feedback too. We are also working on a better in-app help area that will surface the many ways we're always listening to feedback.
