### ISSUE TITLE
IRC doesn't work :(

### ISSUE THREAD

**Issue by mitchhentges** [gitterHQ/gitter#750]
```
10:50 -!- Irssi: Looking up irc.gitter.im
10:50 -!- Irssi: Connecting to irc.gitter.im [107.23.228.38] port 6667
10:50 -!- Irssi: Connection to irc.gitter.im established
10:50 -!- Irssi: Connection lost to irc.gitter.im
```

I've tried both `ircii` and `irssi`. Many sads were had on this day

**Comment by mydigitalself** [comment]
Are you providing a server password you obtained from http://irc.gitter.im ?

https://gitter.zendesk.com/hc/en-us/articles/201867132-Why-won-t-my-IRC-client-connect-

**Comment by mitchhentges** [comment]
Ah, I can't provide my token after connection, it needs to be in config. Thanks!

**Comment by mydigitalself** [comment]
No more sads!

**Comment by mydigitalself** [comment]
Such happy.
