### ISSUE TITLE
Ctrl + F Search Hijacking is evil

### ISSUE THREAD

**Issue by qubodup** [gitterHQ/gitter#751]
Hi,

When an experienced user wants to search the currently viewed chat for a word, gitter says "no way".

Commented video: http://youtu.be/B-oaPbnUxiQ

Steps to reproduce:
1. go to a chat and press ctrl+f and enter a search term that was used in said chat. Press enter.

Expected result:
quickly highlight and jumping through result of that term in the current chat.

Actual result:
First nothing happens for seconds. Then a new chat opens.

Solution:
You can react to the user using ctrl+f and inform them of what tools the site offers but you shouldn't hijack the key combination.

**Comment by kotp** [comment]
:+1:

**Comment by jrafanie** [comment]
I don't know that only advanced users expect the browser's find to work. I would expect gitter to use a different key combination or at the very least, make it Opt in. As it is now, I can't find anything quickly even 3 or 4 pages up in the current room.

**Comment by garth** [comment]
Same issue of OS X with cmd+F.

**Comment by Suor** [comment]
+1

**Comment by MadLittleMods** [comment]
On a non-sighted user note, with a screen reader: NVDA has `NVDA + Ctrl + F` that lets you find on page.

This interaction needs improvement for keyboard users regardless of the `Ctrl + F` binding though and I separated it into this issue: https://github.com/gitterHQ/gitter/issues/1176

**Comment by MadLittleMods** [comment]
The search shortcut has moved to `Ctrl + S`
