### ISSUE TITLE
add link to gitter.im/explore in the web client search results

### ISSUE THREAD

**Issue by rozzzly** [gitterHQ/gitter#756]
So, in the gitter web client I was trying to find new rooms; not necessarily for any one repo,but in general. I wasn't really finding anything with the search bar as it only matches the query against `users` and `user`**/**`repo`. I went to `gitterHQ/gitter` and asked if there was a better way. Took like 20min before I got a response. Durring that time I found (gitter.im/explore)[https://gitter.im/explore/tags/javascript,php,ruby] which was reccomened to me minutes later by @abs @rhutchion (Thanks again guys!) The explore page works/looks great. Yet, from within the actual chat client you don't have anything of the sort. 

##### My suggestion is simple: put a link advertising (gitter.im/explore)[https://gitter.im/explore/tags/javascript,php,ruby at the bottom of the search's autocomplete results.

That's a quickfix and it would definitely promote exploration/interaction. Not to mention, that others might avoid my issue in the future.

And, if you wanted _the-whole-kitchen-sink_... you could even integrate part of the explore page right into the client.

**Comment by mydigitalself** [comment]
We're working on this right now... :)
