### ISSUE TITLE
Android App always returns to Room that was shown when App Launches

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#759]
Reproduction instructions:

1. Open the Gitter Android app and observe the room("foo") that is initially shown.
1. Switch to a different room, "bar"
1. Go away from the Gitter app
1. Switch back tot he Gitter app and observe how it goes to the initial room "foo", instead of the expected "bar"

Here are some other notes on the behavior:

 - You can change the initial room open by changing to that room and closing the app(swiping away).
 - Going to the home screen has the same effect as switching apps.
 - Locking and then unlocking the device while the app is up has the same effect.

---

Nexus 7 2013
 - Android 5.1.1
 - Gitter app v1.0.0 according to the App info

**Comment by rhutchison** [comment]
+1 Having the same issue on android

* Android 5.0.1
* Gitter 1.0.0

**Comment by MadLittleMods** [comment]
While looking through all of the Android bugs, I discovered this is a duplicate of #463.

**Comment by trevorah** [comment]
Reopening as this was closed by a commit that is only on beta atm.

**Comment by trevorah** [comment]
beta program opt-in if you're curious: https://play.google.com/apps/testing/im.gitter.gitter
