### ISSUE TITLE
Github did something weird. Refresh the page to try again.

### ISSUE THREAD

**Issue by groovy354** [gitterHQ/gitter#761]
I accidentally revoked access for github webhooks in Github settings. Now when I want to update integration settings, Gitter shows this message:
```
Github did something weird. Refresh the page to try again.
```
It seems I need to somehow reset the webhooks settings in Gitter, but how?

**Comment by mydigitalself** [comment]
If you sign out of Gitter and sign back in again, does this fix the issue?

You can do this my clicking on yourself (top left) and choosing Sign out.

**Comment by groovy354** [comment]
I tried it and it didn't help

**Comment by mydigitalself** [comment]
One more thing to try is to do that again, quit all of your browser instances and then try again. If not, can you please email support@gitter.im.

**Comment by groovy354** [comment]
It helped! Thank you.

**Comment by f3l1x** [comment]
Hi. I have a same problem with my channels. 

- https://gitter.im/minetro/nette
- https://gitter.im/Markette/Gopay

I cannot change/add new integration with Github.
