### ISSUE TITLE
Split conversations from rooms, like organizations

### ISSUE THREAD

**Issue by tjconcept** [gitterHQ/gitter#763]
Even though I can drag and arrange rooms and conversations, they still jump around when I get a message.
It would be nice if chats were separated from rooms just like organizations are.

**Comment by mydigitalself** [comment]
Not sure I quite understand? Can you elaborate on how this would look or behave?

Note your favourites **should not** jump around. Conversations below the favourites re-order depending on when you last spoke there, sort of like a recents list - although there's a bug in there at the moment that's causing this to not behave exactly as designed, but the regardless, they should still jump around such that rooms with unread message surface to the top.

**Comment by tjconcept** [comment]
What I'm suggesting is a heading e.g. "Conversations" under which all 1-1 conversations were listed, so they're not mixed with rooms.

**Comment by MadLittleMods** [comment]
We are constantly looking to improve the usability of the left menu. We are doing some left menu work at the moment and this may or may not be implemented in the future.
