### ISSUE TITLE
Initial login Search not displayed

### ISSUE THREAD

**Issue by TeckniX** [gitterHQ/gitter#764]
Why is it not possible to allow for a user to search for existing room on initial app load?
I can:
* Create a room
* Go to my orgs
* Open one of the suggested room

That's it! Shouldn't I be able to search also for existing rooms initially? Instead I have to use one of the suggested rooms and then search for the room I'm interested in.

**Comment by MadLittleMods** [comment]
You can use the [explore page](https://gitter.im/home/explore) to find rooms without being logged in. The new Gitter user home page links directly to the `explore` page but you may not see this version of the user home page yet.

Is this a bug where the search box(in the top right) is not available if you are not in a room yet?

**Comment by TeckniX** [comment]
That's correct - You cannot search for anything until a room is created - You can explore, but most of the recommended rooms are Gitter-based rooms

**Comment by mydigitalself** [comment]
We're making changes to this area in general over time, so going to close this issue as it's wrapped up with numerous other internal pieces of work.

**Comment by TeckniX** [comment]
:+1:
