### ISSUE TITLE
Organizations with Topics break the layou

### ISSUE THREAD

**Issue by TeckniX** [gitterHQ/gitter#765]
![rooms](https://cloud.githubusercontent.com/assets/33699/8624855/002710b6-2709-11e5-830a-32272f4908e0.png)

**Comment by mydigitalself** [comment]
This will be removed shortly.

**Comment by MadLittleMods** [comment]
I can't reproduce this issue anyway:

![](http://i.imgur.com/6gvSo9c.png)

**Comment by FrenchBen** [comment]
@MadLittleMods This isn't on the web app but the Mac OSX app -

**Comment by TeckniX** [comment]
@MadLittleMods This isn't on the web-app but rather on the Mac OSX app. Thanks for checking it.
