### ISSUE TITLE
Repo-linked channels do not link to GitHub content properly

### ISSUE THREAD

**Issue by vermiculus** [gitterHQ/gitter#766]
See https://gitter.im/vermiculus/texample/best-place-for-discussion?at=55a144273cc28b2c216cea7a

Content like `#3` isn't linking to `/vermiculus/texample/issues/3`. This is a pretty glaring error, but it's an easy fix. Channels already know which rooms they belong to (this information is even available with the API), so it's just a matter of using that information properly.

**Comment by MadLittleMods** [comment]
A channel with integration is not the same as a repo room. There is another issue dealing with setting the default repo for a room, move discussion there https://github.com/gitterHQ/gitter/issues/757
