### ISSUE TITLE
Markdown parsing issue with underscore italics

### ISSUE THREAD

**Issue by vermiculus** [gitterHQ/gitter#767]
See https://gitter.im/vermiculus/texample/best-place-for-discussion?at=55a1476c2840f1ff0c48a7c3

``` md
this _is_ a _test_
```

Another pretty glaring issue.

**Comment by grahamperrin** [comment]
> `this _is_ a _test_`

That test appears OK at https://gitter.im/gitterHQ/sandbox?at=5930f365142826e97275b061

>> … `I guess one thing to bear in mind is that mailing lists have been around a _long_ time and do work (archival, offline working, threading, take 'off list' when required, cross-post, _etc._). People with experience look at some of the 'new cool stuff' and think 'yes but ...'`

Appears OK in GitHub: 

I guess one thing to bear in mind is that mailing lists have been around a _long_ time and do work (archival, offline working, threading, take 'off list' when required, cross-post, _etc._). People with experience look at some of the 'new cool stuff' and think 'yes but ...'

– and in Gitter at https://gitter.im/gitterHQ/sandbox?at=5930f510142826e97275b616

## Further reading

If the issue recurs: [6.4 Emphasis and strong emphasis](https://github.github.com/gfm/#emphasis-and-strong-emphasis) under _GitHub Flavored Markdown Spec_
