### ISSUE TITLE
/gist command to create a gist from input

### ISSUE THREAD

**Issue by travs** [gitterHQ/gitter#768]
I know there are higher priority items than this, but it would be cool to have the ability to create a gist directly from within gitter. Could default to an anonymous gist maybe, or be linked to the repo you're chatting in somehow...

Anyway it's related to #583, which does not seem to be implemented yet

Great product, as always :+1:

**Comment by vermiculus** [comment]
I'm not sure GitHub's infrastructure supports repository-linked gists. I'm no expert, though.

Without saying it's a bad idea, why do you want this?

**Comment by travs** [comment]
@vermiculus Convenience only. In fact, I think it would be superfluous for gitter to provide this as I think about it, if you are in fact considering #583.
