### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Gouthamve** [gitterHQ/gitter#772]
I am getting the following error while trying to login:
```
Login Failed

We're very sorry, but we're unable to log you in right now. 
(No replica set primary available for query with ReadPreference PRIMARY)
```

Also the gitter Android app is crashing on launch!

Please look into it as I need to get on gitter urgently!

**Comment by Luceos** [comment]
Probably some sort of downtime. Experiencing the same. Frontpage of gitter.im shows several errors as well.

**Comment by abishekrsrikaanth** [comment]
Same here. Works fine now

**Comment by Gouthamve** [comment]
Working now. Thanks!

**Comment by abishekrsrikaanth** [comment]
Having the same issue again

**Comment by mydigitalself** [comment]
When exactly did you experience this issue?

**Comment by abishekrsrikaanth** [comment]
about an hour ago when all the channels on gitter was throwing a 500 ERROR

**Comment by mydigitalself** [comment]
But it's fine now, right?

**Comment by abishekrsrikaanth** [comment]
Yes, it is.

**Comment by mydigitalself** [comment]
You must be the most unlucky person ever, we switched over primary and secondary databases and there's about a 2 second gap in the switchover where this can happen.

**Comment by abishekrsrikaanth** [comment]
OK, it lasted for atleast 10 mins though. which is why I reported this issue. Wouldn't have if it was only for a few seconds...

**Comment by mydigitalself** [comment]
Today or the first time it lasted 10 mins? The first time you reported it was a different issue, so can understand that was a longer issue. Today should not have been that long.

**Comment by abishekrsrikaanth** [comment]
The one that happened 7 days ago was a bit more longer, but today's was definitely around 10 mins.

**Comment by abishekrsrikaanth** [comment]
@mydigitalself is it just me or is it happening to everybody.
Facing the same issue again. Been like this for almost an hour.

Error:
![Error](http://i.imgur.com/TYymiaql.jpg)

**Comment by mydigitalself** [comment]
It appears to be unique to you.

Do you do anything yourself with the GitHub API by any chance?

**Comment by abishekrsrikaanth** [comment]
Nope, I wonder why it is happening. Not sure how I figure out what is causing it. It starts to work again after sometime though

**Comment by mydigitalself** [comment]
The reason I ask is that GitHub's API is returning to us that you've exceeded your rate limit, that means we can no longer make API queries on your behalf.

Perhaps if you contact support@github.com and cc me (mike@gitter.im) and ask them if it's possible to see what is consuming your API rate limit on today's date, we might be able to get some insight. Unfortunately we can't do this on your behalf.

**Comment by mydigitalself** [comment]
The rate limit on GitHub's end resets every hour, which is why it starts working again btw.

**Comment by abishekrsrikaanth** [comment]
Just for info, could you tell me what API requests does gitter do on the application?

**Comment by abishekrsrikaanth** [comment]
The issue is back again. Wonder why it is happening this fast as well. Gonna send github an email now

**Comment by mydigitalself** [comment]
Well any time you see GitHub-related information, that's pretty much a GitHub call.

So issue status for example, commit mentions, hovering over people to get their details, etc...

We do some caching on our side to alleviate pressure on the API and looking at your account I really don't see enough activity there to warrant 5,000 requests in an hour. So my suspicion is that there's either something odd happening on your account or you have some other GitHub application that's consuming your API requests, and only GitHub will be able to tell us that.
