### ISSUE TITLE
Notifications are too short to be usable

### ISSUE THREAD

**Issue by arikfr** [gitterHQ/gitter#774]
It seems that you only use the title field of the notification, which results in the notification text being truncated and most cases only having the username and first word of the message.

Android support additional fields for extended notification text. This is a very simple fix that will improve the usability a lot. If it was open source, I would love to make the relevant pull request...

Today my flow is like this:
1. Get push notification.
2. Open Gitter in the _browser_ so I can read the message, but not loose the notification (which serves as reminder for when I actually have time to reply).
3. When I have time to reply, I open the app to reply.

**Comment by georgiel** [comment]
+1

**Comment by MadLittleMods** [comment]
@arikfr Notifications can now be pulled to be expanded and even reply directly, https://github.com/gitterHQ/gitter/issues/1204

**Comment by arikfr** [comment]
Thanks! Although I switched to an iPhone since :-)
