### ISSUE TITLE
Add Permalinks when not logged in - bookmarkable link

### ISSUE THREAD

**Issue by pdurbin** [gitterHQ/gitter#777]
To get a link to https://gitter.im/gitterHQ/gitter?at=55a8f9e80eba6b8e49826521 I have to log in first.

@mydigitalself asked me to open an issue about this: https://gitter.im/gitterHQ/gitter?at=55a90658c57ead8c6be0293a

**Comment by davilima6** [comment]
:+1:

**Comment by MadLittleMods** [comment]
:+1: Also need permalinks for one-to-one chats
