### ISSUE TITLE
Customisable Infoarea for Organisations

### ISSUE THREAD

**Issue by dervondenbergen** [gitterHQ/gitter#782]
I think it would be useful, if there is the possibility to have a customisable tab like "repo info" for repos but in the organisation channels.

We @bullgit are from all over the world and in our case something like a clock of the different timezones we are from would be useful to see.

That customisable Infoarea could maybe simply accept html, which would enable more complex infos, like an interactive world clock, which can be added via an iframe. The clock itself is simply hosted on our own server.

**Comment by MadLittleMods** [comment]
This is not part of the current plans. I am closing this issue but if it gets a lot more requests and attention then we will reopen.
