### ISSUE TITLE
Convenient way to go way, way back in the room's history

### ISSUE THREAD

**Issue by asampal** [gitterHQ/gitter#783]
I find that I often want to go way back in a room that has been around for a while and which I've just joined, in order to get a better sense of what's been going on. The only way that I have to reach that point in time is to keep scrolling, and scrolling, and scrolling, and scrolling.

Could gitter add a way to jump back to a specific point in time? The UI could be a simple popup with a calendar control. If the date selected is before the room started, then simply go to the beginning, or, better, just offer a one click button to go to the beginning, from the same UI.

**Comment by pdurbin** [comment]
It might be nice to be able to put dates in the URL like http://colabti.org/irclogger/irclogger_log/git?date=2015-07-22

**Comment by asampal** [comment]
As an additional way, sure, but it wouldn't be as convenient in terms of UX.

**Comment by malditogeek** [comment]
Indeed. All rooms have Archives, accessible through Tools icon -> Archives :)

For instance: https://gitter.im/gitterHQ/gitter/archives/all 

@pdurbin You can also pass a date in the URL: https://gitter.im/gitterHQ/gitter/archives/2015/07/23

**Comment by asampal** [comment]
The archives UI is quite nice. Good enough for me. Thanks for the pointer.

**Comment by pdurbin** [comment]
> You can also pass a date in the URL: https://gitter.im/gitterHQ/gitter/archives/2015/07/23

Ah, yes. It looks quite constrained on a phone but looks fine on a desktop. Thanks!
