### ISSUE TITLE
new github users have a bad first time experience

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#786]
They have no suggested rooms, and the whole left menu is blank

They have no search, so its hard to find rooms that they *do* know about.

**Comment by MadLittleMods** [comment]
Here is a screenshot of the experience atm:

![](http://i.imgur.com/zxGh3Ja.png)

**Comment by vRobM** [comment]
:+1:

**Comment by MadLittleMods** [comment]
The new user home covers all of these fronts:

![](http://i.imgur.com/j7eGimm.png)
