### ISSUE TITLE
Modal buttons are inconsistent

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#791]
* cancelling the action is either "close" or "cancel"
* cancelling the action is not in the same place (except for the `x` button)
* progressing the action is not in the same place
* progressing the action does not alway have the same color
* progressing the action does not alway have a button (see #698)

![screen shot 2015-07-24 at 12 41 50](https://cloud.githubusercontent.com/assets/298742/8873844/b320ccd0-3202-11e5-8971-5b4d1d9ed47a.png)
![screen shot 2015-07-24 at 12 53 35](https://cloud.githubusercontent.com/assets/298742/8873896/14c4ce8c-3203-11e5-8b20-774f59c19446.png)
![screen shot 2015-07-24 at 12 52 50](https://cloud.githubusercontent.com/assets/298742/8873888/f7116e22-3202-11e5-80c2-2c3c67d7a1c0.png)
![screen shot 2015-07-24 at 12 42 08](https://cloud.githubusercontent.com/assets/298742/8873845/b4f7aba0-3202-11e5-9e51-78aa36484ee2.png)
![screen shot 2015-07-24 at 12 42 23](https://cloud.githubusercontent.com/assets/298742/8873847/b6d13f0e-3202-11e5-912e-fb6b9094ae0f.png)
![screen shot 2015-07-24 at 12 42 44](https://cloud.githubusercontent.com/assets/298742/8873849/ba01f452-3202-11e5-9ca2-14517f94ee17.png)
![screen shot 2015-07-24 at 12 43 09](https://cloud.githubusercontent.com/assets/298742/8873851/be3e9750-3202-11e5-90a9-2e2c8cd8d732.png)

**Comment by mydigitalself** [comment]
https://drive.google.com/drive/u/1/folders/0B0AUErrr2iVUfkpZWGF5MWNzNmdhdC1wUnJCNUVuUjBaSmllSHh6dnAtUDFVS1o0Sl9VNFE

Contains the style guide, any questions, just ping @ricardobaeta
