### ISSUE TITLE
"Details" under user list is pretty pointless when the list is small

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#792]
![screen shot 2015-07-24 at 13 04 43](https://cloud.githubusercontent.com/assets/298742/8874021/aa11e118-3204-11e5-919f-08593641d7c5.png)

All the information is already there.

**Comment by MadLittleMods** [comment]
Details page has names and usernames. If the button was removed, you would have to hover for name or click on the avatar to bring up user tooltip for this information.

![](http://i.imgur.com/Hwo73z6.png)
