### ISSUE TITLE
Can't send any message from Android app 

### ISSUE THREAD

**Issue by perak** [gitterHQ/gitter#793]
I can write message, but "enter" key makes new line instead "send" message, and there is no "send" button, so I don't know how to send message from android app (???).

Gitter 1.0.0 / Android 5.1.1 / Nexus 7

**Comment by MadLittleMods** [comment]
I am also experiencing this after entering a triple backtick to start a code block. Even clearing it out and switching out of the app and back is not letting me send a message. I also tried to close and force stop the app but it is still in `compose`/multi-line mode

The android app needs a way to switch from `compose` to `chat` mode.

**Comment by perak** [comment]
@MadLittleMods thanks for temporary solution.

**Comment by perak** [comment]
I am just using gitter from tablet and it looks like issue is solved (now icons for multi line mode are shown). Closing this issue. Thanks!

**Comment by MadLittleMods** [comment]
I can't see the icons unless I use [`Rotation Control`](https://play.google.com/store/apps/details?id=org.crape.rotationcontrol) app(see above) to force it into landscape. The Gitter app just needs to support both orientations at the very least.

**Comment by perak** [comment]
Ooops, you're right. No icons - maybe I was in browser today when I saw icons.

**Comment by smiller171** [comment]
:+1:

**Comment by trevorah** [comment]
The fix is currently on beta. You can take a look by joining the beta program: https://play.google.com/apps/testing/im.gitter.gitter

**Comment by smiller171** [comment]
@trevorah No, the issue isn't fixed in beta. It's now impossible to properly send code formatted messages on mobile.

If I put in "```" the old behavior would let me hit enter to go to a new line, the new behavior is to send an empty code format block

I think that the only valid behavior here is to allow newlines in code blocks and have an always-visible send button (like hangouts)

**Comment by MadLittleMods** [comment]
@smiller171 :+1:

> I would prefer just to show a normal/compose toggle rather than removing it for mobile
>
> [...] push a separate "send" button to send a message and enter/return does a new line
>
> *Source: my comment from an internal PR*

**Comment by trevorah** [comment]
I've split adding a compose input / send button out into a separate issue: #873.

This issue was about compose mode incorrectly being enabled, and then being impossible to disable, resulting in people not being able to send messages. Im sorry that the fix means disabling a feature that was hidden on android, but I think that this bug was serious enough to warrant it.
