### ISSUE TITLE
0

### ISSUE THREAD

**Issue by ItamarShDev** [gitterHQ/gitter#794]
as you can see in the pic I have a JS line for some reason

using Chrome on Windows 8.1 64bit
![capture](https://cloud.githubusercontent.com/assets/953371/8907163/d45cd9a8-347c-11e5-9a55-989dc30861e9.PNG)

**Comment by MadLittleMods** [comment]
This is part of a funny quip to try to grab attention/attract some node.js backend developers to join the Gitter team.
