### ISSUE TITLE
Search in messages is missing lots of results

### ISSUE THREAD

**Issue by quintesse** [gitterHQ/gitter#795]
When using the search box on the main page it will not only search users and rooms but also the messages of the current open chat... good...

...except that the results are pretty strange. First of all they don't seem to be ordered chronologically and second many entries seem to be missing.

Just typing in words or parts of sentences that I see on screen or when scrolling back a couple of pages don't seem to appear in the result while it *does* show results from conversations months back!

This makes the search pretty useless IMO.

**Comment by trevorah** [comment]
Thanks for reporting this @quintesse, ive just finished rebuilding the search index, so the results should now stay up to date.

**Comment by quintesse** [comment]
@trevorah I see some improvement but I can still come up with several easy examples where the search doesn't work as expected:

![image](https://cloud.githubusercontent.com/assets/778793/8955796/41014b60-35f0-11e5-9d74-c601cc9ad063.png)

I typed the word "right" and as you can see there's one example right there on the page but it doesn't find it. Then if you look at the results you'll see they're all jumbled up.

But if I type the word "Emacs" it finds the two examples on the page just fine:

![image](https://cloud.githubusercontent.com/assets/778793/8955905/27d0f824-35f1-11e5-80ee-10bbd9bd8480.png)

**Comment by trevorah** [comment]
So you would expect them to be sorted from recent to oldest?

**Comment by quintesse** [comment]
What other order makes sense? In a chat you normally have some idea of chronology, so if you see a reference that talks about the same thing you might think "ok, that's the thread I'm looking for, but it was earlier in the conversation so it will come *after* this one". If the order is due to some search ranking you would have no clue. Search rankings are great for finding things in unstructured and unrelated data, but not for a chronologically ordered chat IMO.

**Comment by mydigitalself** [comment]
Firstly, I'll agree the ordering needs work. Right now we are using a very primitive, almost default Elastic Search relevance ranking.

But it's not as clear-cut as just ordering by date, relevance certainly comes into play too. For instance if you search for "phone number" where the string is exactly "phone number" should be first, whereas "phone me on this number" should also come back in the results but should not appear above an instance of "phone number" . Add stemming into the mix, the problems becomes a little more complex.

**Comment by quintesse** [comment]
Well then maybe an option to switch between "rank" and "date" ordering could be useful (although I understand that might go against wanting the interface to be a simple as possible)

**Comment by MadLittleMods** [comment]
@quintesse See #566

**Comment by trevorah** [comment]
@quintesse as there is an issue for the results sorting, and i've added more monitoring to catch stale search results, im going to close this. Thanks for spotting the original issue though!

**Comment by quintesse** [comment]
You're welcome!
