### ISSUE TITLE
Add or allow users to open/invite a chat about a public repo to the repo owner

### ISSUE THREAD

**Issue by vRobM** [gitterHQ/gitter#796]
Nothing like finding a cool repo or project and there's no way to ask a quick question or start interacting with the maintainers. Make it easy by having a button on github for requesting a chat be started, or have a temporary chat start so users can discuss and later have the project owners claim it or take it further.

**Comment by mydigitalself** [comment]
Hi Rob, we can't really add buttons to pages on GitHub without the owner's access and we've very intentionally not allowed people to create chats around namespaces or projects they don't own. Have you considered opening an issue on the project to get in touch and recommending the use of Gitter in that?

**Comment by MadLittleMods** [comment]
This issue seems to portray/propose something different than what you expressed in the [gitter chat](https://gitter.im/gitterHQ/gitter?at=55b6b618bda88f9578e643e5).

> Are you guys working on a feature to help owners of repos get enouraged/notified to start a room to discuss their project?

Visiting a page without a room could have a "I want to chat about user/repo" button. With that information, while we don't want to annoy repo owners with a email on a threshold, having those stats available to the repo owner when logging into Gitter could help convince them further to open a Gitter room for their community.

**Comment by vRobM** [comment]
You are right Eric, I took it a bit too far not realizing how the system
actually worked when trying to explain it. Thank you for the followup.

Thanks Mike for the reality check.

The stats play is much more plausible showing :1: interest or similar. If
enough people increment the counter in a short enough amount of time
(week?), it may make sense to let the repo owner know while keeping
relevant temporally.

-- Rob

about.me/vRobM
  [image: Rob Marković on about.me]
    <http://about.me/vRobM>

**Comment by briantopping** [comment]
Hi all, sorry to necro this thread. I had a rogue thought on this and @MadLittleMods pointed to this issue.

I am in agreement that rooms should not be opened without a repo owner authorizing them. It would probably lead to anger with some repo owners who are already doing their best and can't handle the added load, regardless of how well intentioned by fans of the repo.

That said, what if the room could be created in a "no posting" mode? In other words, a room for a repo that people can join, but nobody can post until the repo owner authorizes the room by the existing workflow? Without nagging the owner, this gives them some indication of the demand for a room, and if they approve it, have a pre-populated room to start with.
