### ISSUE TITLE
Hideable job advert

### ISSUE THREAD

**Issue by tjdett** [gitterHQ/gitter#797]
The job advert is cute, but uses >75px of contact bar height that would otherwise be used for... well, contacts.

![image](https://cloud.githubusercontent.com/assets/437845/8947356/638c52c8-35dd-11e5-91c1-b9b49a54c8b4.png)

After it has been viewed it would be nice to be able to close it.

**Comment by mydigitalself** [comment]
The advert is temporary and will be removed soon.
