### ISSUE TITLE
Images requested from i.stack.imgur.com show images from i.imgur.com

### ISSUE THREAD

**Issue by JakeEhrlich** [gitterHQ/gitter#798]
So I posted the following link on a channel in Gitter: http://i.stack.imgur.com/DFn7t.jpg
But what was shown was this (NSFW) image: http://i.imgur.com/DFn7t.jpg

You can imagine my embarrassment when the image displayed.

Apparently AlienBlue has this issue as well:
https://www.reddit.com/r/AlienBlue/comments/3ezxuu/bug_istackimgurcom_becomes_iimgurcom_which/

**Comment by MadLittleMods** [comment]
@JakeEhrlich If you were not able to delete this message in time, can you share the room name so we can remove it?

**Comment by JakeEhrlich** [comment]
I was able to delete it in time. Thanks for the quick response however!

**Comment by malditogeek** [comment]
Ugh, that was very unfortunate @JakeEhrlich :-1: 

I fixed it already. Thanks for reporting it!

**Comment by JakeEhrlich** [comment]
Thanks! So do I need to update Gitter somehow or was this a server side thing?

**Comment by malditogeek** [comment]
@JakeEhrlich was a server side thing, you don't need to update anything

we use an open source project called iframely to embed content and they were redirecting to the wrong content, fixed ours and reported back to them so hopefully AlienBlue will fix it too at some point: https://github.com/itteco/iframely/pull/88

:+1:

**Comment by JakeEhrlich** [comment]
Seems to work on my end now (for some reason on that address I have to use https). Awesome!
