### ISSUE TITLE
Enable Notifications pop up continually pops up

### ISSUE THREAD

**Issue by datakid** [gitterHQ/gitter#800]
There is no obvious way to disable the pop up asking me to enable notifications. I have no desire to enable notifications. I never will. I would like to never be asked again.

**Comment by MadLittleMods** [comment]
@datakid Do you by chance have the `#notifications` hash id in the URL? 

*ex.* `https://gitter.im/gitterHQ/gitter#notifications`

This will pop the notifications on page load, refresh, etc. If this is the case, just remove that part of the URL.

**Comment by datakid** [comment]
No, not using #notifications. Didn't even know that was a thing.

**Comment by MadLittleMods** [comment]
@datakid Just trying to understand the circumstances/environment in which this happens.

 - Do you have it set to "Don't notify me at all"?
 - Is the "Hide unread message badge" checked?
 - Are you in lurk mode?

Does it happen in other browsers or a in-private/incognito instance?

**Comment by datakid** [comment]
I have it set to: 
- notify me when someone mentions me
- "Hide unread message badge" checked (turns lurk on/off)
- yes, lurking.

- happens in 1-to-1 room as well as group rooms
- happens in incognito mode, in both Firefox and Chromium (fully up to date on Ubuntu 14.04.2)
- only happens when I open a new tab and open gitter for the first time since closing it last. I do not leave a gitter tab open all the time, only while at work (we use it for group chat at work)

**Comment by mydigitalself** [comment]
@MadLittleMods I think @datakid is talking about the little green banner that appears in app asking to enable notifications.

@datakid in Firefox, if you press Cmd+i/Ctrl i them go to permissions, you should see "Notifications" set that to "Block" in Chrome, it's under chrome://settings/content

**Comment by MadLittleMods** [comment]
Ahh, I have not experienced the desktop notifications pop out before. Pressing "Block"(in Chrome) seems to have worked for me in my testing.

![](http://i.imgur.com/5ztUxw8.png)

**Comment by datakid** [comment]
Thanks Mike.

------
The most dangerous phrase in the language is, "We've always done it this
way."

- Grace Hopper

**Comment by mydigitalself** [comment]
No problem at all.
