### ISSUE TITLE
Mobile chat input inaccessible after focus

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#802]
On a Nexus 7 in landscape orientation (~960px), using the Gitter web app in Android Chrome or Firefox: you can not see what you are typing. And the textarea chat input is inaccessible if you stop focusing after sending a message/typing.

You have to refresh the page again to get to the input back but as soon as you focus and start typing the problem happens again.

This issue can also be compounded by the occasional auto-focus. [Reported here](https://github.com/gitterHQ/meta/issues/13#issuecomment-99877890).

---

From some remote debugging, The textarea gets a `height: 0px` when you start typing.

```
<textarea
	class="chat-input__text-area"
	name="chat" id="chat-input-textarea"
	placeholder="Click here to type a chat message. Supports GitHub flavoured markdown."
	autofocus=""
	maxlength="4096"
	style="height: 0px;"
>
</textarea>
```

To combat this, if you add `height: 100% !important;` to `.chat-input__text-area` it works as expected. The reason to add it there with `!important`, is because you can't toggle the `height` declaration in the `style` attribute because it will get set again by JS right away.

It seems the auto-height JS calculation(for multiple lines) has a bug where it calculates a height of `0px` for some reason even when you are just entering normal text with no new lines.

---

Discovered by @der-On in this ticket: https://gitter.zendesk.com/agent/tickets/905

**Comment by der-On** [comment]
:+1 :+1

**Comment by trevorah** [comment]
We should probably do the resize using the textarea's `rows` attribute, and then set a min/max height.

**Comment by trevorah** [comment]
Whoever fixes this, please look at this related issue: https://github.com/troupe/gitter-webapp/issues/470

**Comment by der-On** [comment]
Why aren you setting the height of the textarea at all using inline styles/js?

Just set it's height to 100% and it will always match the wrapping div.

**Comment by trevorah** [comment]
@der-On we have some javascript logic to expand the textarea when you type over 3 lines.

**Comment by der-On** [comment]
The use `min-height: 100%` on the textarea

**Comment by der-On** [comment]
Any news on this? Currently gitter is very hard to use on mobile because of that. I always have to turn the device to portrait to type and to landscape to get the menu into view.

**Comment by trevorah** [comment]
Looking at this now.
