### ISSUE TITLE
Can't sign in on Android app

### ISSUE THREAD

**Issue by k-bx** [gitterHQ/gitter#803]
I input my credentials and see some 404 error: 

http://imgur.com/J4tiWFZ

Please help.

**Comment by mydigitalself** [comment]
Are you trying to access a private repository chat by any chance? Perhaps you can tell me the name/url of the room you are trying to access?

**Comment by k-bx** [comment]
Not trying to access any repo, just installed app, launched, input my
GitHub username/password and saw this screen.

**Comment by mydigitalself** [comment]
That's pretty odd. Can you do me a favour please:

Visit gitter.im in your web browser, join a room from there and then open the app again and tell me if you still have the same problem.

**Comment by mydigitalself** [comment]
Hey again. Someone else just reported with another client and confirmed there's an issue there we are investigating. Thanks for reporting.

**Comment by k-bx** [comment]
The issue is resolved now. Thanks!
