### ISSUE TITLE
Question: converting user to organization

### ISSUE THREAD

**Issue by dou-ua** [gitterHQ/gitter#804]
Hi! I have a github user (`dou-ua`), from which I created multiple channels in gitter and people joined them. But I realized that, since dou-ua is a user (not organization), page https://gitter.im/dou-ua shows a private-chat with that user, instead of a nice page, which lists all rooms for this user with number of participants.

If I will convert dou-ua user to a github organization:
- will channels still exist (with current users in them) as-is?
- will page https://gitter.im/dou-ua start listing them?

Thanks.

**Comment by mydigitalself** [comment]
Once you convert the user into an org, let us know and we can convert it on our side. Once you've done this, you will need to sign out of Gitter  (I assume you are now going to create a new GitHub user account) and then sign back in with your new GitHub account.

Please get in touch on support@gitter.im once you've done this and we can convert the old user into an org. We will also need to know the new user's account - it should be the owner of the newly created Org.

**Comment by dou-ua** [comment]
@mydigitalself thanks. Can you please confirm it won't affect existing users and channels (they won't be kicked, channels won't need re-creation, history won't be lost etc.)?

**Comment by mydigitalself** [comment]
Correct, that's what the conversion utility we will do ensures.
