### ISSUE TITLE
Unable to Un-Unsubscribe

### ISSUE THREAD

**Issue by ishotjr** [gitterHQ/gitter#805]
I was frustrated by the number of emails I have been getting from Gitter, so I changed all of my rooms to `mention`/*"Notify me when somebody mentions me"* - but still got emails.  As such, I located the subtle *Unsubscribe* link mentioned in https://github.com/gitterHQ/gitter/issues/553 and disabled email notification completely.  What I've discovered though is that the real issue may have been that my individual room notification preferences seemed to have mostly failed to save (LMK if you'd like another issue?), meaning that the email notifications I received were "legitimate" based on my actual settings - so, I'd like to re-enable email notifications now that I've gone through and re-saved my notification settings for each room (hoping it sticks this time?!) - but I simply cannot figure out how to, or even where to start - there seems to be no general preferences or account settings page that I can find? :confused:

**Comment by mydigitalself** [comment]
Hey, we don't currently have a way in the UI to do it, we assumed that if people wanted to unsubscribe, it was pretty final! I can certainly re-enable it for you on our side and we're going to be adding this capability to the UI in the near future. 

You should be receiving them again now.

**Comment by ishotjr** [comment]
@mydigitalself Seems to have worked - thanks! :bowtie: :+1:

**Comment by MadLittleMods** [comment]
You can now resubscribe using the notification defaults modal.

![](http://i.imgur.com/HIrnn5E.gif)
