### ISSUE TITLE
Profile Pic not updating

### ISSUE THREAD

**Issue by ionescu77** [gitterHQ/gitter#807]
Hello,

I first reported this in Gitter chat:

- I have changed my github: nickname & profile picture
- however I cannot get this updated in the gitter apps

Is there a workaround besides de-registering and registering again to gitter?

Thank you

**Comment by mydigitalself** [comment]
Hi

Unfortunately GitHub doesn't support username renames through the API, we can try do it manually for you, but it may have unintended side-effects.

What was your old username?

Mike

**Comment by ionescu77** [comment]
Hi mydigitalself,

my old Github nick is
- razvansky
my new Github nick is
- ionescu77

If you can give it a try with a manual update I would apreciate and take my chances.

Thanks a mil!

Raz

**Comment by mydigitalself** [comment]
Hmmm, that old username doesn't seem to exist, but I certainly see an account for ionescu77. If you chat in Gitter, does it have your username as ionescu77?

**Comment by ionescu77** [comment]
Tryed to reproduce and it seems to be fixed on the gitter fow mac 1.162. Thank you
