### ISSUE TITLE
Integration configuration is cumbersome

### ISSUE THREAD

**Issue by pitrou** [gitterHQ/gitter#813]
Currently, configuring an integration is a one-off thing: e.g. I add a github integration and choose all parameters upfront. If I want to later change that, I need the delete the existing integration and recreate it from scratch. That's wildly impractical (also, there's the risk I don't replicate the settings properly).

**Comment by MadLittleMods** [comment]
Duplicate of #426. Move conversation [there](https://github.com/gitterHQ/gitter/issues/426).
