### ISSUE TITLE
🐛 Regression on sidebar profile hover in next

### ISSUE THREAD

**Issue by samccone** [gitterHQ/gitter#816]
<img width="506" alt="screen shot 2015-08-11 at 1 13 43 pm" src="https://cloud.githubusercontent.com/assets/883126/9204383/f5196224-402a-11e5-95ae-c207f832ca32.png">

The button style seems incorrect...

**Comment by mydigitalself** [comment]
No, that's exactly how it should be.

*ahem*

hacky fix. all the buttons are getting a makeover very soon. they. are. a. mess.

**Comment by mydigitalself** [comment]
(Hacky fix is building and deploying now btw)

**Comment by samccone** [comment]
:goat: :+1:

**Comment by mydigitalself** [comment]
Thanks for the report dude.
