### ISSUE TITLE
Android app doesn't support physical keyboard

### ISSUE THREAD

**Issue by dlmarquis** [gitterHQ/gitter#817]
I have an LG Enact, and I can't use symbols accessed using the fn key, and Gitter won't rotate when I open the keyboard (this should happen regardless of whether autorotate is on).

**Comment by MadLittleMods** [comment]
I don't think we will add support if the physical keyboard isn't acting like a normal Android software keyboard. If you have any tips to easily make it compatible, we would love to hear.

The app now auto-rotates so it should be handled if your device handles the orientation API correctly.
