### ISSUE TITLE
Notifications not displayed (potentially network related)

### ISSUE THREAD

**Issue by alyec** [gitterHQ/gitter#818]
On our work network gitter does not trigger browser based notifications.  In the chat room @mydigitalself suggested that the websocket may be blocked and a fallback method may not be triggering the notification.

I tested the same machine on and off our work network, and notifications do work in the latter case.  I also check that the websocket is connected in both cases (so it isn't explicitly blocked) but the traffic looks quite different.

Work network: websocket connections typically last for a few seconds, this is usually followed by a pair of GET requests.
>  `https://ws.gitter.im/faye?message=[{"channel":"/meta/handshake","version":"1.0","supportedConnectionTypes":["websocket","long-polling","eventsource","cross-origin-long-polling","callback-polling"],"id":"gt","ext":{"token":"...","version":"becdd2","troupeId":"...","connType":"online","client":"web","eyeballs":0}}]&jsonp=__jsonp115__`

>  `https://ws.gitter.im/faye?message=[{"channel":"/meta/connect","clientId":"...","connectionType":"callback-polling","id":"gu"}]&jsonp=__jsonp116__`

Outside network: websocket connections last longer (usually open until the browser is closed).

It seems that something is terminating the websocket connection early, but I'm not certain if the callback method is getting enough information for the notification or if there is something else being blocked.

**Comment by MadLittleMods** [comment]
@alyec Are you still running into this?

**Comment by alyec** [comment]
Seems to have passed.  I checked with some of my coworkers as well and I think it's working.  I can't really say if it was a gitter update that fixed this or some network change on our end.
