### ISSUE TITLE
Copying chat messages to another app will never show you the username on first message

### ISSUE THREAD

**Issue by thoys** [gitterHQ/gitter#819]
example:
```
@nightpool our GitHub integration is built a lot deeper into Gitter and isn't part of the services API
thoys 15:41
is there a proper way of copy pasting messages from here?
I wanted to quote a funny conversation
```

The top message has no username.

I think to fix this the locking of names selection should temporary be disabled whenever you start selecting a chatmessage.

Note: this is only the case when you copy chat to another app, if you copy chat within gitter itself, it works fine.

**Comment by MadLittleMods** [comment]
:+1: Blocking user-select on the username is a bit odd to me.
