### ISSUE TITLE
Activity indicator misleading

### ISSUE THREAD

**Issue by pitrou** [gitterHQ/gitter#820]
I'm not sure I understand it well, but it seems the activity indicator is based on whether the person is "active" (green) or "idle" (orange). However, someone may be "idle" but still have a gitter window open and therefore be ready to answer any passing message, so the indication doesn't seem very useful.

**Comment by mydigitalself** [comment]
The green indicator means they are looking at the chat right now, we're aware this causes some confusion and will look to improve it in the future. #256
