### ISSUE TITLE
Win10/Firefox40 renders text much differently than before

### ISSUE THREAD

**Issue by onebree** [gitterHQ/gitter#822]
By before, I mean Win8.1 and Firefox 39

It appears that the font is "Source Sans Pro", which I do not locally have. I have third party cookies disabled, along with Ghostery and uBlock Origin.

![screenshot 2015-08-14 21 09 27](https://cloud.githubusercontent.com/assets/9038433/9286757/ef44c424-42c8-11e5-9c3b-f74f3e714142.png)

**Comment by MadLittleMods** [comment]
@onebree Can you look at the dev console, is there any content warnings/errors, etc?

Does the CDN work for you, can you [download the `woff` file from this link](https://cdn03.gitter.im/_s/Saac272b/fonts/sourcesans/SourceSansPro-Regular.otf.woff)(no need to install, just testing connection)?

**Comment by onebree** [comment]
@MadLittleMods Yes I can download the file. And here is a screenshot of the console

![capture](https://cloud.githubusercontent.com/assets/9038433/9286803/26aaf860-42ca-11e5-9929-a910a83ab66c.PNG)

**Comment by MadLittleMods** [comment]
@onebree Can you try disabling the Ghostery and uBlock Origin, one by one to see if that is the issue?

**Comment by onebree** [comment]
Yes same issue as I disabled each. I have the default content/font settings for my browser. I really hope this is not an issue with Windows 10, although it probably is. I am currently downloading the desktop client now, and report any findings

**Comment by onebree** [comment]
@MadLittleMods The desktop client for Windows is perfect. Zero issues. I know it sounds stupid, but Gitter does not require _any_ flash, right? I do not have that installed in Firefox.

I will use the desktop client for now. I prefer the web, because I do not use it too often, but oh well.

**Comment by MadLittleMods** [comment]
@onebree Try using the dev tools network tab and see if the font is getting requested but not applied. Here is a gif of those steps:

Use `Ctrl + Shift + R` to reload and clear cache.

![](http://i.imgur.com/R1jOz4Y.gif)

[Chrome network dev tools fonts gif](http://i.imgur.com/wwx9kDc.gif)

You can also sort by `status` to see if anything is wonky(not `200 OK`), *the faye connections are status `101`*.

**Comment by onebree** [comment]
Yes, the font is severed properly.

![capture](https://cloud.githubusercontent.com/assets/9038433/9287073/b39f9dea-42d2-11e5-9a1f-57b7f5f630ff.PNG)

**Comment by MadLittleMods** [comment]
@onebree What is the plugin icon with the `CSS` and minus sign? ![](http://i.imgur.com/8ATeyV5.png)

**Comment by onebree** [comment]
That is Reddit Enhancement Suite. And yes, I tried disabling the add-on, and no changes to Gitter. I also disabled other add-ons I have (TabMix Plus, CookieKeeper) and there seemed to be no change with the font.

I am going to try Gitter on my work computer right now. CentOS 7 with Firefox 38.2.0 (ESR)... AND no issue with font rendering. Everything is smooth, like it should be.

**Comment by mydigitalself** [comment]
Does this happen with FF 40 too? I've had some issues with FF39 in general.

**Comment by onebree** [comment]
@mydigitalself As mentioned in the title, this happens with Firefox 40 (specifically 40.0.2). I did not notice it on 39 on Windows 8.1. I have not visited Gitter at home (where the issue occurs) lately, so IDK if it has improved at all.

**Comment by MadLittleMods** [comment]
@onebree Did you have any luck finding a solution with this?

**Comment by onebree** [comment]
I will check when I get home. Sorry for the late response. I have not needed to visit Gitter at home, and have been very busy.

**Comment by MadLittleMods** [comment]
@onebree status update?

**Comment by onebree** [comment]
@MadLittleMods I apologize for another late response. The following is the latest screen shot and some new specs:

- Firefox 41.0.1, 32-bit
- Windows 10, 64-bit
- No MS Office (or its fonts) installed
- UBlock Origin
- Ghostery

![gitter-fail](https://cloud.githubusercontent.com/assets/9038433/11016376/ca50630e-854d-11e5-910f-2304a6416551.PNG)

**Comment by MadLittleMods** [comment]
I have been using Windows 10 for a while now and haven't noticed any of these font-rendering/aliasing issues in Chrome or Firefox

**Comment by onebree** [comment]
I guess you can close the issue. I haven't had the need to visit Gitter in months on a Windows system, so I continue to forget this issue.

**Comment by MadLittleMods** [comment]
Still curious on what the issue is so if you ever figure it out in the future, feel free to add a reply!
