### ISSUE TITLE
Can enter suggested room in iOS app

### ISSUE THREAD

**Issue by ikkentim** [gitterHQ/gitter#824]
I can tap on suggested room icons or names whatever I wan't but it does nothing.

![photo_2015-08-18_16-51-15](https://cloud.githubusercontent.com/assets/2820647/9333321/99208002-45c9-11e5-9a54-75d711d66785.jpg)

**Comment by trevorah** [comment]
Thanks for spotting this @ikkentim. I've pushed out a fix now, and there will be a ios update out soon with a more future-proof fix.
