### ISSUE TITLE
horizontal overflow on homepage in mobile

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#828]
Set your useragent / device to "iPhone 5":
![screen shot 2015-08-24 at 12 50 05](https://cloud.githubusercontent.com/assets/298742/9439422/b2bf9522-4a5e-11e5-9432-251da7fdfcc2.png)

**Comment by MadLittleMods** [comment]
Screenshot please :)

**Comment by trevorah** [comment]
Done!

**Comment by trevorah** [comment]
Looks like its something in the pricing panel. Delete that section from the dom and the overflow disappears.

**Comment by trevorah** [comment]
Found it. Negative margins are making some assumptions about the width of their parents. I'll prep a fix.
