### ISSUE TITLE
gitter.im site won't load resources when accessed from company network

### ISSUE THREAD

**Issue by svetoslavkostadinov** [gitterHQ/gitter#829]
Hello, 

I can never load gitter page (or ubuntu app) when try to access it from my company network. 
The errors I get are listed in the screenshot I am attaching to this Issue. 

Any ideas how I can access these missing resources from company network will be appreciated. 

FYI the github page loads just fine.
![cdn02 gitter im-error-load-resources-2015-08-24 11 24 21](https://cloud.githubusercontent.com/assets/2222313/9444301/cdf85f82-4a53-11e5-85ce-17a1e4541c9e.png)

**Comment by mydigitalself** [comment]
Hi there,

Perhaps you could ask your network administrators if there's any reason our CDNs are being blocked or not accessible. It's pretty much impossible to diagnose on our end to be honest.

**Comment by svetoslavkostadinov** [comment]
I thought so... :) Thanks for the quick response! 
I will be talking to the admins again. 
Feel free to close/delete this issue. 

Thanks!
