### ISSUE TITLE
getting "500: Internal Server Error" - when trying to create a channel

### ISSUE THREAD

**Issue by Renetnielsen** [gitterHQ/gitter#830]
Hello gitter!
I have been trying to create a channel for our organization, but when i do i get this message: "Unable to create channel".
As far as i could debug, the resides in your api (error from response below)

```
{"error":"exception: insertDocument :: caused by :: 11000 E11000 duplicate key error index: gitter.troupes.$uri_1  dup key: { : \"srcagency\" }"}
```

Here is a screenshot + curl (stripped for cookies, access-token etc).

![screen shot 2015-08-25 at 13 42 01](https://cloud.githubusercontent.com/assets/3541298/9465685/19023d64-4b2f-11e5-8994-216a3dd41e0c.png)

```
curl 'https://gitter.im/api/v1/private/channels' --data-binary '{"security":"PRIVATE","name":"lounge","ownerUri":"srcagency"}'
```

**Comment by MadLittleMods** [comment]
Hey @Renetnielsen 

Can you try again?

GitHub is being DDoS'ed at the moment and even though you are creating a private channel, we still do a permission check against the org to make sure you the user is part of the org.

The DDoS attack may be unrelated to this issue.

**Comment by Renetnielsen** [comment]
Hey @MadLittleMods, and thanks for the quick response.

I just tried again, but im still getting the samme error + response from the server.
```
{"error":"exception: insertDocument :: caused by :: 11000 E11000 duplicate key error index: gitter.troupes.$uri_1  dup key: { : \"srcagency\" }"}
```

Yea i noticed on their status page, since we use github alot - we noticed it being slow earlier.
But i dont think this is part of the problem, since i tried creating a room based on a repository, this seems to work fine. 
So the problem only relies in when i wanna a channel, so i can decide which people to invite n stuff.

**Comment by suprememoocow** [comment]
Hi @Renetnielsen, sorry about that. It's a problem on our side. We're working to create a fix for this immediately. Shouldn't take too long, but I'll let you know once it's rolled out.

**Comment by Renetnielsen** [comment]
Hi @suprememoocow.

Awesome :+1:

**Comment by suprememoocow** [comment]
Hi @Renetnielsen, that change should be in now. Sorry about the delay, the change took a little longer than I had expected but it should be fixed for you now. 

Please let me know if you're still experiencing problems.

**Comment by Renetnielsen** [comment]
Hi @suprememoocow.
It works like a charm, and thanks! We are now able to create the channel we wanted! :+1:

**Comment by suprememoocow** [comment]
Great! Sorry about the inconvenience but glad it's working for you now.

**Comment by Renetnielsen** [comment]
@suprememoocow no problem! And thanks again, gitter is amazing!! :+1:  :+1:
