### ISSUE TITLE
Support for Command-T style switching between rooms.

### ISSUE THREAD

**Issue by pipermerriam** [gitterHQ/gitter#831]
In Slack, if you use the keyboard shortcut `<Command> - T` a dialogue is open that allows you to switch which room you are currently chatting in with a fuzzy text match.

See the "Quick Switcher" on their documentation.  https://slack.zendesk.com/hc/en-us/articles/201374536-Slack-keyboard-shortcuts.

**Comment by MadLittleMods** [comment]
Hey @pipermerriam 

You can press `Ctrl + F` and then just start typing a room name to get some results and press enter or navigate with the arrow keys.

Is that sufficient?

**Comment by pipermerriam** [comment]
Yeah.  It appears this is a situation on disparate key bindings across
different tools.  Any it didn't seem like cmd-t was bound to anything.
Would adding it as a secondary mapping to this functionality be possible?

**Comment by cutandpastey** [comment]
@pipermerriam @MadLittleMods It would be 100% better to make key bindings configurable as I would prefer this to be cmd-p and I'm 100% sure other people would like other bindings.

**Comment by trevorah** [comment]
Doesnt cmd-t open a new tab in most browsers? Although cmd-p is used for printing, i dont think anyone has hit that key combo since the 90s...

**Comment by trevorah** [comment]
As always, make sure that [alt isnt being pressed](https://medium.com/medium-eng/the-curious-case-of-disappearing-polish-s-fa398313d4df) when listening for these keypresses...

**Comment by MadLittleMods** [comment]
@cutandpastey Open up a separate issue for customized keyboard shortcuts/bindings

**Comment by cutandpastey** [comment]
@trevorah yeah, ctrl-p is for printing but its also a vim [plugin](https://github.com/kien/ctrlp.vim) for fuzzy matching files, there's also [another plugin](https://github.com/wincent/Command-T) for fuzzy matching which uses ctrl-t which I'm assuming is the inspiration for the slack key combo.
