### ISSUE TITLE
Gitter now breaks a lot of code entered

### ISSUE THREAD

**Issue by PWKad** [gitterHQ/gitter#833]
Any time I enter a ' gitter corrects it to the Microsoft Word versions.  This *does not work in code* so we can no longer have users copy and paste code samples, even if they were enclosed in back ticks.

It does the same thing for double quotes and we just found out for multiple dashes.  We use this for a chat room for the github integration and this is really starting to cause some issues.

**Comment by trevorah** [comment]
Hmm, have you got autocorrect turned on for quotes? You should be able to disable it by right clicking on the text field.

**Comment by PWKad** [comment]
@trevorah it appears to be in the 'native' OSX app only now that I look in to this further, not the web version.  I can just ditch the native client I guess.

**Comment by trevorah** [comment]
@PWKad ive made a fix that should reach production in the next few days. It disables the quote autocomplete on all clients.

**Comment by PWKad** [comment]
@trevorah I'm trying to help someone disable this on OSX native and the option seems to be gone now and they are stuck with it, probably from a legacy build.  What can be done?
