### ISSUE TITLE
gitter learn page css is broken 👷

### ISSUE THREAD

**Issue by samccone** [gitterHQ/gitter#836]
<img width="999" alt="screen shot 2015-08-27 at 1 52 43 pm" src="https://cloud.githubusercontent.com/assets/883126/9531399/02b57720-4cc3-11e5-9c5d-be3c7e2881ee.png">

**Comment by trevorah** [comment]
Thanks sam! i'll take a look.

**Comment by trevorah** [comment]
Looks like it was pointing to an old a/b test that doesnt exist anymore. The fix is going through the deployment process now.

**Comment by trevorah** [comment]
And its live! Thanks for reporting it sam!

**Comment by samccone** [comment]
👌
