### ISSUE TITLE
Ctrl+click no longer opens web links in the systems default browser

### ISSUE THREAD

**Issue by ryanmcnz** [gitterHQ/gitter#837]
Previously, it was possible to use ctrl+click to open web links in the systems default browser.
This seems to no longer work, meaning that links always open up within a new webkit window that gets created by Gitter.
Is this the intended behavior? It seems quite restricting.

Note: This was under the Linux desktop app, on the latest version of Ubuntu.

**Comment by MadLittleMods** [comment]
`Ctrl + click` and `Middle Click` work just fine to open a link in a new tab for me.

Gitter Webapp in Chrome on Windows 8.1

**Comment by MadLittleMods** [comment]
Clicking the links in the Desktop app opens them in a browser for me Gitter v2.4.0 on Windows 8.1.
