### ISSUE TITLE
Gitter desktop app on Windows 7 freezes on taskbar, runs in background

### ISSUE THREAD

**Issue by danielvoicu** [gitterHQ/gitter#838]
The app window freezes and can't be accessed in any way. It seems that the application is still active in the background, as I can see the activity in a chatroom from its thumbnail preview (see attached image).

I tried:
 
 * signing out and signing back in
 * uninstalling and cleaning the registry then reinstalling the app
 * leaving all the chatrooms from the web interface, considering that it might be a problem if a chatroom is very active.
 
![thumbnail-gitter](https://cloud.githubusercontent.com/assets/7198550/9561436/25e90522-4e4e-11e5-8ef2-94b3586ed698.png)

**Comment by trevorah** [comment]
Hi @danielvoicu, is there any chance you could attach some logs? The instructions to setup logging are here: https://gist.github.com/trevorah/bfeb4ad69e4633dc76c5

**Comment by danielvoicu** [comment]
Hi @trevorah, I've setup Sawbuck and logged Gitter for 3 minutes. What should I paste over here? The log is pretty long, should I post only the error messages or the full log?

**Comment by MadLittleMods** [comment]
@danielvoicu Please paste in a [gist](https://gist.github.com/).

**Comment by danielvoicu** [comment]
@MadLittleMods Sure! I've pasted the full log in a gist. It can be found here: https://gist.github.com/danielvoicu/224ec7af64a7df663b28

Thanks and please let me know if I can help with anything.

**Comment by MadLittleMods** [comment]
Hey @danielvoicu,

Try the latest v3.0.3 version of the desktop app and report your experience :grinning:

**Comment by danielvoicu** [comment]
Hi @MadLittleMods,

Unfortunately I can no longer test it on Windows 7, but I've installed it on my current setup and I can confirm that it works fine on Windows 8.1. :grinning: 

Thanks!

**Comment by MadLittleMods** [comment]
Happy to re-open when someone can reproduce.

**Comment by ChristVolo1** [comment]
Hello, I have this problem on startup. I have Windows 7, and Gitter stopped opening, so I tried to uninstall it and reinstall it. Programs and Features said it wasn't able to uninstall all features of Gitter. It now still tries to open on startup, still shows in my taskbar as a thumbnail, and still shows up in Task Manager. How do I uninstall this?

![uninstalled gitter but it shows in task bar and task manager](https://cloud.githubusercontent.com/assets/23203383/24488111/46c8da20-14da-11e7-8049-91dee5b8eea1.jpg)

**Comment by MadLittleMods** [comment]
@ChristVolo1 Please create a separate issue instead of globbing onto this one. See https://github.com/gitterHQ/desktop/issues/175 for uninstalling fully.
