### ISSUE TITLE
Make status symbols more discoverable

### ISSUE THREAD

**Issue by gagern** [gitterHQ/gitter#839]
Coming to gitter for the first time, I noticed that all the people in the room hat some yellow dot overlaid over their icon. I didn't know what these meant. I could only assume that this had something to do with the fact that there were many people in that list, but no current activity at all. I searched the docs, but only got them explained in the gitter (itself) channel.

I think it would be nice to point out the status overlay somewhere in the docs, in a way that it matches the search terms `icon`, `status`, `online`, `presence`, `overlay`, `yellow`, `green`. It would also be nice if the mouse-over popup could show the same icon all by itself, and spell out its meaning. You might also want to discuss the list of members in general, like when are people included in that list, how is it sorted, what's the difference between that icon view and the “see all” button.

**Comment by MadLittleMods** [comment]
Great suggestion, inside Gitter, they are called "eyeballs".

Eyeballs represent whether the person is actively looking at the screen/has focus in that window.

 - #256

**Comment by MadLittleMods** [comment]
I added an article to zendesk, [*Eyeballs Disambiguation*](https://gitter.zendesk.com/hc/en-us/articles/204767252) that covers how the eyeballs currently work.

Move any further conversation to #256
