### ISSUE TITLE
🌵 Text input size in malformed

### ISSUE THREAD

**Issue by samccone** [gitterHQ/gitter#840]
#### steps to reproduce

1. view gitter in the browser
2. resize the window to half size
3. :cry: 

![screen shot 2015-08-31 at 9 47 50 am](https://cloud.githubusercontent.com/assets/883126/9584352/906a9e60-4fc5-11e5-8f08-3ec06a6cbb8e.png)

----

pressing enter fixes the size issue

**Comment by MadLittleMods** [comment]
I can't reproduce this. I use Gitter half size on a 1080p monitor all the time with no issue in Chrome on Windows 8.1.

Can you provide the following details?
 - Browser and OS?
 - Gif of the problem to help reproduce.

**Comment by trevorah** [comment]
It could be something to do with the text-area resize logic... I'll be poking around that area soon.

**Comment by MadLittleMods** [comment]
If it is resize logic, then related to gitterHQ/gitter#802
