### ISSUE TITLE
Broken URL in activity block

### ISSUE THREAD

**Issue by alesculek** [gitterHQ/gitter#842]
When a link has some special character(which is allowed by jenkins) then the link in the activity block is broken.

![gitter-broken-link](https://cloud.githubusercontent.com/assets/3257430/9659218/8297dbc2-524f-11e5-80da-01af040cff49.png)

Result html href is (bad):

```
http://jenkins.bisnode.cz:8181/job/dev-int.admin%20DEPLOY%20master%20to%20dev-int%20(admin.dev-int.bisnode.cz
```

Instead of this (expected):

```
http://jenkins.bisnode.cz:8181/job/dev-int.admin%20DEPLOY%20master%20to%20dev-int%20(admin.dev-int.bisnode.cz)/44/
```

Affected: Firefox and desktop client on Ubuntu. Both same result.
Maybe related to #661 

Thanks.

**Comment by trevorah** [comment]
Looks like this is an issue with our markdown parser. Here is where we construct the message: https://github.com/gitterHQ/services/blob/master/lib/jenkins/index.js#L46

Parenthesis in urls are the worst.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/716
