### ISSUE TITLE
Getting rid of a ghost room

### ISSUE THREAD

**Issue by davclark** [gitterHQ/gitter#843]
Hi there, this is an almost verbatim repeat of #723, which is closed for that one user. I have the same problem with an org renamed from berkeley-dsc -> [BIDS-collaborative](https://github.com/BIDS-collaborative).

Is there still no way to automatically handle such a rename? In my case I don't care at all about history (there is very little).

**Comment by davclark** [comment]
I have managed to get everyone to leave the room at this point.

**Comment by MadLittleMods** [comment]
Hey @davclark 

Sorry for not getting to your ticket in a timely manner.

Do you want to us to move the messages in `https://gitter.im/berkeley-dsc` to `https://gitter.im/BIDS-collaborative` and then you can delete the `berkeley-dsc` room?

**Comment by davclark** [comment]
No worries. There is nothing in the room that needs to be saved - so you can just delete it. Or if it's easier to move it, that's fine too!

**Comment by MadLittleMods** [comment]
@davclark I have deleted the `berkeley-dsc` room. Unfortunately GitHub's API doesn't inform us or redirect us, so we have no way of knowing when a rename happens.
