### ISSUE TITLE
https://gitter.im/oh-my-fish/oh-my-fish not working

### ISSUE THREAD

**Issue by bpinto** [gitterHQ/gitter#844]
Hi, the room `https://gitter.im/oh-my-fish/oh-my-fish` is redirecting to a wrong channel. Could you help us with that? Thanks

> The Gitter link results in a 404 "this is not the chat you were looking for" page. Assuming something wasn't updated when the repository was moved back, as it actually tries to look for wa/oh-my-fish.

Reference: https://github.com/oh-my-fish/oh-my-fish/issues/1

**Comment by bpinto** [comment]
Hey everyone, sorry to bump this so soon, but is there a way to get this fixed? After our repo was hijacked and destroyed, we would like to get back running as soon as possible.

**Comment by malditogeek** [comment]
hi @bpinto 

I'm trying to figure out what's going with this repo. Has this repo been renamed and/or changed ownership several times? We keep a history of old uri and looks like it went through: "oh-my-fish/oh-my-fish", "fish-shell/oh-my-fish", "wa/oh-my-fish", "wa/omf"

Also, looks like the permissions are not quiet right, was this a private repo that went public?

Why do you say your repo was "hijacked and destroyed"? What happened exactly?

**Comment by malditogeek** [comment]
We renamed your existing room to `oh-my-fish/oh-my-fish` so it's accessible now but would be good if you can answer me the questions above :point_up: so we can clarify how you ended up in this situation.

**Comment by bpinto** [comment]
It's quite a long story and most related data (issues) that was made public have been removed by the hijacker.

Long story short: I've created `oh-my-fish` three years ago and later we moved to `oh-my-fish` organisation with 2 other admins (3 in total). This hijacker-owner started to take actions that were affecting the community so we decided to remove him from the team, unfortunately before that he moved the repo to an organisation we didn't have access to. Later, he destroyed the repository.

If the repository was moved to a private repository, I don't know, I can only guess it was yesterday.

**Comment by bpinto** [comment]
If you need more information, let me know.

@derekstavis, @bobthecow and @scorphus might be able to provide more details.

**Comment by scorphus** [comment]
:+1: I confirm the answers given above

**Comment by bobthecow** [comment]
It was moved a couple of times in the last few days, changed into a private repo, moved two or three more times, then made public again. It's all a bit bizarre.

**Comment by bobthecow** [comment]
It's like a stolen car, taken on a high speed chase, then dumped at a chop shop. The gutted remains of the repo still exist, but it now has nothing in common with the old (or current) oh-my-fish.

**Comment by malditogeek** [comment]
Alright, that explains most of it. Glad we got it solved :+1:
