### ISSUE TITLE
Desktop app on windows auto update shows Update Ready toast but clicking does not update

### ISSUE THREAD

**Issue by eeevans** [gitterHQ/gitter#846]
The auto update keeps popping the toast that Update Ready but clicking does not reload app but dismisses toast then toast pops a few seconds again later.  Also goes away after timeout and then pops again after a few seconds.  Quite the show here.
Thanks,
Ed

**Comment by trevorah** [comment]
2.4.0 in fact fixes the annoying autoupdater. The quickest fix to skip it is to download the full installer at https://gitter.im/apps.

**Comment by eeevans** [comment]
Thanks, thought I was going to go nuts.

**Comment by trevorah** [comment]
If you are curious, you can check out the changes here: https://github.com/gitterHQ/desktop/compare/2.3.3...2.4.0

**Comment by eeevans** [comment]
Cool, thanks
