### ISSUE TITLE
chat input view out of sync with compose mode state

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#847]
You can reach a state where the chat input is in compose mode, but the icon shows chat mode.

Steps to reproduce:
1. switch to compose mode
2. refresh page
3. you are still in compose mode, but the icon shows chat mode

This is due to us rendering the chat input on the server, but storing the compose mode state in localstorage.

**Comment by Psithief** [comment]
I came to report this, but it's already here. :+1: Please fix.

**Comment by trevorah** [comment]
We have a fix that is currently in staging. You can try it out by going to http://next.gitter.im
