### ISSUE TITLE
Settings menu for per-room notifications for Android

### ISSUE THREAD

**Issue by georgiel** [gitterHQ/gitter#848]
A great deal of apps have a settings menu built in, which allows far finer control. Such as only push mentions `@MadLittleMods`

It is a much better UX.

Tbh, just the same as web app would rock, mentions only, lurk mode, etc. Set on a room by room basis.

**Comment by georgiel** [comment]
+1

**Comment by georgiel** [comment]
:+1:

**Comment by trevorah** [comment]
Blocked by upcoming changes to notifications: https://github.com/troupe/gitter-webapp/issues/397

There is little point in adding a new settings activity if its going to be broken a week later.

**Comment by GeorgeUni** [comment]
:+1:

**Comment by trevorah** [comment]
Should be landing in the next few hours as 2.7.0
