### ISSUE TITLE
Feature request. Mobile. @mentioned autocomplete

### ISSUE THREAD

**Issue by georgiel** [gitterHQ/gitter#849]
Mobile application doesn't autocomplete@names

And I can't click on to mentions

**Comment by MadLittleMods** [comment]
Related to gitterHQ/gitter#775

**Comment by MadLittleMods** [comment]
Auto-complete works in the webapp on mobile devices.

Auto-complete is not functioning in the Android app though.

**Comment by trevorah** [comment]
The fix is currently on beta. You can take a look by joining the beta program: https://play.google.com/apps/testing/im.gitter.gitter
