### ISSUE TITLE
Typing lags behind textarea input display on Android

### ISSUE THREAD

**Issue by georgiel** [gitterHQ/gitter#851]
There's sometimes a bit of noticeable lag between typing and it being visible in the interface if you type too quickly

**Comment by MadLittleMods** [comment]
@georgiel What device are you using? Are you using a custom keyboard?

I don't experience any lag.

**Comment by georgiel** [comment]
Nexus 5 with android 5.1.1.
 Swipe enabled standard keyboard

not often, just sometimes

**Comment by georgiel** [comment]
And it wasn't just the once, happened again last night.

It might be a slowed internet thing though, not entirely sure.

:+1:

**Comment by MadLittleMods** [comment]
@georgiel Does this ever happen with other apps and the keyboard?

**Comment by georgiel** [comment]
not seen it happen on desktop or on other apps no.

On Fri, Sep 25, 2015 at 1:26 PM, Eric Eastwood <notifications@github.com>
wrote:

> @georgiel <https://github.com/georgiel> Does this ever happen with other
> apps and the keyboard?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitterHQ/gitter/issues/851#issuecomment-143203519>.
>



-- 
Regards,

George William Langham

**Comment by GeorgeUni** [comment]
:+1:

**Comment by MadLittleMods** [comment]
We haven't had any other reports of this and the new app has been out for a while now. If anyone is experiencing this still, feel free to comment.
