### ISSUE TITLE
Can't edit/delete my reply

### ISSUE THREAD

**Issue by mahanmarwat** [gitterHQ/gitter#855]
Last night I sent a message (which was full of typos) in a gitter room, as I realized that my message have typos, I tried to edit/delete it but I was unable. Those options for edit/delete looked in gray color, like they have been turned off.
Right now the fix is of no use to me, cuz the guy has already seen my stupid English. But it will help in future.
![untitled2](https://cloud.githubusercontent.com/assets/6587438/9791936/0631fdf8-57f7-11e5-9a93-65e07e6b6fe4.png)

**Comment by MadLittleMods** [comment]
Hey @mahanmarwat,

You can only edit messages up to 5 minutes after posting a message. See the [*Editing messages* article on zendesk](https://gitter.zendesk.com/hc/en-us/articles/200296302-Editing-messages)

**Comment by mahanmarwat** [comment]
@MadLittleMods Hmmm, this is good. But I think they have to show a message (tooltip are alike) to the user, so, that he know ahead of the time.
Also when I delete a message, they still show "this message has been deleted", they are not going to completely remove it.

**Comment by IshtmeetSingh** [comment]
Having the same issue lately, I wonder why the limit is five minutes.

**Comment by ndkv** [comment]
@IshtmeetSingh To keep everybody honest? 

It is problematic, though, when someone e.g. makes a typo and doesn't delete their message within 5 min.

**Comment by ndelvalle** [comment]
If you post sensitive data by mistake and can not delete it ever again, that sucks...
