### ISSUE TITLE
Release the Android apk

### ISSUE THREAD

**Issue by ahstro** [gitterHQ/gitter#856]
Would you consider making the apk for the Gitter Android app available to download without Google Play installed? I know we're not many, but there are people out there that refrain from using Google Services on our devices, and it would be great to still be able to use Gitter.

**Comment by MadLittleMods** [comment]
:+1:

**Comment by trevorah** [comment]
Probably not. Workarounds already exist and this would add extra pain to our release process.

**Comment by ahstro** [comment]
According to the [official docs](https://developer.android.com/tools/publishing/app-signing.html#considerations), all apps from the same publisher should be signed with the same key. Therefore, publishing the apk would be as easy as pushing the `app-release.apk` to `https://update.gitter.im/android/latest`using some sort of [post-build script](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html). This should be a one-time less-than-an-hour setup which would benefit many, Gitter included.

**Comment by trevorah** [comment]
Nope, we would lose all push notifications as well because the play store would be missing. Its not as simple a 30 min task.

**Comment by c33s** [comment]
+1 for a direct download option.

@trevorah what do you mean with loosing the push notifications?

**Comment by trevorah** [comment]
We depend on [gcm](https://developers.google.com/cloud-messaging/) for our push notifications. Gcm depends on Google Play Services.

**Comment by ahstro** [comment]
There are alternatives, like [µg's GmsCore](https://github.com/microg/android_packages_apps_GmsCore), which I personally use myself. As long as you have a visible warning that the APK alone will not work without push notifications, I don't see the problem.

**Comment by vvombat** [comment]
Most apps i know implement polling and a small check in the start-up or installation process to check if GCM is available on the given device. E.g. Threema handled it that way afaik. That said I'd love to have gitter as an apk or on F-Droid or something. ;)

**Comment by gmoyanollc** [comment]
Another +1 for direct download option.  I can not log on with Android 5.1 to chat without enabling "Chrome.Request desktop site".

**Comment by TheDiamondYT1** [comment]
@vvombat F-Droid is for open source apps. However the gitter devs wont open source it. it woule be wo much easiee.
