### ISSUE TITLE
Remove Rotate iPad for "better experience"

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#857]
Remove the rotate iPad message. Should work either orientation just fine.

*note:* It also seems to be using the Troupe logo instead of Gitter.

 - https://twitter.com/robwormald/status/642179262682828800

![](https://pbs.twimg.com/media/COl6oj3UcAEUYUv.jpg:large)

**Comment by trevorah** [comment]
Hmm, pretty sure I removed this in troupe/gitter-webapp@46fc7b72380bfed50edd81a38f765b28d81d16a3. Is this still happening in prod?

**Comment by trevorah** [comment]
This is fixed in 13.5.0.
