### ISSUE TITLE
Banned users can't read see @mentions or leave/hide

### ISSUE THREAD

**Issue by githubjeka** [gitterHQ/gitter#861]
When a user was banned and getting message then he can't hide the channel and read personal messages

![image](https://cloud.githubusercontent.com/assets/874234/9976246/d7c7abba-5ee6-11e5-8b3d-b70b2c0c8997.png)

![image](https://cloud.githubusercontent.com/assets/874234/9976248/ef176c1a-5ee6-11e5-881e-8e3568b3dbce.png)

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/808

**Comment by MadLittleMods** [comment]
Closed in favor of https://github.com/gitterHQ/gitter/issues/808
