### ISSUE TITLE
Participate in the IRCv3 working group

### ISSUE THREAD

**Issue by erlend-sh** [gitterHQ/gitter#876]
Have you guys considered participating in the IRCv3 working group? It seems quite relevant to your mission.

http://ircv3.net/

https://github.com/ircv3/ircv3-specifications

**Comment by malditogeek** [comment]
That looks very interesting @erlend-sh, especially considering we wrote and run our IRC bridge for Gitter: https://github.com/gitterHQ/irc-bridge :rocket: 

Will definitely take a look at that spec and see what are they trying to achieve. Thanks for the links!

**Comment by erlend-sh** [comment]
Yeah, I find your IRC bridge very impressive, that's why I figured you might be interested ;)
