### ISSUE TITLE
Delay for email notifications

### ISSUE THREAD

**Issue by hackebrot** [gitterHQ/gitter#877]
Hi there,

thank you for making **gitter** :bow:

I noticed that I receive email notifications for unread messages delayed by one hour. Not sure if this is intended, but I personally prefer to receive emails instantly.

Any feedback is appreciated! Thanks :wave:

*This may be related to #143?*

**Comment by MadLittleMods** [comment]
Hey there,

Email notifications are currently batched up in hour chunks to avoid a bombardment of emails for every message. #143 sounds like a great compromise and we are looking at adding in depth settings to notifications in the future.

**Comment by hackebrot** [comment]
I see, thank you very much for your quick response @MadLittleMods! :bow: 

Just got myself the Mac OS X app :smile_cat:
