### ISSUE TITLE
missing space in email

### ISSUE THREAD

**Issue by meejah** [gitterHQ/gitter#880]
The reminder emails ("8 unread messages in") are missing a space before the URL. E.g. I get "8 unread messageshttps://gitter.im/..."

**Comment by MadLittleMods** [comment]
Thank you for the report @meejah.

Note: This only happens in the text-only version:

> Hi there,
> 
> This is what you missed while you were away.
> 
> gitterHQ/gitter: 3 unread messageshttps://gitter.im/gitterHQ/gitter
> 
> Kind regards,
> Gitter
