### ISSUE TITLE
"More [organisation name] Rooms" globe fails to go to correct org.

### ISSUE THREAD

**Issue by DeleteIT** [gitterHQ/gitter#884]
When I open Gitter in the latest Chrome, I find that if I click the globe in my current room, I'll go to the organisation's rooms (provided the globe even appears).

Alternatively upon opening a tab, and navigating to Gitter, if I move from that chat to another org's chat, and try to click their globe, I go to the first room's org page.

One time, it just logged me out entirely, another, it put the GitHub change log for the first room's org in a private chat, it's really kind of a "Okay, doing what I want now." sort of bug.

**Comment by MadLittleMods** [comment]
Hey @DeleteIT,

Thank you for the report. We are already tracking this issue internally along with several other bugs surrounding the org page globe button; secret sauce private link: https://github.com/troupe/gitter-webapp/issues/566

**Comment by mydigitalself** [comment]
What's the story with the globe, I can't seem to reproduce this - although the globe, oddly, isn't showing on `gitterHQ/gitter`

**Comment by DeleteIT** [comment]
If it doesn't show up, you need to close the tab, and then open a new one, navigate to Gitter.

**Comment by MadLittleMods** [comment]
This should be resolved with some [recent work](https://github.com/troupe/gitter-webapp/issues/566) to fix all the issues surrounding the org page globe.
