### ISSUE TITLE
Can not create https://gitter.im/oppia/oppia

### ISSUE THREAD

**Issue by sunu** [gitterHQ/gitter#885]
Hi!
We're trying to create a repo room at https://gitter.im/oppia/oppia. But it always results in a "Unable to create room" message.

**Comment by MadLittleMods** [comment]
Here are some more details on the issue [we discussed in `gitterHQ/gitter`](https://gitter.im/gitterHQ/gitter?at=560bba98ff22c70f6fab53ef).

 - @sunu is receiving a `403` permission denied on the POST request to create the room
 - @sunu is a member of the organization (not sure if admin of the repo)

**Comment by mydigitalself** [comment]
@sunu do you have push access to the repo?

**Comment by MadLittleMods** [comment]
@sunu Feel free to re-open if you are still running into issues. Closing due to no response.
