### ISSUE TITLE
A way to hide messages based on a filter criteria

### ISSUE THREAD

**Issue by VladShcherbin** [gitterHQ/gitter#888]
It would be great to have an option to hide messages.

For example, if we have a bot, who announces something or greets people, or tells statistics - someone may not want to see this messages. It would be great to have an option to hide a message and a button to toggle this setting in options, for example:

/hide message

So, this message won't be shown to users, who turns it on in options.

Another option would be as suggested [here](https://github.com/gitterHQ/gitter/issues/370) to have an ability to hide messages from certain users with /hide @username.

Any thoughts? Almost a year passed after it was asked for.

**Comment by VladShcherbin** [comment]
The first one is easy to implement - just add a flag (similar to \` and \`\`\`) and if the message starts with it, do not show to users, who turns hide option in options.

The second one is even easier to implement actually - just store an array with hidden user_ids in the user model and check the id of sender before the message rendering.

This feature is very needed for a year now.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/gitter/issues/370 as it does cover your use case of hiding a user/bot. The "flag" token text suggestion was a possible solution but we are more likely to go with the mute by username.
