### ISSUE TITLE
Retrieve message by id

### ISSUE THREAD

**Issue by Odonno** [gitterHQ/gitter#890]
It could be interested to retrieve a single message (or a group of messages) using their id. Using this endpoint for example : 

    GET /v1/rooms/:roomId/chatMessages?id=560ae5f495756f1402bc841d

And maybe for multiple messages

    GET /v1/rooms/:roomId/chatMessages?id=560ae5f495756f1402bc841d,560aeef6f4b61c106fb2a9f3

**Comment by MadLittleMods** [comment]
It looks like you can get a single message using this endpoint that isn't documented(should be added)

```
GET https://api.gitter.im/v1/rooms/:roomId/chatMessages/:messageId
```

**Comment by Odonno** [comment]
I did not tested it yet but I think it'll work.
I have updated the docs based on your answer https://github.com/gitterHQ/docs/pull/7

Thank you !

**Comment by MadLittleMods** [comment]
@Odonno I have tested this endpoint and it seems to work great.
