### ISSUE TITLE
Re-enable email notifications

### ISSUE THREAD

**Issue by davclark** [gitterHQ/gitter#893]
So, I'm running a large set of projects, and we're using Gitter. Some folks disabled email notifications, but then realized they wanted them. Is there still no way to re-enable these notifications?

For reference, I disabled them using the main unsubscribe link from the bottom of an email. But that was because I planned to have Gitter open most of the time.

**Comment by MadLittleMods** [comment]
This comment applies still: https://github.com/gitterHQ/gitter/issues/805#issuecomment-127958946

> Hey, we don't currently have a way in the UI to do it, we assumed that if people wanted to unsubscribe, it was pretty final! I can certainly re-enable it for you on our side and we're going to be adding this capability to the UI in the near future.

You can have those folks send a email to support@gitter.im and we can take care of it.

**Comment by MadLittleMods** [comment]
You can now resubscribe using the notification defaults modal which is accessible by clicking the "Configure Defaults" action on the bottom-left of any notification modal.

![](http://i.imgur.com/HIrnn5E.gif)
