### ISSUE TITLE
🐛 Activity feed state is showing another room

### ISSUE THREAD

**Issue by samccone** [gitterHQ/gitter#898]
(not running next)

![screen shot 2015-10-05 at 12 21 46 pm](https://cloud.githubusercontent.com/assets/883126/10290923/bffbe7d6-6b5b-11e5-93fa-dc1ecea790d2.png)

Issues are from the marionette room.. this issue persists across refreshing the page
There are no JS errors in the console

All of my rooms are actually showing the logs from the marionette room :cocktail:

**Comment by mydigitalself** [comment]
Is this still happening Sam? Can check it out tomorrow when we see you. I can't reproduce at all.

**Comment by samccone** [comment]
looks to be A-OK now was borked earlier, will close, we can reopen if it pops up again

:bride_with_veil:

**Comment by MadLittleMods** [comment]
I can't reproduce on production or next.

Does this happen in other browser sessions?
