### ISSUE TITLE
Display emojis as text in IRC

### ISSUE THREAD

**Issue by raine** [gitterHQ/gitter#903]
![screen shot 2015-10-07 at 10 29 43](https://cloud.githubusercontent.com/assets/11027/10331467/58518eb8-6cde-11e5-81bd-678e0b339c3f.png)

![screen shot 2015-10-07 at 10 29 31](https://cloud.githubusercontent.com/assets/11027/10331463/512ce0f6-6cde-11e5-929f-d64f14f9b315.png)

Seeing the emoji as `:+1:` would be an improvement.

**Comment by MadLittleMods** [comment]
These display just fine on IRCCloud and it seems there is some blank space in your client where it should go. Perhaps your client just tries to substitute an emoji and the image is broken?

**Comment by mydigitalself** [comment]
Displays just fine in Adium as well, I think @MadLittleMods is probably right that it's a client issue as I've tested the code and we're absolutely sending the plain text version through.
