### ISSUE TITLE
Tongue face turns into winky tongue face emoji

### ISSUE THREAD

**Issue by noinkling** [gitterHQ/gitter#905]
`:P` turns into :stuck_out_tongue_winking_eye: rather than :stuck_out_tongue:

This is a big deal because :stuck_out_tongue_winking_eye: conveys a slightly different, some say flirtier, impression than :stuck_out_tongue:

So I propose that you change `:P` to :stuck_out_tongue: and leave :stuck_out_tongue_winking_eye: to `;P` where it belongs. Thank you for your consideration in upholding emoji nuance.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/781
