### ISSUE TITLE
Please deactivate "autocorrect" on the text input field

### ISSUE THREAD

**Issue by frozeman** [gitterHQ/gitter#906]
Currently on Mac OSX when typing `"` or `--`, Mac autoconverts this into `“` and `—`, which breaks code examples.

If you add `autocorrect="off"` to the `<textarea>` you can prevent this. Autocorrect would be disabled but I think it would be a fair trade-off.

Or you make sure to change the characters automatically back, if they got converted.
This is especially important in inline code examples and code blocks.

**Comment by lerouxb** [comment]
See also https://twitter.com/haroenv/status/651290787142103040

**Comment by trevorah** [comment]
Hooray for safari-only attributes!

**Comment by frozeman** [comment]
i assume electron or node webkit is used, so it would be chrome...

**Comment by frozeman** [comment]
But yes, its a mac experience thing (which is probably the majority of web developers ;) )

**Comment by SaintPeter** [comment]
Could this be made optional or platform specific?  I use the Windows version of the App and I miss Chrome's spellcheck.
