### ISSUE TITLE
Duplicated notifications (N notifications each time opening settings)

### ISSUE THREAD

**Issue by piotrpalek** [gitterHQ/gitter#908]
[As reported on the gitterHQ/gitter channel](https://gitter.im/gitterHQ/gitter?at=5617bd4c1b0e279854bd8ed6) (we need to go deeper), I noticed duplicated notifications when being mentioned.

Steps to reproduce:

 1. Let yourself be mentioned.
 2. See (properly) one notification.
 3. Open notification settings.
 4. Close notification settings.
 5. Let yourself be mentioned.
 6. See the duplicated notification.

Note that each time you enter the notification settings and close it an additional duplicated notification shows up.

**Comment by piotrpalek** [comment]
Soo.. after poking around for a few minutes the problem seems to be that in you run `requestBrowserNotificationsPermission` every time the settings window is opened, which (after running `notifications.enable()`) adds a new event listener to `appEvents` every time it's run (so every time the settings window is opened) :)

**Comment by MadLittleMods** [comment]
:+1: I can reproduce this everytime. @piotrpalek Thank you for catching this :grinning:

**Comment by cutandpastey** [comment]
This should now have been fixed. Please let me know if this continues.

**Comment by MadLittleMods** [comment]
Seems to be resolved for me on production and next.
