### ISSUE TITLE
@/all mentions not cleared on iOS (sometimes)

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#911]
Steps to reproduce:

1. Lurk in a room and then get someone to @/all you in a room
2. Make sure there's enough subsequent chat messages such that the @/all doesn't initially appear on the screen. **This appears to be the important bit and the cause of the issue**
3. Scroll up to the @/all notice that the messages appears to be marked as read, but isn't

**Comment by ForbesLindesay** [comment]
I've been getting this constantly every time I've tried gitter and had to give up and use the irc bridge :( so glad you've managed to reproduce it.

**Comment by trevorah** [comment]
related issue: https://github.com/troupe/gitter-webapp/issues/492

**Comment by trevorah** [comment]
There have been some recent changes to this logic from @suprememoocow and I can no longer produce this, so Im going to assume that this is now fixed.
