### ISSUE TITLE
Issues with Github Organizations

### ISSUE THREAD

**Issue by TylorS** [gitterHQ/gitter#912]
When I click on one of the Organizations that I belong to, I can not view anything, and it also just sort of freaks out.

Heres a screenshot of what's going on: https://i.imgur.com/uwBck11.png

It does that and "loads" forever.

**Comment by MadLittleMods** [comment]
This is a bit strange, it looks like it is trying to bring up the community org page for the room instead of the org room.

I am not able to reproduce this on production or next. It seems the `OpenJSX` room is not in your main room list which may be a hint or a red herring. I tried to leave an org room, then click the room under "Your Organizations" but it didn't freak out.

 - Can you elaborate on some specific reproduction steps?
 - What browser/OS? Is it a desktop app?

**Comment by TylorS** [comment]
I'm not sure how to be more specific on reproducing it, apologies there if it is too vague.
 I simply click on the 'OpenJSX' link in the sidebar and this occurs.

The above image is what occurs to me, on the Ubuntu Linux x64 desktop application. 
Chrome, and Firefox. Although Within the version in the web browsers, I am able to do this multiple times, by that I mean 'nest', but for some reason it opens once it's been 'open' 3 times. The below picture can explain much better than my words.

http://i.imgur.com/E9fAflx.png

**Comment by cutandpastey** [comment]
A fix for this should have gone out yesterday. We could only guess at the cause as we could not replicate. Please let me know if this is fixed.

**Comment by TylorS** [comment]
Unfortunately it has not been fixed for me. In the web browser it opens the OpenJSX organization room in the second window instead of the third window. Sometimes now the Desktop application will crash when trying to open the my OpenJSX Organization tab, other times it will act as before.

I think that I will try building the application from source and see If I can find the issue.

**Comment by cutandpastey** [comment]
@TylorS could you provide some more screenshots? I don't really get what you mean by second and third window. Thanks.

**Comment by TylorS** [comment]
http://i.imgur.com/qBG1EUv.png This is what I mean by "second" window as opposed to the last screenshot above only opened on the "third" window. This is of Firefox 41.0 on Ubuntu 15.10 64 bit

**Comment by cutandpastey** [comment]
@TylorS a fix for a similar issue has now gone out. Could you please let me know if this issue has been fixed? Thanks.

**Comment by TylorS** [comment]
Yes! Everything is working properly now. Thank you!

**Comment by cutandpastey** [comment]
@TylorS Great news. This is a pretty interesting bug. Would you be able to post a screenshot of what you are getting now? I'm assuming its the organisations page displaying all their public rooms but it would be awesome if you could confirm that for us?

**Comment by TylorS** [comment]
Desktop application: http://i.imgur.com/GEitdTH.png
Firefox: http://i.imgur.com/ONb1S7y.png
Chrome: http://i.imgur.com/gMa4Rwl.png
