### ISSUE TITLE
Add a link to the NuGet package (API Client)

### ISSUE THREAD

**Issue by Odonno** [gitterHQ/gitter#914]
Recently, I uploaded a [NuGet package](https://www.nuget.org/packages/gitter-api-pcl) so that others can use the Gitter API more easily! This .NET project/library is dedicated to targeting the Gitter API.

 - NuGet package : https://www.nuget.org/packages/gitter-api-pcl
 - Source, GitHub repository : https://github.com/Odonno/gitter-api-pcl

I used this NuGet on a project that I have been working on for months now, https://github.com/Odonno/Modern-Gitter.

The NuGet is currently targeting all of these platforms: 

 - Windows (Phone) 8.1 (+ Windows 10)
 - .NET Framework 4.5
 - Xamarin.iOS
 - Xamarin.Android

I think it could be great to inform developers that this package exists, perhaps on the [developer site](http://developer.gitter.im/).

Thanks to @MadLittleMods

**Comment by gep13** [comment]
For what it is worth, this definitely gets my vote :+1: 

I also think that Modern-Gitter deserves a mention in the 3rd Party Apps section here: https://gitter.im/apps

**Comment by MadLittleMods** [comment]
Closing in favor of a more general discussion on how we should present these 3rd party API clients: https://github.com/gitterHQ/gitter/issues/921
