### ISSUE TITLE
Typeahead Room Linking/Autocomplete

### ISSUE THREAD

**Issue by SaintPeter** [gitterHQ/gitter#916]
I use Gitter with Free Code Camp, who has a TON of rooms.  I frequently want to refer someone to another room that they have not visited yet.  Right now the "easiest" way to do that (on the web) is to click over to the room, copy the url, click back, and paste it in.  In the app I have to click over, click the tool icon, click share and click "Share this room", copy the URL, close the window, click back to the other room and paste it in.

I would like to see some sort of auto-complete, similar to the `@` functionality, where I could, perhaps, type `/` or some other symbol and have an auto-complete of rooms in the channel family come up, or in general autocomplete on room names.

For example, typing `/Hel` in the Free Code Camp family should bring up `FreeCodeCamp/Help`, `FreeCodeCamp/HelpBasejumps`, `FreeCodeCamp/HelpZiplines`etc.

When a room is selected, it should turn into a friendly clickable link for that room.

**Comment by MadLittleMods** [comment]
Hey @SaintPeter,

Thanks for the write-up. This actually has another issue open that covers this topic: https://github.com/gitterHQ/gitter/issues/117 - Move discussion there please :)
