### ISSUE TITLE
Bad/Invalid Codepen can kill room

### ISSUE THREAD

**Issue by SaintPeter** [gitterHQ/gitter#919]
We had an issue on the FreeCodeCamp/HelpZiplines room today where a user posted a Codepen which had some sort of infinite loop in it.  Anyone who visited the channel would immediately freeze their browser or app.  This is double-trouble for the App, since it defaults to the last channel you were in, so you have to connect to another channel with a Browser to even get access to Gitter.

The only way that we were able to work around it was to use Firefox to enter the room, kill the individual process controlling the iFrame, and put a bunch of spacer text to force the CodePen link off the screen.

While this was clearly an accident on the part of a novice coder, the possibility of linking a malicious CodePen (or many of them) could result in a room being rendered unusable.  The CodePen is also sitting there like a time bomb for anyone who visits the archives.

There needs to be an easy way to disable in-line URL expansion for all channels.  A global setting, maybe?

There also potentially needs to be a way for non-moderators to report/block a bad link.

**Comment by MadLittleMods** [comment]
@SaintPeter If you provide the message ID and room name, I can remove the message for you.

---

This is also a problem for annoying `alert` calls, see https://github.com/gitterHQ/gitter/issues/648

The collapse setting is already an open issue here: https://github.com/gitterHQ/gitter/issues/714

**Comment by SaintPeter** [comment]
I don't know how to get the message ID without crashing my browser.

The room name is above, FreeCodeCamp/HelpZiplines.

It's probably within the last 30 messages or so, since there has been low traffic on the room today.

**Comment by MadLittleMods** [comment]
*note:* The message has been taken care of. The codepen seems to be working now and @SaintPeter is fine with leaving it.

**Comment by MadLittleMods** [comment]
Codepen now offers an embed preview option: http://blog.codepen.io/2015/10/20/oembed-previews/

We will look into implementing :)

**Comment by MadLittleMods** [comment]
This was solved a little while ago when we Codepen added the [oEmbed Previews](https://blog.codepen.io/2015/10/20/oembed-previews/).

You now have to push "Run Pen" to activate the pen

![](http://i.imgur.com/xLYhiVM.png)
