### ISSUE TITLE
Add 3rd party API clients to developer.gitter.im

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#921]
There are a few 3rd part API clients that make it easier to interact with the Gitter API just like [`node-gitter`](https://www.npmjs.com/package/node-gitter). We should probably list these somewhere on [developer.gitter.im](https://developer.gitter.im/).

 - [`gitter-api-pcl`](https://github.com/Odonno/gitter-api-pcl) by @Odonno, see https://github.com/gitterHQ/gitter/issues/914
 - [`GitterRxJavaSDK`](https://github.com/Gitteroid/GitterRxJavaSDK) by @amatkivskiy

**Comment by Odonno** [comment]
Hi @MadLittleMods,

Another NuGet package to simplify authentication this time : *gitter-api-auth* https://github.com/Odonno/gitter-api-auth. You can use it in complement of *gitter-api-pcl*.

**Comment by MadLittleMods** [comment]
Added via https://github.com/gitterHQ/docs/commit/c4bb6d434d1d8b068778c9358801ab36f253c985
