### ISSUE TITLE
Remove userhome for android

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#922]
The point of userhome was to allow the user to join rooms. Now that we have search, it is simply a way of showing content to a user when they first log in, so that they see something incase they're not a member of any rooms.

But it's **ugly**.

Instead, we should avoid the empty room list state by showing the suggested rooms there. [Like this](https://www.google.com/design/spec/patterns/empty-states.html#empty-states-displaying-empty-states):

![patterns_emptystates_starter](https://cloud.githubusercontent.com/assets/298742/10582774/66adbfe8-7681-11e5-8975-6a8721999883.png)

**Comment by lerouxb** [comment]
:+1:

**Comment by lerouxb** [comment]
Btw, are there plans for a room card / banner / cover image? (That could be used when featuring rooms like this.)

**Comment by trevorah** [comment]
Yeah, i personally think that we should start representing rooms as cards when they become more than just a chat room. Kinda like showing albums instead of tracks. But there are not plans for that coming up.
