### ISSUE TITLE
Add information about gv and meta fields

### ISSUE THREAD

**Issue by Alex-Bond** [gitterHQ/gitter#923]
Hi!

There are no information about the `gv` and `meta` fields. Can you add information and example of data for this fields?

```
{
  // ...
  "fromUser": {
    // ...
    "gv": "3"
  },
  "meta": {}
},
```

**Comment by MadLittleMods** [comment]
The `meta` field is currently used for nothing but it has been there forever and is probably just legacy.

The `gv` field stands for gravatar version and is used for cache busting. Thanks to @suprememoocow for [this tidbit](https://gitter.im/gitterHQ/developers?at=562816106b0cea6a101190cb).

**Comment by MadLittleMods** [comment]
Closed via https://github.com/gitterHQ/docs/commit/ea7397fae9896f27823bade0245f0809ce0124e5
