### ISSUE TITLE
Cannot successfully login.

### ISSUE THREAD

**Issue by clburns** [gitterHQ/gitter#931]
I previously had access to Gitter, and have used it in the past. However, yesterday at one point I was not able to interact with the page. It had signed me out. When trying to go back to it and clicking on Existing User Login, the page just refreshed (on chrome, firefox, and edge). 

I have tried revoking access to it on my github account, login and authenticate, then get kicked back to the home page. 

The android mobile app says "No connection, try again later"

The Desktop App, after logging in, directs to the home page.

**Comment by MadLittleMods** [comment]
What does your applications page look like (what Gitter apps)? https://github.com/settings/applications

**Comment by clburns** [comment]
Currently it only contains "Gitter Public Repo Access", which was revoked and re added recently.

**Comment by clburns** [comment]
I am part of a private organization that has a Gitter room and I have allowed the gitter app to gain access to it on first signin (after revoking the application). However, on both of their accounts they have "Gitter Public Repo Access" and "Gitter Private Repo Access" where mine only has Public (that has organization access). Not sure if this has anything to do with it from preventing me to connect or not.

**Comment by MadLittleMods** [comment]
@clburns The 404 should have a link to add the permission again but you can also just use this link: https://gitter.im/login/upgrade?scopes=repo

Also make sure you have one methods in here complete: https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-

**Comment by clburns** [comment]
@MadLittleMods I used the first link you gave me, and it just reloaded the home page again after trying to login. I then revoked Gitter public repo access from my applications and tried the link, reauthenticated and it sent me back to the home page again. 

With the second link you gave me, both options were tried and no success. As for the second option the Gitter Private Repo Access was not being generated, only the Public Repo Access.

However I'm not sure it has anything to do with the private repo access as that my private organization completely removed me from the organization to see if I would be able to login and it still returns me back to the home page, where everyone else can access their gitter accounts and rooms.

**Comment by lerouxb** [comment]
@clburns Which room do you want to access? What happens when you try and browse to it directly?

**Comment by clburns** [comment]
At this moment I can't access any room. If I browse to a room that is public it shows the room. However when I click the "Login with github to start talking" it just takes me to the home page again. I just tried this on the https://gitter.im/gitterHQ/gitter room.

**Comment by mydigitalself** [comment]
@clburns what happens if you try from an incognito/private browser session?

**Comment by clburns** [comment]
@mydigitalself Same thing, in all browsers and on different machines.

**Comment by mydigitalself** [comment]
Weird. I've tried something on our end, can you try again in an incognito browser again please?

**Comment by clburns** [comment]
Just tried, same thing sadly.

**Comment by mydigitalself** [comment]
Hmmm. Will try investigate further. If you do have a moment, perhaps we could jump a Skype screen sharing/Hangout session.

**Comment by clburns** [comment]
Sure thing, I'm about to hop on a flight now. Maybe tomorrow?

**Comment by mydigitalself** [comment]
Cool - I'm mydigitalself on Skype too, just ping me there and we can try and figure out this headscratcher. Thanks for your time and patience.

**Comment by clburns** [comment]
@mydigitalself, hey there, sorry I wasn't able to get you the first time on skype. However there has been a change. Now it gives me an error when trying to login

"We're very sorry, but we're unable to log you in right now. 
(E11000 duplicate key error collection: gitter.users index: githubId_1 dup key: { : 14093364 })"

**Comment by MadLittleMods** [comment]
Hey @clburns we just had a another ticket of this. Did you rename your accounts at all?

The problem previously was caused by someone having two gitter accounts, `userA` and `userB`. They deleted `userA` and renamed `userB` to `userA`. We just needed delete the old `userA` entry in the db.

**Comment by clburns** [comment]
@MadLittleMods that actually might of happened, I remember renaming this one. However the issue started after I renamed this one, like maybe a full day or 2. I don't remember if I had another account on gitter or not for certain.

**Comment by MadLittleMods** [comment]
@clburns Has this been resolved? If not, send a message to support@gitter.im with the whole situation on what accounts were renamed and deleted to what and we have the tools to handle this now.
