### ISSUE TITLE
Deleting uploads doesn't work

### ISSUE THREAD

**Issue by nerdyglasses** [gitterHQ/gitter#932]
I cannot delete my own message, since it's grayed out.

![screenshot 2015-10-26 13 43 12](https://cloud.githubusercontent.com/assets/449438/10729131/8675203a-7be7-11e5-8b02-e5c3f18f2b2f.png)

using this gitter version
![screenshot 2015-10-26 13 44 06](https://cloud.githubusercontent.com/assets/449438/10729151/a6a63704-7be7-11e5-934b-08125c14fdd4.png)

**Comment by MadLittleMods** [comment]
Hey @nerdyglasses, you can only delete messages for up to 5 minutes after posting, see https://gitter.zendesk.com/hc/en-us/articles/200296302-Editing-messages
