### ISSUE TITLE
Cannot 'Remove' User: "Failed to remove user, Not Found"

### ISSUE THREAD

**Issue by SaintPeter** [gitterHQ/gitter#933]
Had a disruptive user on one of our rooms and I attempted to "Remove" them, but I got a message "Failed to Remove User, Not Found".
![image](https://cloud.githubusercontent.com/assets/553494/10770572/3aff9e92-7ca9-11e5-8640-a45e15c0c3c9.png)

I'm reasonably confident that I have the right permsions, here is the user interface:
![image](https://cloud.githubusercontent.com/assets/553494/10770591/5d56d6f4-7ca9-11e5-9527-dd3e9d3fbce4.png)

1. If I had the right permissions, it should remove them.
2. If I don't have the right permissions, it should let me know.

The issue with this specific user is resolved, but I'm concerned that if there were a future issue I wouldn't be able to ban them.

**Comment by MadLittleMods** [comment]
The user `iOSDevelopin` exists on Gitter.

If you didn't have permissions, it would say "You do not have permission to remove people. Admin permission is needed."

I am currently looking into the code on how this situation arises.

**Comment by mydigitalself** [comment]
I think it's actually a UI bug. My guess would be that someone else had already removed them from the room or they manually left and the `REMOVE` button shouldn't display on the user popover if they aren't in the room any more. 

I can certainly reproduce it by removing someone who's not actually in the room this way.

**Comment by SaintPeter** [comment]
I am reasonably confident that they were still in the room.  They spoke very shortly after I "removed" them.

**Comment by mydigitalself** [comment]
You want to try and remove me from FreeCodeCamp/FreeCodeCamp ?

**Comment by SaintPeter** [comment]
That did appear to work - or at least didn't give me an error.

**Comment by mydigitalself** [comment]
Yeah, I'm removed. It could have been a race condition.

He said something as you were removing him and maybe someone else also removed him at the same time. 

Going to close this, shout if it happens again.
