### ISSUE TITLE
API endpoint to Hide Rooms

### ISSUE THREAD

**Issue by amatkivskiy** [gitterHQ/gitter#936]
It would be great to have an API endpoint for updating the "hidden" status of rooms.

And also extend the room object to add a `hidden` field so it is exposed to the API.

**Comment by MadLittleMods** [comment]
@amatkivskiy You can use `DELETE https://api.gitter.im/v1/user/me/rooms/:roomId` which will set the `lastAccessTime` to null and hide it from the left menu

Feel free to submit a PR to document it: https://github.com/gitterHQ/docs
