### ISSUE TITLE
Search results UI bug

### ISSUE THREAD

**Issue by raine** [gitterHQ/gitter#940]
It's showing wrong room name in the search results, I believe it should be "Messages in ramda/ramda"
 
![screen_shot_2015-10-29_at_10_11_24](https://cloud.githubusercontent.com/assets/11027/10813159/892752f4-7e25-11e5-85e5-88c999fd8959.png)

**Comment by MadLittleMods** [comment]
> Reproduction:
> 
> Reload
> Note the room you are in and start searching.
> Notice that the "Messages in [page-load-room]" title matches up correctly
> Switch rooms
> Search again and notice it uses the name is still `[page-load-room]` (incorrect)
> 
> [*source*](https://github.com/troupe/gitter-webapp/issues/655)

**Comment by cutandpastey** [comment]
This should now be fixed and live. Thanks @raine for reporting.
