### ISSUE TITLE
API capability to add/remove rooms

### ISSUE THREAD

**Issue by julianusti** [gitterHQ/gitter#942]
Add capability to `add/remove` rooms via API.

What I see as great feature for `Sidecar` is to add ability to use it on your own purpose, not only as a public chat for open source projects but also for your own business where you want to connect tech people.

**Comment by MadLittleMods** [comment]
I think you can create and destroy rooms but it is not currently documented.

**Comment by julianusti** [comment]
@MadLittleMods wow, that sounds awesome :)

**Comment by daytripper** [comment]
Related: is there way to change room names without deleting and creating new?

**Comment by MadLittleMods** [comment]
@daytripper There is no way to change room names. You have to create a new room name and we can transfer the messages over.

**Comment by daytripper** [comment]
Okay:
https://gitter.im/Peeragogy/CurrentCorrectionsKeepingUpToDate should be /Housekeeping
https://gitter.im/Peeragogy/PeeragogyPatterns should be /Patterns
https://gitter.im/PeeragogyPatterns/PLoP should be /Patterns/PLoP

**Comment by julianusti** [comment]
@MadLittleMods sup man :) any progress on the subject request? Have u found the endpoints or/and documented them?

**Comment by MadLittleMods** [comment]
@julianusti I have not documented yet but here is an overview (untested):

#### Create Room

HTTP verb: POST
 - `req.query.uri || req.body.uri`

#### Delete room

HTTP verb: DELETE
 - `req.params.troupeId` (not sure how to get at the moment)
