### ISSUE TITLE
Click to edit room topic only works on page load

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#947]
Currently, you can double click the topic in a room to edit it. But this only works for initially for the room that is loaded on page load.

 1. Reload Gitter
 1. Double click the room topic
 1. Notice how you can edit it (turns into text input)
 1. Switch to another room
 1. Notice how you can't edit room topics anymore

**Comment by cutandpastey** [comment]
@MadLittleMods has this been fixed? I can't replicate on production or `master`?

**Comment by MadLittleMods** [comment]
@cutandpastey Not fixed, I can reproduce on `next`

**Comment by cutandpastey** [comment]
hmmm, weird. I can't, which browser are you in (please don't say chrome :smile: )?

**Comment by mydigitalself** [comment]
I can reproduce in Chrome just fine.

**Comment by mydigitalself** [comment]
Hmm, after a refresh, I can't reproduce again.

**Comment by MadLittleMods** [comment]
I use Chrome and can still reproduce it.

**Comment by MadLittleMods** [comment]
This actually seems to be an issue of if you don't cancel editing of the topic and switch rooms. Same as  https://github.com/gitterHQ/gitter/issues/1096.

In this case, we need to refrain from using a internal `this.editingTopic` js variable and instead put a class to check on the topic element so that we never run into this situation and don't have to maintain the correct state through the variety of ways the chat-frame could change.
