### ISSUE TITLE
Option to disable graphical emoticons

### ISSUE THREAD

**Issue by MichielBijl** [gitterHQ/gitter#949]
Emoticons and smileys are all fine and dandy, but I find them rather distracting. I would like to request an option to turn them off (including the graphical display of smileys and the auto fill that shows when you type `:`).

Even an option to just disable the auto fill would be appreciated (that menu drives me crazy). It is more annoying than helpful, especially when typing code.

**Comment by StommePoes** [comment]
Since I often don't see emoticons, watching what I type get turned into :someweirdtext: is super-offputting. Another vote to let us escape the madness if we so choose.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/781

**Comment by MichielBijl** [comment]
Any news on this (or issue #781)?

**Comment by MadLittleMods** [comment]
https://github.com/gitterHQ/gitter/issues/781 encompasses what you want to do. And the original title is a duplicate of https://github.com/gitterHQ/gitter/issues/164. Move discussion to those issues.
