### ISSUE TITLE
Android app not logging in

### ISSUE THREAD

**Issue by floogulinc** [gitterHQ/gitter#951]
When I try to use the Android app, I login with GitHub and enter my two-step code, then it just goes to the Gitter web interface:

I'm running version 2.3.1 on Android 6.0

![](https://i.imgur.com/46TCJNW.png)

**Comment by magp** [comment]
Similar issue here. The app requires login each time it is launched.

Device Information:
Phone: Samsung Note3
Android version: 5.0

Description (see images for screens):
Each time I open the app I get the first screen. I press on "Existing User Login" and then get the second screen. Then, after login + pass (I confirm my Github 2FA is off) I get the third screen and can use normally. 
However, this process described happen every time I launch the app, making it inconvenient.
Furthermore, the back button on the phone will also logout Gitter and show a Github screen.

![appflow](http://i.imgur.com/dLFnVO9.png)

I can provide further information if needed.

**Comment by floogulinc** [comment]
as far as I can tell, what's happening is that it's not catching the login. Normally it first displays the normal Gitter login screen and the app is supposed to catch when you have logged in and display the app's more native interface. What's going on here is that its not catching it and just continuing to display the webview, which happens to be Gitter's normal mobile web UI. You'll notice when you hit links to outside Gitter in this state, it opens them in the same webview. I believe this issue with not catching the GitHub login has to do with two-step authentication. Someone should test this on the same device, logging on with an account without two-step and then one with it enabled.

**Comment by magp** [comment]
I can confirm I do not have two factor auth activated on GitHub:
<img width="274" alt="screen shot 2015-11-01 at 14 20 05" src="https://cloud.githubusercontent.com/assets/3720800/10872295/104d1f9e-80ff-11e5-9945-99d0ff6764ad.png">
so it shouldn't be that.

**Comment by floogulinc** [comment]
@magp oops I guess I glanced over where you said that.

**Comment by trevorah** [comment]
Hmm, I can reproduce this too with the latest beta. I'll take a look at what's changed.

**Comment by trevorah** [comment]
We've found the issue, we're working out a fix now. It's a server side change, so we should be able to get it out pretty quickly.

**Comment by trevorah** [comment]
The fix is live now. If you restart the app, you should be able to log in correctly now. Thanks for reporting this!
