### ISSUE TITLE
Add ability to create a 'one to one' room by searching user

### ISSUE THREAD

**Issue by Odonno** [gitterHQ/gitter#955]
I see there is a way to create a room by searching a repository or creating a new channel (see image below). But, for a some purpose, it could be great to have a 3rd option : searching for a GitHub user and see if it is possible to invite him in a 'one to one' conversation.

![Create a room](https://cloud.githubusercontent.com/assets/6053067/10882973/2a48aaa6-816f-11e5-8e8a-f1f004f96ad1.PNG)

**Comment by MadLittleMods** [comment]
@Odonno Right now you can do this through the search field in the top-right.

Exposing a flow in the "Create room" modal could be useful as well.

**Comment by Odonno** [comment]
@MadLittleMods Oh ok. I see that now. I was in the home page, so I did not see that search bar.

Indeed, could be useful to make it more visible by adding an option inside the modal.

**Comment by mydigitalself** [comment]
Technically, rooms and 1:1 are the same, but I'm not sure that putting a 1:1 in there is the right place.

Note that search will be moving to the left and always available, so this becomes less of an issue. Going to close this.
