### ISSUE TITLE
Sort "People" view to show "Online" people first.

### ISSUE THREAD

**Issue by SaintPeter** [gitterHQ/gitter#958]
There doesn't seem to be any rhyme or reason as to how the users in the "People" section are displayed.  It should favor those who are online.
![image](https://cloud.githubusercontent.com/assets/553494/10929770/a7d906f2-826c-11e5-8361-a6f81c0c68fc.png)

**Comment by SaintPeter** [comment]
Oh, sorry, duplicate #124

**Comment by MadLittleMods** [comment]
Thanks @SaintPeter, Move discussion to #124
