### ISSUE TITLE
Add eyeballs/status to people in People View modal("See All")

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#959]
The people's view dialog should **show online** eyeballs/status and sort everyone similar to #124.
![](http://i.imgur.com/liK3H9o.png)

**Comment by abhisekp** [comment]
@MadLittleMods looks like this issue has been resolved apart from the sorting thing. (i guess) :smile: 
thanks.  :+1:

**Comment by MadLittleMods** [comment]
@abhisekp Thanks for catching the update :) -  Sorting is tracked by #124
