### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by nhu** [gitterHQ/gitter#963]
Hi,
I am working with my colleagues in a company network which is using a proxy.
Gitter definitly needs an option to set the http/https proxy or it has to use the system proxy.
I'am currently on Windows 10.

EDIT:
Closed because wrong place. Moving to desktop client repo.

**Comment by MadLittleMods** [comment]
I think the issue @nhu is referring to is here:

 - https://github.com/gitterHQ/desktop/issues/26
 - https://github.com/gitterHQ/desktop/issues/49
