### ISSUE TITLE
Keyboard shortcuts navigation order wrong in left menu

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#965]
Pressing `Ctrl + Shift + up/down` navigates the left menu but it seems to do it in a bizarre order sometimes and doesn't always show `:focus` styles.

I can only reproduce this after sleeping my computer in the morning and coming back hours later.

![](https://i.imgur.com/jWzIVEr.gif)

![](https://i.imgur.com/xBN1uKj.gif)

**Comment by nicolas33** [comment]
Same issue while my system never sleeps.

**Comment by MadLittleMods** [comment]
This is now solved with the [release of the new left-menu](http://blog.gitter.im/2016/05/12/a-new-look-for-gitter/).
