### ISSUE TITLE
2FA on Github breaks Gitter

### ISSUE THREAD

**Issue by OmgImAlexis** [gitterHQ/gitter#967]
I've got 2FA setup on my account and I'm not sure why but bit seems that Gitter doesn't work at all with it enabled, currently I can only access the Gitter site if I'm logged out. Since my Chrome is logged I can't open any Gitter pages, the only time it works is if I'm in Incognito mode. Once I forced my Chrome to log out by clearing my cache I could then try and login again. Once I tried again it'd just tell me it got the wrong token after I got redirected from the 2FA page.

**Comment by trevorah** [comment]
Hmm, we had a hiccup earlier today with our caching. Could you try again now please?

**Comment by OmgImAlexis** [comment]
Works fine and https://github.com/gitterHQ/gitter/issues/396 seems to be working as well. Not sure if the OP still has the issue though.

**Comment by trevorah** [comment]
Thanks for the update @OmgImAlexis
