### ISSUE TITLE
API - Add Command Endpoint or support commands sent via messages

### ISSUE THREAD

**Issue by SaintPeter** [gitterHQ/gitter#989]
When a bot sends a slash command via the API the command is simply echoed out as a plain text message, not executed.

Primary use case is to enable bots to use the `/ban @username` command, but other commands could potentially be useful, like an `/unban` for a time limited ban, or `/query @username` to have a bot initiate a one on one conversation with a user.

**Comment by Alex-Bond** [comment]
+1

**Comment by abhisekp** [comment]
:+1:

**Comment by abhisekp** [comment]
I think this issue is resolved but undocumented in the API docs. There are already command endpoints for all types of commands that is used in the **gitter-webapp** as the webapp also uses the API to execute the commands.

**Comment by MadLittleMods** [comment]
I think @abhisekp commented somewhere that these commands are already available throughout the API.

From the referenced issue, it looks like you are after the `/ban` command which can be found at:

`POST https://gitter.im/api/v1/rooms/:room_id/bans`
 - `username`: Username to ban


Having an option to parse commands in messages is neat idea to cut down on complexity.

**Comment by abhisekp** [comment]
@MadLittleMods I wonder why they're not in the documentation yet. There are many undocumented command endpoints.

Here is a small list
> [![](http://i.imgur.com/B5U40Hi.png)](http://i.imgur.com/B5U40Hi.png)

**Comment by MadLittleMods** [comment]
Hey @abhisekp,

Thanks for the list, I was working on getting some of the undocumented endpoints documents and will add any that I missed from your list.

**Comment by MadLittleMods** [comment]
Commands have their own respective API endpoints, you can look at the network traffic and perform the action to see how it is done. Feel free to submit a PR for any missing endpoints: https://github.com/gitterHQ/docs

**Comment by abhisekp** [comment]
@MadLittleMods yeah! Documentations are old school. Devs should be able to look at the network traffic and perform action. :smiling_imp: 
And walla! I found `removeMessages`. I should try that. :smirk:
