### ISSUE TITLE
iOS background notifications should be sent for at-mentions and private messages where a user is merely idle, not logged out

### ISSUE THREAD

**Issue by posita** [gitterHQ/gitter#996]
This is my effort to reopen #419. I installed the Gitter iOS app and received zero background notifications for any message in any rooms in which I was participating (background meaning when Gitter.app was not the front-most app).

*UPDATE: I think I understand what's going on here. I was also logged into the same room from my desktop's web browser. This means my status was "idle", not "logged out". This suppresses background notifications on iOS. I don't think this is the correct behavior. Consider the following:*

* *User starts work for the day and logs into Gitter on her desktop*
* *User later decides to go to lunch, but doesn't want to miss any important messages, so she locks her desktop and grabs her iPhone, on which she has installed the Gitter iOS app*
* *User's status is set to "idle" in her various rooms because she is still logged in via her desktop*
* *While she is savoring her tonkatsu, a coworker at-mentions her with an important message that requires her immediate attention*
* *Because her status is "idle" rather than "logged out" (due to her still being logged in via her desktop), she receives no background notification on her iPhone and is oblivious to the message until she either returns to her desktop or unlocks her iPhone and looks at the Gitter app icon badge*

*This is a problem.*

The iOS app UI is so neutered in its current state that notifications seem to be the primary benefit (they tell me when I need to open Chrome and log into gitter.im to get access to the full app). But even those don't appear to work! :sob:

~~FWIW, it seemed that the Gitter.app was getting reaped (or paused?) while in the background. I'm not sure if this is a non-sequitur.~~ *UPDATE: This does not appear to be related as far as I can tell.*

**Comment by posita** [comment]
UPDATE: I think I understand what's going on here. I was also logged into the same room from my desktop's web browser. This means my status was "away", not "logged out". This suppresses background notifications on iOS. I don't think this is the correct behavior. Consider the following:

* User starts work for the day and logs into Gitter on her desktop
* User later decides to go to lunch, but doesn't want to miss any important messages, so she locks her desktop and grabs her iPhone, on which she has installed the Gitter iOS app
* User's status is set to "away" in her various rooms because she is still logged in via her desktop
* While she is savoring her tonkatsu, a coworker at-mentions her with an important message that requires her immediate attention
* Because her status is "away" rather than "logged out" (due to her still being logged in via her desktop), she receives no background notification on her iPhone and is oblivious to the message until she either returns to her desktop or unlocks her iPhone and looks at the Gitter app icon badge

This is a problem.

**Comment by MadLittleMods** [comment]
This is as expected on all platforms. If you have a desktop instance open, you won't receive notifications on Android or iOS, etc. We do this so that all of your devices don't buzz when you get a new mention.

Notifications is one area we are currently working on to expand and fill the gaps.

**Comment by posita** [comment]
@MadLittleMods, you guys might want to check out how Slack does this. They do it right.

**Comment by mydigitalself** [comment]
Note the Mac.app *should* instruct the servers to send notifications once your screensaver kicks in, which we believe to be truly idle. So in your given case, you should start receiving notifications once the screensaver kicks in when you're at lunch. (Note, this feature is not currently extended to Windows & Linux).

Just because your Gitter.app isn't in focus, doesn't mean that all of a sudden you should be receiving **both** desktop and mobile notifications.

However, what I will say is that it's not as good as it can be and will be improved in the future, but our philosophy on this is to try and be smarter about notifications in general and, admittedly, there are cases where we don't always get it right.
