### ISSUE TITLE
Global notification settings

### ISSUE THREAD

**Issue by caalberts** [gitterHQ/gitter#999]
Can we have a global notification setting that applies to all chatrooms please?

**Comment by MadLittleMods** [comment]
@caalberts Soon :)

**Comment by caalberts** [comment]
Looking forward to it. Thanks! :+1:

**Comment by pederjohnsen** [comment]
+1

**Comment by abhisekp** [comment]
:+1:

**Comment by aohorodnyk** [comment]
:+1:

**Comment by igrybkov** [comment]
+1

**Comment by CADbloke** [comment]
yes, please. :)

**Comment by sirinath** [comment]
+1

**Comment by MadLittleMods** [comment]
This has been implemented and can be accessed from any notification modal -> Configure defaults:

![](http://i.imgur.com/eq6EOex.png)
